### ISSUE TITLE
Build broken as npm module

### ISSUE THREAD

**Issue by thanpolas** [jonobr1/two.js#129]
Unless i'm missing something terribly obvious the npm module is broken because the build cannot find the underscore dependency.

The whole codebase assumes that underscore `_` is available in the global context while that is not the case when the two.js package is consumed as an npm package via browserify... 

I guess the same holds for the rest of the third-party dependencies

**Comment by jordanstephens** [comment]
@jonobr1 Any update on releasing a version to npm with the dependencies properly defined?
