### ISSUE TITLE
Zoom UI demo not working in Firefox

### ISSUE THREAD

**Issue by hansjorg** [jonobr1/two.js#131]
The Zoom UI demo isn't working in Firefox (I'm using FF34).

FF doesn't recognize the `mousewheel` event. By changing it to the standard `wheel`, it triggers in both FF and Chrome.

Next, on the first invocation of the `clientToSurface` function, I get an error in the console: `Unexpected value matrix(NaN NaN NaN NaN NaN NaN) parsing transform attribute.`

On all subsequent invocations, `this.surfaceMatrix.inverse()` returns null.

**Comment by jonobr1** [comment]
This fixes the issue: https://github.com/jonobr1/two.js/commit/3d09cc80d9dd09cf76b2209d831c9855c8f8d8a4

Thanks for reporting!
