### ISSUE TITLE
Some examples are not working anymore

### ISSUE THREAD

**Issue by grifotv** [jonobr1/two.js#132]
https://jonobr1.github.io/two.js/examples/

eg:
https://jonobr1.github.io/two.js/examples/physics.html

it has a JS error:
![screen shot 2015-02-04 at 10 48 31](https://cloud.githubusercontent.com/assets/435351/6039121/6788c476-ac5b-11e4-884a-557bacc9ceb7.png)

last night every example was working fine.

**Comment by grifotv** [comment]
it looks fixed now

**Comment by jonobr1** [comment]
Yes! Sorry! I accidentally pushed the dev branch to gh-pages which has some breaking changes. Sorry for the inconvenience! It's back to normal now.
