### ISSUE TITLE
Degraded performance because the stage update fires in each animation frame

### ISSUE THREAD

**Issue by sompylasar** [jonobr1/two.js#135]
This library misuses `requestAnimationFrame` for doing stage updates in each run of the animation loop. If the stage update is heavy, the animation is laggy.

Please learn why this is bad for performance and how to improve the design:
- https://developer.mozilla.org/en-US/docs/Games/Anatomy#Other_ways_to_handle_variable_refresh_rate_needs
- http://www.chandlerprall.com/2012/06/requestanimationframe-is-not-your-logics-friend/
- http://nokarma.org/2011/02/02/javascript-game-development-the-game-loop/#thats_it

The code that needs improvement:
https://github.com/jonobr1/two.js/blob/master/src/two.js#L1593

``` javascript
  (function() {

    requestAnimationFrame(arguments.callee);

    Two.Instances.forEach(function(t) {

      if (t.playing) {
        t.update();
      }

    });

  })();
```

Moreover, by using the Backbone event system to call back for the stage update logic, the library introduces more overhead into the animation:
https://github.com/jonobr1/two.js/blob/master/src/two.js#L1336

``` javascript
    /**
     * Update positions and calculations in one pass before rendering.
     */
    update: function() {

      // ...

      this.trigger(Two.Events.update, this.frameCount, this.timeDelta);

      return this.render();

    },
```

The demo that could perform better: http://jonobr1.github.io/two.js/examples/particle-sandbox.html
Browser: `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36`
Screen:

```
window.innerWidth: 1920
window.innerHeight: 979
```

The goal to move towards: http://www.goodboydigital.com/pixijs/bunnymark/ (P.S. This demo defaults to WebGL, and they misuse requestAnimationFrame the same way, too.)

**Comment by jonobr1** [comment]
Thanks for the post! I'm glad you're interested enough in the project to post your thoughts on how to improve things. I'm happy to take a look at this, but I want to be very up-front that __this is no__ _game engine_. It's a __rendering__ engine. As such the update there's nothing to stop you from running an `update` loop on your own `setInterval` or `setTimeout` in order to have consistent game logic changes.

Further, comparing pixijs and two.js is a bit like comparing Adobe Photoshop to Adobe Illustrator. There is a lot of overlap, but one does some things better, faster, easier, whatever comparator you'd like to use vs the other library.

**Comment by sompylasar** [comment]
@jonobr1 Thanks for your attention! As long as the library provides its own animation loop (that, moreover, starts unconditionally), it should not be laggy as it is now with regard to the particles demo. The experience of game engine developers could help you to improve performance of the library regardless of what the original purpose was.

It's the demos and the documentation that give the users of your library directions to put stage updates into the time-critical animation loop. Remember that each render should not last more than 16ms for smooth animations. Any extra code takes away these precious milliseconds that could otherwise be utilized by the rendering.

**Comment by darosh** [comment]
There is a space for performance improvement in the matrix math. I tweaked just 4 Matrix methods and got boost from 37 to 60 FPS in Chrome:

![image](https://cloud.githubusercontent.com/assets/297320/11019833/2150c9c8-860c-11e5-99bd-3e01e4158d38.png)

Links: [data and chart](http://bl.ocks.org/darosh/raw/65f9046bcb91c5f516a1/?r={two:{canvas:{rectangle:{60:60,240:59.6,720:37.3,1440:21.8,1920:16.7}},svg:{rectangle:{60:60,240:59.8,720:35.5,1440:20.9,1920:16.1}},webgl:{rectangle:{60:60,240:59.7,720:48,1440:18.8,1920:16.7}}},two-tweak:{canvas:{rectangle:{60:60,240:60,720:60,1440:36.4,1920:26.9}},svg:{rectangle:{60:60,240:60,720:59,1440:33.9,1920:26.2}},webgl:{rectangle:{60:60,240:60,720:49.4,1440:35.2,1920:29}}}}), [source code](http://bl.ocks.org/darosh/65f9046bcb91c5f516a1/)

Tweaks:
1. ```Two.Matrix.prototype.identity``` is quite heavy, using ```.set``` and ```_.exend``` 
2. V8 has issues with [optimizing arguments objects](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments) in some cases
3. ```parseFloat(elements[0].toFixed(3))``` can be just ```elements[0]``` or use faster rounding without conversion to ```String``` like ```Math.round(x*1000)/1000``` or maybe ```((x*1000) | 0)/1000```

Further improvements could be:
1. using something like [stackgl/gl-mat3](https://github.com/stackgl/gl-mat3) withTyped Arrays or [pixi/matrix](https://github.com/pixijs/pixi.js/blob/master/src/core/math/Matrix.js) saying *Matrix class as an object, which makes it a lot faster* 
2. removing multiply(a,b,c,d,e,f,g) calls copying parameters from scale, transform, ... methods
3. removing Underscore loops and Backbone events from math

Regarding the default loop: in my opinion it would be nice to have it optional and run it only when it is needed. There may be other non-two.js jobs for requestAnimationFrame on the page. I had to disable it:
```html
<script>
    // Backup requestAnimationFrame & restore after first call to disable two.js auto loop start
    // https://github.com/jonobr1/two.js/issues/135
    window._requestAnimationFrame = window.requestAnimationFrame;

    window.requestAnimationFrame = function () {
        window.requestAnimationFrame = window._requestAnimationFrame;
    };
</script>

<script src='//cdnjs.cloudflare.com/ajax/libs/two.js/0.5.0/two.min.js'></script>
```
Additionally I added ```renderer.scene.subtractions.splice(0);``` after ```renderer.clear();``` to clear allocated memory (I had to, 1 rounded rectangle consumes 140kB). 

More benchmarks comparing two.js with other frameworks here: http://bl.ocks.org/darosh/a71ff1c9d6e163e2faea

**Comment by jonobr1** [comment]
This is fantastic research! Thanks so much for sharing. I'll put this on my personal roadmap to integrate.

**Comment by jonobr1** [comment]
So, still have a ways to go before we get to similar performance of bunnymark, but I updated the matrix math starting with this [commit](https://github.com/jonobr1/two.js/commit/c162e2d00ba4e0ae71dbdd2034a8b0f9bd12dc19) as well as decoupled Request Animation Frame.

If you specify `autostart: true` when instantiating an instance of Two.js or when you call `two.play();` it will kick off an instance of Request Animation Frame. However, if you don't and want to manage your own update loops, then you can call `two.render` or `two.update` on your own without worrying that the library will spin up Request Animation Frame itself.

I know it took awhile, but thanks for all the help! Hope this helps you guys out.
