### ISSUE TITLE
Add ability to scale X and Y independently

### ISSUE THREAD

**Issue by tranzfuse** [jonobr1/two.js#136]
Hi, I'm late to the party.

As discussed previously in #23, I would be interested in the ability to scale X separately from Y.

A simple example of what I'd like to achieve, demonstrated with the CSS equivalent: http://codepen.io/tranzfuse/pen/vEPMrw

(I see that issue #23 is quite old at this point, so maybe this has been addressed already, but it wasn't clear to me if so)

Thanks for your hard work @jonobr1, this is a cool library. I discovered it the other day and dove right in.

**Comment by jonobr1** [comment]
Thanks for the issue! Yes, this is still an unresolved thing unfortunately. Fortunately the `Two.Matrix` class is actually pretty robust. It's a bit more code, but you can do `x`, `y` transformations separately by handling all the matrix transformations yourself. Here's a demo: http://jsfiddle.net/jonobr1/jdojyzaw/

**Comment by tranzfuse** [comment]
Awesome. Works for me for now. Should I close this issue, or do you intend to get around to implementing the separate scaling in a more direct way soon-ish?

**Comment by jonobr1** [comment]
I think we should close this for the moment. Including this in a more direct way in Two.js would require breaking API changes and `v0.5.0` already has one major change.
