### ISSUE TITLE
Fill is Very Slow

### ISSUE THREAD

**Issue by adammhaile** [jonobr1/two.js#137]
I was testing out two to see if it would meet my needs for a matrix visualizer in which I need to draw "pixels" and change their color. However, changing the color with fill is epically slow. It will drop to < 5FPS. But if I, for example, used the rotate parameter, it would run at 60FPS, with a couple thousand pixels.  See test code below. Is there anything specific I may be doing wrong? I can't imagine a simple fill operation would be so slow... what's also weird is that the CPU utilization for fill is much less than that when using rotate.

```html
<!doctype html>
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="two.min.js"></script>
    <style>
      body {
        background-color: red;
      }

      #vis {
        background-color: yellow;
        border: 2px solid #000000;
        height: 100px;
        width: 100px;
        margin-top: 50px;
        float: left;
      }

      #fps {
        background-color: white;
        color: black;
        font-size: 2em;
        float: left;
        top: 0;
        width: 100px;
        height: 50px;
      }

    </style>

    <script>
      var rects = [];
      var numX = 32;
      var numY = 32;
      var pixelSize = 15;
      $(document).ready( function() {
          var fpsDiv = $('#fps');
          var elem = $("#vis");
          elem.width(numX * pixelSize)
;          elem.height(numY * pixelSize);
          var two = new Two({
            autostart: true,
            fullscreen: false,
            width: elem.width(),
            height: elem.height(),
            type: Two.Types.webgl
          }).appendTo(elem.get(0));
          
          var pw = pixelSize;
          var ph = pw;
          for(var x=0; x<numX; x++){
            for(var y=0; y<numY; y++){
              var r = two.makeRectangle(x*pw+(pw/2), y*ph+(ph/2), pw, ph);
              r.fill = "#00FF00";
              r.stroke = "#000000";
              rects.push(r);
            }
          }

          two.update(); 
          console.log("W:" + two.width + " H:" + two.height);
          console.log(two.renderer);
          two.bind('update', function(frameCount, timeDelta) {
            fpsDiv.text(Math.floor(1000/timeDelta));
            var c = '#'+(Math.random()*0xFFFFFF<<0).toString(16);
            $.each(rects, function(i,v){
              v.fill = c;
              //v.rotation += 0.03;
              v.fill = c;
            })
          });        
      });
    </script>
  </head>
  <body>
    <div id="fps"></div>
    <div id="vis"></div>
    
  </body>
</html>
```

**Comment by jonobr1** [comment]
Hey @adammhaile,

Thanks for the message and trying out two.js! The reason this happens is because of the way the `webgl` renderer works. Currently the library re-uploads a 2D texture every time a `fill`, `stroke`, `linewidth`, `cap`, `join`, or `scale` property has changed on an object. This operation is __very__ slow. So if you can confine or reduce how many times you call this a frame.

I would suggest making a prototype that creates _all possible_ items and variations on load. Then when you need to change you swap out items. I often create a [pool](https://github.com/warprecords/tether/blob/gh-pages/src/pool.js) to work with a fixed amount of elements without having to change the way I work too much.

Depending on how many items you want in your scene the `canvas` renderer may perform better. Hope this helps!

**Comment by adammhaile** [comment]
Changing to canvas improved it 3x... to 6FPS :P 
I can't make an object for every color because I would need to make 2^24 objects for each square :(

I made a copy of the [particle sandbox](http://jonobr1.github.io/two.js/examples/particle-sandbox.html) and added a fill operation to that, and it has no problem... even with WebGL.

I added this to var operations:

```javascript

color: {
              enabled: false,
              update: function(particle) {
                var c = Math.floor((Math.random() * colors.length));
                particle.fill = colors[c];
               }
            },

```

That works great. 60FPS even with a ton of shapes. Is that somehow functioning differently from my example from before?

**Comment by jonobr1** [comment]
hmmm, that's really interesting. I'll fiddle with this more, but all I really noticed was that maybe `$.each` is slower than `for`?

http://jsfiddle.net/jonobr1/gkun01f6/1/ Does this perform better on your end? Also, the rotation is _fast_!

**Comment by adammhaile** [comment]
Nope... same speed here :(

**Comment by jonobr1** [comment]
and you need to change the color of each one of them every frame? And they may or may not be the same color?

**Comment by adammhaile** [comment]
Yup... I'm getting in data that represents every pixel and need to update
every single one every time.

**Comment by jonobr1** [comment]
Cool. Surprisingly the `svg` renderer is much faster: http://jsfiddle.net/jonobr1/gkun01f6/2/

**Comment by adammhaile** [comment]
Weird... with canvas, it was fine up to a 15x15 grid, but the second I hit
16x16 it dropped to 20fps.
With svg, it starts to break down at around 24x24. Sadly, I need 60FPS at
much higher object counts... up to 10,000 or more.

**Comment by jonobr1** [comment]
Hmmm, unfortunately I don't think you'll get that kind of performance out of Two.js.., you need to offload way more calculations than Two.js offers on the GPU to get that performance out of `webgl`.

For this instance I think you're better off with Three.js using the `THREE.PointCloud` and `THREE.ShaderMaterial`

**Comment by adammhaile** [comment]
Ahh... I was afraid of that. I never could figure out how to do the 2D
thing in Three.js... but hadn't found pointcloud. Will give that a shot.
Thanks!
