### ISSUE TITLE
calling group.remove results in Uncaught TypeError

### ISSUE THREAD

**Issue by JoeMattie** [jonobr1/two.js#138]
Works as intended, but I'm left with a ton of:

Uncaught TypeError: Cannot read property '_matrix' of undefined

in the console.

**Comment by JoeMattie** [comment]
Trace

Uncaught TypeError: Cannot read property '_matrix' of undefined
two.js:4870 webgl.polygon.render
two.js:4783 webgl.group.renderChild
two.js:116 _.each._.forEach
two.js:4833 webgl.group.render
two.js:5451 _.extend.render
two.js:2821 _.extend.render
two.js:2812 _.extend.update
two.js:3072 (anonymous function)
two.js:3069 (anonymous function)

**Comment by jonobr1** [comment]
Thanks for posting this! Do you have a live example I could inspect further?

**Comment by JoeMattie** [comment]
Hey, I figured out why I was getting this error.  I had been rewriting the polygons' .id property with my own identifier.  Keeping a lookup table instead resolved the problem

**Comment by jonobr1** [comment]
Glad to hear that fixed things!
