### ISSUE TITLE
possible project, two.js based audio visualizer

### ISSUE THREAD

**Issue by trashhalo** [jonobr1/two.js#142]
http://codepen.io/trashhalo/full/EjpoJO/

A little weekend project I whipped up. Connects to your microphone via web audio. Two.js changes circle scale based on average audio level and circle fill color based on bass vs treble levels. Unplug your headphones, allow mic on that tab and give it a try. (only tested in chrome)

**Comment by trashhalo** [comment]
I made this too :) http://codepen.io/trashhalo/full/OVwwyE/

**Comment by jonobr1** [comment]
Very Cool!
