### ISSUE TITLE
Change origin of Polygons and Groups

### ISSUE THREAD

**Issue by fnky** [jonobr1/two.js#143]
It would be nice to be able to change the origin of a `Two.Polygon` and `Two.Group` that transformations will respect.

``` js
var rect = two.makeRectangle(50, 50, 200, 200);
rect.origin = Two.Anchor(200, 200); // The origin is relative to the `rect` x and y position.
```

The above code would change the origin of the `rect` from center

![1](https://cloud.githubusercontent.com/assets/995050/8766307/7c2b9520-2e33-11e5-9c86-c448bcc0c6a7.png)

to bottom right

![2](https://cloud.githubusercontent.com/assets/995050/8766308/828e2c5c-2e33-11e5-9ea5-3454d28b2c0b.png)

And a transform such as `scale` would respect the `rect`'s origin

![3](https://cloud.githubusercontent.com/assets/995050/8766320/b5b6c3d2-2e33-11e5-8883-1ade4f379cbe.png)

**Comment by jonobr1** [comment]
Hey, thanks for posting!

So `Two.Group`s and `Two.Polygon`s both have a `center` and `corner` method as a short hand to do origin changes. e.g:

````javascript
var shape = two.makeRectangle(two.width / 2, two.height / 2, 50, 50);
shape.corner(); // The origin now resides at the top left corner of the rectangle
````

I love you're thinking, but the tricky part of having a persistent variable to represent `origin` is that it can cause confusion in how the rendering is setup in two.js. You can always change how a child is oriented in relation to a parent though! For groups you can iterate through the children and change each child's `translation`. e.g:

````javascript
var offset = new Two.Vector(200, 200);;
_.each(group.children, function(child) {
  child.translation.addSelf(offset);
});
````

And for `Two.Polygon`s like in your example you can iterate through the vertices and change their `x` and `y` properties. e.g:

````javascript
var offset = new Two.Vector(200, 200);
_.each(rect.vertices, function(v) {
  v.addSelf(offset);
});
````

This will have a similar effect as to the one you desire. Finally, the `make` methods — like `two.makeRectangle` — all create shapes where their origins are calculated and placed at the center. Alternatively you can build out your own shapes using `new Two.Polygon(x, y, x, y, x, y ...)` and this shape will respect exactly the vertices you throw at it. For more on Two.Polygon check out the [documentation](http://jonobr1.github.io/two.js/#two-polygon)!

**Comment by fnky** [comment]
Hi, jonobr1 thanks for your well-described answer.

I was hoping to have an easier approach, since origin points are an important part of 2D objects, in my opinion.

Also there were no documentation regarding the `.center()` method on `Two.Polygon` and `Two.Group` other than in the changelog.

I hope we can figure something out to implement a more controllable with less boilerplate.

**Comment by jonobr1** [comment]
Thanks for your suggestion. While I think the concept you are describing as origins are helpful and a defined as a paradigm in other applications like Illustrator and After Effects, including these into the underlying `Two.Shape` would limit the functionality of the matrix, `Two.Matrix`, which is ultimately more useful than an `origin` property.

My main concern with adding an `origin` property is not about altering the vertices of a shape or the `translation` of a groups children, but of keeping *state* of the origin and its relation to the matrix.

If this is helpful I can add other methods for specific origins like `corner` and `center`. `corner` could take an argument to pass in the corner you'd like to attach the origin to. e.g:

````javascript
rect.corner(Two.Corners.LowerRight);
````

**Comment by fnky** [comment]
That could be a good solution, it would make it more customizable.

Also a quick question; Is the `origin` used for the rotation/scaling/etc. point, or would this also work with `Two.Anchor`?

**Comment by jonobr1** [comment]
Yes, the underlying matrix affects rotation and scaling. Check out [this example](http://jsfiddle.net/jonobr1/aedvz344/).

**Comment by larrybotha** [comment]
@jonobr1 I'm all over two.js like a disease...

So in exploring rotations of paths and groups, I've put together 2 different demos, both of which let you play around with offsets, as well as exploring the logic for rotating around a point using a mouse or touch:

[Path Rotations](http://codepen.io/larrybotha/pen/yabOxk)
[Group Rotations](http://codepen.io/larrybotha/pen/LRLZLm)

If it weren't for this issue I'd probably still be completely lost.

**Comment by 1deadpixl** [comment]
Wondering if we can reopen this issue. The `corner()` method doesn't seem to work as expected.

Admittedly, I'm new to the library, but I was expecting `rect.corner()` to draw the vertices starting from the top-left corner. After creating a rectangle (with `new Two.Rectangle`), calling `corner()`, and drawing it, the rectangle is still positioned from its center point. I also checked the `vertices` property and it shows the vertices positioned from the center, not the top-left. `origin` shows as `(0, 0)` but that doesn't seem to have any effect on the vertices.

It would be helpful to hear the logic behind the thinking here. `corner()` seems counterintuitive and I don't think that manually specifying vertices should be necessary for a simple function as this.

Thanks for a great library! I look forward to using it more.

**Comment by jonobr1** [comment]
Ironically the higher level primitive shapes don't adhere to `corner` or `center` methods.

Rectangle specifically has a vector property, `origin`, that offsets the "center" point of drawing. Happy to reopen and would love to hear how you think it should work.
