### ISSUE TITLE
Add a text in polygons?

### ISSUE THREAD

**Issue by ColinUNCG** [jonobr1/two.js#145]
1. Can I add a text in polygons?
2. If yes, how to style them?

**Comment by jonobr1** [comment]
Unfortunately, Two.js doesn't support text. You can create outlined text in an SVG file and import that using Two.js `interpret` method. There is discussion to add it to Two.js though. See: https://github.com/jonobr1/two.js/issues/141

**Comment by ColinUNCG** [comment]
@jonobr1 Thanks.
