### ISSUE TITLE
Can we setup a "z-index" for a Polygon or a Group ?

### ISSUE THREAD

**Issue by ColinUNCG** [jonobr1/two.js#146]
The front Polygon (or Group) can cover the behind.

**Comment by jonobr1** [comment]
The `z-index` of a polygon or group is in the order that it's added to the scene. Here's an example of how to do that: http://jonobr1.github.io/two.js/examples/depths.html

**Comment by jonobr1** [comment]
I think it would be awesome to have a method like in Adobe Illustrator to bring an object to front / back.

**Comment by ColinUNCG** [comment]
Agree.  That method will be awesome. 
Thanks !!!
