### ISSUE TITLE
anyone play with "two.js" and "D3.js force" together? 

### ISSUE THREAD

**Issue by ColinUNCG** [jonobr1/two.js#147]
It looks like "two.js" conflicts with "D3.js force".  Can anyone get it working? or show us an example?
Thanks

**Comment by jonobr1** [comment]
As in this: https://github.com/mbostock/d3/wiki/Force-Layout ?

**Comment by jonobr1** [comment]
Sorry, that wasn't an answer to your question. I just wanted to know if this was the D3.js force you were referring to? I don't think there are any two.js examples on that page.
