### ISSUE TITLE
Microsoft Edge and gradient

### ISSUE THREAD

**Issue by off-border** [jonobr1/two.js#156]
Whin i'm trying to render element with gradient in Microsoft Edge browser i get the error:

    : Unable to set property 'length' of undefined or null reference ( two.js (4883,11) )

My code:

    shadow = two.makeCircle( 0, 0, ball.radius + 5 )
    shadow.linewidth = 0
    shadow.fill = two.makeRadialGradient( 0, 0, ball.radius + 5, new Two.Stop( 0.8, 'rgba(0,0,0,1)' ), new Two.Stop( 1, 'rgba(0,0,0,0)' ) )
    ...
    two.update()

But In Chrome and Firefox it's okay.

**Comment by jonobr1** [comment]
Thanks for posting the issue! I'm going out to buy a Windows Machine today. I'll get back to you shortly with a fix.

**Comment by jonobr1** [comment]
The latest build on the `master` should have this fixed. Thanks for reporting!
