### ISSUE TITLE
Two.js View Box Rendering Area

### ISSUE THREAD

**Issue by tkellehe** [jonobr1/two.js#157]
Hello,
I have been currently using Two.js as a renderer for a simulator due to its smooth capabilities at handling SVG elements allowing events to govern the update loop of the simulator. When handling this, I needed a way to restrict the rendering space within multiple browsers. The majority of browsers handle the viewing area nicely by modifying the Two object controlling the space, but (not to any surprise) IE was unable to keep the objects within the space. I am merely bringing this up to help with the consistency between browsers for Two.js. Unfortunately, I am unable to provide the hack used to handle the transformations to allow the re-sizing of the rendering space for Two.js, but the IE hack to keep objects from drawing outside the viewing space is quite simple. So, the fix for this is to place the styling ```overflow: hidden;``` on the svg element the Two object controls. That allows the rendering space for the Two object between browsers to appear the same.

P.S. Great job on this library!!!

**Comment by jonobr1** [comment]
Thanks for sharing! Making a consistent experience across browsers is definitely an interest for the project. I'll add this simple fix.

**Comment by jonobr1** [comment]
Okay, the `overflow` property is set to `hidden` by default in the `master` branch. See this commit as ref: https://github.com/jonobr1/two.js/commit/b937d35a9a7b9d06ee7434605aaa0dc66e00cc6d
