### ISSUE TITLE
Issue with Two.Polygon

### ISSUE THREAD

**Issue by captainill** [jonobr1/two.js#158]
I am getting this error using `makePolygon`

http://jsfiddle.net/j1tdL0ap/2/

`Error: Invalid value for <path> attribute transform="matrix(NaN NaN NaN NaN NaN NaN)"`

I'm new to the library and was getting the issue using `Two.Polygon` so I thought I'd try `makePolygon` to be sure I wasn't doing something funky. Here's a bit more pseudo code showing what I'm trying:

```
    this.two = new Two({
      fullscreen: true,
      autostart: true
    }).appendTo(document.body);
    this.tileHeight = 16;
    this.tileWidth = 32;

    let size = {
      width: this.tileWidth,
      height: this.tileHeight
    }

    let tile = new Two.Polygon([
      new Two.Anchor(0, size.height / 2),
      new Two.Anchor(size.width / 2, 0),
      new Two.Anchor(0, -size.height / 2),
      new Two.Anchor(-size.width / 2, 0)
    ]);
    this.two.add(tile);
```

**Comment by jonobr1** [comment]
Ah, this is because:

As of `v0.5.0` (the version you're using) `Two.Polygon` and `two.makePolygon` refer to making an N-Sided symmetrical shape. In order to make what _was_ a `Two.Polygon` please use `Two.Path` and `two.makePath`. Sorry about the confusion!
