### ISSUE TITLE
Pan and Zoom

### ISSUE THREAD

**Issue by adamdburton** [jonobr1/two.js#16]
This is a question rather than an issue but it's the best place to ask.

I'm trying to add a pan and zoom feature to the game I'm making (with two). I've got the pan working fine, but i'm struggling with the zoom. Would some kind person mind giving a quick example of how to zoom the scene to the mouse coordinates like Google Maps please?

**Comment by meetzaveri** [comment]
@adamdburton Hey, I would like to know that how did you implemented Pan feature?

**Comment by jonobr1** [comment]
As asked in https://github.com/jonobr1/two.js/issues/519, here's an updated example with the panning implemented as well. https://github.com/jonobr1/two.js/issues/519
