### ISSUE TITLE
How can I use requirejs to call two.js in build folder?

### ISSUE THREAD

**Issue by moliqingwa** [jonobr1/two.js#162]
Like that:

require.config({
    paths: {
        jquery: 'jquery-2.1.4',
        backbone: 'backbone-min',
        two: 'two_dev',
        underscore: 'underscore'
    },

    shim: {
        underscore: {
            exports: '_'
        },
        backbone: {
            deps: ["underscore", "jquery"],
            exports: "Backbone"
        },
        two: {
            deps: ['underscore', 'backbone'],
            exports: 'two'
        }
    },

});

require(['two'], function() {
    var two;
    var $window = window;
    $(function() {
        var elem = document.querySelector('#test');
        var params = {
            width: elem.getBoundingClientRect().right - elem.getBoundingClientRect().left,
            height: elem.getBoundingClientRect().bottom - elem.getBoundingClientRect().top,
            type: Two.Types.webgl
        };
        two = new Two(params).appendTo(elem);
    });
});

Any suggestions, tks:)

**Comment by jonobr1** [comment]
Thanks for posting this! If you get the latest builds from the [dev branch](https://github.com/jonobr1/two.js/tree/dev/build) there will be an updated version of Two.js to be compatible with require.js. The usage unfortunately will have to be like this:

````
require.config({
  paths: {
    two: 'path/to/two-js/two'
  }
});

require([
  'module1',
  'module2',
  'two'
], function(m1, m2) {

  // Two is available because it is populated in the global namespace
  var two = new Two({ fullscreen: true }).appendTo(document.body);

});
````

Hope this helps!

**Comment by moliqingwa** [comment]
Thanks for your quick response, it's really a great help:)
