### ISSUE TITLE
Question: How the doc is build?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [jonobr1/two.js#163]
Hello @jonobr1!

Awesome job for two.js, and even more for the documentation!
http://jonobr1.github.io/two.js/#two-class

Was wondering what you where using to build it?
Is is built from comments/doc in the code? And if so, how do you do that? 

Best regards and thanks for your future answer :smiley:

**Comment by jonobr1** [comment]
Sorry for the delay! Thanks for the question! Unfortunately the documentation is generated by hand............ :-1:

**Comment by AdrieanKhisbe** [comment]
where is the source? That i have a look to it :smiley:

**Comment by jonobr1** [comment]
You can just view the page source on the HTML page. I hand wrote everything
you see there.

**Comment by AdrieanKhisbe** [comment]
Okey Dokey. Tahanks for the answer
