### ISSUE TITLE
Mobile code for zoom example

### ISSUE THREAD

**Issue by rupl** [jonobr1/two.js#168]
Hey again, I have been really enjoying this library! I have a site which is strikingly similar to your [zoom example](http://jonobr1.github.io/two.js/examples/zui.html). primarily aimed at touch users, it's a shared drawing space that people create shapes on, then manipulate them via touch. I just switched over to using two.js to draw the shapes (before I was just using DOM nodes + CSS Transforms).

Once I had two.js running, I set out to make the canvas pan/zoom-able. I thought maybe the code could serve as a starting point for the zoom example. Here's the PR for my project which relies on hammer.js to handle touch interactions, and two.js to draw the scene: https://github.com/rupl/bustashape/pull/24 — if you want I can try porting it into your existing zoom example.

**Comment by jonobr1** [comment]
Hey @rupl,

Glad you like the project! Your project sounds very cool and ambitious. I checked out the sandbox on my phone (iPhone 6 / Chrome) and it's cool, but I don't think it works correctly. Your origin is always bound to the upper left corner of something, maybe it's the SVG document or maybe it's the screen — I can't tell.

I feel like it should be bound to the midpoint between the two touch points that are creating the `pinch-to-zoom`. Are you suggesting that you'd add `hammer.js` to the `zui.html` example or actually rewrite the logic of zui?

**Comment by rupl** [comment]
Yes you're right, it is implicitly bound to the top-left of the top-level group that holds the shapes.

I wouldn't rewrite the `zui.html` file, but yeah I thought maybe hammer could be used to add touch support. I'll mess around with my code a bit more to fix that issue with the origin and get back to you.

**Comment by rupl** [comment]
Is there a method for directly manipulating the `two.scene._matrix` object or are there bad consequences? I see the object when I inspect my top-level [`Two.Group`](https://jonobr1.github.io/two.js/#two-group), but the underscore makes it feel like an internal store that I shouldn't touch.

I've come much closer to creating an intuitive gesture, but right now I'm accomplishing it by calculating my own matrix: `transform="matrix(scaleX 0 0 scaleY x-scaleX*x y-scaleY*y)"` and applying it to the `Two.Group` DOM element directly (stepping around two.js) [as described in this SO answer](http://stackoverflow.com/a/6714140/175551). While it works for pinches, it means calculating basic panning is complicated compared to using the `translation.set()` provided by Two, since direct DOM manip causes the `two.scene.translation` data to become out of sync with each gesture.

**Comment by rupl** [comment]
After digging around SO a bit more I found your answer to another poster: http://stackoverflow.com/a/29615068/175551

`_matrix.manual` seems to be the answer!

If I have further support questions I will be sure to ask on SO and tag it properly so a wider audience has access to the answer.

**Comment by jonobr1** [comment]
Yep, `_matrix.manual` is the way to go!
