### ISSUE TITLE
Electron and requestAnimationFrame()

### ISSUE THREAD

**Issue by tstrokes** [jonobr1/two.js#169]
I'm trying to use twojs in an Electron Application but I'm running into the following error:
`requestAnimationFrame not a function`. Any advice would be appreciated. This may inform the discussion: https://discuss.atom.io/t/requestanimationframe-not-a-function-error/23089/1. Not sure how to fix this for twojs though.

**Comment by jonobr1** [comment]
Thanks for the message @tstrokes. I'm not familiar with Electron, but looking at that thread it looks like `window` doesn't have the same properties as a typical browser `window`. Try giving the `dev` branch a try. Let me know if that works or doesn't.

**Comment by tstrokes** [comment]
Unfortunately, I have the same error with the dev branch. Would there be anyway to install the dev branch with npm?

**Comment by jonobr1** [comment]
Ah, sorry that didn't work... I made a new issue to stop using third party libraries (https://github.com/jonobr1/two.js/issues/171). It sounds related.

Another thing to try in your script is to define a global `window` variable as an object. This way `request animation frame` can export to it and also be discovered through it.

**Comment by Nirlah** [comment]
@tstrokes have you found any solution?

**Comment by tstrokes** [comment]
I didn't pursue this very much because I put my project on hold.

**Comment by OwenOrsini** [comment]
This will work with Electron if you change `requestAnimationFrame` to `window.requestAnimationFrame` here (https://github.com/jonobr1/two.js/blob/master/build/two.js#L3756).

**Comment by jonobr1** [comment]
Thanks for the info @OwenOrsini. I wonder why it's only compatible with `v0.5.0` and not `v0.6.0+`. I have removing 3rd parties as a milestone in `v0.7.0`, maybe that will help.

**Comment by OwenOrsini** [comment]
Looks like there is some problem with scope Two is on. It seems `This.Two` is undefined and Two is only defined on the Window `window.Two`. 

So I can get this to work with the current version if I change `this.Two` to `window.Two`. Im not really sure how this would work otherwise since `this.Two` is never defined but I haven't really delved deeper into this yet.

**Comment by skyrpex** [comment]
Maybe I could lend a hand on this...

I would convert the modules into proper CommonJS modules. Those could be used by Node directly, or be compiled (with Webpack, for instance) into a single bundle (optimized for browsers).

I believe it would solve the current problem.

**Comment by jonobr1** [comment]
That would be fantastic @skyrpex! I've tried to export out the two.js object and it's related classes, but seems like I keep doing it incorrectly.

**Comment by jonobr1** [comment]
Any updates on this? I've completely removed third-party dependencies in Two.js.

I think this should resolve the problem and work with electron, but not totally sure. If someone could check or show me how to check then I'll give it a go. Thanks!

**Comment by jonobr1** [comment]
Also, I've removed `requestAnimationFrame` on import. `requestAnimationFrame` now only initializes if you set `autostart: true` on an instance of Two.js.

**Comment by jonobr1** [comment]
<img width="1280" alt="screen shot 2018-04-04 at 7 53 07 am" src="https://user-images.githubusercontent.com/220033/38315382-3abb793c-37dd-11e8-90d4-a638182a49a0.png">

This fix is confirmed on the `npm latest` of `two.js`: https://www.npmjs.com/package/two.js
