### ISSUE TITLE
path.beginning and path.end question

### ISSUE THREAD

**Issue by captainill** [jonobr1/two.js#170]
I've been able to animate a stroke around a path by keeping `path.beginning` at it's default and incrementing `path.end` from 0 to 1. I'd like to animate both the beginning and end though to allow for animation that looks like this:

![colicons](https://cloud.githubusercontent.com/assets/438899/12934715/82ed2ece-cf45-11e5-976e-59aedd68cc25.gif)

I'm getting an error setting `path.beginning` and I'm not sure why because I assumed I could set it just like `path.end`
`Error: Invalid value for <path> attribute d="L...`

Seems like I'm missing fundamental. I can provide an example if needed. Would love any possible guidance!

**Comment by jonobr1** [comment]
Thanks for posting! This sounds like a bug on my end. Do you have a potential example online I could test on?

**Comment by jonobr1** [comment]
Also, does switching the renderer change the error? Try starting up two.js with the type param as `Two.Types.canvas`:

````
var two = new Two({
  type: Two.Types.canvas
});
````

**Comment by captainill** [comment]
Ah! Very cool. Using `type: Two.Types.canvas` has it working as expected.

I'll try and create a jsfiddle tomorrow to illustrate the error using SVGs although for my purposes canvas works just as well!

**Comment by jonobr1** [comment]
Great to hear! If that's the case then there's something wrong with the SVG
renderer. If you don't mind putting an example up then I can work on fixing
it. Happy coding!

**Comment by sneaknz** [comment]
I'd love to see the example also — sounds exactly like something I'm trying to do!
