### ISSUE TITLE
Remove Third Party Dependencies

### ISSUE THREAD

**Issue by jonobr1** [jonobr1/two.js#171]
The third parties we use are great! However, it adds complication to the portability of the library. As such create internal functionality to reproduce this. Other benefits include: speeding up events for per frame usage, running two.js in windowless environments like browserify, and reorganizing how request animation frame and update logic coexist to be more data-to-rendering agnostic.

**Comment by arodic** [comment]
Happy place :)

**Comment by jonobr1** [comment]
:+1:

**Comment by larrybotha** [comment]
For underscore, some of the helpers will likely still be helpful, but you'd not want to import the entire library.

Replacing underscore with lodash/fp and ES6 allows one to import only the code associated with a specific module, which will drastically reduce compiled file size, while eliminating the need for rewriting all the functionality (unless replacing simple map / filter / reduce functions):

```javascript
import shuffle from 'lodash/fp/shuffle'; // only import shuffle and its deps

const myArr = [1,2,3,4];
const shuffledArr = shuffle(myArr);
```

**Comment by jonobr1** [comment]
This is updated in the current `dev` branch.
