### ISSUE TITLE
Custom attributes

### ISSUE THREAD

**Issue by HorizonShadow** [jonobr1/two.js#172]
I imagine there's a way to do this, but I can't find it for the life of me.

I want to add my own attributes to the rendered objects. For example, if I'm rendering an SVG, to add `stroke-dasharray` as an attribute. 

There's nothing about it in the docs, the close`st thing I came across was `manual` as a last parameter in `Path`, but this isn't available in `Polygon` for me to try.

**Comment by jonobr1** [comment]
You sure can! Here it is:

````
var path = two.makePath(...);
two.update(); // You have to force the renderer to update so the element will be created.
var elem = path._renderer.elem; // The SVG Element
elem.setAttribute('custom-attr', customValue);
````

Hope that makes sense!

**Comment by HorizonShadow** [comment]
Ah, wonderful. Thank you very much.
