### ISSUE TITLE
SVG Renderer, Translation and Scale result in jittery shapes

### ISSUE THREAD

**Issue by mascha** [jonobr1/two.js#173]
When using 
a) the two.scene with translation and scale 
b) the svg renderer

two.js displays erratic behavior in that objects which are far from the origin (x=0,y=0) start to 'jump' around slightly. This disappears with the canvas renderer.

**Comment by jonobr1** [comment]
Thanks for reporting! Do you have an example online that I could look at? Or maybe more information of browser and OS you're finding this?

**Comment by triLithium** [comment]
After a reimplementation and correct integration with angular2 I could not reproduce the aforementioned behavior. Before I simply added the two.renderer.domElement to the angular dom, which does seem to work well with it's caching capabilities. The SVG element then directly influence the other layers, resulting in repeated relayouts during zoom ( which results in jittery behavior)

So I think this should be closed for now.

**Comment by jonobr1** [comment]
Glad to hear it worked out!

**Comment by triLithium** [comment]
Sadly the jittery behavior resurfaced. I'm working on a small demo as an example.
