### ISSUE TITLE
Tween.js can't tween all properties.

### ISSUE THREAD

**Issue by elliottregan** [jonobr1/two.js#174]
Specifically, I can't get `scale` tweening to work, or `rotation`. 

Also, I sometimes need to tween `_opacity`, as opposed to `opacity`... Any suggestions as to why? I have a feeling this is related.

**Comment by jonobr1** [comment]
Which Tween.js are you using? Those are all getters / setters so if you want to affect them your destination needs to be a plain object not a Two.js class.

If you have an example I can help you out further. Thanks for posting!

**Comment by elliottregan** [comment]
Thanks for getting back!

I'm using http://github.com/tweenjs/tween.js

Example code: http://codepen.io/elliottregan/pen/mVGQgw

If you look at my Tween on line 319 of the JS file:

```javascript
    var showBlobTween = new TWEEN
      .Tween(blob)
      .to({
        _opacity: 1
      }, 2000)
      .easing(TWEEN.Easing.Sinusoidal.InOut);
    showBlobTween.start();
```

I found that I could tween `_opacity`, but not `opacity`. I also can't tween `_scale` or `scale` (or `rotation`, for that matter): 

```javascript
    var showBlobTween = new TWEEN
      .Tween(blob)
      .to({
        _opacity: 1,
        _scale: 1
      }, 2000)
      .easing(TWEEN.Easing.Sinusoidal.InOut);
    showBlobTween.start();
```

My solution for tweening other properties (based on the Tween.js example you provided) was to update the rotation in the `onUpdate()` callback elsewhere, but any easing needs to be handled manually (and the code starts to get really ugly at that point).

**Comment by elliottregan** [comment]
I guess it seems like `.translation` is the only property that can be tweened with Tween.js?

**Comment by jonobr1** [comment]
Your Codepen works well! Though I didn't see any usage outside of changing vertices. Here's a [jsfiddle](https://jsfiddle.net/jonobr1/72bytkhm/) showing that it's quite simple to affect `rotation`, `scale`, and `opacity`. Just make sure you're passing the right object when you want to manipulate it.

**Comment by rupl** [comment]
Just a heads up for anyone who stumbles upon this issue/Fiddle, the copy of tween.js used in the JSFiddle is three years old and isn't compatible with version 16, the current version you receive when getting the code from GitHub, npm, etc.

Here's the copy referenced in the fiddle: https://github.com/tweenjs/tween.js/blob/f1bada896f9db67067184b98dcf689982a0a4c09/src/Tween.js

**Comment by jonobr1** [comment]
FYI I made a PR to fix this on Tween.js: https://github.com/tweenjs/tween.js/pull/291

Please thumbs up it if you'd like to have it merged.

**Comment by rupl** [comment]
nice! Good to know that the fix is so simple even if they don't accept the PR.

**Comment by jonobr1** [comment]
FYI: I also made `Object.defineProperty` within Two.js `enumerable` so it shows up in Tween.js. If you use the `dev` branch the properties mentioned above should work.
