### ISSUE TITLE
Using Hammer.js to control Two.js SVG

### ISSUE THREAD

**Issue by eoinmurphy** [jonobr1/two.js#177]
Hi Jono,

I have asked a question on Stackoverflow that you may be able to answer. You said in a previous comment on SO to post any issues here because you get emailed directly. So here's the question: http://stackoverflow.com/questions/36002234/controlling-two-js-svg-with-hammer-js

Big presentation on Wednesday that I could really do with having Hammer.js working, so any insights would be greatly appreciated. 

Again, thanks so much for your awesome library and work.

**Comment by jonobr1** [comment]
I just posted some comments to the SO post. We'll continue the conversation there.
