### ISSUE TITLE
Chrome throws deprecation message: CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

### ISSUE THREAD

**Issue by Friksel** [jonobr1/two.js#178]
Using two.js Chrome throws this deprecation message:
```
CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.
```

According to a thread here: https://github.com/kangax/fabric.js/issues/2047 this message is probably not the most timeconsuming thing to leave out of (the most recent) Chrome by using this:
```
if (typeof(ctx.imageSmoothingEnabled) !== 'undefined') {
  ctx.imageSmoothingEnabled       = this.imageSmoothingEnabled;
  return;
}
```

**Comment by jonobr1** [comment]
Thanks for posting. This issue is fixed in the [dev branch](https://github.com/jonobr1/two.js/commit/011f5a6de98336ab69c873629086282ab11af038)!

**Comment by Friksel** [comment]
Nice!
