### ISSUE TITLE
the png image not work in two.js

### ISSUE THREAD

**Issue by lzf1201** [jonobr1/two.js#179]
i have use your code

    var elem = document.getElementById('orgChart');
    var params = { type: Two.Types['canvas'], fullscreen: true, autostart: true };
    var two = new Two(params).appendTo(elem);
    var img = document.createElement('img');
    img.onload = function() {
      var sprite = two.makeRectangle(two.width / 2, two.height / 2, 50, 50);
      sprite.image = img;
      sprite.width = sprite.height = 25;
    };
    img.src = './image.png';

    two.update();
two.js version 1.8.3
but ,the image not show in ie11 or chrome.
please help me,thank you

**Comment by jonobr1** [comment]
Sprites have yet to be implemented... Sorry about this! It is on my next milestone.
