### ISSUE TITLE
Example behaving like CAD

### ISSUE THREAD

**Issue by knottech** [jonobr1/two.js#181]
I've created an example: [dwgjs](http://www.iknot.org/dwgjs) which is used to make geometries like CAD. Would you please consider to add it to the example or project list? Thanks.

**Comment by compmeist** [comment]
Great work and potential here!  All that is needed now is a collection (or list) of some sort to contain the references to the objects, perhaps using underscore.

**Comment by jonobr1** [comment]
Nice @knottech! I'm traveling at the moment, but will add it the next time I update two.js.
