### ISSUE TITLE
Path Rotate Around Point?

### ISSUE THREAD

**Issue by QuinDennis** [jonobr1/two.js#185]
I can't seem to find a way to rotate a Path around a specific x,y point.  Am I missing something?  Is that a planned feature?

**Comment by jonobr1** [comment]
`Two.Path`s inherently rotate around a point, the center of itself. To change this all you need to do is add or subtract a vector to all the vertices of a `Two.Path`. e.g:

````javascript
var offset = new Two.Vector(100, 0);
for (var i = 0; i < path.vertices.length; i++) {
  var v = path.vertices[i];
  v.add(offset);
}
````

Full example here: https://jsfiddle.net/jonobr1/h0rbm7ny/3/

In addition to this there are convenience functions for anchoring your object to the center or the upper-left corner: `path.center();` and `path.corner();`

There is some talk about figuring out a more intuitive way to handle this. If you have any thoughts I'm all ears!

**Comment by larrybotha** [comment]
For anyone looking for a demo where they can easily tweak values I've put together a Codepen:
http://codepen.io/larrybotha/pen/yabOxk

**Comment by meetzaveri** [comment]
@larrybotha Thanks for the codepen link
