### ISSUE TITLE
Would it be hard to add shaders to the WebGL output as a post effect?

### ISSUE THREAD

**Issue by 0x80** [jonobr1/two.js#186]
I'm new to two.js and webgl in general but I'm wondering if it would be technically challenging to add shader effects to the two.js output when it's rendering to webgl output. I was thinking about adding it as a post rendering effect on the whole output frame.

Is there a way to hook into the final output (framebuffer?) and append shaders to the rendering pipeline?

**Comment by jonobr1** [comment]
There is currently not a way to append things to the FBO.., but you're more than welcome to overwrite the shader entirely. There aren't any convenient ways to modify / add / delete attributes or uniforms on a shader in Two.js either.

Despite this you have full access to the gl context through `two.renderer.ctx`. Here is where the shaders are defined and you can override them: https://github.com/jonobr1/two.js/blob/master/src/renderer/webgl.js#L887

Before instantiating your instance of `Two` overwrite the shader like so:

````javascript
Two[Two.Types.webgl].Utils.shaders.vertex = anotherVertexShader;
Two[Two.Types.webgl].Utils.shaders.fragment = anotherFragmentShader;

var two = new Two({ autoplay: true }).appendTo(document.body);
````

__Make sure you have the latest release or development version of Two.js for this to access to work.__ I just added it so you can manipulate this. Here's a working example: https://jsfiddle.net/jonobr1/o5657u0t/2/

If you have thoughts on ways to make this easier I'd love to hear them! I do a fair amount of this type of FBO shader interaction in this project: http://tether.plaid.co.uk/ but used three.js to do the FBOs.

**Comment by 0x80** [comment]
Awesome! 

I think for now I have to avoid webgl because it doesn't perform well for the kind of animation I'm trying to do, but it's good to know that this is quite possible already.
