### ISSUE TITLE
How to create fill patterns

### ISSUE THREAD

**Issue by 0x80** [jonobr1/two.js#187]
I'm working on an audiovisual composition which currently uses plain SVG output. I'm hitting a CPU bottleneck so I want to convert it to Two.js in order to render to Canvas or WebGL. I've been comparing Two.js with Fabric.js and Paper.js and decided that I like this library better for its clean API and also I don't need all of the interactivity that the others have.

The only thing that I'm missing in comparison to the other libraries is the ability to fill shapes with patterns. Is there a way to programmatically create fill patterns (textures?) in Two.js?

**Comment by jonobr1** [comment]
Currently, textures aren't supported. I'm trying to get them done by the end-of-the-year. It's quite a big set of features which I'm really excited about and will bring Two.js closer to a `v1.0` release.

However, depending on the context you're dealing with you can get direct access to the underlying draw calls and do your own texturing. It will take me awhile to make an example of this, but if you let me know which context you wanna try it with then I can help you out further.

**Comment by 0x80** [comment]
That's great. Thanks for offering your help. I will probably target svg, but I will get back to you when I'm ready. 

Good to hear that you'r actively working towards a 1.0 release. The amount of commits in that past year made me wonder how actively it is developed still. Hopefully when I get more into it I can help out a bit.
