### ISSUE TITLE
resizing two.js

### ISSUE THREAD

**Issue by skillzzjesse** [jonobr1/two.js#191]
I need to resize the canvas/svg two.js creates. I've tried setting the css, and even the height and width attributes of the svg element. This works, the svg changes size **BUT**, ``two.width`` and``two.height`` remain the same.

I've read trough your documentation but can't seem to find any methods of achieving what I want. 
_Please note that I'm **not** running two.js in fullscreen mode_

(I need this functionality for a webapp i'm making (the canvas should be the size of the parent div) )
**Note:** By canvas I mean the drawing space two.js creates. 

**Is there a way?** :innocent:

**Comment by lesander** [comment]
Set the svg element to width `100%` and height `100%`?

**Comment by jonobr1** [comment]
Indeed there is! Sorry that this is buried. I should add a convenience method on `Two` itself, but you can resize by:

````
two.renderer.setSize(width, height);
````

**Comment by jonobr1** [comment]
Ah, though will you need to set `two.width` and `two.height` manually still. Those are convenience properties, they don't actually do anything.

**Comment by skillzzjesse** [comment]
Thanks a lot! Time to continue the project! :laughing:
