### ISSUE TITLE
two.js domain

### ISSUE THREAD

**Issue by skillzzjesse** [jonobr1/two.js#192]
This issue is merely a hint about the [dns.js.org][1] domain.
I thought it might be cool to have **two.js.org** as domain. So here it is.  Do with it what you want :smile: 

[1]: https://js.org

**Comment by jonobr1** [comment]
I can't tell for sure, but it looks like from the way things are setup that it would actually make `two.js.js.org`, did I read that correctly?

**Comment by skillzzjesse** [comment]
Yeah if you were to do ```repo-name.js.or``` you would indeed get ```two.js.js.org```. However I do think it would be possible to request ```two.js.org```. I did a quick search through the current list of registred subdomains and ```two``` is not yet taken. 

Let's ask the one in charge :smile: 

See [the issue I created][1].

[1]: https://github.com/js-org/dns.js.org/issues/832

**Comment by jonobr1** [comment]
Awesome, thanks!

**Comment by skillzzjesse** [comment]
He responded, please see the issue I created and listed above. :smile:

**Comment by skillzzjesse** [comment]
Question: Are you actually going to add the CNAME? :wink:

**Comment by jonobr1** [comment]
Updated! Thanks!
