### ISSUE TITLE
Complex path with anchor handlers

### ISSUE THREAD

**Issue by Samvherck** [jonobr1/two.js#194]
Hello, I'm starting a new small drawing project and after doing some research and studying the documentation I still cannot figure out how to create complex paths with a combination of lines and rounded shapes. After that I'm planning to put handle points on every anchor and depending on the shape that they are on going to have a different impact on the path when dragging them. (anchor at the top of the circle/arc will act like https://jonobr1.github.io/two.js/examples/advanced-anchors.html)

At the moment I have closed path with all straight lines. Is it possible to create paths like the example beneath? Any help/suggestions are appreciated.

![1](https://cloud.githubusercontent.com/assets/11502660/18742275/8cf4ecde-80b3-11e6-8900-7c21a696d13a.png)

**Comment by jonobr1** [comment]
Thanks for posting the question! You make a great point in that I haven't made a good example to show this off, but you can certainly do this in Two.js. Here's how: https://jsfiddle.net/jonobr1/bkcwe1fr/

Unfortunately, it's a bit complicated. Lemme know if you have any further questions.

**Comment by Samvherck** [comment]
Thanks jonobr1, that was exaclty what I was looking for!
