### ISSUE TITLE
Creating a path without anchors throws an error

### ISSUE THREAD

**Issue by ponychicken** [jonobr1/two.js#195]
I would like to create a path that will be filled with anchors later on.
````
let path = two.makePath([], true)
````
This throws (a harmless) error when trying to assign a NaN matrix as the transform attribute of the path object. This is caused by path.getBoundingClientRect() return an invalid matrix.

**Comment by jonobr1** [comment]
Nice to hear from you @ponychicken! This is a great find. I'll have to go in and fix it. You should be able to do something as you described as well as:

````javascript
var path = two.makePath();
// Maybe even..?
var path = two.makePath(true); // Closed with no anchors. 
````

**Comment by jonobr1** [comment]
Latest dev branch fixes this issue. Thanks for reporting! https://github.com/jonobr1/two.js/commit/81958290af97d3f8eb0556f9835ae5be657cd586

**Comment by ponychicken** [comment]
Great! thanks - and have a nice weekend!
