### ISSUE TITLE
Clickable path borders

### ISSUE THREAD

**Issue by Samvherck** [jonobr1/two.js#198]
Hello, I've created a **complex path** (thanks to github.com/jonobr1/two.js/issues/194). Is it possible to only make the border clickable (with hover effect) without the path itself. 

Can this be done in a simple way or is this only possible by hard calculations: looping and storing all the paths lines/curves and check wether the click/hover event occurs on one of those points?

Thanks.

**Comment by jonobr1** [comment]
Yes, it's possible with the SVG Renderer: https://jsfiddle.net/jonobr1/e2uvusf7/

**Comment by Samvherck** [comment]
Thanks for your answer, but is it also possible when the path is filled with a color/image?

**Comment by jonobr1** [comment]
Yes, just fill the object and then the whole thing is clickable.

**Comment by Samvherck** [comment]
Sorry for not making myself clear, what I'm trying to accomplisch is that the border (linewidth) of a filled path is the only thing clickable and not the inside of the that path. Is this possible or should I start working with multiple layers to create an effect like this? Thanks.

**Comment by jonobr1** [comment]
Ahhh, yes unfortunately you have to make two objects. One that is just the stroke that has the click event and another with the fill.
