### ISSUE TITLE
fill pattern

### ISSUE THREAD

**Issue by crf1111** [jonobr1/two.js#199]
I want to show something like following images with two.js :  
![selection_045](https://cloud.githubusercontent.com/assets/2977266/19211816/401dd3c2-8d78-11e6-96a3-1edc1e276c6e.png)
![selection_046](https://cloud.githubusercontent.com/assets/2977266/19211817/4027fb18-8d78-11e6-9a13-c0f6f153c2ff.png)

Can I use twojs to show these? And how can I do that with twojs? Can someone give me an example ?  
Thanks a lot. @jonobr1

**Comment by jonobr1** [comment]
Thanks for posting @crf1111! There are many ways you can go about drawing these in Two.js. To get a better sense of which method would be best can you explain a little bit more what you'd like to do with these?

**Comment by jonobr1** [comment]
The latest `dev` branch allows you to do this type of pattern really easily. Like so: https://jsfiddle.net/jonobr1/decupu9f/
