### ISSUE TITLE
Add anchors to existing path

### ISSUE THREAD

**Issue by Samvherck** [jonobr1/two.js#202]
Hello, I'm looking for a way to add new anchor points to an existing path without having to recreate it.

My path is created by filling an array with anchor points:

```
var points = [];
var M = new Two.Anchor(0, 100);
var O = new Two.Anchor(300, 100);

M.command = Two.Commands.move;
O.command = Two.Commands.line;

points.push(M);
points.push(O);

var path = new Two.Path(points, true, false, true);
```

When creating a new anchor and adding it to a specific index I get an error:

```
var newAnchor = new Two.Anchor(50, 50);
newAnchor.command = Two.Commands.line;
						
path.vertices.splice(0, 0, newAnchor);

ERROR: error: <path> attribute d: Expected number, "M 0 100 L NaN NaN L 300 10…".
```
As you can see the x and y coordinates (50) get inserted as NaN's, it is possible to just add it to the points array and recreate the whole path but I'm trying to avoid this.

**Comment by jonobr1** [comment]
That should totally work! Thanks for posting this, this is a bug. I've fixed it in the `dev` branch: https://github.com/jonobr1/two.js/commit/bdb4e9804c41528b05014ccbac92aeca6c8fe7d5
