### ISSUE TITLE
Text along a path?

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#203]
For example, how can we do text along a path like in [this SVG example that uses `<textPath>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath)?

**Comment by jonobr1** [comment]
Thanks for posting this @trusktr! At the moment there isn't a way to do this, however you always have access to the underlying SVG element if you're rendering in that environment:

````javascript
var shape = two.makeRectangle(two.width / 2, two.height / 2, 50, 50);
two.update();
shape._renderer.elem // svg element which you can add your own attributes to.
````

I haven't yet, but I'll make a demo for you tomorrow with this working. It'll be great to add this to the library in the future, I didn't know about this API. Thanks!

**Comment by trusktr** [comment]
Awesome, would love to see this API with the WebGL renderer. The reason I was wondering in the first place is because the SVG engine is getting a little slow when I'm rendering a bunch of text on different paths and using masks created using [this technique](https://bl.ocks.org/mbostock/4163057) with a high precision where the masks also follow the same path as the text.

I was hoping I might be able to do it with the WebGL renderer for (hopefully) performance gain.

**Comment by jonobr1** [comment]
Sounds interesting! If you post an example of what you're working I may be able to help point you out in how to squeeze the most out of performance. Until then you can see how to do texts on path with the SVG Renderer like so:

https://jsfiddle.net/jonobr1/vakhyq95/

Hope this helps!
