### ISSUE TITLE
Adding anchor-point before curve results in wrong path

### ISSUE THREAD

**Issue by Samvherck** [jonobr1/two.js#205]
Hello. Inserting a new anchor point before a curve results in an incorrect path. Somehow this new point alters the line even when it has the Two.command.line specified. It is also strange that when adding this point after the curve everthing works fine.

I've created a simple JSFiddler: http://jsfiddle.net/q0se42nm/3/

1. Click 1 time on window: Curve gets added.
2. Click second time on window: points get added as a line before the curve and results in a curved line.

When looking at the path.vertices everything looks fine so I'm not sure where it is going wrong.

![2016-10-28 13_06_51-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/11502660/19804618/b716d3a6-9d0f-11e6-87d0-11aa399d8f0d.png)

Newly added point has correct properties:

![2016-10-28 12_30_08-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/11502660/19803822/1e77909e-9d0b-11e6-9f47-2773ca90aaf1.png)

**Comment by jonobr1** [comment]
Thanks for posting this! You're totally right and there was a bug in all the renderers on how to handle this. Check out the latest dev branch for the fix: https://github.com/jonobr1/two.js/tree/dev
