### ISSUE TITLE
Text position is different between canvas and svg on iOS device

### ISSUE THREAD

**Issue by joyqi** [jonobr1/two.js#207]
I'm using two.js to render some text on iOS device, but I find that there is always a offset of y  coordinate between canvas and svg.

It is perfect when I'm using canvas

![2016-11-15 11 00 58](https://cloud.githubusercontent.com/assets/59437/20291784/9cae8320-ab23-11e6-9f2f-c5da659aa89d.png)

But the y coordinate  is wrong after I changed renderer to svg

![2016-11-15 11 00 44](https://cloud.githubusercontent.com/assets/59437/20291795/ba4242be-ab23-11e6-8aed-e87e0a92dda2.png)

**Comment by joyqi** [comment]
BTW, they are both correct on my PC (Chrome and Safari).

**Comment by jonobr1** [comment]
Thanks for posting @joyqi! Just curious, what text is that you're trying to render? Or maybe even better do you have a working example I can debug against?

**Comment by joyqi** [comment]
@jonobr1 please see this example
https://jsfiddle.net/8q2ym3mw/1/

**Comment by jonobr1** [comment]
It's interesting to hear that they're correct on your PC. They look incorrect for me on my MacBook.

<img width="1056" alt="screen shot 2016-11-16 at 11 25 40 am" src="https://cloud.githubusercontent.com/assets/220033/20362175/701a78b0-abef-11e6-93fb-d0e41259df6a.png">

I think the correct course of action is to apply a `SvgText.dy` attribute that is a percentage of the `Two.Text.size`. More info soon.

**Comment by joyqi** [comment]
Unfortunately, they are both incorrect for me now. The difference is very obvious in some cases.

In this url https://jsfiddle.net/8q2ym3mw/2/ , the offset is very small. I think it's refer to the baseline of the fonts they are using.

**Comment by joyqi** [comment]
Hi, I've found the solution. 

https://jsfiddle.net/8q2ym3mw/3/

Just change the `baseline` from `central` to `central`.

**Comment by jonobr1** [comment]
Awesome, thanks! I'll make sure there's an update in the `dev` branch for this. Please don't hesitate to share what you make as well!
