### ISSUE TITLE
How can I enable event bubbling?

### ISSUE THREAD

**Issue by Zac-Garby** [jonobr1/two.js#208]
Is it possible to enable event bubbling on a path? Specifically, I want a click event to bubble.

**Comment by jonobr1** [comment]
Thanks for the question! Click events are handled by SVG DOM Elements at the moment. If you're going off this example: https://two.js.org/examples/svg-events.html

Then bubbling works as you would normally bubble in DOM.

**Comment by Zac-Garby** [comment]
Okay, thanks :)
