### ISSUE TITLE
Add two small sample projects

### ISSUE THREAD

**Issue by DreaminginCodeZH** [jonobr1/two.js#210]
Hi! Thanks for the great library, and I've implemented two basic computer graphics demos with it. So I'm wondering if some of them can be useful as sample projects?

- https://github.com/DreaminginCodeZH/particle-system-campfire
- https://github.com/DreaminginCodeZH/collision-detection-bubbles

**Comment by jonobr1** [comment]
These are awesome! I'll add them. Thanks for posting 👍

**Comment by jonobr1** [comment]
Just updated! Nice work! https://github.com/jonobr1/two.js/commit/51cd8262efaedb4f4855fc3b9b30fd5549e45dfd
