### ISSUE TITLE
SVG interpretation with transform="matrix"

### ISSUE THREAD

**Issue by dasDaniel** [jonobr1/two.js#211]
I get this error  `<g> attribute transform: Expected number, "matrix(NaN NaN NaN NaN …"`
when using svg that have a transform matrix
is there anything I can do about this or is this a bug? 

`<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" baseProfile="basic" id="Layer_1"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="144px" height="144px"
	 viewBox="0 0 144 144" xml:space="preserve">
	<g transform="matrix( 0.800018310546875, 0, 0, 0.80010986328125, -601.55,-211.55)">
		<rect x="11.154" y="9.171" fill="#FFFFFF" stroke="#000000" stroke-width="3" stroke-miterlimit="10" width="28.455" height="28.455"/>
	</g>
</svg>
`

**Comment by jonobr1** [comment]
Thanks for posting. Just to clarify, you're importing that svg xml with Two.js and getting that error? If that's the case I'll recreate and get back to you. It _sounds_ like a bug, but can't confirm yet.

**Comment by dasDaniel** [comment]
I'm doing it by loading external file, but created a fiddle that uses local
https://jsfiddle.net/n5r623zy/

**Comment by dasDaniel** [comment]
I also noticed that the `scale(2)` isn't working and then tried `rotate(45)`, so it looks like none of the transforms may be working

**Comment by jonobr1** [comment]
Sorry for the delay! This was an error in Two.js' interpretation. It is now fixed in the `dev` branch: https://github.com/jonobr1/two.js/tree/dev
