### ISSUE TITLE
React Wrapper for two.js?

### ISSUE THREAD

**Issue by mindjuice** [jonobr1/two.js#213]
Is anyone aware of a React wrapper for two.js?  I'm thinking of something roughly like the following:

```
render() {
  return (
    <div>
      <Line x1={10} y1={20} x2={30} y2={40} width={2} color='#ff33cc'/>
      <Circle x={this.props.cx} y={this.props.cy} r={this.props.r} />
    </div>
  );
}
```

Essentially just thin wrapper components over the two.js calls to give you a declarative interface that lets you work with the normal React lifecycle.

I can't find anything like this, but it would be nice IMO.  I suppose that since two.js maintains its own internal representation that this would require a custom React backend like the ReactDOM or React Native to generate the equivalent of the virtual DOM and do the diffing.

_p.s. I've seen the examples of using React with two.js, but they are not simple functions from state to views like a good React component should be._

**Comment by jonobr1** [comment]
This sounds cool. I'm not aware of anything like this existing. Do you have a reference on what's the best way to make a wrapper like this? I'm not familiar with React, but I feel something like that should be doable. Would I look up React Wrapper or React Component for more info?

**Comment by mindjuice** [comment]
From a cursory look at the code, something like [`react-canvas`](https://github.com/Flipboard/react-canvas) seems like it would be one way to do it, although perhaps not the best way.  The overhead seems higher than I would hope.

**Comment by mindjuice** [comment]
Actually, [react-konva](https://github.com/lavrton/react-konva) is more like what I imagined.

**Comment by jonobr1** [comment]
Interesting! As far as a usecase are you looking to declaratively define Two.js primitives or your own custom shapes?

Are there libraries like the two you mentioned that are SVG and not canvas based? If react is about manipulating DOM then maybe SVG is the way to go.

**Comment by mindjuice** [comment]
I was primarily thinking of declaratively creating Two.js primitives.  If Two.js was supported in React JSX, custom shapes could easily be built on top.

It's pretty straightforward to manipulate SVG with React already.  Libraries like `victory.js` combine the math of d3 with SVG to make declarative graphs in React.  With `react-konva` you get a similar ability to declaratively define canvas rendering as well.

What I love about Two.js is that you can easily switch from canvas to SVG to WebGL with the same code.  The problem, if I might characterize it as such, is that the Two.js API is imperative and doesn't fit well into the same declarative view lifecycle of React.

Being able to declaratively define Two.js shapes in React JSX would provide a nice abstraction and make it easy to switch between the three render targets.

You're partially right that React is about manipulating the DOM.  However, the React concept can be applied to other "backends".  This is what React Native does.  It gives you the same declarative interface, but for mobile apps on iOS and Android instead of the DOM.

I haven't delved too deep yet, but I can imagine a React backend for Two.js would work with the internal scenegraph.  We would implement a scenegraph diffing capability, and code to make the minimum changes from the current scenegraph to the new scenegraph in the same way React diffs one virtual DOM against another from one render call to the next and then makes the minimal mutations for efficiency.

Declarative animation would require some additional thought (React has ReactCSSTransitionGroup, but it's a bit awkward and relies on CSS animation).

**Comment by jonobr1** [comment]
Ahh, thanks so much for the clarification, @mindjuice. Yeah, this does sound like we could come up with some JSX nomenclature for primitives (e.g: `<two-circle x="0" y="0" radius="10" />`) and then some middleware which you're referring to as a wrapper to pass that code to Two.js to render. So a potential JSX "scene" could look like:
````javascript
<two-renderer type="svg" width="100" height="100" autostart="true">
      <two-line x1={10} y1={20} x2={30} y2={40} width={2} color='#ff33cc'/>
      <two-circle x={this.props.cx} y={this.props.cy} r={this.props.r} />
</div-renderer>
````
Which is pretty much restating what you described in your first post. That sounds cool!

**Comment by trusktr** [comment]
This would be really awesome! It means we could switch the Two.js renderer between SVG, Canvas, WebGL, all while having the same React-based JSX written, which would be nice!

**Comment by adziashvili** [comment]
Anyone managed to get two.js to work with React? @jonobr1 I love what you did. Was trying to get it to work with no success with latest React / Webpack / Es6. If there is a simple guide it would go a long way.

**Comment by jonobr1** [comment]
Unfortunately, I've been backlogged with getting bitmap textures working in Two.js @adziashvili... I haven't forgotten about this and will get to a declarative wrapper eventually. In the meantime I'll look into making a little tutorial so that it's clear how you can inject Two.js with React.

**Comment by trusktr** [comment]
Here's a starting point, not published anywhere but here:

```js
// Two.js
import React from 'react'
import Two from 'two.js/build/two.svg.webpack';

export default
class _Two_ extends React.Component {
  constructor (props) {
    super(props)
    const params = {autostart: true}

    Object.assign(params, props.params)

    this.twoInstance = new Two(params)
    if (!window.twos) window.twos = []
    window.twos.push(this.twoInstance)
    this._containerSize = [0, 0]
  }

  componentDidMount() {
    const {container} = this.refs
    this.twoInstance.appendTo(container)

    const size = getWidthHeight(this.props)

    if (size) {
      this.twoInstance.width = size.width
      this.twoInstance.height = size.height
    }
    else {
      this.twoInstance.renderer.domElement.style.width = '100%'
      this.twoInstance.renderer.domElement.style.height = '100%'

      requestAnimationFrame(() => {
        this.twoInstance.width = parseFloat(getComputedStyle(container).width)
        this.twoInstance.height = parseFloat(getComputedStyle(container).height)
      })
    }

    React.Children.map(this.children, child => {
      if (child instanceof this.twoInstance.Line) {}
    })
  }

  componentWillUnmount() {
    // TODO unmount two
    // TODO stop size poll loop
  }

  render() {
    const size = getWidthHeight(this.props)
    const width = size ? ''+size.width+'px' : '100%'
    const height = size ? ''+size.height+'px' : '100%'

    return (
      <div ref='container' className='react-two' style={{width, height, overflow: 'hidden'}}>
        {React.Children.map(this.props.children, child => React.cloneElement(child, {parent: this}))}
      </div>
    )
  }
}

function getWidthHeight(props) {
    const {params = {}} = props
    if (typeof params.width != 'undefined' && typeof params.height != 'undefined')
      return {width: params.width, height: params.height}
    else return null
}
```

```js
// Text.js
import React from 'react'
import Two, {Group, Text} from 'two.js/build/two.svg.webpack';

import _Two_ from './Two'
import _Group_ from './Group'

class Renderable extends React.Component {
  constructor(props) {
    super(props)
    this.twoInstance = null
    this.createTwoInstance()
    this.applyProps()
  }

  createTwoInstance() {
    if (!this.constructor.Class)
      throw new Error('Class must be defined')

    this.twoInstance = new this.constructor.Class
  }

  componentDidMount() {
    const {parent} = this.props

    if (!( parent instanceof _Two_ || parent instanceof _Group_ ))
      throw new Error('parent must be a <Two> or <Group> component.')

    parent.twoInstance.add(this.twoInstance)

    this.applyProps()
  }

  componentDidUpdate() {
    this.applyProps()
  }

  componentWillUnmount() {
    const {parent} = this.props
    parent.twoInstance.remove(this.twoInstance)
  }

  applyProps() {
    const instance = this.twoInstance

    const {
      translation,
      fill,
      stroke,
      // etc
    } = this.props

    if (translation) instance.translation.set(translation[0], translation[1])
    if (fill) instance.fill = fill
    if (stroke) instance.stroke = stroke
    // etc
  }
}

class _Text_ extends Renderable {
  static Class = Text

  applyProps() {
    super.applyProps()
    const instance = this.twoInstance

    const {
      value,
      size,
    } = this.props

    if (value) instance.value = value
    if (size) instance.size = size
  }

  render() {
    return <div className='react-two-text'></div>
  }
}

export {_Text_ as Text}
```

```js
// Group.js
import React from 'react'
import Two, {Group} from 'two.js/build/two.svg.webpack';
import _Two_ from './Two'

export default
class _Group_ extends React.Component {
  constructor(props) {
    super(props)

    this.twoInstance = null

    this.createTwoInstance()
  }

  componentDidMount() {
    const {parent} = this.props

    if (!( parent instanceof _Two_ || parent instanceof _Group_ ))
      throw new Error('parent must be a <Two> or <Group> component.')

    parent.twoInstance.add(this.twoInstance)

    this.applyProps()
  }

  componentWillUnmount() {
    const {parent} = this.props
    parent.twoInstance.remove(this.twoInstance)
  }

  componentDidUpdate() {
    this.applyProps()
  }

  /*
   * Overriden in child classes, f.e. Interpreter
   */
  createTwoInstance() {
    this.twoInstance = new Group()
  }

  applyProps() {
    const {
      center,
      translation, // can be inherited, groups are not only things with transforms.
    } = this.props

    if (center) this.twoInstance.center()
    if (translation) this.twoInstance.translation.set(translation[0], translation[1])
  }

  render() {
    return <div className='react-two-group'>
      {React.Children.map(this.props.children, child => React.cloneElement(child, {parent: this}))}
    </div>
  }
}
```

```js
// Interpreter.js
import React from 'react'
import Group from './Group'
import Two from './Two'

export default
class Interpreter extends Group {
  /*
   * @override
   */
  createTwoInstance() {
    this.createTwoInstanceFromSvg()
  }

  createTwoInstanceFromSvg() {
    const {twoInstance: two} = getRootTwoReactComponent(this.props.parent)

    const svgNodeContainer = document.createElement('div')
    svgNodeContainer.innerHTML = this.props.svg
    const svgNode = svgNodeContainer.children[0]

    // stupid stupid requirement, the SVG node must be in the DOM or else the
    // interpretatiuon won't work. :/
    document.body.appendChild(svgNodeContainer)

    this.twoInstance = two.interpret(svgNode)
    two.remove(this.twoInstance)

    document.body.removeChild(svgNodeContainer)
  }

  render() {
    return <div className='react-two-interpreter'></div>
  }
}

function getRootTwoReactComponent(reactComponentInstance) {
  while (reactComponentInstance) {
    if (reactComponentInstance instanceof Two) return reactComponentInstance
    reactComponentInstance = reactComponentInstance.props.parent
  }

  return null
}
```

It is missing some classes as you can see, but you can get the idea and the pattern for making the rest of the classes.

Usage is like this, for example:

```js
import Two from './Two.js'
import Text from './Text.js'
import Group from './Group.js'
import Interpreter from './Interpreter.js'
import * as React from 'react'
import * as ReactDOM from 'react-dom'

ReactDOM.render(
  <Two>
    <Group ...>
      <Text value="hello" x={20} y={30} />
      <Group>
        <Interpreter svg={svgString} x={10} y={10}/>
      </Group>
    </Group>
  </Two>
, document.body)
```

It's not complete, but you get the idea of how easy it is to make the components. There probably needs to be a base class or mixin to be home for the common things like `x={}` and `y={}` props, etc...

**Comment by trusktr** [comment]
Now that I think about it, it may be better to write a tool that simply renders regular SVG dom to Two.js. SO the above usage example would become

```js
import * as React from 'react'
import * as ReactDOM from 'react-dom'

ReactDOM.render(
  <RenderWithTwo>
    <svg>
      <g ...>
        <text>...</text>
        <g>
          <svg>...</svg>
        </g>
      </g>
    </svg>
  </RenderWithTwo>
, document.body)
```

then we wouldn't need to make a component for every primitive, we can just write SVG. I'll post back what I end up with...

**Comment by mindjuice** [comment]
@trusktr In your latest idea, don't you end up re-rendering the entire SVG if any props change?  Having separate React components give you the benefit of `shouldComponentUpdate()/PureComponent` optimizations.

Although come to think of it, you would probably need to override `componentWillReceiveProps()` for each component and make corresponding updates to the Two instance (e.g., if you changed the color of a text node, you would need to call a function to change the color to the new value in Two).

**Comment by Neglexis** [comment]
Hey @jonobr1 I see you've self-assigned this, any idea at all yet about your progress?

**Comment by jonobr1** [comment]
Haven't started yet @Neglexis. But I'm working with React more.., so I'm getting a better idea of how I'd like to write a react-wrapper for two. Two.js already has a flag system to only update diffs, so I think there is a nice way to incorporate react functionality to the library.

Unfortunately, this is lower priority item for me and I don't have a clear timeline for this...

**Comment by trusktr** [comment]
@mindjuice 

> don't you end up re-rendering the entire SVG if any props change

In that initial implementation, yes. It's just a starting point. Things can definitely be optimized. :)

---

@jonobr1 and everyone: Even though I suggested an example React implementation above, I'd much rather see a Web Component implementation. Otherwise, the React components are limited to React apps. Then we'd need an Angular interface, Vue interface, LitHTML interface, etc, etc.

In contrast, Custom Elements work in any HTML framework. A-Frame, for example, is a set of Custom Elements that we can use in any HTML framework.

Personally, I really like [SkateJS](https://github.com/skatejs/skatejs) for defining Custom Elements, especially because,

1. it gives us the ability to use React/Angular/Vue/LitHTML/Preact/etc as the renderer for each Custom Element,
2. The `skate.props`/`withUpdate` feature supports typed serialization/deserialization of attributes.
3. Automatic mapping from attributes to instance properties (and optionally from instance property back to attribute).
3. Uses Shadow DOM for composition, so possible to write all our elements using Vue, but we compose all other elements into our components regardless of framework.
4. It is not tied to a build system like [StencilJS](https://stenciljs.com/)
5. Lighter weight than Polymer

My philosphy is choose a framework (React/Angular/Vue/etc) for applications, and choose Web Components for libraries meant to be used in more than one application.

**Comment by jonobr1** [comment]
I also saw a talk on [deck.gl](http://deck.gl) last week at a WebGL meetup. Is it maybe worth looking into how they take an imperative drawing environment ( like WebGL / HTML5 `<canvas />` ) and create a nice React JSX go between layer for developers?

**Comment by waynevanson** [comment]
@jonobr1 I've converted 3rd party libraries that touch the DOM and integrated them into React as controlled components, such as SortableJS. I'd love to help out with this. I haven't used it yet but it looks great. I know I want to use this in my projects.

In terms of React, There are two main options:
+ We could do it declarative through JSX, where everything has props.
+ Create a wrapper where the developer can specify a `ref` and a function that holds all the standard TwoJS code.

I think having both would be great.

> Web Component implementation. Otherwise, the React components are limited to React apps. Then we'd need an Angular interface, Vue interface, LitHTML interface, etc, etc.

Great point @trusktr. All frameworks support the WebComponents in one way or another. With SkateJS, half the work is done for React. If there are any additional features that are React specific, we could just add a few extra components.

If I end up using TwoJS, I'll create a repo somewhere for this.

**Comment by jonobr1** [comment]
Thanks for posting! Please let us know if you make that repo. Would be great to see how you approach it.

**Comment by waynevanson** [comment]
I'll be doing it here unless I change something: https://github.com/waynevanson/two.js-web-components

I'm going got first try Typescript and SkateJS. Tuskr made some valid points worth trying to pursue. I don't know much about SkateJS, but web components basically look like a simple version of VueJS.

**Comment by jonobr1** [comment]
Super cool. Looking forward to seeing what you build.

**Comment by waynevanson** [comment]
@jonobr1 Is there a place I can communicate questions to you excluding this thread? Something like discord. Some of the documentation is unclear/type definitions aren't specific enough.

**Comment by jonobr1** [comment]
Totally. I just started a discord server here: https://discord.gg/2jme9H

( Will expire in one day )

**Comment by npetrangelo** [comment]
Has any progress been made on this in the past year? I recently became curious myself in using two.js in a React framework. I'd like to be able to define my own animation components and then stick them in a two.js canvas component.

**Comment by jonobr1** [comment]
No, but I've been using React for the last couple of months heavily in client work. The way I make a component that is primarily or augmented by Two.js is like so:

```javascript
import React, { useState, useRef, useEffect } from 'react';
import Two from 'two.js';

var params = {
  fullscreen: true,
  autostart: true
};

function MyComponent(props) {

  var ref = useRef();
  var two = useRef(new Two(params));

  useEffect(setup, []);

  function setup() {

    two.current.appendTo(ref.current);

    // Add any shapes you'd like here

    two.current.bind('update, update);
    two.current.bind('resize, resize);

    return function() {
      // Unmount handler
      two.current.unbind('update');
      two.current.unbind('resize');
    }

  }

  function resize() {
    // Resize logic here
  }

  function update() {
    // animate shapes here
  }

  return (
    <div className="stage" ref={ ref } />
  );

}
```

**Comment by PrestonII** [comment]
Hey @jonobr1 - thanks for making this library, I'm loving working with it! I've got two questions though: 

- Is there a reason we should be initializing Two within a ref in your example above?

- I've tried implementing your solution above in a new React Typescript project but can't seem to get it working. I'm basically implementing exactly what you've got above except that I'm doing it within a container div but the 'resize' & 'update' events don't seem to fire unless Two starts off in fullscreen mode.

Here a link to a sandbox example: https://codesandbox.io/s/two-canvas-problem-b5mvs - any thoughts?

**Comment by jonobr1** [comment]
• I found a instances in react (for function declarations) that when I didn't make a ref that it would get reinitialized or unable to be accessed in other functions called within that scope. I've found `useRef` solves that, but I'm all ears if there's a better way to handle that.
• In the npm version you're importing `resize` only gets triggered when `fullscreen: true` for an instance. But, I recently added another parameter: `fitted: true`. If you import the latest dev from github instead `fitted` will match the dimensions of the parent container and when that changes the two.js DOM element will change as well.
• In your demo the `update` event fires, because you have `autostart: true`. If you don't have that set you need to simply add `two.play();` at some point. Perhaps in your app it's when the element becomes viewable in the viewport or on a pointer event. Obviously it's up to you 😄 Conversely you can stop the instance from updating by invoking `two.pause();`.

Hope that helps. Don't hesitate to ask more questions if something comes up.

**Comment by strich** [comment]
Would be fantastic if the above could make its way into the documentation for future reference. I found it useful to get started.

**Comment by jonobr1** [comment]
@strich, this is described on the main [README](https://github.com/jonobr1/two.js#using-es6-imports) and in the [examples](https://two.js.org/examples/#basic-react-template) now, which is also searchable.

I'm going to close out this comment because, for now, I believe Two.js is sufficiently interoperable with React _and_ an implementation like React Three Fiber, but for Two.js would be a separate library. Thanks everyone for the great input!

Happy to reopen this if someone has additional thoughts.

**Comment by jonobr1** [comment]
This library exists, but I haven't published it yet. You can follow the official React wrapper for Two.js here: https://github.com/jonobr1/react-two.js
