### ISSUE TITLE
Filter?  And dead project?

### ISSUE THREAD

**Issue by RichardJECooke** [jonobr1/two.js#214]
Hi, does two.js support filter?  For blurring.

And is the project dead? I see it hasn't changed in a year.

Bonsai hasn't changed in years, and svg.js seems to be highly active with plugins. It looks like the current one to use.

**Comment by jonobr1** [comment]
Blurring isn't available out of the box but you could roll your own based on whatever renderer you use. You can see the latest commits here: https://github.com/jonobr1/two.js/tree/dev. Last one is about 14 days ago.

Whether the project is dead is up to you
