### ISSUE TITLE
Two.interpret. Wrong regex in polygon.points parsing

### ISSUE THREAD

**Issue by levabala** [jonobr1/two.js#217]
At line 2362 of two.js developer version. 

          var points = node.getAttribute('points');

          var verts = [];         
          points.replace(/(-?[\d\.?]+),(-?[\d\.?]+)/g, function(match, p1, p2) {
            verts.push(new Two.Anchor(parseFloat(p1), parseFloat(p2)));
          });

          var poly = new Two.Path(verts, !open).noStroke();
          poly.fill = 'black';
Regular expression "/(-?[\d\.?]+),(-?[\d\.?]+)/g" cannot parse svg polygon.points. For example: "278.68 280.93 278.68 62.18"(Got from Adobe Illustrator CC 2017) won't give us any result to verts array. 

So the variant works normally

          var points = node.getAttribute('points');

          var verts = [];
          var buffer = points.split(' ');
          for (var i = 0; i < buffer.length; i+=2)
            verts.push(new Two.Anchor(parseFloat(buffer[i]), parseFloat(buffer[i+1])));

          var poly = new Two.Path(verts, !open).noStroke();
          poly.fill = 'black';

My browser normally shows the polygon. But some manuals say that is right to write so: "278.68,280.93 278.68,62.18".
Where is truth?

**Comment by jonobr1** [comment]
Thanks for posting @levabala!

I don't know if I understand your question entirely, but it sounds like we can just add a check `if (commasExist)` then do the `dev` branch otherwise do the `points.split(' ');` route. That sounds reasonable.

Do you have an example SVG to test this off of?

**Comment by levabala** [comment]
![image](https://cloud.githubusercontent.com/assets/6113473/23299444/aa133074-fa92-11e6-81ac-3540ade0ab1c.png)

Svg here: https://jsfiddle.net/levabala/usgtapLy/1/

**Comment by jonobr1** [comment]
Let's do the latter! Thanks for the patch. I've updated [`dev`](https://github.com/jonobr1/two.js/commit/449a7e1d3a2bd1bd619c2cc24802b5fe72d59e81) branch with the fix.
