### ISSUE TITLE
Manual fixing

### ISSUE THREAD

**Issue by levabala** [jonobr1/two.js#218]
Current description of Two.Group.clone() at two.js.org doesn't match with reality.

_Manual_
![image](https://cloud.githubusercontent.com/assets/6113473/23311754/3bd14c28-fac8-11e6-91b1-598aae323f16.png)
_Source_
![image](https://cloud.githubusercontent.com/assets/6113473/23311739/330b5fe8-fac8-11e6-9fee-5e16faa7f0c6.png)

**Comment by jonobr1** [comment]
The latest `dev` branch should have this fixed. Thanks for reporting! Should be noted that there may be incongruencies due to [Issue 219](https://github.com/jonobr1/two.js/issues/219).
