### ISSUE TITLE
group.width and group.height

### ISSUE THREAD

**Issue by levabala** [jonobr1/two.js#220]
How can we control width and height of <g> tag inside Two.Group? Get&Set.

**Comment by levabala** [comment]
$(group._renderer.elem).width() - with jQuery.
Are there any other ways to do it?

**Comment by levabala** [comment]
Okay. That's group.getBoundingClientRect()

**Comment by jonobr1** [comment]
Sorry for the delay on this but looks like you were able to find the answer! You should be able to do:

````javascript
var rect = group.getBoundingClientRect();
rect.width // width
rect.height // height
````
