### ISSUE TITLE
Cannot read property 'isFunction' of undefined

### ISSUE THREAD

**Issue by mischaboldy** [jonobr1/two.js#227]
Hi I am trying to implement two.js for an angular 4 project. Unfortunately all of the examples I can find use html or angularJs so I have not been able to get it working. 

I used npm to install two.js:
npm install two.js --save 

Then In my component ts file I am trying to use two.js just to create a simple shape like this:
draw.component.ts:
```
import {Component, OnInit} from '@angular/core';
import * as Two from 'two.js';

@Component({
    selector: 'app-draw',
    templateUrl: 'draw.component.html',
    styleUrls: ['draw.component.scss']
})

export class DrawComponent implements OnInit {

    constructor() {
    }

    public ngOnInit() {
        let elem = document.getElementById('myCanvas');
        let two = new Two({
            type: Two.Types.svg,
            fullscreen: true
        }).appendTo(elem);

        let line = two.makeLine(150, 140, 400, 140);
        line.linewidth = 5;
        line.stroke = "blue";
        two.update();
    }

}
````
draw.component.html:
`<div id="draw-group"></div>`

unfortunately I keep getting the following error: 
```
core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'isFunction' of undefined. TypeError: Cannot read property 'isFunction' of undefined
```
Not sure if I am doing something wrong or whether this is a bug. any help is appreciated

edit:

After some digging I think the problem is that underscore is not loaded in my node module. I tried installing it and in my component underscore works fine but not in the two.min.js. Haven't found a solution yet.

**Comment by mischaboldy** [comment]
Managed to solve the problem by adding it to my cli-scripts.  not a two.js issue

**Comment by agabardo** [comment]
I am facing the same issue. How did you manage to properly install Two.js?

**Comment by jonobr1** [comment]
@agabardo, do you get the same error as the issue states? If not maybe it's because of the import syntax. You have to import two.js like so: `import Two from 'two.js`

For a few reasons none of the other ways work. If that doesn't help then if you can explain your issue in more detail I can help out.

**Comment by mischaboldy** [comment]
It's been a while so not sure if I remember correctly but I think I just copide the library into my assets folder and then imported it in the angular(-cli).json file from my assets

**Comment by agabardo** [comment]
Hi Jono, thank you for your reply.
I have tried that, with the same error.

Cheers,
Chris.

**Comment by agabardo** [comment]
Hi  Mischa, I have tried that as well.
No success so far.
I will try to import the library again later today.

Thanks.
Cheers,
Ademir

**Comment by jonobr1** [comment]
Got it. I haven't personally tried with the angular-cli but I have some time tonight, so I can check and get back to you. It's totally possible there's an issue with Two.js. In fact, `v0.7.0-beta.2` just fixed webpack issues.
