### ISSUE TITLE
Two.Polygon Width & Height

### ISSUE THREAD

**Issue by Harry-Harrison** [jonobr1/two.js#23]
I noticed there's a point in the Up for Discussion section of the readme mentioning a width and height for polygon objects. Personally, that'd be invaluable. Hope it's still under consideration :)

**Comment by jonobr1** [comment]
This now exists in the `dev` branch for:

+ `Two.ArcSegment`
+ `Two.Rectangle`
+ `Two.Ellipse`
+ `Two.Star` (with `innerRadius` and `outerRadius`)
+ `Two.RoundedRectangle`
+ `Two.Polygon`

FYI: since this thread has last been updated `Two.Path` is what the referred to `Two.Polygon` is.
