### ISSUE TITLE
[0.6.0] "requestAnimationFrame" is not an existing module.

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#230]
Yet v0.6.0 of Two.js (the latest that is on NPM) [tries to import it](https://github.com/jonobr1/two.js/blob/v0.6.0/src/two.js#L1988).

Seems like newer commits than 0.6.0 don't try to import this any more, but it's not published on NPM yet.

Would be great if you can publish an update! This currently breaks in some environments, f.e. in Meteor:

![screenshot 2017-07-08 at 4 56 46 pm](https://user-images.githubusercontent.com/297678/27990038-733b0ce0-63fe-11e7-8b1e-e2e2b57ac282.png)

And also `require('requestAnimationFrame')` in the Node repl will fail (assuming `requestanimationframe` is already `npm install`ed).

**Comment by trusktr** [comment]
The production minified version has the same issue

**Comment by jonobr1** [comment]
Sorry about that breaking! I'm close to getting `v0.7.0` in stable and subsequently to the npm registry, but still have a bit to go (namely tests and examples)... In the meantime if you could checkout the `dev` branch directly that would be super helpful.
