### ISSUE TITLE
Mixing Two.js with other WebGL libraries in the same gl context.

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#233]
Hello Jono, I'm curious to know if you've tried, or have any thoughts on how, to mix libraries together.

For example, suppose I am use Three.js and Two.js. I would like to have a single canvas, with a single `webgl` context in my entire application, and to draw using both libraries into the same context.

Are there any utilities in Two.js that allow this to be done? For example, maybe there's a way to modify `gl` state so Three.js can render, then modify the `gl` state to render a Two.js inside a framebuffer and use that as a texture inside the main Three.js scene?

In my specific case, I'm doing [my own 3D stuff (not using a library like Three.js)](https://github.com/trusktr/infamous), and would like to mix it with Two.js. I am thinking I will render either my stuff or Two.js stuff in a framebuffer, and render that framebuffer content in the other. Not sure which direction yet.

**Comment by jonobr1** [comment]
Maybe this thread can help: https://github.com/jonobr1/two.js/issues/226

I don't have much experience mixing `gl.program`s.., so I'm not really sure what to expect. Also, love the name of your own 3D library :)
