### ISSUE TITLE
How to update circle radius?

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#235]
I've got this example:

https://jsbin.com/duluvexofi/1/edit?js,output

where I am incrementing the circle radii, but it doesn't seem to work. Am I doing it right?

**Comment by jonobr1** [comment]
Is that the latest `dev` branch?

**Comment by trusktr** [comment]
Yeah, I used dev from today

**Comment by trusktr** [comment]
Oh wait, sorry, that's not dev, that's 0.6.0 (see the HTML tab).

**Comment by trusktr** [comment]
Ah, it works with `dev`: https://jsbin.com/wisivaraji/edit?js,output

**Comment by jonobr1** [comment]
Niiiiice!
