### ISSUE TITLE
Limit on number of objects?

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#236]
I tried animating 10,000,000 circles, but it doesn't seem to slow down:

https://jsbin.com/wisivaraji/edit?js,output

Is it limiting the number of circles that are rendered?

Here's trying with 99,999,999: https://jsbin.com/diwirunefo/1/edit?js,output

I thought it would've crashed!

**Comment by jonobr1** [comment]
It looks like JSBin is capping you at some number (unknown amount) based on this console output:
<img width="1280" alt="screen shot 2017-07-17 at 11 52 44 pm" src="https://user-images.githubusercontent.com/220033/28304101-18ea3b04-6b4b-11e7-9001-e797d4c1b55f.png">

It should definitely crash. I don't think the DOM can handle more than magnitude of 1000 elements in the tree... 🤔

**Comment by larrybotha** [comment]
244 circles, it appears. That seems low...

![screen shot 2017-07-18 at 09 37 07](https://user-images.githubusercontent.com/1510520/28305693-e59095da-6b9c-11e7-951d-18382ffe597b.jpg)

**Comment by jonobr1** [comment]
Now if instead of at the beginning adding all of them... You add a few on request animation frame. You can get to the limit pretty quick without firing the infinite loop error.., but if someone comes asking you didn't hear it from me 😉

**Comment by trusktr** [comment]
Ah, dang jsbin, I didn't realize it did that. 

Here's with noprotect, 500 SVG DOM circles: https://jsbin.com/hohivekesa/edit?js,output
And here's the same 500 with WebGL: https://jsbin.com/tekuroqowa/edit?js,output

I was hoping the WebGL version would be faster!

As I suspected, here's both without animating radius, 1000 circles, the WebGL is much faster in this case:

- https://jsbin.com/nomohiqozu/1/edit?js,output (SVG)
- https://jsbin.com/cugokisova/1/edit?js,output (WebGL)

**Comment by trusktr** [comment]
That's not a bad idea. Maybe that the only way to do it while showing a responsive load animation at the same time?

**Comment by trusktr** [comment]
Check this out!

- https://codepen.io/osublake/pen/MoMeMg

That is super fast, it is 3000 circles (each one in it's own canvas), sent as textures to Pixi.js. Maybe Two.js can use a similar approach.

**Comment by jonobr1** [comment]
This is actually how the WebGLRenderer already works. If you're looking for more speed you should consider the "canvas" in the codepen as a Two.js scene. Then you can work with Pixi directly. To be clear it's not 3000 canvas' it's 3000 textures drawn with one canvas. Careful programming!

**Comment by trusktr** [comment]
Ah, you're right! The number of canvases is equal to the largest radius used by any circle.

Even so, this is much faster than vanilla Two.js or Pixi.js drawing commands. Could this technique be used to speed up Two.js drawing (for WebGLRenderer)?

Here's a similar demo with vanilla Two.js API, drawing 3000 resizing moving circles (I get 0.25 fps):
https://jsbin.com/cexosiyegi/edit?js,output
