### ISSUE TITLE
Can we draw a dashed line using Two.js ?

### ISSUE THREAD

**Issue by Sudhanshu4122** [jonobr1/two.js#240]

**Comment by jonobr1** [comment]
There currently isn't an easy way to achieve this... Great request!

**Comment by jonobr1** [comment]
The closest thing is to use an image as the background for the stroke of a shape like so: https://jsfiddle.net/jonobr1/tym5s9es/

**Comment by jonobr1** [comment]
You can now draw dashed lines like so: https://jsfiddle.net/jonobr1/x1gc2d0L/

**Comment by krogank9** [comment]
Awesome improvement!

**Comment by perfilyev** [comment]
how about canvas?
