### ISSUE TITLE
`var root = this` breaks in bundlers.

### ISSUE THREAD

**Issue by trusktr** [jonobr1/two.js#241]
Using `var root = this` seems to be breaking Rollup.js bundle. The resulting bundle looks something like

```js
(function() {
"use strict"
commonjsGlobal.Two = (function() {
// Inside here it Two.js code...

var root = this // but this is not window

// ...

})()

})()
```

The issue is here: https://github.com/jonobr1/two.js/blob/e791c2c57cc799522d8795fdb5d9c3bbb12005e6/src/two.js#L3

My Rollup bundle is importing Two from the `two.js` npm package.

**Comment by jonobr1** [comment]
Unfortunately, the npm module breaks with bundlers. The dev branch shouldn't though! I'm still making some final adjustments before tagging the branch... Sorry for the inconvenience!

**Comment by GoToLoop** [comment]
```js
void function () {
  const root = this;

  commonjsGlobal.Two = void function () {
  }();
}();
```

**Comment by GoToLoop** [comment]
(() => {
  commonjsGlobal.Two = void function () {
    const root = this; // global window object too!
    console.log(this === window);
  }();
})();

**Comment by trusktr** [comment]
@jonobr1 Ah, okay, cool! Let me give that a go.

@GoToLoop I don't have control over that code to do that, it is generated by Rollup.

**Comment by trusktr** [comment]
@jonobr1 I see it doing `var root = this` in dev. Here's a PR: https://github.com/jonobr1/two.js/pull/242

**Comment by trusktr** [comment]
I ended up making this `postinstall` script and adding it to package.json:

```js
#!/usr/bin/env node

// a function wrapper is needed for older versions of Node.
~function() {
    "use strict"

    const fs = require('fs')
    const path = require('path')
    const filePath = path.resolve('node_modules', 'two.js', 'build', 'two.js')

    let data = fs.readFileSync(filePath).toString()

    data = data.replace(
        /var root = this/g,
        "var root = typeof window != 'undefined' ? window : typeof global != 'undefined' ? global : null"
    )

    fs.writeFileSync(filePath, data)
}()
```

**Comment by trusktr** [comment]
After doing that, I am able to `import` Two in Rollup-bundled code.

**Comment by jonobr1** [comment]
Sorry for the delay, I'll take a look at the PR tomorrow. Preemptive high-five!

**Comment by trusktr** [comment]
The PR might not be complete, I haven't looked at how build works. I think you can easily modify it though, the fix is really simple.

**Comment by ming-codes** [comment]
Is this fixed? I'm still getting the error.

There's actually a more standard way to reference the global context: [`self`](https://developer.mozilla.org/en-US/docs/Web/API/Window/self)

**Comment by jonobr1** [comment]
Are you using the latest dev or alpha build? It should be fixed there.

**Comment by ming-codes** [comment]
I'm using `0.7.0-alpha.1`. Not sure if it's the latest. It's not exactly the same error, but it's similar in the context object being `undefined`

**Comment by jonobr1** [comment]
I'll look into the self thing. Thanks for the heads up on that!

**Comment by jonobr1** [comment]
Sorry one more question @ming-codes, are you trying to use two.js in Node or an ES6 environment? Just trying to reproduce the `undefined` issue.

**Comment by ming-codes** [comment]
I'm trying to bundle it with Rollup. It's the same use case as @trusktr

**Comment by jonobr1** [comment]
@ming-codes, I was able to bundle the project fine without errors, but I'm not sure how rollup-serve works. Maybe we could take this conversation offline so I could get access to your repository and debug further? Thanks for reaching out!

**Comment by ming-codes** [comment]
Master branch seems to be fine, but it has other issues..

**Comment by jonobr1** [comment]
🤔, master branch is the same as the [v0.7.0-alpha.1](https://github.com/jonobr1/two.js/releases/tag/v0.7.0-alpha.1). Have you tried the `dev` branch?
