### ISSUE TITLE
Texture not working in mac safari

### ISSUE THREAD

**Issue by LakshmiT01** [jonobr1/two.js#243]
I used Nightly code and implemented texture. Its not working in mac safari (v10.1.1). Even the below example is not working in it.
https://jsfiddle.net/jonobr1/Lbu6795r/

**Comment by jonobr1** [comment]
Thanks for reporting! Unfortunately it looks like the `SvgRenderer` has some issues with textures on Safari and I'll definitely look into this right away. In the meantime if you're using `Two.Texture` directly on a custom path you'll need to define `texture.repeat = 'repeat';` at the moment. The `CanvasRenderer` and `WebGLRenderer` seem to work for me on Safari. Keep you posted on this thread.

**Comment by jonobr1** [comment]
Unfortunately this looks like it potentially could be a Safari bug. I've posted for them here: https://bugs.webkit.org/show_bug.cgi?id=175508

**Comment by jonobr1** [comment]
This examples seems to work so I think I need to describe the SVG document differently and it `Two.Texture`s should show up for Safari in the `SvgRenderer`: http://www.boogdesign.com/examples/svg/path-pattern-fill.svg

**Comment by jonobr1** [comment]
Figured out the issue! I wasn't applying `xlink` attributes to the `href` on the images. Dev branch has this fixed: https://github.com/jonobr1/two.js/commit/3e19e47bb55bd64729cfac5e57abe62653834c42
