### ISSUE TITLE
Runtime error bundling with Webpack (Underscore not defined)

### ISSUE THREAD

**Issue by andry-tino** [jonobr1/two.js#247]
I am trying to write a web application using [webpack](https://webpack.js.org) and [two.js](https://two.js.org). For completeness, these are my dependencies:

    "devDependencies": {
      "jasmine-core": "^2.8.0",
      "karma": "^1.7.0",
      "karma-chrome-launcher": "^2.2.0",
      "karma-jasmine": "^1.1.0",
      "karma-webpack": "^2.0.4",
      "webpack": "^3.5.5"
    },
    "dependencies": {
      "two.js": "^0.6.0"
    }

I have the following `webpack.config.js`:

    const path = require('path');
    module.exports = {
        entry: './myentry.js',
        output: {
            filename: 'bundle.js',
            path: path.resolve(__dirname, 'out')
        }
    };

File `myentry.js` just imports _two.js_:

    import two from "two.js";

## Bundling succeeds...
Library _two.js_ is part of my npm dependencies, so it can be found among my local node modules in `node_modules` folder. When I go ahead and create the bundle:

    webpack --config webpack.config.js

It **succeeds** and I get the following output:

    Hash: 5e762def59fa65ff8487
    Version: webpack 3.5.5
    Time: 468ms
                   Asset    Size  Chunks                    Chunk Names
    bundle.js  258 kB       0  [emitted]  [big]  main
       [0] ./myentry.js 271 bytes {0} [built]
        + 1 hidden module

The generated bundle is available [here](https://drive.google.com/file/d/0B7YBzYyRhfbpbXhnM3o2STR0TnM/view?usp=sharing).

## But... running fails:
So I use the bundle in my HTML page:

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>My stuff</title>
        <script type="application/javascript" src="./out/bundle.js"></script>
    </head>
    <body></body>
    </html>

When I open the page in Chrome (I use [http-server](https://www.npmjs.com/package/http-server) to avoid CORS related issues), I get these **errors in F12 Tools**:

    Uncaught TypeError: Cannot read property 'isFunction' of undefined
        at bundle.js:1917
        at Object.<anonymous> (bundle.js:3867)
        at __webpack_require__ (bundle.js:20)
        at Object.root (bundle.js:72)
        at __webpack_require__ (bundle.js:20)
        at Object.defineProperty.value (bundle.js:63)
        at bundle.js:66

If you inspect the bundle, you will see the error is on this line:

    hasEventListeners: _.isFunction(root.addEventListener),

So _underscore_ is not defined, but it is provided inside _two.js_! Why is it a problem with _webpack_?

A detailed post about this is available on StackOverflow [here](https://stackoverflow.com/questions/45902820/underscore-not-defined-when-using-two-js-and-webpack).

**Comment by jonobr1** [comment]
Thanks for posting! I'll take a look at this today. One *huge disclaimer* about the project though is that the npm version is about 10 months behind the dev branch. Have you tried the dev branch instead? It may have this issue already resolved. I'm hoping to have the current [dev](https://github.com/jonobr1/two.js/tree/dev) up to stable by the end of the summer... Sorry about that!

**Comment by andry-tino** [comment]
I did not try the dev branch actually. I will give it a try and see. However it should be interesting to understand what kind of issues there are here with Webpack :)

**Comment by jonobr1** [comment]
I just gave the dev branch a try and this is fixed. It will be solved as an npm dependency once `v0.7.0` hits stable. Sorry for the inconvenience!

**Comment by kurtfusion** [comment]
Andrea thanks for posting! To help others here is how you use the dev branch.
npm install https://github.com/jonobr1/two.js/#dev --save

**Comment by ForsakenHarmony** [comment]
`--save` is actually not necessary with newer npm versions

**Comment by AmirAlavi** [comment]
Hi, @jonobr1 , I stumbled across this because I'm getting a similar error where underscore functions are undefined in a bundle that has underscore as a dependency. Could you share some insight as to what the fix was?

**Comment by jonobr1** [comment]
What version are you using @AmirAlavi? If you use the alpha release this should be fixed 👍 

https://cdnjs.com/libraries/two.js/0.7.0-alpha.1

**Comment by AmirAlavi** [comment]
@jonobr1, sorry, I meant that I'm working on something unrelated to this repository, but searching for my error landed me here and was just hoping to maybe learn how to fix it. I am not using two.js in my project. Did you pin down what it was?

I'm using a different JS library, clustergrammer, and it also has underscore as a dependency, and when I bundle it up, also get "undefined" errors for underscore functions.

**Comment by jonobr1** [comment]
The short answer is that we removed the dependency altogether... But in your case I think whatever way the library your using exports itself both to the window and node contexts you have to import deoencies the same way.
