### ISSUE TITLE
Question: add nodes

### ISSUE THREAD

**Issue by mariomeraz** [jonobr1/two.js#250]
it is possible to add nodes to manipulate the drawing ? on clic event ?

**Comment by jonobr1** [comment]
Certainly! When you say "add nodes" I understand that to mean either:

+ Vertices on a `Two.Path`
+ Objects to the scene

Is that what you had in mind?

**Comment by mariomeraz** [comment]
> Objects to the scene

Like Illustrator on clic event

![captura 2017-09-20 a la s 09 48 00](https://user-images.githubusercontent.com/14825814/30650592-e12f6574-9de8-11e7-8690-17cd15ef56a4.jpg)

Thks

**Comment by jonobr1** [comment]
Yep! https://jsfiddle.net/jonobr1/pje49jLa/

**Comment by jonobr1** [comment]
Sorry, just seeing your response now. At the moment there isn't anything out of the box to give you _that_ specific type of functionality... That doesn't mean it's not possible. It's just not written in the library. We could track it as an enhancement though and I will find the time to add an example.

**Comment by jonobr1** [comment]
Here you go: https://jsfiddle.net/jonobr1/pvhwc7nu/
