### ISSUE TITLE
How to destroy previous new Two() svg instances to create new instances based on data when data is updated dynamically?

### ISSUE THREAD

**Issue by Sudhanshu4122** [jonobr1/two.js#252]
How to destroy previous new Two() svg instances to create new instances based on data when data is updated dynamically?

**Comment by Sudhanshu4122** [comment]
I am working on a  problem statement in which i plot  the gant view using Two.js based on milestone dates data. And when i filter the milestone rows based on search by 'Name' , I have to update the already plotted gant view based on  new search results data. So how can i destroy  the earlier svg instances in gant view and create new one??

**Comment by jonobr1** [comment]
Hey, thanks for the message! Do you any kind of working example online? It makes it easier to really identify a) what you're trying to do and b) how Two.js can help with that.

In the meantime, from what I gather if it's possible do not delete and re-instantiate an instance of `Two`, but rather remove the elements in the scene and make new ones. _Or even better_ would be to make set of shapes that can be re-purposed and assigned to different data sets. The prior would look something like this:
````javascript
for (var i = 0; i < two.scene.children.length; i++) {
  var child = two.scene.children[i];
  two.scene.remove(child);
  Two.Utils.dispose(child);
}
````
