### ISSUE TITLE
Possible project for the projects page?

### ISSUE THREAD

**Issue by futurefabric** [jonobr1/two.js#253]
Hey, found my way here from the two.js Projects page and thought you *might* be interested in a series of animations I've made (and continue to make) with two.js. All viewable from here — [https://www.futurefabric.co.uk/play](https://www.futurefabric.co.uk/play) (all the 2d animations there run off a blend of two.js and my own custom code).

Also thought I'd take this opportunity to say thanks for making such an awesome library, it's a pleasure to work with! :)
Cheers,
Guy.

**Comment by jonobr1** [comment]
WOW, this is gorgeous! If you have a GIF that's 285x200 I'd be happy to throw it up.

Awesome work Guy! Please don't hesitate if you have any feedback regarding Two.js 👍

**Comment by futurefabric** [comment]
Ah, thanks so much Jono! 🙏
Glad you approve and [here's a gif for you](http://cl.ly/1s2f0L0E1K0t) :)

**Comment by jonobr1** [comment]
Just added! Again, awesome work!
