### ISSUE TITLE
Create Path's from just a string

### ISSUE THREAD

**Issue by dougreichard** [jonobr1/two.js#254]
For my needs I have path strings, not SVG. It would seem very silly to create an SVG node just to have it parse the pathstring. So, unfortunately I can't use Two.js for my project.

An SVG Path has the d attribute the describes a path. e.g. `d="M ......z"`. The utils.read.path() has a why of converting the svg node to a two.js compatible set of element. It would be nice to create Two elements from just the string and not needing the node. The Utils.read.path function has a the code to support this, but the is from the d attributes.  Seems like the code could be converted to have a function for just a string and the SVG node version calls that.

For example:
Utils.read.pathString() and have Utils.read.path call pathString

**Comment by jonobr1** [comment]
Thanks for posting. This is definitely possible. In your mind are you thinking of just supplying the `d` attribute?

**Comment by dougreichard** [comment]
Yes the d attribute.

I like your overall abstraction. I think twojs can be enhanced to be a bit more approachable. I've been reading more source code than documentation. When I personally look for a 2D abstraction I typically have used strings with the 'd attribute' format, and the [Path2D API](https://developer.mozilla.org/en-US/docs/Web/API/Path2D) moveTo, .LineTo

Your underlying anchors look great, but a couple of utility APIs for people migrating or used to these other APIs would help twojs be more approachable. Simple path example documentation would help as well. Maybe showing Path2D and equivalent Anchors. 

Your abstractions of gradients is also very good compared to some other libraries. 

I am looking for a 2D abstraction that can render to SVG, Canvas or WebGL with the least amount of code changes when changing renders, and one with great performance. I'm encouraged by twojs features.

**Comment by blu-towers** [comment]
is this now possible to just supply the pathString? or is there a way to as i have some complex svg files i would like to not have to recreate in two.js, i have tried interpret or load command but it doesnt really work 100% of the time.

**Comment by jonobr1** [comment]
No, this is still not possible yet. I'll be sure to update this thread when it is!

**Comment by jonobr1** [comment]
Sorry for the egregious delay, but v0.7.x took more of time than I thought. I'm back at it and this is now implemented in the latest `dev` branch. You can use it like so:

```javascript
var d = 'M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z';
var heart = Two.Path.Utils.interpret(d);
two.add(heart);
```
