### ISSUE TITLE
Can't get path curves to work properly

### ISSUE THREAD

**Issue by ForsakenHarmony** [jonobr1/two.js#256]
I'm unsure what I'm doing wrong, but I can't get paths to work as they should

```
const anchors = [
    new Two.Anchor(0, 25, -25, 25, 25, 25, Two.Commands.move),
    new Two.Anchor(50, 25, 25, 25, 75, 25, Two.Commands.line),
    new Two.Anchor(75, 50, 75, 25, 75, 75, Two.Commands.curve),
  ];

let path = new Two.Path(anchors, false, false, true);
```

![](https://i.imgur.com/zbemjLY.png)

The control points always away from `0,0` but if I check the array they're where I set them to

On the dev branch btw

**Comment by ForsakenHarmony** [comment]
wait, the coordinates are relative?

**Comment by jonobr1** [comment]
Hey there, thanks for the question! Yes, the bezier handle coordinates default to relative. You can change this if you'd like:

````javascript
anchors.forEach(function(a) {
  a.relative = false;
});
````

I should update the docs to clarify this! Thanks for reporting!
