### ISSUE TITLE
Polygons can't be parameterized (using getPointAt) to closure; last segment missing. 

### ISSUE THREAD

**Issue by buzziam** [jonobr1/two.js#257]
Just getting my feet wet with Two.js - so I may not fully understand how or why but: 

It seems that `getPointAt` on a polygon created with `makeStar`, for example, cant find points on the last edge of the polygon - the one between the last node and the first node. Actually I'm seeing that it finds points but they are way off. 

I'll try to put an example together and post it.

**Comment by jonobr1** [comment]
Sorry to hear you're having this issue. It does sound like a bug in `getPointAt`... I can take a peek, but it would be super helpful to have an example to test against! Thanks for reporting!

**Comment by jonobr1** [comment]
I can confirm the bug, fixing now.

**Comment by jonobr1** [comment]
Fixed with this commit: https://github.com/jonobr1/two.js/commit/213ae9b1a04fc21f32a71f8503f412c7c39296b6. It's now on the `dev` branch. Thanks for reporting!

**Comment by buzziam** [comment]
Thanks for fixing! :) 

I started creating the sample before I looked at the status of this issue: 

FWIW: Here is the sample: https://codepen.io/anon/pen/WXPNxr
