### ISSUE TITLE
Easiest way to include text in polygons?

### ISSUE THREAD

**Issue by sudhanshugarg** [jonobr1/two.js#26]
Hi,
I'm trying to include text inside circles and polygons in general. Is there a way to get access to the svg object from the two object, in order to add text to the polygon.

**Comment by dcousens** [comment]
For others, this is what works as of 30/01/2015

``` javascript
var rect = two.makeRect(x, y, width, height);
var domElement = document.querySelector('#' + rect.id);
```

**Comment by jonobr1** [comment]
thanks for the update!
