### ISSUE TITLE
Suggestion: allow specifying 'class' attribute when outputting to SVG

### ISSUE THREAD

**Issue by fr0** [jonobr1/two.js#260]
If my output is `svg`, it's sometimes nice to be able to style elements with CSS. Being able to tag my two.js elements with classes to enable this would be a nice improvement. I understand that this would be ignored when outputting to canvas/webgl, but that's fine.

If this is already possible with two.js, I apologize - I checked the docs but didn't see it anywhere.

**Comment by jonobr1** [comment]
It's a great idea! There's no "easy API" from Two.js to do this, however for any given SVG node you do have access to it from JavaScript. A short-term solution to this problem could be:

````
var path = new Two.Path();
two.add(path);
two.update();
path._renderer.elem.classList.add(myClassName);
````

N.B: In order for the node to be appended the renderer needs to be updated at least once.

**Comment by fr0** [comment]
Thanks for the workaround! I might take a shot at a pull request to implement a more friendly API at some point.
