### ISSUE TITLE
Add project

### ISSUE THREAD

**Issue by wildProgrammer** [jonobr1/two.js#262]
Add my little game to the page with two.js projects if it isn't too ugly to be there.
https://wildprogrammer.github.io/Flying-triangle-game/ 

You have to dodge the squares with your flying triangle.

Controls:
Left arrow key - move left 
Right arrow - move right
Up arrow - move up
Down arrow - move down
Esc - pause/unpause

**Comment by jonobr1** [comment]
This is super fun! I got more than 1000 points on my best try 👍 

I'd recommend a few things:
+ Have you considered making the instance of two the entire dimensions of the page?
+ The quality of motion feels great and is really slick to navigate.
+ Have you considered spending some more time on the art? With the new `Two.Sprite` class it should be pretty easy to swap in some cool art assets!

Nice work @wildProgrammer !

**Comment by ogrotten** [comment]
@wildProgrammer 

Neat.
