### ISSUE TITLE
Two.interpret: Node.js support?

### ISSUE THREAD

**Issue by saschagehlich** [jonobr1/two.js#264]
Are you planning to add Node.js support to Two.interpret, i.e. support passing SVG content as a string? Or is there a SVG parsing library that's compatible with Two.js?

**Comment by jonobr1** [comment]
This is a great question. I'm not familiar with any specific SVG node packages, but if you have a recommendation I'm all ears. If there is a specific one you like it should be quite easy to adapt Two.js to be compatible with it, because all of the SVG dom related code is one place.

**Comment by saschagehlich** [comment]
I tried with xmldom - it rendered without an exception, but the rendering was totally off. I switched to Canvg which uses xmldom internally and works fine. Here's the SVG I tried to render: https://gist.github.com/saschagehlich/0f5634520d8a3abe5cfdc0f82617ec81

**Comment by jonobr1** [comment]
Cool, I'll try to run the test SVGs against these two libraries. Just to confirm, this is what the SVG looks like when I load it into Adobe Illustrator

<img width="778" alt="screen shot 2017-12-11 at 11 04 15 pm" src="https://user-images.githubusercontent.com/220033/33871512-a846bab2-dec7-11e7-92ed-7757f6e06b7c.png">

**Comment by saschagehlich** [comment]
Sorry, wrong SVG file. This is the correct one: https://gist.github.com/saschagehlich/33824b989666553978da4d99ab7455b9

It should look like this:

![screen shot 2017-12-12 at 8 16 40 am](https://user-images.githubusercontent.com/119684/33871963-160cbe6e-df15-11e7-835a-c2bf654f5014.png)

**Comment by jonobr1** [comment]
Sorry for the delay. I went through and was also able to load that SVG with `canvg`. It worked great and wasn't too cumbersome. Honestly.., I think that's the way to go. Nice find and thanks for sharing!
