### ISSUE TITLE
SVG not properly rendered using two.interpret()

### ISSUE THREAD

**Issue by CalitoUy** [jonobr1/two.js#266]
I found that some SVG paths are not properly rendered using two.interpret(svgNode), for example this star ![image](https://user-images.githubusercontent.com/35278904/34749849-8ccfb1a4-f582-11e7-89ae-1a752b1cadd2.png) is shown like this ![image](https://user-images.githubusercontent.com/35278904/34749866-a43f0e3e-f582-11e7-9397-876296c5de0e.png)
The console shows this error:
_Error: <path> attribute d: Expected number, "… -10.15 C -10.6 NaN -15.1 -6.5 -…"._

I debugged the code and I found that this line seems to be wrong:
src/two.js:1096 -> `y1 = control.y;`
I looks like a typo, I think it should be: 
`y2 = control.y; `
If I change it, the error goes away and the image looks better, but still not correct: 
![image](https://user-images.githubusercontent.com/35278904/34750145-2a5dd79c-f584-11e7-9b93-98e0ea6de6d8.png)
¿Any ideas?

Original SVG file: [svg.txt](https://github.com/jonobr1/two.js/files/1617112/svg.txt)

**Comment by jonobr1** [comment]
Thanks for reporting! There were a couple of bugs in the `interpret` function which should be resolved for your SVG in the [dev branch](https://github.com/jonobr1/two.js) now. Here are the fixes: https://github.com/jonobr1/two.js/commit/2bf9cf2a6257142316e84900ac5ad2f83d2e1e8d

**Comment by CalitoUy** [comment]
Thank you very much! Now it works perfectly :)

**Comment by jonobr1** [comment]
No, thank you for raising the issue. Just made the interpret better!

🙌
