### ISSUE TITLE
Can't see graphics on iPhone

### ISSUE THREAD

**Issue by qworin** [jonobr1/two.js#267]
I have an app using two.js to render a dynamic graphics. However I can't see the graphics on my iPhone but it's ok on desktop browser. Are there any requirements on iOS version or other requirements (my iOS version is 8.3)? I tried SVG, canvas, and WebGL renderers to check.

**Comment by jonobr1** [comment]
Uh oh, that doesn't sound good! Are you on Mobile Safari or Chrome? Or both?

Are there any errors when you look at the console? I believe Two.js should work with iOS 7.0+. Aside from WebGL support the main thing the library relies on are `Object.defineProperty` getters and setters.

If you have your project or a version of it online I can check I could help debug it. Thanks for reporting!

**Comment by qworin** [comment]
This is [fiddle](https://jsfiddle.net/mn43jmr9/1/) with some code from the app. I tried to use base64 encoded [images](https://jsfiddle.net/qL6Lb8tn/1/) however they work on iOS 11+ only. Both variants don't work on 8.3: 'roulette' isn't rendered at all.

**Comment by jonobr1** [comment]
Thanks for this! I'm booting up my old iPhone 5 now. In the meantime do you mind checking some other sites? For instance do the [examples](https://two.js.org/examples/) work on your iPhone?

**Comment by jonobr1** [comment]
So, looking at your fiddle there are few errors that pop up. The first one is that you're writing all your JavaScript in ES6, which looks like is not supported by the environment:

<img width="752" alt="screen shot 2018-01-18 at 10 50 09 am" src="https://user-images.githubusercontent.com/220033/35115522-5f28ab68-fc3d-11e7-99ab-9877adc2ab3a.png">

The second is that the images are loaded over an insecure protocol...

<img width="752" alt="screen shot 2018-01-18 at 10 50 03 am" src="https://user-images.githubusercontent.com/220033/35115542-6e26a89a-fc3d-11e7-9157-8686b92fb478.png">

Finally, the examples on https://two.js.org work fine in the iOS Simulator 8.3. Hope this helps!
