### ISSUE TITLE
Any performance test?

### ISSUE THREAD

**Issue by caracal7** [jonobr1/two.js#268]
It will be very good to have something like bunnymark and direct comparison with Pixi and other WebGL wrappers....

**Comment by jonobr1** [comment]
That would be great to have. The closest thing to this would be the [Particle Sandbox](https://two.js.org/examples/particle-sandbox.html). You can add the FPS meter on top. Full disclosure for doing applications in the way bunnymark example works then Pixi has far faster performance than Two.js.

Two.js is better suited for dynamically creating and modifying vector shapes in real-time.

**Comment by caracal7** [comment]
I think bunnymark analog can be implemented in few lines of code. Maybe I will make it if I will have free time) 
But I agree with you what Two.js is not a sprite engine and direct comparison with Pixi is not correct.
But any way Two.js in my project show very good performance with several thousands of rectangles.👍

**Comment by jonobr1** [comment]
Indeed! That being said.., Two.js now does support bitmap images so it should be quite straightforward to make a bunnymark example. I'll add this to my list of examples when I finish up the final changes to v0.7.0. Thanks for reporting!

**Comment by jonobr1** [comment]
For reference: http://pixijs.io/bunny-mark/

**Comment by nowox** [comment]
![image](https://user-images.githubusercontent.com/1132849/43609126-731a99c8-96a3-11e8-82c4-04c835232eed.png)

http://bl.ocks.org/darosh/raw/65f9046bcb91c5f516a1

**Comment by jonobr1** [comment]
This is awesome @nowox. Thanks for sharing. What version of Two.js is this? Also, what is `two-tweak`? What did you tweak?

**Comment by jonobr1** [comment]
This is based on `v0.5.0`. Curious to see how it runs on `~v0.7.0`. Now in 2019 the performance has improved without doing anything specifically:

<img width="551" alt="Screen Shot 2019-03-28 at 8 42 18 AM" src="https://user-images.githubusercontent.com/220033/55139319-bf882d00-5135-11e9-8ac8-15cacd1d460c.png">

I also, now see what tweaks can be made in the `Two.Matrix` class to speed things up. Thanks!

**Comment by nithomio** [comment]
These diagnostics are nice, thank you. It would be nice to see similar benchmarks of the same project implemented in SVG.js, and vanilla js, shown in a side by side comparison.

**Comment by jonobr1** [comment]
Looks like this is a good comparison: https://benchmarks.slaylines.io/two.html
