### ISSUE TITLE
How can I subtract two paths?

### ISSUE THREAD

**Issue by zerazobz** [jonobr1/two.js#270]
I have draw with multiple paths, and there are intersections between them. I want to subtract the intersections.

It's possible?

Many thanks.

**Comment by jonobr1** [comment]
Thanks for inquiring! Unfortunately, Two.js doesn't have any inherent functionality to do what you'd like... One day I hope to add it!

**Comment by jonobr1** [comment]
Closing this and will be tracking the progress of this feature at issue https://github.com/jonobr1/two.js/issues/596
