### ISSUE TITLE
ReferenceError: b is not defined

### ISSUE THREAD

**Issue by ming-codes** [jonobr1/two.js#276]
This line right here https://github.com/jonobr1/two.js/blob/master/build/two.js#L5112

**Comment by jonobr1** [comment]
That error is in the WebGL Renderer. Does a different renderer work? You can try this by:

```javascript
  var two = new Two({
     type: Two.Type.canvas
  });
```

**Comment by ming-codes** [comment]
Yup, type canvas works just fine.

If you look at the code, `b` really isn't defined. 😃 Forgot to declare it or just named wrong?

**Comment by jonobr1** [comment]
Didn't have declaration. The latest `dev` branch has this fixed.
