### ISSUE TITLE
.interpret() breaks transform matrix

### ISSUE THREAD

**Issue by RobinBressan** [jonobr1/two.js#279]
Hi,

I have an issue while using `interpret()` method. My SVG input contains a path which has a `transform` attribute. The `transform` attribute has a matrix as value but after the import by calling `interpret()`, the matrix is reset to `matrix(1 0 0 1 0 0)` and it breaks the display.

Do you have any idea on how to solve this?

Best regards

**Comment by jonobr1** [comment]
Do you have your SVG available online so that I can test against it? Hard to say what the issue is at the moment...

Thanks for the report!

**Comment by RobinBressan** [comment]
Hi,

Thanks for the quick answer. The input SVG is the following:

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMinYMin slice" width="681px" height="454px" style="overflow: hidden;">
    <defs/>
    <g id="two_6" transform="matrix(1 0 0 1 0 0)" opacity="1">
        <path transform="matrix(1 0 0 1 30.866 34.008)" d="M -4.994 -6.174 L 4.993 -6.174 L 4.993 6.173 L -4.994 6.173 Z " fill="#ccc" stroke="#000" stroke-width="1" stroke-opacity="0.6" fill-opacity="0.6" class="" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two_68" style="cursor: pointer;" />
    </g>
</svg>
```

And I got this:

```html
<svg viewBox="0 0 100 100" preserveAspectRatio="xMinYMin slice" width="681px" height="454px" style="overflow: hidden;">
    <defs></defs>
    <g id="two_69" transform="matrix(1 0 0 1 0 0)" opacity="1">
        <g id="two_70" transform="matrix(1 0 0 1 0 0)" opacity="1">
            <g id="two_6" transform="matrix(1 0 0 1 0 0)">
                <path transform="matrix(1 0 0 1 0 0)" d="M -4.994 -6.174 L 4.993 -6.174 L 4.993 6.173 L -4.994 6.173 Z " fill="#ccc" stroke="#000" stroke-width="1" stroke-opacity="0.6" fill-opacity="0.6" class="" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two_68"></path>
            </g>
        </g>
    </g>
</svg>
```

**Comment by jonobr1** [comment]
Latest `dev` branch has fixes for you. One thing that's a bit tricky is that if you initialize Two.js with different dimensions than the SVG you're referencing. The library tries to calculate a ratio that the parent SVG should be rendered at so it looks _similar_ to how you rendered it ( this is why you get an additional group object when you `interpret` an SVG ). **This is an approximation**.

Thanks again for reporting!

**Comment by RobinBressan** [comment]
@jonobr1 Thanks for the fix! But how therefore would you advise me to load an existing SVG?

**Comment by jonobr1** [comment]
Woah, it shouldn't be wrapping your content in a `matrix(0 0 0 0 0 0)`, if anything it should be the identity `matrix(1 0 0 1 0 0)` which shouldn't have any affect on your objects placement. Generally speaking there are two ways to import shapes:

```javascript
// If you have an SVG file somewhere on the internet
two.load('path/to/your/svg-file.svg', function(group) {
  // This group is already placed into the current instance's scene.
});
// If you already have an SVG node on your document's page
var group = two.interpret(document.querySelector('svg#id-of-element'));
```

Hope this helps!
