### ISSUE TITLE
 about fullscreen: true,

### ISSUE THREAD

**Issue by L-Jim** [jonobr1/two.js#282]
when i set  fullscreen: true, overflow:scroll; in my page doesn't work，how can i make it work?

**Comment by jonobr1** [comment]
Sorry for the delayed response! Don't set `fullscreen: true`. You can manage the resize yourself like so:

```javascript
var two = new Two().appendTo(document.body);
window.addEventListener('resize', resize, false);
resize();

two.renderer.domElement.style.display = 'block';
// Any other styles you'd like to include do on the domElement property

function resize() {
  two.width = width;
  two.height = height;
  two.renderer.setSize(width, height);
}
```

When the `fullscreen` parameter is set to `true` Two.js automatically makes the `position: fixed` and does `overflow: hidden` on the body.

**Comment by L-Jim** [comment]
thx
