### ISSUE TITLE
Is there a way to add filters / manipulate defs

### ISSUE THREAD

**Issue by heaversm** [jonobr1/two.js#284]
Want to add the following to my two.js svg:

```
<defs>
    <filter id="filter" filterUnits="userSpaceOnUse" x="-5" y="-5" height="200" width="2000">
      <feTurbulence baseFrequency="0.2" numOctaves="3" type="fractalNoise" />
      <feDisplacementMap  scale="8"  xChannelSelector="R" in="SourceGraphic" />
     
    </filter>
</defs>
```

and then apply it to paths with css (or style attribute):

`path { filter:url(#filter) }`

How would I accomplish this?

**Comment by jonobr1** [comment]
I've never tried this myself, but every instance of `Two.SvgRenderer` has a parent `<svg />` with a child `<defs />`. After the very first `update` call when Two.js is initialized you should have access to the defs like so:

```javascript
var two = new Two().appendTo(document.body);
var filter = Two.SvgRenderer.Utils.svg.createElement('filter', {
  id: 'filter',
  filterUnits: 'userSpaceOnUse',
  x: -5,
  y: -5,
  height: 200,
  width: 2000
});
two.defs.appendChild(filter);
```

I can follow up later this evening with a working example.

**Comment by heaversm** [comment]
Awesome - thanks for the followup. I'll give it a shot as well.

**Comment by jonobr1** [comment]
I'm not sure if this is what it's _supposed_ to look like, but it does look like filters work the way I described above: https://jsfiddle.net/jonobr1/zfqLxpr4/

![capture](https://user-images.githubusercontent.com/220033/40205223-1b37bdb2-59e0-11e8-96d2-0dae96ea804a.PNG)
