### ISSUE TITLE
[docs] Event link rot 

### ISSUE THREAD

**Issue by drhodes** [jonobr1/two.js#285]
Hi, just a heads up, the Events link over on https://two.js.org/index.html is returning 404.

![image](https://user-images.githubusercontent.com/84929/40125334-a96a2860-58f8-11e8-80cd-536166583d70.png)

**Comment by jonobr1** [comment]
Ah, thanks! I'll update that today. In the meantime Events have been added to the source code here: https://github.com/jonobr1/two.js/blob/dev/src/two.js#L1878-L1964

They're _similar_ in usage to Backbone's events but slightly optimized for per-frame usage.

**Comment by jonobr1** [comment]
Updated the documentation. Just for clarity, if you're using the latest Two.js version `v0.7.0-alpha.1` or newer then Two.js is dependency free.

**Comment by drhodes** [comment]
Ok cool, thank you.
