### ISSUE TITLE
Package.json: include module: field

### ISSUE THREAD

**Issue by backspaces** [jonobr1/two.js#290]
By adding a `module: build/two.module.js` entry to package.json, unpkg.com will be able to serve up both script/umd versions of two.js, and esm versions. Here's a discription:
https://github.com/rollup/rollup/wiki/pkg.module

This allows access the script/umd version via:
https://unpkg.com/two.js
and the es6 module:
https://unpkg.com/two.js?module

It's possible you may need to insure two.module.js is included to your npm project, using the unpkg dashboard did not show it:
https://unpkg.com/two.js/
Possibly including a files: field in package.json will do the trick:
```
  "files": [
    "build"
  ],
```

Here's an example for one of my repos:
UMD: https://unpkg.com/@redfish/agentscript
ESM: https://unpkg.com/@redfish/agentscript?module
Dashboard: https://unpkg.com/@redfish/agentscript/

.. and thanks for the great library, very cool indeed!

**Comment by jonobr1** [comment]
Cool, I didn't know that's how it works. I'll add it to the `package.json` when I update to the next latest version: `v0.7.0`

**Comment by jonobr1** [comment]
I updated the [`package.json`](https://github.com/jonobr1/two.js/blob/dev/package.json) but it probably won't propagate until I've actually published `v0.7.0`. Soon, it's coming soon! Thanks for your patience 🙏🙏🙏

**Comment by backspaces** [comment]
Thanks!
