### ISSUE TITLE
Can't figure out how to create simple Bezier path

### ISSUE THREAD

**Issue by schvenk** [jonobr1/two.js#294]
Hi,
I'm just learning Two.js and am stumped trying to create a simple Bezier path. I can create a straight path:

`var path = two.makePath(10, 10, 100, 20, 150, 15, true);`

...or a curved path whose curves I can't control:

`var path = two.makeCurve(10, 10, 100, 20, 150, 15, true);`

Based on the docs it seems like the right answer is to substitute an array of Two.Anchors for the x/y values in the above:
```
var path = two.makeCurve([new Two.Anchor(10, 10, 0, 0,0,0, Two.Commands.curve), new Two.Anchor(100,20,-100,-100,0,110,Two.Commands.curve), new Two.Anchor(150,100,0,0,0,0)], true);
```

But it doesn't make any difference—if I use `makeCurve()`, I still get the default curves rather than anything custom from my control values; if I use `makePath()`, I still get straight lines. What am I missing?

**Comment by jonobr1** [comment]
Thanks for the question @schvenk!

Yeah, it's not super obvious to make a bezier curve for your control at the moment... I'm working on a new api to do that. But, in the meantime this is how it's done:

```
var points = [
  new Two.Anchor(-10, -10, 0, 0, 0, 0, Two.Commands.move),
  new Two.Anchor(10, -10, 0, 0, 0, 0, Two.Commands.curve),
  new Two.Anchor(10, 10, 0, 0, 0, 0, Two.Commands.curve),
  new Two.Anchor(-10, 10, 0, 0, 0, 0, Two.Commands.curve),
  new Two.Anchor(-10, -10, 0, 0, 0, 0, Two.Commands.close)
];
var bezierPath = new Two.Path(points);
bezierPath.automatic = false;
two.add(bezierPath);
```

**Comment by schvenk** [comment]
Thanks, that did it! One follow-up question though. It looks like the control points exist in the global coordinate space, whereas in most cases one wants to operate on a tangent to the curve—is there an easy way to do that?

**Comment by jonobr1** [comment]
Yeah, so an anchor has a "controls" property. On that are the "left" and "right" controls. It also has a "relative" property ( a Boolean ) to switch between global and local space
