### ISSUE TITLE
Update Documentation for Two.js

### ISSUE THREAD

**Issue by jonobr1** [jonobr1/two.js#295]
This is a multipart issue:

1. Update documentation based on [jsdocs](http://usejsdoc.org) formatting
2. Render documentation with [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown)
3. Style documentation based on [https://two.js.org/](https://two.js.org) and include with `dev` repository for local development

**Comment by jonobr1** [comment]
Have currently added documentation to all "top level" `src` files. Now need to go through `src/effects`, `src/renderer`, and `src/shapes` and add documentation there to complete step one.

<img width="251" alt="Screen Shot 2019-03-28 at 8 36 37 AM" src="https://user-images.githubusercontent.com/220033/55138814-9dda7600-5134-11e9-9091-f22ca6aa8873.png">

**Comment by eulertour** [comment]
> Have currently added documentation to all "top level" src files. Now need to go through src/effects, src/renderer, and src/shapes and add documentation there to complete step one.

Is this true? Looking at the documentation at https://two.js.org/#documentation, it seems that documentation for Two.Matrix, Two.Registry and Two.Shape are missing.

**Comment by jonobr1** [comment]
@eulertour, the most up-to-date documentation lives in the source files now. This documentation has yet to be generated because I'm still writing it for each class, property, function, etc. Inline above each property there is a jsdoc style comment that describes what it does or expects.

I still have the effects folder and the renderers folder to do before I tackle rendering the documentation into HTML.

**Comment by meetzaveri** [comment]
Hey Jono,

Just wanted to let you know that some of the new APIs(such as two.makeArrow) are not part of the documentation. 

Is documentation moved away or it isn't updated acc. to latest stable release of 0.7.0?

**Comment by jonobr1** [comment]
Thanks for your post @meetzaveri, if you read the thread you'll see that the documentation has been moved to the source code as jsdocs style comments. This issue is to track generating and styling the new documentation for the site.

If you'd like to see what exists so far you can pull the latest dev repository, `npm install`, run `npm run docs:generate`, and finally `npm run docs:dev`.

**Comment by meetzaveri** [comment]
Got it. This clears out my confusion

**Comment by jonobr1** [comment]
New designs for the Two.js site and documentation by the amazing @yuinchien:

![Overview Page](https://user-images.githubusercontent.com/220033/112202521-dad48880-8be7-11eb-87c1-6502f21b15b7.png)
Here's the [figma file](https://www.figma.com/file/h3sSHqsw0WXZ0QpvtqvfqT/Two.js-Website).

**Comment by meetzaveri** [comment]
New design looks dope

**Comment by meetzaveri** [comment]
I think with this new design, API docs looks more accurate than before. 

Any idea when will be new design pushed?

**Comment by jonobr1** [comment]
No clear timeline on when this will all be implemented. But, slowly making progress!

Thanks for your patience.

**Comment by jonobr1** [comment]
Updated documentation is up on http://two.js.org/ now. Enjoy!

**Comment by yuinchien** [comment]
<img width="360" alt="Screen Shot 2021-11-28 at 12 31 54 PM" src="https://user-images.githubusercontent.com/406636/143784892-d3fb1939-d436-4553-b5ec-5c537b337432.png">

For mobile, perhaps you can remove the floating button label, having the button in circle shape is better for small screen.

**Comment by yuinchien** [comment]
<img width="824" alt="Screen Shot 2021-11-28 at 12 35 33 PM" src="https://user-images.githubusercontent.com/406636/143784995-ea81ce52-c932-4cb7-b639-4f4fd58f2d4a.png">

Text in <code> looks very thin, might want to increase font-weight.

**Comment by yuinchien** [comment]
<img width="200" alt="Screen Shot 2021-11-28 at 12 37 07 PM" src="https://user-images.githubusercontent.com/406636/143785184-0b78aa5b-b70f-40d9-8ac5-2504ce8d0c87.png">
The vertical line should left align with the category label, ~5px to the right.

**Comment by jonobr1** [comment]
Thanks @yuinchien, made those updates and just pushed them to the site.
