### ISSUE TITLE
Calculating coordinates of a position along a line/curve/shape at percentage X

### ISSUE THREAD

**Issue by handlez36** [jonobr1/two.js#297]
I often see these two lines when trying to move a point along a shape (shape, line, curve, polygon, etc...)...

```
shape.getPointAt(percentage, point.translation);
point.translation.addSelf(shape.translation);
```

I would think the first line would get the coordinates on the **_shape_** at a specific percentage along that shape, and subsequently set the **_point's_** position to those coordinates. Why wouldn't that line be enough to animate the point along the shape? I've tried it myself in another project, and see that the second line is needed, but cannot understand why. Thank you!

**Comment by jonobr1** [comment]
Thanks for posting this question! Yes, it is a bit confusing. I haven't looked at this specific code in a bit, but from what I gather the two steps are:

1. Get the point as it corresponds to a percentage along the vertices of the Path.
2. Add the Path's translation to get the "world position" of where the user expects to see the point.

**Comment by handlez36** [comment]
Ah OK, so the point along the line doesn't necessarily correspond to the "browser stage coordinates". So as an example, the coordinates I get with getPointAt is actually on the path, but just in a different coordinate system...is that accurate? 

I'm more used to having to translate between coordinate systems in 3D graphic programs, but I think that makes sense.

Thanks for the clarification.

**Comment by jonobr1** [comment]
Exactly, `getPointAt` is getting the points on the local coordinate system of the object. Those points are moved around by the `translation`, `rotation`, `scale` properties uniformly on the `Two.Path` to make the browser stage coordinate system.
