### ISSUE TITLE
Is there any way to bind mouse events to a motion of a polygon?

### ISSUE THREAD

**Issue by eliteluxury** [jonobr1/two.js#298]

**Comment by eliteluxury** [comment]
Hello @jonobr1. Sorry, I am completely new with two.js.
I made a Polygon using Two.Path, and I want to bind mouse event with only one side of Polygon.
Is it possible?

**Comment by jonobr1** [comment]
Ah, I see. You'll have to create additional shapes on top in order to isolate the event to one side. Here's an example of that: https://jsfiddle.net/jonobr1/49fo506u/

**Comment by eliteluxury** [comment]
https://zplan.co.uk/demo

Could you check this? It is built by Three.js. The room(path) area can be resized by dragging on a side of it.
Can i do this with two.js?

**Comment by jonobr1** [comment]
Cool demo! Yes, this is possible in Two.js

**Comment by eliteluxury** [comment]
I looked on your example and it looks what I was looking for.
Thanks @jonobr1 ,

**Comment by eliteluxury** [comment]
Could you not close this issue? I think I would get a new question soon?

**Comment by eliteluxury** [comment]
OK, thanks. :)
