### ISSUE TITLE
Get Text Width/Height

### ISSUE THREAD

**Issue by marwie** [jonobr1/two.js#299]
Hello, is it possible to get the Text Width/Height?

GetBoundingClientRect seems to only return the Anchor Point Position.

**Comment by jonobr1** [comment]
Thanks for posting this question @marwie. Currently there isn't a great way to calculate the bounding box for text...

Do you think it would be okay with an estimation? This would be derived from the `text.leading` value and the `Two.Text`'s transformation matrix. Not totally sure how to calculate the width consistently. I know there's a `canvas2d` API for getting the width. Any thoughts or suggestions would be greatly appreciated!

**Comment by jonobr1** [comment]
It looks like I'll be able to do an estimation with the Canvas API. The reason I think we should go through this route is that it will work on headless environments as well as all the renderers. In addition to this when the `<canvas /> v5` spec rolls out there will be additional properties to accurately measure a text element.

**Comment by jonobr1** [comment]
The current dev branch has an estimation [patch](https://github.com/jonobr1/two.js/commit/6dc59cf6a3143f94c0ef181fab5509bd87ed45d8) for this. Let me know if you try it out! Thanks for reporting.
