### ISSUE TITLE
Library wont start

### ISSUE THREAD

**Issue by F4Tornado** [jonobr1/two.js#300]
When I run this code:

```javascript
let two = new Two({
  fullscreen: true
}).appendTo(document.body);
```

I get these errors:

Chrome and Opera: Uncaught TypeError: Cannot read property 'style' of null    two.js:364

Firefox: TypeError: document.body is null     two.js:364:44

Edge: SCRIPT5007: SCRIPT5007: Unable to get property 'style' of undefined or null reference
two.js (364,44)

It's all referring to this line of code:
a.fullscreen ? (a = d.bind(k, this), d.extend(document.body.style, {

**Comment by jonobr1** [comment]
Which version of Two.js are you using?

**Comment by F4Tornado** [comment]
The one on the download page of the website.

**Comment by jonobr1** [comment]
🤔 

Maybe the download got corrupt. Or maybe you're trying to invoke this in a special context where `document` doesn't exist? With the same version of the library it works fine in [this jsfiddle](http://jsfiddle.net/jonobr1/up3m97dL/).

**Comment by F4Tornado** [comment]
I logged document and it was there. Also, your jsfiddle isn't correct. It runs

```javascript
let two = new Two({
	fullsc
})
```

**Comment by jonobr1** [comment]
Sorry about that! The [JSFiddle](http://jsfiddle.net/jonobr1/up3m97dL/) is up to date now. Any chance you can throw it online? Unfortunately, I won't be able to help you out if we continue in this manner.

**Comment by F4Tornado** [comment]
Yes...

**Comment by F4Tornado** [comment]
Here it is: https://f4tornado.github.io/TwoJS-Debugging/

It wont work instantly.

**Comment by jonobr1** [comment]
Ah, the reason it won't work is because you need to either:

A) Move the JavaScript `<script />` tags to be children of the `<body />` element
B) Wait for the `window.onload` event to fire

For the latter you'll have to do:

```javascript
var two;
window.onload = function() {
  two = new Two({
    fullscreen: true
  }).appendTo(document.body);
};
```

**Comment by F4Tornado** [comment]
Thanks! :-D

**Comment by jonobr1** [comment]
Awesome, happy coding!
