### ISSUE TITLE
How can I create an arc?

### ISSUE THREAD

**Issue by eliteluxury** [jonobr1/two.js#304]
![arc](https://user-images.githubusercontent.com/35144713/43874985-6bd1fe88-9b97-11e8-8142-08d656867b85.png)
I want to create part of circle, like in the picture.
Is there any easy way to do this?

**Comment by jonobr1** [comment]
This is the closest / fastest out of the box solution: https://jsfiddle.net/jonobr1/5qy7dxht/

**Comment by eliteluxury** [comment]
Hello @jonobr1 , Thank you very much.
One more question, does the arc segment is a path so that i can get vertices(anchors) from it?

**Comment by eliteluxury** [comment]
And where can i find the functions like two.makeArcSegment() that is not in the document?

**Comment by jonobr1** [comment]
@eliteluxury, `Two.ArcSegment` is a path so you can access its vertices the same way as any path.
```javascript
var arc = two.makeArcSegment(x, y, innerRadius, outerRadius, startAngle, endAngle);
arc.vertices // An array of vertices
```
As far as all the `make` functions. Right now the best way to find them is to see the primitives in [shapes folder](https://github.com/jonobr1/two.js/tree/dev/src/shapes). Each type of shape has a `make` function. I'm currently working on better documentation before releasing `v0.7.0` officially. Until then, this method will have to do... Sorry!

**Comment by eliteluxury** [comment]
Thank you @jonobr1,
I'd like to ask you one more question.

How can i change the origin of a path?

**Comment by jonobr1** [comment]
You can use path.translation which is a 2 component vector to move shapes around. But, if you need to change where the vertices are oriented around that vector you need to iterate through all the vertices... If you have thoughts on how you'd like it to work I'm all ears!

**Comment by jonobr1** [comment]
Tracking the discussion about origins here: https://github.com/jonobr1/two.js/issues/303
