### ISSUE TITLE
Basic usage example does not work

### ISSUE THREAD

**Issue by kinospro** [jonobr1/two.js#305]
What have done
I put basic example code right after two.js script tag.
`
	window.onload = function() {
	var elem = document.getElementById('draw-shapes');
	var params = { width: 285, height: 200};
	var two = new Two(params).appendTo(elem);
	var circle = two.makeCircle(72, 100, 50);
	var rect = two.makeRectangle(213, 100, 100, 100);

	circle.fill = '#ff8000';
	circle.stroke = 'orangered';
	circle.lineWidth = 5;

	rect.fill = 'rgb(0, 200, 255)';
	rect.opacity = 0.75;
	rect.noStroke();

	two.update();};
`
And this canvas inside body tag:
< canvas id="draw-shapes" width="500" height="500"></ canvas>

What is expected: Canvas filled with circle and rectangle.

What I see: Empty page. Canvas tag filled with SVG, but nothing shown:
`<svg version="1.1" width="285" height="200" style="overflow: hidden;"><defs></defs><g id="two_0" transform="matrix(1 0 0 1 0 0)" opacity="1"><path transform="matrix(1 0 0 1 72 100)" d="M 50 0 C 50 12.628 44.285 26.425 35.355 35.355 C 26.425 44.285 12.628 50 0 50 C -12.629 50 -26.426 44.285 -35.356 35.355 C -44.286 26.425 -50 12.628 -50 0 C -50 -12.629 -44.286 -26.426 -35.356 -35.356 C -26.426 -44.286 -12.629 -50 -0.001 -50 C 12.628 -50 26.425 -44.286 35.355 -35.356 C 44.285 -26.426 50 -12.629 50 0 Z " fill="#FF8000" stroke="orangered" stroke-width="5" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two_1"></path><path transform="matrix(1 0 0 1 213 100)" d="M -50 -50 L 50 -50 L 50 50 L -50 50 Z " fill="rgb(0, 200, 255)" stroke="transparent" stroke-width="1" stroke-opacity="0.75" fill-opacity="0.75" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two_2"></path></g></svg>`

Tested with 
Ubuntu 16.04
Chrome Version 68.0.3440.84 (Official Build) (64-bit)
Firefox 61.0.1 (64-bit)

**Comment by jonobr1** [comment]
Thanks for posting! There are two key params you'll need to do for this to work, I think.

```javascript
var two = new Two({
  type: Two.Types.canvas,
  width: 285,
  height: 200,
  domElement: document.getElementById('draw-shapes')
});
```

This will ensure instead of constructing and appending its own DOM Element, Two.js uses the one you're referring to.

**Comment by kinospro** [comment]
Thank you, jonobr1. Your version works fine.
Do you think example [here](https://two.js.org/#basic-usage) should be updated to work right away?
