### ISSUE TITLE
Add generative-design to project section

### ISSUE THREAD

**Issue by nitin42** [jonobr1/two.js#307]
Hello 👋🏻

First of all, thank you for such an awesome library for creating graphics. I have been working generative art and started using Two.js for some of the designs. I'd love to share my work with the community.

All the designs that I have created live here - https://generative-design.surge.sh

Some of the designs are interactive.

I'd love to see this being mentioned in project section!

**Comment by jonobr1** [comment]
Super cool! I'd be happy to add it to the Two.js projects 💯

**Comment by jonobr1** [comment]
Do you mind making a gif that is 286 x 200 animated gif of your favorite piece? Once I have that I can add it to the site. Nice work! 👏

**Comment by nitin42** [comment]
Awesome! Here you go -

![demo](https://user-images.githubusercontent.com/16336071/44519408-9492b200-a6ea-11e8-86b8-7ab649ea7e06.gif)

**Comment by jonobr1** [comment]
Awesome, it's up! https://two.js.org/projects/

**Comment by nitin42** [comment]
AWESOME! Thanks a lot 😄
