### ISSUE TITLE
graph drawing editor using two.js

### ISSUE THREAD

**Issue by hichem147** [jonobr1/two.js#310]
I am interested in using two.js to develop something like cytoscape.js (nodes, edges, pan & zoom, move node[drag & drop], add custom data to nodes and edges)
My starting point was : https://medium.com/@jakelandowski/small-graph-rendering-demo-with-two-js-5ef83fce476c
I stick to find simple tutorials. I am C# developer (can use JS but not expert in JS)
Should I go through three.js (the parent of two.js) to understand how to hook events to nodes ? 
Where I can find examples that can be a good starting point ? 
There are some concepts that are not easy to understand without some tutorials (like p5.js tutorials).
I stick with zoom (as mouse position the center), and select nodes.
Select Nodes : is there already in two.js the functionality to select a shape ? how to do it ?
Should I use canvas only or canvas & svg ? like in some examples that I found ?
To code the select Nodes, since the nodes are circles, I went through all the vertices and calculated the distance between the Mouse position and the each circle and I could find the selected node, but I am not sure that this is the best way to do it with two.js. At the same time I think that when I will go to the zoom, there should be other concepts about the rendering position.
Zoom : I saw the example of zoom UI with two.js https://two.js.org/examples/zui.html but I didn't understand how to use it.

I will include here the code I wrote where I have some problems to see why the scale of the vertexGroup and edgeGroup make the code draw both the initial shapes, and the scaled shapes !!!
[two_tuto.zip](https://github.com/jonobr1/two.js/files/2314108/two_tuto.zip)

I hope to find answers to these questions, at least some orientations where to start.

**Comment by jonobr1** [comment]
Looking really cool @hichem147! You have the right architecture setup for the application, just need a few more details for the specific `pan` and `zoom` states. Let me update [that example] to simplify things and that should get you sorted. 👍

**Comment by jonobr1** [comment]
Here's a cleaned up example for you: https://jsfiddle.net/jonobr1/hc196sju/

**Instructions:**
+ Click and drag to pan
+ Mousewheel / 2 finger-trackpad to zoom

You're going to want to use the latest version of Two.js from the `dev` branch ([here](https://github.com/jonobr1/two.js/blob/dev/build/two.js)) and then also import the extra `Two.ZUI` class by including [this script file](https://github.com/jonobr1/two.js/blob/dev/extras/zui.js)

It's up to you how you'd like to bind the event listeners so that your UI is intuitive. You can see in the demo I'm creating `mousedown` and `mousehweel` event listeners to set this up. But because the `Two.ZUI` is agnostic of UX you can hook up the `translateSurface` and `zoomBy` functions to other things if you'd like. Good luck!

**Comment by hichem147** [comment]
Great !!!
I will see how to make it work for my needs !!!
Thanks a loooot for your help !!!
I am convinced that 2D is the way our brain works, and a 2D library (like two.js) is usefull for mind maps, diagrams, ...

**Comment by jonobr1** [comment]
Also, if you're interested in building your own Pen Tool here's some starter code for it: https://jsfiddle.net/jonobr1/pvhwc7nu/

**Comment by hichem147** [comment]
Hello Mr Brandel,

Thank you for your proposition,
in fact I am working on a something like graph editor.
- placing nodes (with Node.id "N" + nodes_Num) (circle with text of its id
in it : N1, N2, ...)
- create branches linking two nodes
- select nodes, branches (single-select, multi-select, using
mouse-click-position, ctrl, shift[inside the rectangle defined by the
mouse])
*- Pan & Zoom (thanks to you for your help in the ZUI)*
- Move select nodes and at the same time the linked edges to the selected
nodes.

Until now I am just recreating functionalities that I found in
cytoscape.js, but the idea is to be able to have more freedom in
manipulating branches.
At the end my goal is to create a wire harness editor (only for nodes and
branches)

Here is where I am,
[X] placing nodes (with Node.id "N" + nodes_Num) (circle with text of its
id in it : N1, N2, ...) : *Done*
[X] create branches linking two nodes : *Done*
[/] select nodes, branches (, multi-select, using mouse-click-position,
ctrl, shift[inside the rectangle defined by the mouse])
         * single-select Nodes *Done*
         * single select branches (calculating distance to line-segment)
*Done*
         * Multi select Nodes, branches using Ctrl *Done*
         * Multi select branches using ctrl *Done*
         * Multi select Nodes/Branches using Shift + rectangle defined by
the mouse : *TO DO*
- write label on branche
          * Write branche label in the middle of the branche (line segment)
*Done*
          * automatic rotation with the branche angle *TO DO*
- write lable on node *Done*
*- Pan & Zoom (thanks to you for your help in the ZUI) **Done*
- Move select nodes and *at the same time the linked edges *to the selected
nodes considering the [real coordinates/rendered coordinates]
- Export SVG / PDF.

*Here is the current code main_v2.js :*
*I couldn't create a functional JSFiddle with my code*
/////////////////////////////////////////
//
https://medium.com/@jakelandowski/small-graph-rendering-demo-with-two-js-5ef83fce476c
const distanceBetween = (anchor, point) => Math.sqrt((anchor.y -
point.y)**2 + (anchor.x - point.x)**2);

console.log('ALLAH AKBAR');
var NbCircles = 0;
var  Status = 'PAN';
const two = new Two
({
fullscreen: true,
type: Two.Types.canvas
});

var isDragging = false;

 var styles = {
family: 'proxima-nova, sans-serif',
size: 10,
weight: 90
 };

const main = document.getElementById('main');
two.appendTo(main);

const canvas = main.getElementsByTagName('canvas')[0];

const vertexSize = 12;
const vertexOutlineSize = vertexSize / 3;

// Thickness of edge line
const edgeWidth = vertexOutlineSize;

var edgeNodes = [];
var nbEdges = 0;
const tolerance = 8;
const rayonExtremites = vertexSize;
function createEdge(vertex1, vertex2){
var edgeID = "segment_" + nbEdges;
let edge = two.makeLine(vertex1.translation.x, vertex1.translation.y,
vertex2.translation.x, vertex2.translation.y);
edge.stroke = "#BDBDBD";
edge.linewidth = edgeWidth;
edgeGroup.add(edge);
edge.id = edgeID;
var labelX = (vertex1.translation.x + vertex2.translation.x)/2;
var labelY = (vertex1.translation.y + vertex2.translation.y)/2;
var edgeLabel = two.makeText(edgeID, labelX, labelY, styles);
edgeLabel.fill = 'black';
two.update();
}


function linePosition(line, start=true){
return {
x: line.vertices[start ? 0 : 1].x + line.translation.x,
y: line.vertices[start ? 0 : 1].y + line.translation.y
};
}

function insideVertex(x, y, centerX, centerY, radius){
return x > centerX - radius && x < centerX + radius &&
y > centerY - radius && y < centerY + radius;
}

var mouse = {
  current: new Two.Vector(),
  previous: new Two.Vector()
};

var move = {
start: new Two.Vector(),
end: new Two.Vector()
};

var zui = new Two.ZUI(two.scene);
var realMousePos;

two.renderer.domElement.addEventListener('mousewheel', scroll, false);
two.renderer.domElement.addEventListener('mousedown', mousedown, false);

function mousedown(e) {
mouse.current.set(e.clientX, e.clientY);
mouse.previous.copy(mouse.current);

move.start.set(e.clientX, e.clientY);
window.addEventListener('mousemove', mousemove, false);
window.addEventListener('mouseup', mouseup, false);
realMousePos =
mouse.current.clone().subSelf(two.scene.translation).divideScalar(two.scene.scale);
}

function mousemove(e) {
mouse.current.set(e.clientX, e.clientY);
if(!isDragging){
isDragging = true;
}

var dx = mouse.current.x - mouse.previous.x;
var dy = mouse.current.y - mouse.previous.y;

// To Pan
if (Status !== 'MOVE'){
zui.translateSurface(dx, dy);
} else {
// Move Selected Nodes
Move_SelectedNodes(dx, dy);
}

mouse.previous.copy(mouse.current);
}

function mouseup(e) {
move.end.set(e.clientX, e.clientY);
window.removeEventListener('mousemove', mousemove, false);
window.removeEventListener('mouseup', mouseup, false);
}

function scroll(e) {

  e.stopPropagation();
  e.preventDefault();

  var dy = (e.wheelDeltaY || - e.deltaY) / 1000;

// To zoom by an increment
  zui.zoomBy(dy, e.clientX, e.clientY);

}
//=========== RUN =============//


// 2 logical groups for edge lines
// 1 currently animating the other for finished animating
const edgeRenderingGroup = two.makeGroup();
const edgeGroup = two.makeGroup();

// The logical grouping of shape objects
// Like layers in photoshop/illustrator
const vertexGroup = two.makeGroup();
const selectedVertices = [];
const selectedBranches = [];

// Array that holds the actual shape objects
const vertices = vertexGroup.children;
const branches = edgeGroup.children;

function Unselect_SelectedNodes(){
while(selectedVertices.length > 0){
selectedVertices[0].fill = '#A9D0F5';
selectedVertices.shift();
}
}

function Unselect_SelectedBranches(){
while(selectedBranches.length > 0){
selectedBranches[0].stroke = "#BDBDBD";
selectedBranches[0].linewidth = edgeWidth;
selectedBranches.shift();
}
}

function Render_SelectedNodes(){
for(let iVertex = 0; iVertex < selectedVertices.length; iVertex++){
selectedVertices[iVertex].fill = '#FF8000';
}
}

function Render_SelectedBranches(){
for(let iBranche = 0; iBranche < selectedBranches.length; iBranche++){
selectedBranches[iBranche].stroke = "#F4A460";
selectedBranches[iBranche].linewidth = edgeWidth*1.5;
}
}

function getSelectedNode(mousePos_real){
var result = null;
for(let iVertex = 0; iVertex < vertices.length; iVertex++)
{
if (insideVertex(mousePos_real.x, mousePos_real.y,
vertices[iVertex]._translation.x, vertices[iVertex]._translation.y,
vertexSize))
{
var dist = mousePos_real.distanceTo(vertices[iVertex]._translation);
if (dist < vertexSize){
SelectedNode_done = true;
var vertexSelected = vertices[iVertex];
return vertexSelected;
}
}
}
return result;
}

//Create Vertex on click
canvas.onclick = function(event)
{
if (isDragging == true) {
isDragging = false;
var Dx = move.start.x - move.end.x;
var Dy = move.start.y - move.end.y;
if ((Math.abs(Dx) + Math.abs(Dy)) > 10){ return; }
}
// x, y position of the click event
let x = event.offsetX;
let y = event.offsetY;
var mousePos = new Two.Vector(x, y);
if (Status == 'NODE'){
let x = Math.round(realMousePos.x);
let y = Math.round(realMousePos.y);
let vertex = two.makeCircle(x, y, vertexSize);
NbCircles++;
vertex.id = "N" + NbCircles;
var directions = two.makeText(vertex.id,x, y, styles);
      directions.fill = 'black';
// Set fill color outline thickness
vertex.fill = '#A9D0F5';
vertex.noStroke();
vertexGroup.add(vertex);
two.update();
}
if (Status == 'SELECT'){
var SelectedNode_done = false;
if(vertices.length > 0){
var SelectedNode = getSelectedNode(realMousePos);

if(!event.ctrlKey){
Unselect_SelectedNodes();
}
if (SelectedNode !== null){
selectedVertices.push(SelectedNode);
}

if (selectedVertices.length > 0){
Render_SelectedNodes();
}
}
var selectedBranche = null;
if (branches.length > 0){
console.log("realMousePos");
console.log(realMousePos);
for(let iBranche = 0; iBranche < branches.length; iBranche++){
if (isBetween(branches[iBranche].vertices[0],
branches[iBranche].vertices[1], realMousePos, tolerance, rayonExtremites)){
selectedBranche = branches[iBranche];
}
}
if(!event.ctrlKey){
Unselect_SelectedBranches();
}
if (selectedBranche !== null){
selectedBranches.push(selectedBranche);
}

if (selectedBranches.length > 0){
Render_SelectedBranches();
}
}
}//end if

if (Status == 'BRANCHE'){
var SelectedNode_done = false;
if(vertices.length > 0){
var SelectedNode = getSelectedNode(realMousePos);
//if no selected node => Unselect selected nodes
if (SelectedNode == null){
Unselect_SelectedNodes();
edgeNodes.length = 0;
} else {
if (selectedVertices.length < 2){
//Create Edge
if(edgeNodes.length == 0){
console.log("<<<<<<< un seul node selected 1 ... waiting for the other node
!!!");
console.log(edgeNodes);
edgeNodes.push(SelectedNode);
} else if (edgeNodes.length == 1) {
console.log("les deux nodes sont definis >>>>>>>");
console.log(edgeNodes);
if (edgeNodes[0].id != SelectedNode.id){
edgeNodes.push(SelectedNode);
}
}
if (edgeNodes.length == 2){
nbEdges++;
createEdge(edgeNodes[0], edgeNodes[1]);
edgeNodes.shift();
}
} else {
edgeNodes.length = 0;
}
console.log("unselect selected nodes");
Unselect_SelectedNodes();
console.log("selectedVertices.push(SelectedNode)");
selectedVertices.push(SelectedNode);
}

if (selectedVertices.length > 0){
Render_SelectedNodes();
}
}
}//end if

if (Status == "PAN"){
}
if (Status == "MOVE"){
console.log("MOVE");
}
};

// Render loop
two.bind('update', function(){
});

two.play();

function SetStatus(status){
console.log("NEW MODE : " + status);
Status = status;
if (Status !== 'MOVE'){
Unselect_SelectedNodes();
}
if (Status == 'MOVE'){
document.body.style.cursor  = 'move';
} else {
document.body.style.cursor  = 'default';
}
}

function Point_To_Line_Distance (Node1, Node2, mousePos) {
var mx = mousePos.x, my = mousePos.y;
      var vx = mx-Node1.x,   vy = my-Node1.y;   // v = A->P
      var ux = Node2.x-Node1.x,   uy = Node2.y-Node1.y;   // u = A->B
      var det = vx*ux + vy*uy;

      if (det <= 0)
      { // its outside the line segment near A
        return vx*vx + vy*vy;
      }

      var len = ux*ux + uy*uy;    // len = u^2
      if (det >= len)
      { // its outside the line segment near B

        return Math.pow(Node2.x-mx,2) + Math.pow(Node2.y-my,2);
      }

      return Math.pow(ux*vy-uy*vx,2) / len;    // (u X v)^2 / len
    };

function isBetween(a, b, c, tolerance, rayonExtr) {
var squaredlengthba = (b.x - a.x)*(b.x - a.x) + (b.y - a.y)*(b.y - a.y);
    //test if the point c is inside a pre-defined distance (tolerance) from
the line [a - b]
    var distance = Math.abs( (c.y - b.y)*a.x - (c.x - b.x)*a.y + c.x*b.y -
c.y*b.x ) / Math.sqrt(squaredlengthba);
    if (distance > tolerance) { return false; }

    //test if the point c is between a and b
    var dotproduct = (c.x - a.x) * (b.x - a.x) + (c.y - a.y)*(b.y - a.y);
    if (dotproduct < 0) { return false; }


    if (dotproduct > squaredlengthba) { return false;
}

var distPoint1 = a.distanceTo(c);
if (distPoint1 < rayonExtr) { return false;
}

var distPoint2 = b.distanceTo(c);
if (distPoint2 < rayonExtr) { return false; }

    return true;
};
/////////////////////////////////////////

and here is a print screen of an output.
[image: image.png]


I expect to get some difficulty to have the functionality
- Move select nodes and *at the same time with the linked edges *to the
selected nodes considering the [real coordinates/rendered coordinates]

I suppose I will need to use
                   two.bind('update', function(){
                   });
to make the node move at the same time with the linked edges.

I will get back to you.

Thanks for your help.

Best regards.

Hichem CHTARA
From TUNISIA

Le dim. 26 août 2018 à 16:35, Jono Brandel <notifications@github.com> a
écrit :

**Comment by hichem147** [comment]
finally I could create a JsFiddle : https://jsfiddle.net/hichem147/fdzn1u0x/
Create Nodes by : Click button [Node], then click where you want to add a node
Create Branches : click button [Branche], then select the nodes you want to link by a branche

**Comment by jonobr1** [comment]
Looks great so far 🙌
