### ISSUE TITLE
How to remove a circle included in a group

### ISSUE THREAD

**Issue by hichem147** [jonobr1/two.js#312]
Hi, I thank you for your help in the graph editor, I am facing two concepts that I couldn't understand even if I tried a lot of things before to get back to you :).
1) How to have the node label written over the nodes, 
2) How to remove a circle
I could remove a text in the scene with no problems.
      var Node_Label = two.makeText(node_id,x, y, styles);
      Node_Label.remove();
but with the circle I have an error 

the circle is included in a group (as said the blogger, to make the circles be drawn over the edges)
https://medium.com/@jakelandowski/small-graph-rendering-demo-with-two-js-5ef83fce476c
I tried the following syntax to remove the circle from the group
     vertexGroup.remove(selectedNodes[iVertex].circle);
and I tried 
     selectedNodes[iVertex].circle.remove();
I get the following error
Uncaught TypeError: Cannot read property '_renderer' of undefined
    at Two.Circle.render (two.js:4614)
    at Two.Group.render (two.js:4575)
    at Two.(anonymous function).render (file:///E:/COFAT/WebGraph/two/two_Graph02/two.js:5146:27)
    at Two.root.Two.render (two.js:2202)
    at Two.root.Two.update (two.js:2193)
    at loop (two.js:2560)

to reproduce the error : create 2 or 3 nodes 
- click button [(+) Node] then, 
- click in the canvas where you want to create a node

to remove the nodes : 
- click button [Select]
- click over the circle of the node to remove
- click button [(-) Node]
- click button [Pan/Zoom]

The code is attached here
[two_Graph03.zip](https://github.com/jonobr1/two.js/files/2339561/two_Graph03.zip)

**Comment by jonobr1** [comment]
On line `291` `Node_Circle.id = node_id;` has unintended consequences. You cannot modify the id in this way. Instead add a new property like `Node_Circle.node_id = node_id;` as a way to reference it for later use.

**Comment by hichem147** [comment]
thanks for your help !!!
