### ISSUE TITLE
Interpreted svg renders off origin

### ISSUE THREAD

**Issue by eddnav** [jonobr1/two.js#316]
Any idea why this might be happening?:

https://codepen.io/eddnav/pen/mGGGmE

Notice the image is shown as if it was translated half of its width from origin.

**Comment by jonobr1** [comment]
<img width="1552" alt="screen shot 2018-09-19 at 11 07 37 pm" src="https://user-images.githubusercontent.com/220033/45781715-154cbb80-bc61-11e8-9572-9ec098f634e2.png">

Is this what you see?

I had to comment out the `two.remove(svg);` part. If you want to draw the image from the center of it you can run `svg.center();` and then move it to wherever you'd like. Hope this helps!

**Comment by eddnav** [comment]
Worked perfectly!
