### ISSUE TITLE
How to access WebGL Vertex Buffer

### ISSUE THREAD

**Issue by sanatshah** [jonobr1/two.js#318]
I have specified the renderer to use Two.type.webgl. When I inspect the two.shape I see a _renderer object that contains a WebGl Buffer and some other information, but the WebGl Buffer seems to be empty. 

What is the process getting the ArrayBuffer? I am looking to caclulate aabb for shapes. 

Thanks.

**Comment by jonobr1** [comment]
Thanks for the question! Have you tried calling two.update() before inspecting the _renderer object?

Also, when you say AABB are you referring to Boolean operations on shapes? The WebGL Renderer actually draws the shape in canvas2D and then uploads it as a texture, so it may not even be possible in the way you'd like to proceed.

That being said I've been looking at ways to change and upgrade the WebGL Renderer to not have this upload step. It'll be awhile but I have made some progress to do much of the tesselation in the fragment shader.

**Comment by sanatshah** [comment]
Ok I see, that makes sense. Thanks for the reply!

**Comment by jonobr1** [comment]
Of course! And yes, always happy to have PRs 😺 

Don't hesitate to start another issue if you have any other questions.
