### ISSUE TITLE
Question/Documentation: What is the difference between two.js and paper.js?

### ISSUE THREAD

**Issue by RichardJECooke** [jonobr1/two.js#319]
This project looks like it has identical features to paper.js, an older animation library.

Please will you put in the documentation what the difference/reasoning/audience is?  I'm not sure which one to use when starting to learn 2D animation.

**Comment by jonobr1** [comment]
The aims of the two libraries are similar and in fact there is some discussion about combining the two. But generally speaking..:

+ Paper.js is more feature complete for advanced manipulation of paths. For instance you can do Boolean operations. Two.js is more nascent and doesn't have that type of control.
+ Two.js is render agnostic so it can render into SVG, canvad2d, and webgl environments. Paper.js tenders to canvas2d.

One large similarity is that both librariers are run by individuals.

There are many other small things and while I appreciate your concern to map out the differences for people it's not realistic for the limited resources that I operate under. I'd happily post on the documentation ( which I'm almost done revamping ) an article of the differences if you or someone else maps that. Hope this is helpful!
