### ISSUE TITLE
How can I resize my canvas/svg  on 16/9 ratio and scale. 

### ISSUE THREAD

**Issue by shader04** [jonobr1/two.js#322]
https://vuetifyjs.com/en/layout/aspect-ratios I'm using for hold my canvas. if I give a size to canvas, v-responsive does not work. when it comes to the same height as the canvas it stops.  But in any case, "new Two" automatically gives height. I want to make a free drawing and shrink the canvas by 16/9 and keep the picture I draw.

**Comment by shader04** [comment]
![screenshot from 2018-10-08 17-56-25](https://user-images.githubusercontent.com/27967616/46616584-8aeecd80-cb23-11e8-8b93-66d6e5f076b3.png)
![screenshot from 2018-10-08 17-56-21](https://user-images.githubusercontent.com/27967616/46616586-8cb89100-cb23-11e8-938c-2d4e33678ccc.png)
like that. i couldn't do this on two.js

**Comment by shader04** [comment]
![basliksisz](https://user-images.githubusercontent.com/27967616/46617037-76f79b80-cb24-11e8-8d23-3723c4589765.jpeg)
![basliksiz](https://user-images.githubusercontent.com/27967616/46617038-77903200-cb24-11e8-8898-5c63f800e23c.jpeg)

like that. i couldn't do this on two.js

**Comment by shader04** [comment]
like that. i couldn't do this on two.js

![screenshot from 2018-10-08 18-04-49](https://user-images.githubusercontent.com/27967616/46617136-adcdb180-cb24-11e8-8df4-5f14054378cc.png)
![screenshot from 2018-10-08 18-04-33](https://user-images.githubusercontent.com/27967616/46617138-ae664800-cb24-11e8-9311-4782214c3e1e.png)

**Comment by jonobr1** [comment]
Thanks for your question! I don't know if I fully understand.., but whenever the ratio updates you need to call `two.renderer.trigger( Two.Events.resize, newWidth, newHeight );` and then it'll be respected. Also, make sure that you're using the latest Two.js on the `dev` branch. Hope this helps!

If not please try to post the code online so I can help debug further.

**Comment by shader04** [comment]
> Thanks for your question! I don't know if I fully understand.., but whenever the ratio updates you need to call `two.renderer.trigger( Two.Events.resize, newWidth, newHeight );` and then it'll be respected. Also, make sure that you're using the latest Two.js on the `dev` branch. Hope this helps!
> 
> If not please try to post the code online so I can help debug further.

https://codepen.io/johnjleider/pen/bgJOrX?editors=1010 firstly thank you for your interest. Here's my codes. I want the things I draw when I resize the canvas to shrink in the same place. for example, if I draw a round in the bottom right corner at 1920x1080, I want this round to remain in the same place at 640 × 480. I hope I could explain my problem

**Comment by jonobr1** [comment]
Ah okay, I think I understand a bit better. You're going to want to change your `resize` event to look more like this:

```javascript
window.addEventListener("resize", function(event) {
  var scale = elem.offsetWidth / vuem.two.width;
  vuem.two.scene.scale = scale;
  vuem.two.renderer.setSize(elem.offsetWidth, elem.offsetHeight);
});
```

Then whenever you're drawing you need to apply the scale value of `vuem.two.scene.scale` to the `x`, `y` values of the mouse position. This will make sure the user draws where they want to regardless of the size of the canvas. E.g:

```javascript
x = event.offsetX / vuem.two.scene.scale;
y = event.offsetY / vuem.two.scene.scale;
```

**Comment by shader04** [comment]
> Ah okay, I think I understand a bit better. You're going to want to change your `resize` event to look more like this:
> 
> ```js
> window.addEventListener("resize", function(event) {
>   var scale = elem.offsetWidth / vuem.two.width;
>   vuem.two.scene.scale = scale;
>   vuem.two.renderer.setSize(elem.offsetWidth, elem.offsetHeight);
> });
> ```
> 
> Then whenever you're drawing you need to apply the scale value of `vuem.two.scene.scale` to the `x`, `y` values of the mouse position. This will make sure the user draws where they want to regardless of the size of the canvas. E.g:
> 
> ```js
> x = event.offsetX / vuem.two.scene.scale;
> y = event.offsetY / vuem.two.scene.scale;
> ```

Yeah! Thank you so much for your help. I've added a div that changes the size in 16/9 format, but what is the reason the svg'm goes under the div? https://codepen.io/alper-koan/pen/VEPMaj?editors=1010

**Comment by jonobr1** [comment]
I'm not exactly sure how that Vue component works, but it looks like it's adding a 56% `padding-top` CSS command to the `#responsive` divider element. If you add this line after constructing Two.js it should fix it:

```javascript
this.two.renderer.domElement.style.position = 'absolute';
this.two.renderer.domElement.style.top = 0;
this.two.renderer.domElement.style.left = 0;
```

**Comment by shader04** [comment]
> I'm not exactly sure how that Vue component works, but it looks like it's adding a 56% `padding-top` CSS command to the `#responsive` divider element. If you add this line after constructing Two.js it should fix it:
> 
> ```js
> this.two.renderer.domElement.style.position = 'absolute';
> this.two.renderer.domElement.style.top = 0;
> this.two.renderer.domElement.style.left = 0;
> ```

thank you, worked. I'm grateful for your help
