### ISSUE TITLE
How do I know if a point is in the area I selected?

### ISSUE THREAD

**Issue by webenters** [jonobr1/two.js#323]
How do I know if a point is in the area I selected?
like the API:  isPointInPath(x, y)

**Comment by webenters** [comment]
I need to interact with a certain area of the graphic I am drawing.

**Comment by webenters** [comment]
Thanks, [this example](https://two.js.org/examples/advanced-anchors.html) is similar to my case, but I use the canvas, i want to bind different parts in one canvas. can I do this? (Because I had draw a pie charts, I should mouseover in different part and show different tips)

**Comment by jonobr1** [comment]
This example shows how you can make a simple Pen Tool in Two.js: https://jsfiddle.net/jonobr1/pvhwc7nu/

But, for your case if the Pie Chart already exists I think you'd have to make a custom function to check for hover etc.. I can make a demo for this, but if you have some sample code it would be easier to build off of and show you a specific example.

**Comment by jonobr1** [comment]
FYI: I am tracking hit-test logic here https://github.com/jonobr1/two.js/issues/306

**Comment by webenters** [comment]
> This example shows how you can make a simple Pen Tool in Two.js: https://jsfiddle.net/jonobr1/pvhwc7nu/
> 
> But, for your case if the Pie Chart already exists I think you'd have to make a custom function to check for hover etc.. I can make a demo for this, but if you have some sample code it would be easier to build off of and show you a specific example.

supper cool, it's very useful
