### ISSUE TITLE
how can I use brush like  an eraser

### ISSUE THREAD

**Issue by shader04** [jonobr1/two.js#324]
hello, I can make drawing using makeCurve as in your free drawing example. I can do undo and redo operations by playing on two.scene.children but I have to change drawing mode to something like destination-out for deletion, just like on context2d. Can I edit two.scene.children._collections? What is the way to return to eraser mode?

**Comment by shader04** [comment]
edit : I don't want to remove objects completely, just think of spelling mistakes and you want to continue to erase and draw

**Comment by jonobr1** [comment]
You could set specific objects to `visible = false`, but that wouldn't allow for partial object erasure. Would something like this solve the problem for you?

https://jsfiddle.net/jonobr1/c258fs31/
