### ISSUE TITLE
Add ability to connect more lines on one point and intersection point

### ISSUE THREAD

**Issue by sami8github** [jonobr1/two.js#326]
If there is possibility to add ability to connect more lines on one point and ability to make shapes share points (intersection).

![image](https://user-images.githubusercontent.com/41632592/47263083-f5bfe180-d4f1-11e8-98d5-2957a4e39976.png)

**Comment by jonobr1** [comment]
You can, but at the moment it's not super intuitive. Here's an example recreating the scene on the right which you're interested in.

https://jsfiddle.net/jonobr1/31e27tpy/
