### ISSUE TITLE
The size of an Ellipse is changed when clone

### ISSUE THREAD

**Issue by t3space** [jonobr1/two.js#329]
Hello @jonobr1 , I am contacting you again as I met a problem when I clone an Ellipse object.
![image](https://user-images.githubusercontent.com/43683716/47827629-aa29f500-dd87-11e8-923f-ed04070b6a33.png)

The background circle is the origin Ellipse object

![image](https://user-images.githubusercontent.com/43683716/47828171-89af6a00-dd8a-11e8-941b-57b9b4c2812d.png)

And this is the cloned one.

I just cloned, I am not sure why the size is changed.

I'd like to know if I need to add some more operations.

Thanks!

**Comment by jonobr1** [comment]
Nothing wrong on your end. There was an issue with the `Two.Ellipse.clone` method. It's fixed in the latest `dev` branch. Thanks for reporting!

**Comment by t3space** [comment]
Thanks @jonobr1
