### ISSUE TITLE
Two.js and Aurelia

### ISSUE THREAD

**Issue by arnonuem** [jonobr1/two.js#334]
I cant get Two.js work together with Aurelia and Webpack.

When i try to import like `import { Two } from 'two.js';` i get the following error.

```
ERROR in ./node_modules/two.js/build/two.module.js
Module not found: Error: Can't resolve 'fs' in 'D:\Projekte\dev\dlr\windsim\node_modules\two.js\build'
 @ ./node_modules/two.js/build/two.module.js 11637:19-32
 @ ./src/public-root.js
 @ ./src/main.js
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper```

Any ideas?

**Comment by jonobr1** [comment]
This is in a node environment, right? ( And not in the browser )

**Comment by arnonuem** [comment]
Aurelia is a competitor for AngularJS

**Comment by arnonuem** [comment]
I think all would be fine if there was a possibility to use two.js with webpack

**Comment by jonobr1** [comment]
Got it. Two.js should be compatible with Webpack. Lemme double check

**Comment by jonobr1** [comment]
It looks like from your error Two.js thinks you're in a headless environment. But, you're loading this in the browser correct?

**Comment by arnonuem** [comment]
yes

**Comment by arnonuem** [comment]
I did `npm install two.js --save` in my Aurelia project like i do with all 3rd party libraries.
And then i usually go into the dist folder of what was downloaded in my node_modules folder and i look within the dist file for the module exports.
In your case it says `module.exports = Two;`

Then i import the library using `import { Two } from 'two.js';`

Btw. I am using ES6.

**Comment by arnonuem** [comment]
If you want to try it out on yourself you can take a look into this quick setup guide of Aurelia. https://aurelia.io/docs/build-systems/aurelia-cli/

**Comment by jonobr1** [comment]
Thanks for sharing. I'll give this a try tonight.

**Comment by jonobr1** [comment]
Thanks again for posting and sorry for the delay. I've published latest builds to `npm` and dev. If you re-install two.js it should work with Aurelia ( webpack ).
