### ISSUE TITLE
Incorrect vertice calculation on resize

### ISSUE THREAD

**Issue by chrisjansky** [jonobr1/two.js#335]
Downloading the latest beta version and copy pasting (literally) the Gradients example, I get a weird vertice miscalulation on browser resize. Rolling back to v0.6.0 fixes the issue. See the screenshot attached.
![screenshot 2018-11-22 at 00 49 10](https://user-images.githubusercontent.com/5342612/48873879-a15d9980-edf0-11e8-9ad7-9d5174728579.png)

**Comment by jonobr1** [comment]
Thanks for reporting. That example is running with v0.6.0. I think there was a slight API change to the gradients which is why it looks busted in the latest. I'll confirm and follow up once I'm in the studio.

**Comment by jonobr1** [comment]
I tried the latest from `npm` and from the repo and the example works fine for me.

**Comment by Muneem** [comment]
i also face same issue. its adding extra vertices. in two.rectangle there were 4 vertices before but with latest release there are 5 vertices

**Comment by jonobr1** [comment]
The 5 vertices should only be added if it's a Two.Sprite, not if it's a rectangle. I'll check on that. To confirm, that specific example uses jQuery and some other third party libraries. Those are loaded correctly and there aren't any errors in the console?

Just trying to find a way to reproduce it on my side.

**Comment by jonobr1** [comment]
Ah, I was able to reproduce the problem. Here's an updated version that works with `v0.7.0+`: https://jsfiddle.net/jonobr1/n1fx9jkm/

The main issue is that you don't need to modify the vertices on window resize. You can change the `width` and `height` parameters like so:

```javascript
// Do this
rectangle.width = two.width;
rectangle.height = two.height;
// Instead of 
rectangle.vertices[0].x = - two.width / 2;
rectangle.vertices[0].y = - two.height / 2;
// ... etc. for all vertices
```

**Comment by Muneem** [comment]
i am using two.rectngle not tw.sprite and its still adding 5 vertices.

**Comment by chrisjansky** [comment]
@jonobr1 Rewriting the resize function seems to have fixed it, thanks!
