### ISSUE TITLE
Is it possible to change visual ordering regardless of grouping? 

### ISSUE THREAD

**Issue by ceremcem** [jonobr1/two.js#336]
I have an [ordering issue in my application](https://github.com/ceremcem/aecad/issues/9) which I'm using a totally different library other than two.js. I'm curious about if Two.js has a solution for this particular issue already. (Related SO question [here](https://stackoverflow.com/q/53426138/1952991))

## Description 

I need to define a component (collection of `Shape`s in a parent `Group`) that consists of a circle with a text. When 2 instances overlaps, their texts should be stay readable, unlike this: 

![image](https://user-images.githubusercontent.com/6639874/48968406-51552180-f000-11e8-8868-38e6cb68dd40.png)

Is there such an ordering option available in Two.js?

# Related

By the way, following SVG *trick* (the `<use />` tag) does the job: (adapted from [so answer](https://stackoverflow.com/a/24013696/1952991))
```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="107.36328" height="100" viewBox="359.5,265,107.36328,100">
   <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal">
      <g transform="translate(409.5,315)">
         <circle cx="0" cy="0" r="50" fill="#ff0000"/>
         <text id="foo" x="0" y="0" fill="#000000" font-family="sans-serif" font-weight="normal" font-size="12" text-anchor="start">hello world</text>
      </g>
      <g transform="translate(419.5,325)">
         <circle cx="0" cy="0" r="40" fill="#ffff00"/>
         <text x="0" y="0" fill="#000000" font-family="sans-serif" font-weight="normal" font-size="12" text-anchor="start">hi there</text>
      </g>
   </g>
   <use transform="translate(409.5,315)" xlink:href="#foo" />
</svg>
```

...which produces the desired output: 

![image](https://user-images.githubusercontent.com/6639874/48968372-a5abd180-efff-11e8-8dcc-0d960a394b2d.png)

**Comment by jonobr1** [comment]
In Two.js I would construct my application like so:

```javascript
var content = new Two.Group();
var ui = new Two.Group();
var elements = [];

var element = {};
element.circle = new Two.Circle(...);
element.text = new Two.Text(...);

elements.push(element);
content.add(element.circle);
ui.add(text);

two.add(content, ui); // Objects in `content` will show up under objects in `ui`
```

TBH you could probably construct it this way in Paper.js too.

**Comment by ceremcem** [comment]
To be more specific, please consider the following example: (sorry, it's mostly copy/paste)

```js
var elem = document.getElementById('draw-group');
var two = new Two({ width: 285, height: 200 }).appendTo(elem);

var circle = two.makeCircle(-70, 0, 50);
var rect = two.makeRectangle(70, 0, 100, 100);
circle.fill = '#FF8000';
circle.stroke = 'orangered';
rect.fill = 'rgba(0, 200, 255, 0.75)';
rect.stroke = '#1C75BC';
var group = two.makeGroup(circle, rect);


var circle2 = two.makeCircle(-70, 0, 50);
var rect2 = two.makeRectangle(70, 0, 100, 100);
circle2.fill = '#FF8000';
circle2.stroke = 'orangered';
rect2.fill = 'rgba(0, 200, 255)';
rect2.stroke = '#1C75BC';
var group2 = two.makeGroup(circle2, rect2);

group2.translation.set(two.width / 2, two.height / 2);

// And have translation, rotation, scale like all shapes.
group.translation.set(two.width / 2, two.height / 2);
group.rotation = Math.PI;
group.scale = 0.75;

// You can also set the same properties a shape have.
group.linewidth = 7;

two.update();
```

The result is: 

![image](https://user-images.githubusercontent.com/6639874/48968968-34245100-f008-11e8-863f-c29a71bc6ecf.png)

How could it be possible without touching the `Group` contents?

# Rationale 

The further positioning, rotation etc. operations in the application rely on `Group` facilities.

**Comment by jonobr1** [comment]
Unfortunately there isn't a direct way to change the render order as you describe... One work around could be this though:

```
var circle = new Two.Circle(...);
var text = new Two.Text(...);

contents.add(circle);
ui.add(text);

// Set the translation of both objects to the same Two.Vector
// This will force the same position of the objects
text.translation = contents.translation;

// Or listen when the circle translation changes and update accordingly
circle.translation.bind(Two.Events.change, function() {
  text.translation.copy(circle.translation);
});

```

**Comment by ceremcem** [comment]
Thank you for your time and explanations. I think, `circle.translation.bind` will do the trick: 

* Upon my component creation, component will decide what to stay in [`HUD Layer`](https://user-images.githubusercontent.com/6639874/48971598-e53ce280-f02c-11e8-938c-cb9f4da60d2f.png)
* Component will duplicate the geometry(ies) while marking them `temporary`
* ...and will arrange their position when its position is changed. 

It's very nice to see that Two.js has such a subscription mechanism out of the box.
