### ISSUE TITLE
two.group rotation property

### ISSUE THREAD

**Issue by Muneem** [jonobr1/two.js#341]
I have created 2 two.line objects and then put it in two.group. When i apply rotation then all of its vertices are flipped.

I want to know where is that rotation property implemented as from code i think so its only transform property which is applying rotation? Actually i wanted to know why all those vertices are flipped?

**Comment by jonobr1** [comment]
Do you have an example online? This is where Two.js updates the rotation and applies it to the underlying matrix ([here](https://github.com/jonobr1/two.js/blob/dev/src/shape.js#L244)).
