### ISSUE TITLE
WebGL circle mask issue

### ISSUE THREAD

**Issue by snorpey** [jonobr1/two.js#343]
Hey there,

thank you for creating this amazing library!

I just came across a bug when trying to create a simple mask. It seems to use a rectangle instead of a circle for the mask:

Expected output:
<img width="386" alt="screen shot 2019-01-13 at 18 18 57" src="https://user-images.githubusercontent.com/166433/51088425-c838ac00-175f-11e9-95db-5b818055531c.png">

Actual ouput:
<img width="385" alt="screen shot 2019-01-13 at 18 18 39" src="https://user-images.githubusercontent.com/166433/51088430-d4bd0480-175f-11e9-9897-b38cc445c584.png">

This bug only occurs when using the `webgl` renderer, in both `v0.60` and `v0.7.0-beta.3`.  It looks fine in the `canvas` renderer.

You can find the code here:
https://jsfiddle.net/pgjh6qfy/1/

OS: `macOS High Sierra 10.13.6`
Browsers: `Firefox 64.0.2`, `Chrome 71.0.3578.98` and `Safari 12.0.2`

**Comment by jonobr1** [comment]
Thanks for sharing! Unfortunately, I haven't cracked masks on the WebGL Renderer.., but this is a great issue to track to fix it.

**Comment by KramerTech** [comment]
Just encountered this issue myself. And as a followup, things aren't quite right on canvas either when the mask starts moving as in the example:

https://two.js.org/examples/clipping-mask.html?type=canvas

**Comment by jonobr1** [comment]
This has been partially updated in the latest dev. Unfortunately, when using masks in webgl I can't figure out how to get a pass through within the stenciled context. So, if you're drawing elements underneath the mask it won't work perfectly. If you don't draw anything underneath the mask it should work fine now.

**Comment by adroitwhiz** [comment]
@jonobr1 This is fixed now, right?

**Comment by jonobr1** [comment]
Yep!

**Comment by adroitwhiz** [comment]
So this issue can be closed?
