### ISSUE TITLE
Option for changing the rendering order of objects in canvas

### ISSUE THREAD

**Issue by manusoman** [jonobr1/two.js#346]
Can you tell me if there is any option available to change the order of rendering of objects in canvas with code? If it's not available, can you guys think about adding it?

**Comment by jonobr1** [comment]
Currently the only way to change order programmatically is to create `Two.Group`s and add children to different ones. E.g:

````javascript
var background = two.makeGroup();
var foreground = two.makeGroup();

var circle = two.makeCircle(0, 0, 50);
background.add(circle);

var square = two.makeRectangle(0, 0, 50, 50);
background.add(square);

foreground.add(circle); // Circle will show up on top now
````

Alternatively, if you're rendering with the Canvas or WebGL renderer you can just change the array on the scene directly:

````javascript
var circle = two.makeCircle(0, 0, 50);
var square = two.makeRectangle(0, 0, 50, 50);
two.scene.children.splice(0, 1, circle);
// Circle should show up on top of square
````

I'm tracking your request as a feature [here](https://github.com/jonobr1/two.js/issues/245). Thanks for posting!
