### ISSUE TITLE
loading of svgs not working with react component

### ISSUE THREAD

**Issue by gerwinbrunner** [jonobr1/two.js#348]
I'm trying to load svgs but they do not show up. 
They are loaded and fetched, 

Here is the minimal sample app and react component to reproduce the error:
https://github.com/gerwinbrunner/twojs-react-sample

The wired thing is that when I past the this code:
```
    two.load("https://raw.githubusercontent.com/jonobr1/two.js/dev/tests/images/interpretation/D.svg", (shape, svg) => {
      // svg is a Two.Group that has all the children 
      console.log('svg loaded!', shape, svg);
      shape.center(); // I center the object's shapes 
      shape.noStroke().fill = "green";
      shape.translation.set(two.width / 2, two.height / 2); // move to the center of the canvas
    }); 
```

Into the [two.js blank page](https://two.js.org/examples/blank.html) console - the svgs are displayed.

Doing the same in the [sample app](https://github.com/gerwinbrunner/twojs-react-sample) does however not work :(

Anybody got an idea what the issue could be?

**Comment by jonobr1** [comment]
Are there any errors? One change from the latest version of Two.js from npm is that the library doesn't automatically add the loaded SVG to the scene. So if there are no errors you'll still need to add

```javascript
two.add(svg);
```
