### ISSUE TITLE
Manipulate text using Two.Text 

### ISSUE THREAD

**Issue by 10vish** [jonobr1/two.js#350]
Can I add, update, delete text and increase/reduce object size using two.js.

**Comment by jonobr1** [comment]
Yes, you can change the text like so:

```javascript
var text = new Two.Text('hello world', 0, 0);
text.value = 'goodnight moon';
text.size = 20;
```

Hope this helps!

**Comment by 10vish** [comment]
Hi, Thanks for responding!

I am trying to achieve,
- On click there will be a text box, where cursor will be blinking, i can write/update text.
- Delete icon in right corner to delete the text.
- Trying to add Text bound expand feature also

Is this possible in canvas

**Comment by jonobr1** [comment]
No problem. Thanks for asking! This is all possible with Two.js / `Two.Text` and built in browser features.

**Comment by 10vish** [comment]
I want to make text field editable, how can I achieve that ??

**Comment by jonobr1** [comment]
You can change the `text.value` on `keyup` events. e.g:

```javascript
two.renderer.domElement.addEventListener('keyup', function(e) {
  var c = String.fromCharCode(e.which);
  if (e.keyCode === 46) { // This is delete
    // Subtract last character of text.value
    text.value = text.value.slice(0, str.length - 1);
  } else {
    text.value += c;
  }
}, false);
```

**Comment by 10vish** [comment]
Hi Jono,

Thank you so much!
 
I have one more question, 
Is it possible break the longer sentence to multiple lines.

**Comment by jonobr1** [comment]
Unfortunately the only way to do that is to make multiple `Two.Text` objects. e.g:

```javascript
var line1 = two.makeText('This is a line of text');
var line2 = two.makeText('and this is the second line');

line1.translation.y = 0;
line2.translation.y = line2.leading;
```

Be sure to handle all of your line height details through `Two.Text.leading` 👍

**Comment by 10vish** [comment]
Thanks Jono!!

**Comment by jonobr1** [comment]
Happy coding!
