### ISSUE TITLE
zui x and y after zoom

### ISSUE THREAD

**Issue by blu-towers** [jonobr1/two.js#352]
How can you get the relative x and y after zooming, i have tried e.pageX / zui.scale but its not returning the correct value.

**Comment by jonobr1** [comment]
Thanks for the question. You're inquiring about a child object of the scene or the scene being zoomed?

**Comment by jonobr1** [comment]
For a `Two.Path` or `Two.Group` you can always call `path.getBoundingClientRect();` to get its screen-space position or `path.getBoundingClientRect(true);` to get its relative positioning.

For the object that is being zoomed you can always pass in the screen-space x, y — in your example `e.pageX` — `zui.clientToSurface(x, y);` which returns a vector coordinate on the surface of the zoomable plane.

Hope this helps!
