### ISSUE TITLE
Positioning two image sprites relative to each other?

### ISSUE THREAD

**Issue by bellarerakshith** [jonobr1/two.js#353]
How can i position two image sprites relative to each other? The first sprite has its position translated to the center of the canvas. Now when i add another sprite it positions itself at the center of the first sprite. How can i make the position relative to the first sprite and not the canvas?

**Comment by jonobr1** [comment]
Unfortunately the only way right now is to use `Two.Group`s like so:

```javascript
var group = two.makeGroup();
var a = new Two.Rectangle(0, 0, 50, 50);
var b = new Two.Circle(0, 0, 50);

group.add(a, b);
group.translation.x = two.width / 2;
group.translation.y = two.height / 2;
b.translation.x = - 10; // Moves relative
```

Hope this helps~!
