### ISSUE TITLE
Cloning an SVG group duplicates children

### ISSUE THREAD

**Issue by jcneshi** [jonobr1/two.js#354]
When I create a group by reading an SVG element (which has 5 children paths) then clone it, the clone has 10 children (each child path is duplicated, easy to tell because the same path ID is present twice).

```
      // Load SVG like in the official example
      var logo;
      $('#assets svg').each(function(i, el) {
        logo = two.interpret(el).center();
        logo.children.forEach(function(child) {
          child.vertices.forEach(function(v) {
            v.ox = v.x;
            v.oy = v.y;
          });
        });
      });
      
      var logoMask = logo.clone();
      console.log('logo.children', logo.children)      // length = 5
      console.log('logoMask.children', logoMask.children)      // length = 10
```

Is this a bug, or is this somehow expected behavior for some reason I don't understand?

**Comment by jonobr1** [comment]
Sounds like a bug. Thanks for reporting, I'll work on this ASAP.

**Comment by jonobr1** [comment]
Actually, upon looking closer. Which version of Two.js are you using? You can verify this by `console.log(Two.Version);`

I'm looking at the latest from the `dev` branch and the children length looks correct.

**Comment by jcneshi** [comment]
Oh, seems it's `v0.7.0`

**Comment by jonobr1** [comment]
Yeah, do you mind either sharing your SVG or giving the latest dev version a try? I will be publishing these updates to `npm` later this month.
