### ISSUE TITLE
How to Clip Text to a Rectangle

### ISSUE THREAD

**Issue by 10vish** [jonobr1/two.js#356]
I am having a rectangle, inside that I am placing text. it is a dynamic text which updates on typing. I don't want the text to go outside the rectangle. So I need to clip it. how can I do that

**Comment by jonobr1** [comment]
There are a couple of ways you could go about doing that depending on what the desired effect is: 
- Masks ([example](https://jsfiddle.net/jonobr1/me7839j4/2/)): click on the canvas to toggle between masking or not.
- BoundingBox Check ([example](https://jsfiddle.net/jonobr1/fp29dtw4/7/)): each frame the program checks to see the width of the current text. If that width is greater than `two.width`, the width of the whole canvas, then the program adds characters to the next text object which is being displayed on a different line.
