### ISSUE TITLE
instance two.js on mocha test

### ISSUE THREAD

**Issue by lucabecchetti** [jonobr1/two.js#359]
Hi guys, I'm trying to test my function using mocha and two.js, to have a dom API inside a test I use: 

jsdom-global/register

And if inside a test a print (document.body) I have an object!

But creating two instance:

```
var two = new Two({
        fullscreen: true,
        autostart: true
      }).appendTo(document.body);
```

I have this error:

```
})((typeof global !== 'undefined' ? global : (this || self || window)).Two);
  ^
TypeError: Cannot read property 'Utils' of undefined
```

What's wrong?

**Comment by jonobr1** [comment]
Are you using the latest npm release of `v0.7.0-beta.3`?
