### ISSUE TITLE
remove stroke of specific line of rectangle

### ISSUE THREAD

**Issue by Muneem** [jonobr1/two.js#360]
is it possible to remove stroke of specific side of rectangle?

**Comment by jonobr1** [comment]
Not _officially_, but there are number of ways you could achieve the effect.

1. You can set dashes `Two.Path.dashes` which takes an array of numbers alternating the length of the dash and the length of the space between the two dashes. If you had a 50 x 50px rectangle I think you should be able to set the dashes to: `[50, 0, 50, 0, 50, 50]` to remove one side.
2. You can also set the `Two.Path.beginning` or `Two.Path.ending` to only draw a certain percentage of the stroke. By setting `Two.Path.beginning = 0.25` you effectively stop drawing one side.

Hope this helps!
