### ISSUE TITLE
Issue with path not properly rendering

### ISSUE THREAD

**Issue by yliapis** [jonobr1/two.js#361]
I am making a graph animation mainly using `Path` objects, and it looks like overlaying paths will sometimes prevent each other from rendering properly. The attached image should explain what is happening in more detail:

<img width="608" alt="line_clipping" src="https://user-images.githubusercontent.com/14884413/55679389-a0756200-58d0-11e9-8cb7-6a66b412a7df.png">

**Comment by jonobr1** [comment]
Paths have a default fill of white. You need to either call `path.noFill();` or set the the fill to `transparent` or `none`.

**Comment by yliapis** [comment]
Perfect, that fixed it, thanks!
