### ISSUE TITLE
I want to add textarea as foriegn object within Twojs group object. Is it possible ?

### ISSUE THREAD

**Issue by 10vish** [jonobr1/two.js#362]
I want a foreign object instead of the twojs text object in the group (that group has delete icon, rectangle, and other elements). Is it possible

**Comment by jonobr1** [comment]
Yeah, I used this technique for the [Node Editor](https://www.justareflektor.com/tech?editor) in Just A Reflektor. You'll need to:

1. Use the SVG Renderer, the default type in Two.js.
2. Then get access to the SVG Element of whatever objects created in Two.js are.
3. Then add your foreign objects to the element.

Like this: https://jsfiddle.net/jonobr1/vct4srLm/

**Comment by 10vish** [comment]
Hi Jono,

Thank you so much. It helped.
