### ISSUE TITLE
How to draw on top of Google Maps?

### ISSUE THREAD

**Issue by markschmid** [jonobr1/two.js#366]
How can we draw on top of Google Maps?

In the following example, two is appended to a yellow div (for visibility).
In that yellow div, the map cannot be moved around. It seems like two.js is preventing events from being passed through.

https://apps.neoos.ch/testing/

We would like to draw on top of Google Maps (using two.js) while being able to interact with both the map and the two.js shapes.

Thanks!

**Comment by jonobr1** [comment]
A simple solution can be to remove pointer events on the Two.js canvas or SVG like so:

````javascript
var two = new Two(...).appendTo(document.body);
two.renderer.domElement.style.pointerEvents = 'none';
````

A more elegant solution would be to force Two.js as an overlay on the entirety of Google Maps and then to run your own event handlers to control both Two.js and the Google Maps interface. I'll try to come up with an example of that soon!

Thanks for posting and hope this helps.

**Comment by markschmid** [comment]
Thanks, in the meantime I've come across the `pointer-events: none` CSS property too. Unfortunately, it does not work in our case, since we need to interact with both the two.js shapes and the underlying Google map.

If you could come up with an example of that, it would be awesome!

**Comment by jonobr1** [comment]
Here's a working example using the Google Maps JavaScript API: https://jsfiddle.net/jonobr1/sj1q47vp/ (note: you'll need an API key to run this)

You could do some really cool animations and data binding with this setup! Would be cool to combine with [ZUI](https://two.js.org/examples/zui.html) extra to have animated overlays.

**Comment by jonobr1** [comment]
This example is modified from Google's Maps API example ([link](https://developers.google.com/maps/documentation/javascript/tutorial)). I'm listening to Google Maps events to update the user interaction. Here are all the events ([link](https://developers.google.com/maps/documentation/javascript/events)).
