### ISSUE TITLE
Do Typescript Types Exist?

### ISSUE THREAD

**Issue by nojvek** [jonobr1/two.js#367]
Awesome repo. While looking at package.json. I don’t see an entry for types that points to the library’s typescript interface. 

This would make it very easy to get started with Two.js since the editor (e.g Vscode) can give excellent code completion and show contextual documentation while using the library.

**Comment by jonobr1** [comment]
Thanks for posting @nojvek. We had this in a previous version that was handwritten by a contributor. But, with the impending auto generated documentation we should be able to add this.

**Comment by musachy** [comment]
Is there a way to generate the TS types currently?

**Comment by jonobr1** [comment]
Not yet. You'll see this issue updated when it is!

**Comment by bluenote10** [comment]
As far as I can see, there are definitions on [definitely typed](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/two.js).

The only problem is that they are missing ZUI type definition, so this part cannot be used from TypeScript at the moment.

**Comment by jonobr1** [comment]
Thanks for that note @bluenote10, is that something we can flag with them?

**Comment by jonobr1** [comment]
Got it. Well, maybe that's a good place for me to start then. Thanks!

**Comment by jonobr1** [comment]
They do now: https://github.com/jonobr1/two.js/blob/dev/build/two.module.d.ts
