### ISSUE TITLE
Two.js Groups add issue

### ISSUE THREAD

**Issue by SharkMan201** [jonobr1/two.js#370]
I have been using Two.js for a relatively large project with a lot of SVG objects, the scene sometimes gets a bit laggy which made me notice an issue that apparently only occur when the scene is laggy.

I have multiple Two.groups that I use as a Z-Index reference, and I have an event that when mouse is down on an SVG object I change the group which its in using Group.add to put it in another group (update the Z-index of it), and when mouse is up I return the SVG object to its original group (return it to the original Z-index). However something weird sometimes happen which is the SVG object disappears from the canvas despite it being on the Two.group and all of the other elements in that group are drawn fine.

Update: Using two.Update after Group.add seems to fix the issue, but I am still not sure if that is the correct behavior so I am leaving this issue open for you guys to decide.

Than you.

**Comment by jonobr1** [comment]
Thanks for sharing your experiences and sorry that this issue is occurring. Any chance you can post a live demo to exemplify the issue? It makes it much easier to debug / reproduce your issue if you share something running on codepen, jsfiddle, or some other HTML document.

**Comment by SharkMan201** [comment]
Here is a fiddle that causes the issue, http://jsfiddle.net/Lmo2fbgz/28/, but it is very dependent on the performance of the machine, there is a variable blocksCount which indicates how many SVGs are drawn I suggest you change it until the issue appears (the issue occurs at 900 but at my team mates machines 900 is too much to handle and the issue occurs at 400), your machine could be able to handle 900 well so you might want to increase it, anyway in order to produce the issue simply left click at the document if some of the SVG blocks disappeared then the issue occured. The issue occurs only with the first click, clicking again would bring back the blocks and the issue doesn't seem to happen again.

**Comment by jonobr1** [comment]
Thanks for posting. I think the refine this issue a bit. The behavior I notice — while may seem like it's tied to the number of objects, performance, or lag — occurs reliably if I comment out the `mousedown` event and click very quickly three times. _What I think is happening is that the flags to remove an element are overriding the flags to append elements._ This could be due to the order of operations getting lost as flags are triggered and the removal flags simply happening after the additions. I'll look into this further. Thanks for sharing!

**Comment by jonobr1** [comment]
The latest dev branch has this resolved enforcing added elements to only exist once.
