### ISSUE TITLE
Is it possible to specify your own pre-existing canvas element when constructing a Two.JS instance?

### ISSUE THREAD

**Issue by wobblyrampack** [jonobr1/two.js#371]
Hi, hope someone can help with this.

I'm experimenting with Two.JS to swap out existing functionality written in pure canvas context. I'm using Typescript so I have the latest two.js package and associated Typescript declarations.
One of the requirements is to use a pre-existing canvas element rather than leaving it to two.js to construct one automatically. 
The only way I could find to do this in two.js would be do the following horrid hack:

`const renderer = new (Two.default as any)({
            domElement: this.ctx.canvas,
            type: Two.default.Types.canvas,
            fullscreen: true,
            autostart: true
        });`

Am I missing something really obvious?

**Comment by jonobr1** [comment]
That's correct. You don't have to add any of the additional parameters. It should look like this:

````
import { Two } from 'two.js';
// Your canvas is defined as `myCanvas`
const two = new Two({
  domElement: myCanvas
});
````

The domElement passing is working correctly, but I've never tested in Typescript, only Node.js environments like Webpack. Did this configuration not work for you?

**Comment by wobblyrampack** [comment]
It only seemed to work for me if I override the typescript declarations as they don't specify domElement as a valid key for the options passed into the constructor. But looking at the docs for two.js I can't see it specified in the options object keys either!

**Comment by jonobr1** [comment]
I've not explicitly declared anything for Typescript, so I'm not sure where it would've gotten any reference to what is valid or not. But, unless you're looking at the comments in the code, the documentation is grossly out of date. My main priority is to complete the new autogenerated docs.

For clarification, is there a file your script is referencing to infer declarations as defined by this tutorial? https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
