### ISSUE TITLE
 Is it possible to load a previous svg created with two

### ISSUE THREAD

**Issue by deathleader** [jonobr1/two.js#372]
Hello,
I would like to create a function to "go back", so I save every svg before the one currently modified.
But I have difficulty associating these svg with the created Two element.
I tried to  do this :
`    var myCanvas = document.getElementById('contenitore_disegno_canvas');
         
            var el = $('#contenitore_disegno_canvas svg')[0];
           
                ctx = new Two({
                    autostart: true,
                    width: (parseInt(canvas_var.def_l) * 0.3) + 100,
                    height: (parseInt(canvas_var.def_h) * 0.3) + 100,
                    domElement: el
               }).appendTo(myCanvas);

            ctx.interpret(el);`
but my ctx variable don't have any children inside.

**Comment by jonobr1** [comment]
Thanks for the question. Yes this should work, but the API changed around — I think — `v0.6.0`. As a result the `interpret` function _returns_ a Two.js group which you can then subsequently add yourself. It doesn't automatically add it. The final line of your code should be modified to:

````javascript
var group = ctx.interpret(el);
ctx.add(group);
// group.clone(); // if you want to make another one
````
