### ISSUE TITLE
TwoJS Error with read only

### ISSUE THREAD

**Issue by BradLattice** [jonobr1/two.js#373]
I'm bad with english, but heres my code 

````typescript
import React, { Component } from 'react'
import PreTwo from 'two.js'

const Two = PreTwo

const INITIAL_STATE = {}

class Canvas extends Component {
  canvasRef
  two
  background
  foreground

  constructor(props) {
    super(props)
    this.state = {
      ...INITIAL_STATE,
    }
    this.canvasRef = React.createRef()
    // this.gameLoop = this.gameLoop.bind(this);
    // this.resize = this.resize.bind(this);
  }

  componentDidMount() {
    this.canvasInit()
  }

  canvasInit() {
    this.two = new Two({
      width: this.canvasRef.current.clientWidth,
      height: this.canvasRef.current.clientHeight,
      type: Two.Types.svg,
    })
    this.two.appendTo(this.canvasRef.current)

    // two has convenience methods to create shapes.
    var circle = this.two.makeCircle(72, 100, 50)
    var rect = this.two.makeRectangle(213, 100, 100, 100)

    // The object returned has many stylable properties:
    circle.fill = this.two.makeRadialGradient(
      0,
      0,
      115,
      new Two.Stop(0, '#ffffff', 1),
      new Two.Stop(1, '#fff000', 1)
    )
    circle.stroke = 'orangered' // Accepts all valid css color
    circle.linewidth = 5

    rect.fill = 'rgb(0, 200, 255)'
    rect.opacity = 0.75
    rect.noStroke()

    // Don't forget to tell two to render everything
    // to the screen
    this.two.update()
    // E6EBF1
  }
  render() {
    return (
      <div
        style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}
      >
        <div
          style={{ width: '100 % ', height: '200vh', cursor: 'pointer' }}
          id="canvas2d"
          ref={this.canvasRef}
        />
      </div>
    )
  }
}

export default Canvas
````

Im getting an error as seen [here](https://i.imgur.com/uUZRPyK.png)

After spending a day I've decided I'm wasting my time. Clearly it's working [here](https://glitch.com/~blossom-yacht) (codepen like site) 

**TO CLARIFY : I'm trying to get gradients working. As soon as i do anything with Two.Stops it seems to break**

Is this an issue with Gatsby / React / Typescript interfering with TwoJS? Any help is GREATLY appreciated

**Comment by jonobr1** [comment]
Sorry you're running into this problem. This is an issue with Two.js SVG Renderer. It's fixed in the `dev` branch, but hasn't been pushed out to NPM yet. Two things you can do to fix this immediately:

1. You can `npm install git+https://git@github.com/jonobr1/two.js.git --save`
OR
2. Use the `CanvasRenderer` via the prop: `type: Two.Types.canvas` when you create a new instance of Two.js

I'm hoping to have a new stable version of Two.js up in the next month. At that point this shouldn't be an issue for you through NPM. Hope this helps!

**Comment by BradLattice** [comment]
Thank you so much!!! I really appreciate your hard work! Loving twoJS so far!

**Comment by jonobr1** [comment]
Glad it's working out! More updates soon 👍
