### ISSUE TITLE
Switch to Import Statements

### ISSUE THREAD

**Issue by jonobr1** [jonobr1/two.js#374]
Instead of relying on a global namespace to access functionality of Two.js move towards using import statements and reconstructing a namespace in the build procedure.

Some previous work has been done on this for other projects like: https://github.com/mrdoob/three.js/blob/dev/utils/modularize.js

**Comment by mikebolt** [comment]
I could rewrite the source files so that they use es6 import/export statements, then create builds with rollup. I did that for tween.js. Does that sound good?

**Comment by jonobr1** [comment]
That would be amazing and hugely appreciated! Is it as simple as just rewriting the beginning and ending of each file? This project is slightly more complicated than Tween.js in that there are multiple files and inter-file dependency.

**Comment by jonobr1** [comment]
One other question, can the rollup process generate Typescript types? There's been a different request for that: https://github.com/jonobr1/two.js/issues/367

Maybe once this is squared away that issue becomes easier to solve?
