### ISSUE TITLE
interpret issue with rotated objects

### ISSUE THREAD

**Issue by blu-towers** [jonobr1/two.js#375]
using this svg and the latest dev branch the rotated ellipse is not at the correct angle

`<svg width="153.2" height="162.36" xmlns="http://www.w3.org/2000/svg">
                     <g transform="translate(50,50)">
                      <title>Layer 1</title>
                      <g stroke="#000000" id="s69">
                       <g id="svg_1" transform="scale(1.2592592239379883) ">
                        <path id="svg_2" stroke-width="0.7" fill="none" d="m-26.5,-26.5l53,0l0,14a48,48 0 0 1 -39,39l-14,0l0,-53z" fill="#fff"/>
                        <ellipse id="svg_3" stroke-width="0.4" ry="14" rx="28" cy="0" cx="0" transform="rotate(-45 0,0) " fill="#fff"/>
                        <circle id="svg_4" stroke-width="0.5" r="1.5" cy="15" cx="-15" fill="#fff"/>
                        <path id="svg_5" stroke-width="0.3" d="m-10.5,-26.5l-16,16" fill="#fff"/>
                        <rect id="svg_6" stroke-width="0.2" height="1" width="2" y="19.5" x="-20" transform="rotate(-45 -20.000000000000014,19.499999999999996) " fill="#fff"/>
                       </g>
                      </g>
                     </g>
                    </svg>`

**Comment by jonobr1** [comment]
Thanks for posting @blu-towers, I just pushed an update to the `dev` branch that has a fix for you. Unfortunately, I'll be holding off on publishing a new version to NPM until I sort out the module imports properly for headless environments (which if you're interested you can follow [here](https://github.com/jonobr1/two.js/issues/374)).

In the meantime you can use the latest version like so:

````terminal
npm install --save git+https://git@github.com/jonobr1/two.js.git
````

**Comment by blu-towers** [comment]
thanks for this will try it out, i also seem to be getting issues with stroke svg objects from adobe i have the following svg and it adds a double stroke i think.

`<svg id="e3cf1dab-8132-4f78-991c-ed1084ec8564" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28.52 28.52">
  <title>example4</title>
  <rect x="0.5" y="0.5" width="27.52" height="27.52" fill="#fff" stroke="#1d1d1b" stroke-miterlimit="10"/>
  <path d="M13.58,18.61a4.26,4.26,0,0,0-3.44-3.43.8.8,0,0,0-1-.47.78.78,0,0,0-.47.47,4.25,4.25,0,0,0-3.4,3.41.8.8,0,0,0-.51,1,.81.81,0,0,0,.51.51,4.25,4.25,0,0,0,3.4,3.41.81.81,0,0,0,.75.52.83.83,0,0,0,.75-.52,4.24,4.24,0,0,0,3.44-3.43.8.8,0,0,0,.5-.74A.83.83,0,0,0,13.58,18.61ZM10.2,21.87v-.35a.81.81,0,0,0-1.61-.18.54.54,0,0,0,0,.18v.34a2.66,2.66,0,0,1-1.68-1.7h.32a.81.81,0,0,0,.18-1.61.54.54,0,0,0-.18,0H6.91a2.62,2.62,0,0,1,1.68-1.69v.34a.81.81,0,0,0,1.61.18.54.54,0,0,0,0-.18v-.35a2.64,2.64,0,0,1,1.71,1.7h-.36a.81.81,0,0,0-.18,1.61.54.54,0,0,0,.18,0h.36A2.65,2.65,0,0,1,10.2,21.87Z" transform="translate(-0.71 0.52)" stroke="#fff" stroke-miterlimit="10" stroke-width="0.75"/>
  <path d="M24.8,18.61a4.26,4.26,0,0,0-3.44-3.43.8.8,0,0,0-.75-.51.81.81,0,0,0-.75.52,4.26,4.26,0,0,0-3.41,3.41.81.81,0,0,0,0,1.52,4.26,4.26,0,0,0,3.41,3.41.81.81,0,0,0,.75.52.83.83,0,0,0,.75-.52A4.24,4.24,0,0,0,24.8,20.1a.8.8,0,0,0,.5-.74A.82.82,0,0,0,24.8,18.61Zm-3.39,3.26v-.35a.81.81,0,0,0-1.61-.18.54.54,0,0,0,0,.18v.34a2.66,2.66,0,0,1-1.68-1.7h.33a.81.81,0,0,0,.18-1.61.54.54,0,0,0-.18,0h-.33a2.67,2.67,0,0,1,1.68-1.69v.34a.81.81,0,0,0,1.61.18.54.54,0,0,0,0-.18v-.35a2.61,2.61,0,0,1,1.72,1.7h-.36a.81.81,0,0,0-.18,1.61.54.54,0,0,0,.18,0h.36A2.65,2.65,0,0,1,21.41,21.87Z" transform="translate(-0.71 0.52)" stroke="#fff" stroke-miterlimit="10" stroke-width="0.75"/>
  <path d="M13.58,7.4A4.22,4.22,0,0,0,10.14,4a.83.83,0,0,0-.75-.52A.81.81,0,0,0,8.64,4a4.25,4.25,0,0,0-3.4,3.41.8.8,0,0,0-.51,1,.81.81,0,0,0,.51.51,4.25,4.25,0,0,0,3.4,3.41.8.8,0,0,0,1,.47.78.78,0,0,0,.47-.47,4.26,4.26,0,0,0,3.44-3.43.82.82,0,0,0,0-1.51ZM10.2,10.65V10.3a.81.81,0,0,0-1.61-.18.54.54,0,0,0,0,.18v.34A2.61,2.61,0,0,1,6.91,9h.32a.81.81,0,0,0,.18-1.61h-.5a2.66,2.66,0,0,1,1.68-1.7V6a.81.81,0,0,0,1.61.18.54.54,0,0,0,0-.18V5.63a2.65,2.65,0,0,1,1.71,1.71h-.36A.81.81,0,0,0,11.37,9a.54.54,0,0,0,.18,0h.36A2.64,2.64,0,0,1,10.2,10.65Z" transform="translate(-0.71 0.52)" stroke="#fff" stroke-miterlimit="10" stroke-width="0.75"/>
  <path d="M24.8,7.4A4.22,4.22,0,0,0,21.36,4a.83.83,0,0,0-.75-.52.81.81,0,0,0-.75.52,4.26,4.26,0,0,0-3.41,3.41.81.81,0,0,0,0,1.52,4.26,4.26,0,0,0,3.41,3.41.8.8,0,0,0,1,.47.78.78,0,0,0,.47-.47A4.25,4.25,0,0,0,24.8,8.89a.82.82,0,0,0,.5-.75A.8.8,0,0,0,24.8,7.4Zm-3.39,3.25V10.3a.81.81,0,0,0-1.61-.18.54.54,0,0,0,0,.18v.34A2.68,2.68,0,0,1,18.12,9h.33a.81.81,0,0,0,.18-1.61h-.51a2.66,2.66,0,0,1,1.68-1.7V6a.81.81,0,0,0,1.61.18.54.54,0,0,0,0-.18V5.63a2.65,2.65,0,0,1,1.72,1.71h-.36A.81.81,0,0,0,22.59,9a.54.54,0,0,0,.18,0h.36A2.61,2.61,0,0,1,21.41,10.65Z" transform="translate(-0.71 0.52)" stroke="#fff" stroke-miterlimit="10" stroke-width="0.75"/>
</svg>
`
