### ISSUE TITLE
.opacity property affects both fill and stroke

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#384]
As far as I can tell, there's no way to modify stroke opacity independently of fill opacity, although the same isn't true of stroke and fill color.

Is there a way to achieve this without overlaying a second Two.Path?

**Comment by jonobr1** [comment]
This is due to the inconsistency between SVG and Canvas rendering. You can overwrite this yourself on the SVG renderer by accessing the SVG directly:

````javascript
two.update();
var elem = path._renderer.elem;
````

**Comment by yoeran** [comment]
I just use rgba/hsla/hexa values for fill and stroke colors to achieve this.

**Comment by eulertour** [comment]
@yoeran's solution is clean enough for my purposes, so this can be closed unless you plan to add a numerical property at some point.

**Comment by jonobr1** [comment]
Sounds good.
