### ISSUE TITLE
Is it possible to export canvas as svg ?

### ISSUE THREAD

**Issue by R2ALPHA** [jonobr1/two.js#390]
Hi, hope someone can help with this.
Recently I stuck in a situation where I need to export canvas as svg. 
Is there any way through which I can export canvas as svg?
I have gone through the documentation but didn't found any ways to do so
or I am missing something ?

**Comment by jonobr1** [comment]
If you can create your canvas in Two.js then it should be as simple as instantiating Two.js as an SVG instead of a canvas:
````javascript
var two = new Two({
  type: Two.Types.svg
});
````
If you're interested in exporting a `<canvas />` element to SVG that is made in Two.js that is currently not supported.
