### ISSUE TITLE
Two.js Typescript Error

### ISSUE THREAD

**Issue by demirtas91** [jonobr1/two.js#391]
Hello, 
I add two.js to my angular projects by using "npm install --save @types/two.js"  and import in project as `import * as Two from 'two.js';` and add button to call addShape():

```javascript
function addShape() {
    // Make an instance of two and place it on the page.
    let elem: HTMLElement = document.getElementById('shape-draw');
    let params = { width: 285, height: 200 };
    let two :Two= new Two(params).appendTo(elem);
   two.update;
};
```
but in the console I see the this error 

```
AboutPageComponent.html:47 ERROR TypeError: two_js__WEBPACK_IMPORTED_MODULE_2__ is not a constructor
    at AboutPageComponent.addShape (about-page.component.ts:38)
    at Object.eval [as handleEvent] (AboutPageComponent.html:47)
    at handleEvent (core.js:38098)
    at callWithDebugContext (core.js:39716)
    at Object.debugHandleEvent [as handleEvent] (core.js:39352)
    at dispatchEvent (core.js:25818)
    at core.js:37030
    at HTMLButtonElement.<anonymous> (platform-browser.js:1789)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
View_AboutPageComponent_0 @ AboutPageComponent.html:47
proxyClass @ compiler.js:19436
logError @ core.js:39651
handleError @ core.js:9162
dispatchEvent @ core.js:25822
(anonymous) @ core.js:37030
(anonymous) @ platform-browser.js:1789
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:34182
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
AboutPageComponent.html:47 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 51, nodeDef: {…}, elDef: {…}, elView: {…}}
```

what is the problem in this code?

**Comment by jonobr1** [comment]
Sorry for the delay. I believe the write import is:

`import Two from 'two.js';`

**Comment by demirtas91** [comment]
Thank you for reply and sorry for my delay. 
I changed this part but another problem was occured. 
New Error--- Module '"C:/Users/Kerem/Desktop/ui/client/node_modules/@types/two.js/index"' has no default export. 
I write this code in Typescript and I don't know how to import javascript class to my project.

**Comment by Sorceror** [comment]
@demirtas91 you're most probably using too old version of types for the two.js library. 
I'm using [this version of two.js from npm](https://www.npmjs.com/package/twojs-ts) and it works in TS code just fine (types are already included in the package, no need to install them separately). 
Just use `import * as Two from 'twojs-ts';` for import are you're ready to go,

**Comment by jonobr1** [comment]
Adding onto what @Sorceror says, if you use `two.js` as your module, make sure you're using the latest beta version or the development branch from the github repository.

**Comment by matndev** [comment]
Hello, I up this issue because @types/two.js last version package should be outdated. Can you provide some Typescript declaration files in the future for Angular2 users ?

**Comment by jonobr1** [comment]
Thanks @matndev, gonna give this a try: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by jonobr1** [comment]
Using the above described method, this commit now has types added to the repo and referenced correctly (I believe) in the package.json: https://github.com/jonobr1/two.js/blob/dev/build/two.module.d.ts
