### ISSUE TITLE
Bringing an object to the top

### ISSUE THREAD

**Issue by defund** [jonobr1/two.js#393]
Is there a way to elevate an object over the rest? Right now, I want to switch between two shapes overlapping each other.

**Comment by jonobr1** [comment]
Yes, for any group you can just add an object to bring it to the front. e.g:

```javascript
var a = two.makeCircle(0, 0, 50);
var b = two.makeCircle(10, 10, 50);
two.scene.add(a); // a will be above b
```

**Comment by jonobr1** [comment]
You can also run typical JavaScript Array operations on the children property of a `Two.Group`. Like so:

````javascript
two.scene.splice(1, 1);
````

**Comment by defund** [comment]
Ah, I was using .add but I wasn't sure if that was intended. Thanks!

**Comment by meetzaveri** [comment]
@jonobr1 What if I wanted to send object to the deep back, like exact opposite of this? Is there any method intended for it?

**Comment by jonobr1** [comment]
The `splice` method would allow you to do that:

```javascript
group.children.splice(0, 0, path);
```

The first parameter is the index to start the operation. The second parameter is how many elements from the starting index you'd like to remove. The third and subsequent parameters is/are any new elements you'd like insert at the starting index.

**Comment by meetzaveri** [comment]
Got it!
