### ISSUE TITLE
How to draw in canvas or webgl?

### ISSUE THREAD

**Issue by matmis** [jonobr1/two.js#395]
For example when I want to render in Canvas I set the type to canvas like this:
```javascript
var params = { width: 285, height: 200, type: Two.Types.canvas };
```

and the html tagname to canvas like this:
```html
<canvas id="draw-shapes"></canvas>
```

But then there is nothing in the output. What am I doing wrong?

https://codesandbox.io/embed/how-to-change-twojs-render-type-rg5xu

**Comment by jonobr1** [comment]
The issue is that Two.js is creating a canvas and you're appending it to another canvas `#draw-shapes`. You can fix the problem by making the canvas with id `draw-shapes` a `<div />` like so:

````html
<div id="draw-shapes"></div>
````

Or you pass in `draw-shapes` as the canvas to Two.js like so:

````javascript
var params = { width: 285, height: 200, domElement: elem };
````

**Comment by matmis** [comment]
Thanks!
