### ISSUE TITLE
Bugs in twojs-ts

### ISSUE THREAD

**Issue by P0oOOOo0YA** [jonobr1/two.js#396]
I'm using  [twojs-ts](https://www.npmjs.com/package/twojs-ts) NPM package which i guess is published by this repository maintainers also. If it's not then what is the proper way to use this lib with **typescript** cause i didn't find any **type definition file** for this lib.

## `makePolygon` definition is wrong. 

it should be `makePolygon(x: number, y: number, radius: number, sides: number): Two.Polygon;`

## `makePath` throws error (Using SVG Renderer):

```ts
canvas.makePath([0,0, 1,1, 2,2], true);

```
react-dom/cjs/react-dom.development.js:487 Uncaught TypeError: a[d].bind is not a function
    at c.Path.BindVertices (/node_modules/twojs-ts/two.js:159)
    at c.Path.set [as vertices] (/twojs-ts/two.js:164)
    at new c.Path (twojs-ts/two.js:158)
    at l.Two.makePath (/twojs-ts/two.js:57)
```

**Comment by jonobr1** [comment]
Sorry for the confusion but two-ts is *not* maintained by me, the maintainer of this project. You should be able to use `npm install two.js` with typescript. Unfortunately, there aren't any definitions created for Two.js yet though.
