### ISSUE TITLE
Can't remove shapes

### ISSUE THREAD

**Issue by clawdebob** [jonobr1/two.js#398]
Hi! I am new to this svg library, and it seems i don't understand how `remove` method works. For example i want to remove some elements with specific className.

Here is a code of my class which handles rendering:
```javascript
import Two from 'two.js';

class Renderer {
    constructor() {
        const board = document.getElementById('board');
        const params = {width: 2000, height: 2000};
        this.svg = new Two(params).appendTo(board);
        this.render = this.render.bind(this);
    }

    renderElement(element, x, y) {
        const props = element.props;
        const rect = this.svg.makeRectangle(x, y, element.width, element.height);
        rect.fill = props.fill;
        rect.opacity = props.opacity || 1;
        rect.noStroke();
        if (props.id) {
            rect.node_id = props.id;
        }
        if (props.className) {
            rect.className = props.className;
        }
        return this.render();
    }

    removeElement(element) {
        for (let c = 0; c < element.length; c++) {
            const shape = this.svg.interpret(element[c]);
            this.svg.remove(shape);
        }
        return this.render();
    }

    render() {
        this.svg.update();
    }
}

export default Renderer;
```

And here i want to remove all shapes with className "ghost"
```javascript
const activeGhosts = document.getElementsByClassName('ghost');
ghost.props.className = 'ghost';
if (activeGhosts.length > 0) {
      this.props.renderer.removeElement(activeGhosts);
}
```

But this code doesn't work and i don't understand why.

**Comment by jonobr1** [comment]
Thanks for posting. A couple of things:

First, interpret creates new elements into the Two.js canvas. For instance it's used when you load an SVG from a file like, `two.load('path-to-file/symbol.svg');`. If you'd like to select elements by class name you can use a function provided by Two.js like so:
````javascript
var elements = two.scene.getByClassName(className);
````
Then when you iterate through those elements you can simply call remove on the element without any reference to anything like so:
````javascript
for (var i = 0; i < elements.length; i++) {
  var elem = elements[i];
  elem.remove();
}
````
Those two changes should alleviate your problem. If not feel free to follow up.

**Comment by clawdebob** [comment]
@jonobr1 Thanks for such a great answer. Sorry that it took me so long to check out this solution, but it doesn't seem to work either in my case. Variable `elements` just displays empty list in my case, although there are plenty of shapes with specified `className` and simple `getElementsByClassName()` perfectly finds all of them. I suspect i am doing smth wrong with the way i create shapes.

Maybe in this peice of code, i am trying to apply `className` property in a wrong way:
```javascript
    renderElement(element, x, y) {
        const props = element.props;
        const rect = this.svg.makeRectangle(x, y, element.width, element.height);
        rect.fill = props.fill;
        rect.opacity = props.opacity || 1;
        rect.noStroke();
        if (props.id) {
            rect.node_id = props.id;
        }
        if (props.className) {
            rect.className = props.className;
        }
        return this.render();
    }
```

**Comment by jonobr1** [comment]
No problem. Your implementation looks right. I think the issue lies on Two.js side. For the meantime if you add the class in this way then the search will yield real results:

````javascript
rect.classList.push(props.className);  // Instead of what you put
````

This should work, but I'll make sure to fix the `className` issue tomorrow. Once that's implemented however you'll need to use the dev branch instead of npm, or other way you're adding the library.

**Comment by clawdebob** [comment]
@jonobr1 Thanks! This method works perfectly!

**Comment by jonobr1** [comment]
Okay the latest dev branch has `className` connected to `classList` so you'd be able to use className instead of classList if you'd like.
