### ISSUE TITLE
Two.Matrix.copy is not a function

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#404]
001d15d51776f1f441ac3ed238e4d574fc233325 added calls to Two.Matrix.copy, which isn't a function.

**Comment by jonobr1** [comment]
Thanks! I missed a commit when fixing this issue: https://github.com/jonobr1/two.js/issues/402

**Comment by jonobr1** [comment]
This is added to the latest dev branch via this commit: https://github.com/jonobr1/two.js/commit/7a315de66304d2d3032fb53861bf2377e9d81031
