### ISSUE TITLE
TODO in Group.clone is ambiguous

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#406]
Can you elaborate on the implications of [this TODO](https://github.com/jonobr1/two.js/blob/0a1624eb417bb047849d7eb2061fc4816919f424/src/group.js#L507-L511)? If it can cause subtle bugs it may be worth adding a `console.warn` if the problem is triggered.

**Comment by jonobr1** [comment]
I _think_ this is for the `SVGRenderer` there won't actually be any svg elements until it's bound to the renderer and drawn.
