### ISSUE TITLE
Add build files to .gitignore

### ISSUE THREAD

**Issue by adroitwhiz** [jonobr1/two.js#411]
Currently, handling the `build` folder in PRs is quite awkward.

It would probably be easier if the `build` folder wasn't stored in the dev branch at all, and builds were only done in a separate "releases" branch.

There are also several CI services that could automate building.

**Comment by jonobr1** [comment]
I agree it's better to PR without building, CI or not.

**Comment by jonobr1** [comment]
One issue with this solution that will prevent me from implementing this at the moment is that until I can get into releasing Two.js at regular intervals, it's recommended (and used in many cases) to `npm install` from the dev branch directly.

I will create a new issue to have better structure contributions. If you have any references or feedback on that side of things please feel free to update this issue: https://github.com/jonobr1/two.js/issues/412
