### ISSUE TITLE
Two.js is not competible with Node, or Browserify exactly

### ISSUE THREAD

**Issue by tiye** [jonobr1/two.js#43]
I'm a fan of Node.js and I want to package twojs in my code with Browserify.
I tried to place the file `build/two.js` with a new generated `package.json`, then require it in a script.
Well, seems it doesn't work.. the `_` object behaves strangely..

I found such code like this:
https://github.com/jonobr1/two.js/blob/master/src/two.js#L1304-L1310

``` js
  //exports to multiple environments
  if (typeof define === 'function' && define.amd)
  //AMD
  define(function(){ return Two; });
  else if (typeof module != "undefined" && module.exports)
  //Node
  module.exports = Two;
```

It says in the comments that CommonJS style is supported, I guess.
But it's broken.

**Comment by cgfarmer4** [comment]
For anyone reading this now, the twojs-browserify package is out of date. You can just use browserify-shim which makes staying up to date easier than relying on a 3rd party.

`npm install --save-dev browserify-shim`

Package.json

```
  "browser": {
    "two": "./app/vendor/two.js" 
  },
  "browserify": {
    "transform": "browserify-shim"
  },
  "browserify-shim": {
    "two": "Two" 
  },
```

This allows you to then do the following in your browserify dev files.

`const Two = require('two');`

**Comment by jonobr1** [comment]
Thanks for the update @cgfarmer4. Also, at the time of this writing the latest on the `dev` branch is dependency free so it should play well with AMD packages / modules.

**Comment by oparisy** [comment]
Thanks to your explanations @cgfarmer4, I have been able to set up an example of using two.js with browserify. Should it help someone reading this thread, it is available at [two-js-browserify-shim](https://github.com/oparisy/two-js-browserify-shim).
