### ISSUE TITLE
Two.Path.clone() makes a shallow copy of .vertices

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#430]
Exemplified here:
```html
<!doctype html>
<html>
  <head>
    <script src="./two.js/build/two.js"></script>
  </head>
  <body>
    <script>
      let p = new Two.Path([new Two.Vector(0, 0)]);
      let q = p.clone();
      q.vertices[0].x = 500;
      console.log(p.vertices[0].x); // 500
    </script>
  </body>
</html>
```

**Comment by jonobr1** [comment]
This commit fixes the issue: https://github.com/jonobr1/two.js/commit/a830913e445494bb5a6ea0183230f259b2185e8e

Would be good to think about ways to keep a shallow clone of vertices. It would greatly reduce the memory footprint when cloning many of the same paths.
