### ISSUE TITLE
twojs-ts is out of date

### ISSUE THREAD

**Issue by koderush** [jonobr1/two.js#433]
The twojs-ts(https://www.npmjs.com/package/twojs-ts) is fairly out of date, and there are quite a few methods in Two.js don't have type definition in twojs-ts.

Is it possible to update twojs-ts to catch up two.js?

**Comment by jonobr1** [comment]
Thanks for your post @koderush. Unfortunately, that package is not managed by me or the Two.js repository... I am, however, currently working on ([via this branch](https://github.com/jonobr1/two.js/tree/jsdocs)) automated documentation for Two.js which will include up-to-date typescript definitions.

**Comment by koderush** [comment]
Thanks for the response. I'm very much looking forward to the auto generated type definitions, like what Three.js is doing.
