### ISSUE TITLE
How to resize group to specific width and height?

### ISSUE THREAD

**Issue by schirrmie** [jonobr1/two.js#434]
Hi,
i load an svg from external file and interpret them to two.js object

html

```
<div id="svg-assets" class="d-none">
  <object type="image/svg+xml" data="./assets/svg.svg" id="svg"></object>
</div>
```

javascript

```
    var _svg = $('#svg')[0];
    var svg = this.two.interpret( _svg.contentDocument.getElementsByTagName('svg')[0] );
```

How can I set width and height for that svg? I only found to scale that svg but I need width and height.

Regards

**Comment by jonobr1** [comment]
Thanks for posting your question. One way to set this is with scale and `svg.getBoundingClientRect()`. This returns an object with a `width` and `height` parameter. You can then use that information to inform how you'd like to scale the svg. Here's an example not using an svg, but a group. An svg should work in the same way: https://jsfiddle.net/jonobr1/ob01mzqf/

**Comment by schirrmie** [comment]
Thanks for your quick answer. That looks good I will try that.
