### ISSUE TITLE
SVG mask support

### ISSUE THREAD

**Issue by dev0nian** [jonobr1/two.js#436]
Does twojs have support for [SVG mask element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask)?

I noticed that you can set a path as a mask to a group, but that creates a `<clipPath>` element, and that is not what I need.

Thanks in advance for your help.

**Comment by jonobr1** [comment]
Unfortunately not. While it's an awesome feature of SVG, there's not an obvious cross-render way to achieve the same effect. That being said, you can inject your own custom SVG elements into a Two.js scene if you like. For instance, pseudo code would consist of this logic:

````javascript
var utils = Two.SvgRenderer.Utils;
var elem = utils.createElement('mask');
utils.setAttributes(elem, {
  id: 'my-mask'
});
two.scene._renderer.elem.appendChild(elem);
var rect = two.makeRectangle(two.width / 2, two.height / 2, 50, 50);
rect.fill = '#my-mask'
````
