### ISSUE TITLE
If I remove group do I need to remove nested objects?

### ISSUE THREAD

**Issue by caracal7** [jonobr1/two.js#437]
If I remove group from scene and want to release memory do I need to remove nested objects and groups?

My scene is 
```
   __group
       __bodyGroup
          __body
          __bodyFront
          __circle
       __turretGroup
          __turret
```

Is it enough?
```
    this._render.two.remove(this.__group);
```
or I need
```
    this._render.two.remove(
        this.__body,
        this.__bodyFront,
        this.__circle,
        this.__turret,
        this.__bodyGroup,
        this.__turretGroup,
        this.__group
    );
```

**Comment by jonobr1** [comment]
I'll have to revisit this with an example for further detail, but if you're looking to get rid of all the children _forever_, as in you won't be using them in another scene in Two.js you can call `Two.Utils.release(group);` after removing it from the scene. This should destroy all events and other items that would keep those objects from being garbaged collected.
