### ISSUE TITLE
How to make a responsive path?

### ISSUE THREAD

**Issue by karolpad** [jonobr1/two.js#438]
Hello! First off, thank you for making this amazing library!
I'd like to start off by saying I'm relatively new when it comes to graphics programming so I apologize if this is a silly question. I've tried searching existing issues for something similar but the things I did find I don't think could help me.

I am setting up my instance of Two like so:
`var two = new Two({ width: '100%', height: '100%' }).appendTo(this.stage.current);`

And then I am making a path with 5 vertices like so:
```
 var anchors = [
    new Two.Anchor(375, 250, null, null, null, null, Two.Commands.line),
    new Two.Anchor(730, 250, null, null, null, null, Two.Commands.line),
    new Two.Anchor(730, 800, null, null, null, null, Two.Commands.line),
    new Two.Anchor(375, 800, null, null, null, null, Two.Commands.line),
    new Two.Anchor(375, 250, null, null, null, null, Two.Commands.line),
];
let fooPath = new Two.Path(anchors);
two.add(fooPath);
```

My path renders correctly, but of course the x,y coordinates provided for the vertices are absolute, so when my parent element resizes in anyway the path does not update position or size. I was wondering how to make the path update its position and size relative to the width and height of the parent element? In case it helps, I am using Two.js with React. Thanks!

**Comment by jonobr1** [comment]
Thanks for the question. This definitely is confusing if you're new to graphics programming. Unfortunately you can't use percentage strings to evaluate a responsive design. What you'll have to do is:

````javascript

var stage = this.stage.current;
var two = new Two({
  width: this.stage.outerWidth // or however you'd calculate your elements width
  height: this.stage.outerHeight
}).appendTo(stage);

var path = two.makePath(375, 250, 739, 250, 730, 800, 375, 800, 375, 250);
// you can also make a rectangle like so: var rect = two.makeRectangle(centerPositionX, centerPositionY, widthOfRectangle, heightOfRectangle);

// Initially draw the path to the page
two.update();

// This is called every time the window is resized
two.bind('resize', function() {
  // Center the path on the stage
  path.position.x = two.width / 2;
  path.position.y = two.height / 2;
  // Don't forget to draw your changes
  two.update();
});

````

If you don't want to do fullscreen you'll have to do this:

````javascript

var stage = this.stage.current;
var two = new Two({
  fullscreen: true, // This makes the canvas / svg responsive to the entire page
}).appendTo(stage);

var path = two.makePath(375, 250, 739, 250, 730, 800, 375, 800, 375, 250);
// you can also make a rectangle like so: var rect = two.makeRectangle(centerPositionX, centerPositionY, widthOfRectangle, heightOfRectangle);

// Initially draw the path to the page
two.update();

// This is called every time the window is resized
window.addEventListener('resize', function() {
  var box = stage.getBoundingClientRect();
  two.renderer.setSize(box.width, box.height);
  two.width = box.width;
  two.height = box.height;
  // Center the path on the stage
  path.position.x = two.width / 2;
  path.position.y = two.height / 2;
  // Don't forget to draw your changes
  two.update();
}, false);

````

Hopefully this helps get you on your feet!

**Comment by karolpad** [comment]
Thank you for the quick response! My parent element is not fullscreen so looking at your second example I'm a bit confused why we pass `fullscreen: true` as a param in the constructor. The element that I have set as `stage` is nested inside a Bootstrap column so I figured setting the width/height params in the `Two` constructor to the computed width/height of the column would be the way to go (my `stage` element has 100% width and 100% height, filling the column)

Secondly, when I try setting the width and height in the constructor directly, the function I have bound to the `resize` event is not getting called. I was using a simple `console.log()` to test, but nothing was printing to the console. Here's how I did it:
```js
two.bind('resize', function() {
  console.log('resized')
});
```
Again, thank you for the help!

**Comment by jonobr1** [comment]
Sorry for the confusion. Here's a working example: https://jsfiddle.net/jonobr1/wd0p72n4/

You need to manage the size of the Two.js scene yourself and update any elements within that scene accordingly. This would need to be added at the point where your code changes or listens to the change of the size of the parent element.
