### ISSUE TITLE
v0.7.0 build stable and publish to NPM

### ISSUE THREAD

**Issue by adroitwhiz** [jonobr1/two.js#439]
What still needs to be done before 0.7.0 can be released? I'd be happy to help out with the release.

**Comment by jonobr1** [comment]
Nice to hear from you @adroitwhiz. It's a good question. I have a milestone here for tracking it: https://github.com/jonobr1/two.js/milestone/2

Buuuut, it's been so long and it's such a big jump from the current version on NPM, we should increment it and push the milestones all back a version. Would you wanna help with those duties?

**Comment by adroitwhiz** [comment]
Sure! I don't have the necessary permissions to change the issue milestones, though--you'll probably need to do that yourself.

I've mostly been waiting for the ES6 modules PR to be merged before looking into making any more changes, because I don't want to have to backport all of them to that PR's branch. Hopefully with 0.7.0 out of the way, that PR can be merged?

I can also look into porting over all the JSDoc changes into the ES6 modules branch.

A while ago I also updated all the examples to work with the latest Two.js version. That work can be found in [this branch](https://github.com/adroitwhiz/two.js/tree/update-website)--I've held off on a PR until an actual 0.7.0 release can be vendored into the `third-party` folder.

**Comment by jonobr1** [comment]
Sweet, yeah that all makes sense and is exciting to hear! I'd be happy to update the milestones and focus on merging the ES6 module PR as soon as I tag and push updates to NPM. We'll make this ticket a new published version.

**Comment by jonobr1** [comment]
Okay, this is complete:

1. Latest tag has been made ([link](https://github.com/jonobr1/two.js/releases/tag/v0.7.0))
2. Latest package has been made ([link](https://github.com/jonobr1/two.js/packages/19214))
3. Master has been updated ([link](https://github.com/jonobr1/two.js/tree/master))
4. npmjs.org has been updated ([link](https://www.npmjs.com/package/two.js))
