### ISSUE TITLE
Is it possible to bring a selected item on top of all other object using two.js

### ISSUE THREAD

**Issue by 10vish** [jonobr1/two.js#447]
I have an SVG board, where image, circle, and other things are rendered. 
Ex: I will select a circle first, then square. now the circle is behind the square.
If I click on the circle I want circle above the square.

**Comment by 10vish** [comment]
Hey thanks, I got the solution.

**Comment by jonobr1** [comment]
Glad to hear. If you don't mind posting your solution then other developers using Two.js may find your process helpful. Thanks!
