### ISSUE TITLE
Framerate varies widely between computers

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#448]
I wrote [this animation](https://jsfiddle.net/eulertour/ucp43L8j/107/), which I intended to have a one second runtime. The animation consistently finishes in about a second on my laptop but my desktop takes almost twice as long on the same code, despite running on superior hardware.

* Is this the correct way to write an animation that I intend to have a one second runtime on any computer, or is there a better way?
* Do you know what might cause the framerate to vary so widely between computers, or how I could fix/debug the issue?

I attached a profile I recorded in Chrome from my desktop [here](https://github.com/jonobr1/two.js/files/4143920/fadeout_desktop_prof.log). If you view it in chrome's devtools, you'll see that during most of the animation the javascript interpreter doesn't seem to be doing anything at all.

Desktop specs:
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce RTX 2060 SUPER
Memory: 16Gb

Laptop specs:
CPU: Intel i5-8265U (8) @ 3.900GHz
GPU: Intel UHD Graphics 620
Memory: 8Gb

**Comment by jonobr1** [comment]
It's weird that your desktop would be slower than your laptop based on those specs... For more precise time based animations I recommend using the second argument `timeDelta`, which has a small caveat that on the first frame it doesn't exist. I've forked your example to show:

https://jsfiddle.net/jonobr1/o1nc0shy/

**Comment by eulertour** [comment]
After debugging some more it looks like this is a bug caused by some interaction between the nvidia drivers for linux and chrome. I found that the animation lasts for one second if I use firefox on my desktop (but not if I use chrome on my desktop) and I verified that it lasts for one second if I use firefox or chrome on my laptop (which doesn't use nvidia drivers).

I also found that if I play your version of the animation on my desktop with chrome, the animation _does_ run for one second but the circle doesn't disappear (zooming in a bunch it looks like there are two circles: one which is static and a second which is positioned exactly on top of the first and does the fade out). If I play your version of the animation on my desktop with firefox it runs for a second and the circle disappears. To summarize:

desktop (w/ nvidia drivers):

||firefox|chrome|
|-|-|-|
|my animation|✔️|runs slowly|
|your animation|✔️|renders incorrectly|

laptop:

||firefox|chrome|
|-|-|-|
|my animation|✔️|✔️|
|your animation|✔️|✔️|

In any case, this isn't a bug in two.js.

**Comment by jonobr1** [comment]
Oh wow, I'm so sorry to hear. I'd recommend posting on Chrome bugs. If you do, please link to it in this thread. I'd be happy to follow it. The more follows it gets then the more attention it puts on the Chromium team.

**Comment by eulertour** [comment]
Looking at the script you wrote again, I found that the reason the circle didn't completely fade away is because it setting the opacity based on the framerate rather than the runtime. This test fixes it, although it still runs at a low framerate:
https://jsfiddle.net/eulertour/ucp43L8j/110/

Also, I submitted a bug to chromium [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1048027).
