### ISSUE TITLE
Unable to draw lines from the right-center of a div to left-center of another

### ISSUE THREAD

**Issue by armsp** [jonobr1/two.js#451]
This is more of a question than an issue, but given the fact that you might have come across it before, I am hoping for an answer. Asked this on [SO](https://stackoverflow.com/questions/60487499/lines-connecting-the-center-of-two-divs-using-grid-overlay-and-getboundingclien) too, nothing so far.

I am able to draw line and do basic things using this wonderful library. However using [`getBoundingClientRect`](https://javascript.info/coordinates) to get the vertical center of the `div` and connect two `div`s together is proving more difficult than I thought. The base is a css grid and I make a grid overlay which I use for drawing lines b/w `div`s. 
I have been at it for 3 days now and just nothing seems to be working at all.

Following is a slightly modified version of the SO code -
```html
<style>
    * {
        border: 1px solid black;
    }
.container {
    border: 1px solid red;
    display: inline-grid;
    grid-template-columns: 1fr 1fr;
    grid-template-rows: 1fr 1fr;
    grid-gap: 5em 5em;
    justify-content: center;
    align-content: center;
    position: relative;
    z-index:2;
}
.overlay {
    /* border: 2px dotted green; */
    position: absolute;
    height: 100%;
    width: 100%;
    z-index:1;
    grid-column: 1 / 3;
    grid-row: 1 / 3;
    /* box-sizing: content-box; */
    /* box-sizing: border-box; */
}
.item {
    border: 1px solid blue;
    justify-self: center;
    align-self: center;
    /* padding: 5%; */
    /* margin: auto; */
    /* box-sizing: content-box; */
    /* box-sizing: border-box; */
    /* display: block; */
}
</style>
<body>
    <div class="container">
        <div id="a" class="item">A</div>
        <div id="b" class="item">B</div>
        <div id="c" class="item">C</div>
        <div id="d" class="item">D</div>
        <div id="draw" class="overlay"></div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/two.js/0.6.0/two.min.js"></script>
    <script>
        var elem = document.getElementById('draw');
        var params = { width: "100%", height: "100%" };
        var two = new Two(params).appendTo(elem);

        var element = document.getElementById('a');
        var position = element.getBoundingClientRect();
        var x = position.left;
        var y = position.top;
        var Xa = x + position.width;
        var Ya = y + position.height / 2;

        var element = document.getElementById('b');
        var position = element.getBoundingClientRect();
        var x = position.left;
        var y = position.top;
        var Xb = x;
        var Yb = y + position.height / 2;

        var line = two.makeLine(Xa, Ya, Xb, Yb);
        line.fill = '#FF8000';
        line.stroke = 'red';
        line.linewidth = 2;
        two.update();
    </script>
</body>
```
However it ends up looking like this -
![image](https://user-images.githubusercontent.com/12681262/75846336-febd0480-5e01-11ea-8425-7db24d74ac23.png)
Now, this is a contrived example, the thing is that it is much worse in my actual use case where the `div`s are actually svg icons inside `div` with margins and padding. But solving this thing first would atleast tell me how to approach this issue.  

I am willing to put in the effort if you could guide me on how to get it done. Perhaps the way I am doing it is not the best approach? You can just give me pointers and I can come back to you with the results too.

**Comment by jonobr1** [comment]
The origin, or zero, zero, of Two.js is the upper left hand corner of the two.js svg (or canvas if you're using a different renderer). So, if you wanted to draw something from one corner to the other it would be like this:

```javascript
var line = two.makeLine(two.width, 0, 0, two.height);
```

If you wanted to infer the widths of the `div`s in order to make the line relative to them then you need to account for the width and height of the `div`s. The placement may be more complex in your project, but at least here you can achieve this like so:

```javascript
var rect = elem1.getBoundingClientRect();
var x1 = two.width - rect.width / 2;
var y1 = 0 + rect.width / 2;

var rect = elem2.getBoundingClientRect();
var x2 = 0 + rect.width / 2;
var y2 = two.height - rect.height / 2;
```

If your project is more complicated, for instance if the divs are not at corners which is what it sounds like you're saying in your post, then you'll have to calculate the `div`'s position _in relation_ to Two.js's canvas. You can do this like so:

```javascript
var rects = {
  elem: elem.getBoundingClientRect(),
  two: two.renderer.domElement.getBoundingClientRect()
};
var left = rects.elem.left - rects.two.left;
var x = left + rects.elem.width / 2;
```

**Comment by armsp** [comment]
Your comments helped me a lot. It looks like half of the svg divs have this issue and half of them don't. I am going to take a closer look at those that fail. 

The way you asked me to use - 
```js
var rects = {
  elem: elem.getBoundingClientRect(),
  two: two.renderer.domElement.getBoundingClientRect()
};
```
really helps in getting the centers. Thank you so much. 
Now I have to deep dive into svgs to understand why the `getBoundingClientRect` itself is failing around a few of them - I can actually see a small rect centered at the svg if the page loads slowly and thats why i think the act of `var x = left + rects.ele.width;` or `var x = left + rects.ele.width/2;` doesn't work because the rect is so small even though the svg itself is large.

**Comment by jonobr1** [comment]
Is the SVG an image? It sounds like you're calling the rect calculator before there's content in the SVG.

**Comment by armsp** [comment]
No, I don't think that is the issue. I did more experiments and I couldn't believe what I saw. Turns out your code works perfectly on all the svgs in Chrome, however it fails for some in Firefox (which is what I use for development and in general and would very much like to support).
**Chrome render** -
![chrome](https://user-images.githubusercontent.com/12681262/76006748-f44e5800-5f32-11ea-99a4-3739c36bad96.png)

**Firefox render** -
![firefox](https://user-images.githubusercontent.com/12681262/76006764-fadccf80-5f32-11ea-822a-a53fc23fd763.png)

I have made a [gist](https://gist.github.com/armsp/fda662ceadf4de8a6caa98309c04909d) for you to try it out yourself. Any feedback would be very helpful. I am really new to web development, I wish I knew all these things before.

**Comment by armsp** [comment]
@jonobr1 I am trying to get the same line animated. It should be simple enough using `tweenjs` and I found some code in one of the earlier issues. However the following doesn't animate. Could you please help me in figuring out how to get `tween.js` to work with `two.js` and get a simple animation running. It would really help me move forward with the project. I have the following code that sort of works except the animation even though the animation code is present -
```html
<html>
<head>
    <style>
        object, div {
            border: 1px solid red;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tween.js/16.3.5/Tween.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/tween.js/16.7.0/Tween.js" ></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/two.js/0.6.0/two.min.js"></script>
</head>

<body>
    <div id="my-div"></div>
    <!-- <object id="my-div"></object> -->
</body>
<script>
    var elem = document.getElementById('my-div');
    var params = { width: 500, height: 500 };
    var two = new Two(params).appendTo(elem);

    var x = two.width/2;   console.log(x);
    var y = two.height/2;  console.log(y);
    var circle = two.makeCircle(x, y, 60);
    var keyframe = new TWEEN.Tween(circle.translation);

    window.addEventListener('click', function(e) {
        var duration = 1000; // Defined in milliseconds
        var destination = {
            x: e.clientX,
            y: e.clientY
        };console.log(destination);
        keyframe.to(destination, duration);
        keyframe.start();
    }, false);

    two.bind('update', function(frameCount, timeDelta) {
        TWEEN.update();
        console.log('Tween updated');
    });
    two.update();
</script>
</html>
``` 
I get a static circle despite the click event triggering the function and the console printing the destination coordinates, there's just no animation.

**Comment by jonobr1** [comment]
You need to call `two.play();` instead of `two.update();` at the end of your document. I would also recommend upgrading your version of Two.js to the latest stable v0.7.0: https://cdn.jsdelivr.net/npm/two.js@0.7.0-stable.1/build/two.js
