### ISSUE TITLE
makeArc sweep direction

### ISSUE THREAD

**Issue by merickiranoglu** [jonobr1/two.js#452]
Hello, 
I'm not a geometry expert but just wanna report an issue I had.

This is how I defined my arc.
```
var prevPt = points[i - 1];

var dxNext = nextPt.x - pt.x;
var dyNext = nextPt.y - pt.y;
var angleNext = Math.atan2(dyNext, dxNext);

var dxPrev = prevPt.x - pt.x;
var dyPrev = prevPt.y - pt.y;
var anglePrev = Math.atan2(dyPrev, dxPrev);

var innerRadius = 0;
var outerRadius = 20;

var arc = two.makeArcSegment(pt.x, pt.y, innerRadius, outerRadius, anglePrev, angleNext)

```
And output is;
![stackoverflow](https://user-images.githubusercontent.com/41736493/76170967-e2b9ba00-6197-11ea-9832-4146214d31f0.png)

At first node (after the line with the length of 225.46), sweep direction is counter clockwise. At second node (after 142.35), sweep direction is clockwise.How do I force it to be always counter clockwise?

Thanks.

**Comment by jonobr1** [comment]
Thanks for sharing this. They should be all operating in the same direction. Let me see what I can do to alleviate this issue.

**Comment by merickiranoglu** [comment]
I'm sharing my work-around, I hope it helps,
  ```
            if (anglePrev < 0.0)
            {
                anglePrev += Math.PI * 2.0;
            }
            if (angleNext < 0.0)
            {
                angleNext += Math.PI * 2.0;
            }
            if (angleNext > anglePrev)
            {
                anglePrev += Math.PI * 2.0;
            }
```

I'm not sure if this is enough, but it worked for my case.

**Comment by jonobr1** [comment]
Glad you were able to figure it out. Upon a closer look, you can enforce the clockwise / counterclockwise directionality of the arc yourself by doing this:

```javascript
var startAngle = Math.min(anglePrev, angleNext);
var endAngle = Math.max(anglePrev, angleNext);
// This ensures that the `startAngle` is always "to the left" of the `endAngle`
var arc = two.makeArcSegment(pt.x, pt.y, innerRadius, outerRadius, startAngle, endAngle);
```

This confusion is caused by the ability to make the `startAngle` greater than the `endAngle` and the arc to still calculate and render something to the screen.
