### ISSUE TITLE
`Two.interpret`: third parameter `add` is not respected for SVG node `g`

### ISSUE THREAD

**Issue by joergplewe** [jonobr1/two.js#455]
When calling `Two.interpret` with third parameter `add=false`, the returned group ist nonetheless added to the scene. This is at least the case when the toplevel SVG node is a `g`.

This is because `Two.Utils.read['g']` already adds the new group to the parent.

**Comment by jonobr1** [comment]
Good catch, the interpret function was originally meant to be only for `svg` tags, but there shouldn't be any reason not to apply this logic to any top level tag.

**Comment by jonobr1** [comment]
The latest `dev` branch has this fixed: https://github.com/jonobr1/two.js/tree/dev/build
