### ISSUE TITLE
How to define coordinates for Two.Group?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#457]
I wanted to know the way of defining coordinates(x,y) for specific group. Regardless of using method like `two.makeGroup` or creating instance like `Two.Group`, I wanted to specify coordinates to it. 

Or if it is not possible for this object, what should be alternate steps to set coordinates for specific group?

**Comment by jonobr1** [comment]
Do you mean move a `Two.Group` in space? That you can use `group.translation.x = 50;`.

If you want to change the coordinate space of the scene then move the scene. For instance this makes the 0, 0 coordinates of any object added the middle of the screen: `two.scene.translation.set(two.width / 2, two.height / 2);`

Hope this helps. Don't hesitate to elaborate on your question if this doesn't answer it.

**Comment by meetzaveri** [comment]
Yeah I was asking for group because for any object like rect or path, there are x and y coordinates in schema. But I didn't find that for Two.Group after reviewing documentation. 

As you said, does `group.translation.x` acts as same use-case that I provided above?

**Comment by meetzaveri** [comment]
I got it. Thanks for the response
