### ISSUE TITLE
How to resize line ? How to change x1,x2 coordinates for path?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#461]
I have been using line(using `two.makeLine`) which I want to be resizable. If I get some increase count, how I am suppose to change it's x2 coordinate ?

Is there any method through which I can change x2 coordinate for line?

Changing x2 coordinate will simulate like if line's width is increasing horizontally. 
![Screenshot from 2020-05-01 11-36-41](https://user-images.githubusercontent.com/21293048/80786112-39dc7980-8ba0-11ea-8832-42081ddf3f55.png)

**Comment by jonobr1** [comment]
If I understand correctly you can do:

````javascript
line.vertices[1].x += 50; // Increases second `x` vertex by 50 pixels.
````

**Comment by meetzaveri** [comment]
@jonobr1  It worked. Thanks for reaching out quickly. Your given solution proved exactly what I was looking for.
