### ISSUE TITLE
Tweak suggestion for Two.Text decoration property

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#462]
Hey, I was reading documentation for `Two.Text`. I came across `decoration` property and suggested values for it were `underlined`, 'strikethrough`. 

But I checked that correct value is `underline` instead of `underlined`. 

So I wanted to notify you about this small issue.

Source Image
![chrome-capture (10)](https://user-images.githubusercontent.com/21293048/80907292-98862c80-8d33-11ea-9fa9-9bd11ca4303a.jpg)

Hope you got the context.

**Comment by jonobr1** [comment]
Thanks!
