### ISSUE TITLE
text.decoration doesn't work

### ISSUE THREAD

**Issue by welkinwong** [jonobr1/two.js#463]
```
const text = two.makeText(string, 0, 0);
text.fill = '#fff';
text.size = 14;
text.weight = 'bold';
text.style = 'italic';
text.decoration = 'underline' or text.decoration = 'strikethrough' 
```
![image](https://user-images.githubusercontent.com/6650440/81182902-ff7c3d80-8fe0-11ea-8d6f-5c57446f8e87.png)

only decoration not working

**Comment by jonobr1** [comment]
Which renderer are you using?

**Comment by welkinwong** [comment]
> Which renderer are you using?

i use canvas

**Comment by jonobr1** [comment]
This updated on the latest dev branch: [WebGL](https://github.com/jonobr1/two.js/commit/d33a5d6380e2a93bd2bacd88276f8720f27ca683) • [Canvas](https://github.com/jonobr1/two.js/commit/c854a1cc5d5d77fd46a18080f479926c5d39dc5b)
