### ISSUE TITLE
Rotation rounding leading Firefox to constantly redraw rotating shapes, severely affecting performance

### ISSUE THREAD

**Issue by jonohewitt** [jonobr1/two.js#464]
Firefox currently has code that detects the scale of a shape transform, which allows for differences of < 1e-5 to account for rotation. When Two.js converts a rotation matrix to a string to set the property, the toFixed function is rounding to 3 decimal places which is causing scale differences greater than this 1e-5 limit. This causes Firefox to think that the shape scale has changed and leads it to redraw the shape. 

This causes severe performance issues on Firefox with rotating animations such as: https://looping-squares.superhi.com

(Thanks to @jrmuizel from Mozilla for giving me his explanation of this issue which I have paraphrased above - please let me know if I've butchered it!)

**Comment by jonobr1** [comment]
That totally makes sense. I can increase the precision to that. To confirm, this is just with the SVG renderer, right?

**Comment by jonobr1** [comment]
This is fixed on the latest dev branch by this commit: https://github.com/jonobr1/two.js/commit/ff9ade2308da3e28b43c9d8ed1adea79646d9ca8

Gave it a shot with the example you gave and works much better now 👍 Thanks for reporting!
