### ISSUE TITLE
How to give rounded corners to path structure

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#465]
Suppose I have rectangle type structure created by `two.makePath()`.

Preview(Current):
![chrome-capture (11)](https://user-images.githubusercontent.com/21293048/82179753-b4292f80-98fc-11ea-80ed-4265fcc11e31.jpg)

So how do I set rounded corners to that structure?

Like (Expected):
![chrome-capture (13)](https://user-images.githubusercontent.com/21293048/82180540-5c8bc380-98fe-11ea-9e3f-3af96fc0baf1.jpg)

**Comment by jonobr1** [comment]
You need to use the `two.makeRoundedRectangle` method instead of `two.makePath`. The parameters are `x`, `y`, `width`, `height`, and `radius`.

**Comment by meetzaveri** [comment]
Yes, I have used it(rounded rect). But I want to apply rounded corners for this typical path structure. 

Is there any way to do that?

**Comment by jonobr1** [comment]
You can set `path.curved = true;` but there's no way to control roundness. This can be tracked as an enhancement feature.

**Comment by meetzaveri** [comment]
Okay got it. I will find a turnaround for time being until there's an update on this.

**Comment by jonobr1** [comment]
In the meantime (and this is a bit of a hack) you can set the `stroke` color to the same color as the `fill` and increase the `linewidth`. Then set `join` to `round` and change the `miter` value (default is 4). For certain cases this can get you the effect of rounded corners without actually making rounded corners.

**Comment by meetzaveri** [comment]
Yeah took your suggestion and I did that for time being. It works!

**Comment by jonobr1** [comment]
Glad to hear!

**Comment by jonobr1** [comment]
Tracking the functionality you're describing as a feature here: https://github.com/jonobr1/two.js/issues/467
