### ISSUE TITLE
Creating Two.Sprite or Two.Texture in headless mode. "loadHeadlessBuffer" triggers "ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by soullpoint** [jonobr1/two.js#468]
Hi, I'm trying to load an image onto the canvas in headless mode, but I'm getting "require is not defined" when I try to do so. 

I'm running this outside of the browser, within a test.js script by calling it `node test.js`.

Is this a known issue or do you have any idea what I might be doing wrong / if there are any work arounds?

**Comment by jonobr1** [comment]
Yeah, it looks like the latest versions of node will not pass their global context onto `Function`s. I have a branch that is patched to work and will be merging this into `dev` as soon as I've tested it more thoroughly. If you need a fix immediately, I recommend using this branch for the time being: https://github.com/jonobr1/two.js/tree/issue-468

**Comment by adroitwhiz** [comment]
Why does the function take the form of a string?

**Comment by jonobr1** [comment]
Because the code `var fs = require('fs');` will throw an error in browsers, so that code has been stringified to package for both environments.

**Comment by adroitwhiz** [comment]
If my understanding is correct, won't it only throw an error if you actually try to run it?

**Comment by jonobr1** [comment]
I can't remember off the top of my head, but when I originally made it I wanted to go that route. At the time, it would throw an error regardless, which is why I ended up stringifying it. But, I should check to see if this has maybe also been updated.

**Comment by jonobr1** [comment]
Okay, after further testing I was able to get things working and not failing any other tests. This has been pushed to the latest `dev` branch here: https://github.com/jonobr1/two.js/commit/505b78b6151ebe357bc03ab1babdef3e2067ee77

Thanks for posting!
