### ISSUE TITLE
Path stroke on mask

### ISSUE THREAD

**Issue by pvamshi** [jonobr1/two.js#469]
I am very new to `two.js` or vector drawing ... so sorry for noob question :) 
```
group.add(new Two.Rectangle(0,0,1000,1000));
path.stroke = 'white';
group.mask = path;
```
How do we get stroke for the path ? 
![image](https://user-images.githubusercontent.com/1425006/82759225-4b562180-9dec-11ea-84f4-2d68f5ffdf5d.png)

**Comment by pvamshi** [comment]
Added path twice :)

**Comment by jonobr1** [comment]
Glad you figured it out. To reiterate, once a path is set as a mask it is not drawn to the canvas. Both its fill and stroke are applied to what will be the masked region.
