### ISSUE TITLE
[Question] Change axis of rotation

### ISSUE THREAD

**Issue by pvamshi** [jonobr1/two.js#471]
Another dumb question. I figured out rotation works always at origin when the object is created. 

Is there a way to change axis of rotation dynamically. For example, change axis of rotation from center to one corner of a rectangle.

**Comment by jonobr1** [comment]
There isn't an elegant way to handle this yet.., but you can achieve what (I think) you're asking for by simply altering the vertices yourself. If you had a `path` variable you can do this like so:

```javascript
var rect = path.getBoundingClientRect(true);
for (var i = 0; i < path.vertices.length; i++) {
  path.vertices[i].x -= rect.width / 2;
  path.vertices[i].y -= rect.height / 2;
}
```

This example would make the "center" of rotation the upper-left-hand corner of the shape.

**Comment by pvamshi** [comment]
I am sure if I made my point clear. My apologies. 
If I understand correctly, the above code just moves the path by half its size up and left right ? 
What I meant is let the path stay where it is and change the anchor of rotation , like shown in pixijs documentation 
https://github.com/kittykatattack/learningPixi#rotation
I can show a screencast to make myself clear if needed. 

Thanks for taking time to explain me

**Comment by pvamshi** [comment]
I tried a little and gained more understanding :) . 
This is what I wanted : 
(code in typescript, sorry about that ) 
```typescript
function rotateAtAnchor(
  two: Two,
  obj: Rectangle,
  anchor: Vector,
  rotation: number
) {
  const originalParent = obj.parent;

  // obj - anchor
  anchor.multiplyScalar(-1);
  obj.translation.addSelf(anchor);

  // add obj to new group, detach from original parent
  const g = two.makeGroup(obj);
  //rotate the group
  g.rotation = rotation;

  //restore anchor to its original value
  anchor.multiplyScalar(-1);
  //move group to anchor
  g.translation = anchor;
  //add group to original parent
  g.addTo(originalParent);
}

```

Now I can use the above function and rotate my object 90° at bottom right corner  . 

```typescript
  const r = two.makeRectangle(300, 500, 400, 200);
  const anchor = new Vector(500, 600);
  rotateAtAnchor(two, r, anchor, Math.PI / 2);
```
![image](https://user-images.githubusercontent.com/1425006/83579949-02fcd900-a53b-11ea-8732-90e7b187f39f.png)
to 
![image](https://user-images.githubusercontent.com/1425006/83579972-1740d600-a53b-11ea-81ae-59eac290d8db.png)

**Comment by jonobr1** [comment]
Yeah, I totally understood your question. You can achieve the same output without additional groups by modifying the vertices directly. But, glad you were able to get it working as you liked.
