### ISSUE TITLE
ZUI is not a constructor error

### ISSUE THREAD

**Issue by maleficca** [jonobr1/two.js#475]
Hi there, thanks for all the work in the two.js, it's a great package.

I am working with two.js in Vue.js application and I'm trying to implement Zoom/Pan features by using the zui.js class.
The problem is that I cannot import it without getting an error:
`TypeError: two_js_extras_zui__WEBPACK_IMPORTED_MODULE_14__.ZUI is not a constructor`

This error is also visible in codepens which are utilizing this class, like this one:
https://jsfiddle.net/jonobr1/hc196sju/

Is there something that can be done to make zui.js work?

**Comment by jonobr1** [comment]
Thanks for the question. You need to use the extras in the `/build` folder.

E.g: use this link instead of the one you have in your JSFiddle: https://rawgit.com/jonobr1/two.js/dev/build/extras/zui.js

**Comment by maleficca** [comment]
Thanks for your reply! I was importing it in the following manner in my Vue.js code:

`import ZUI from "two.js/extras/zui.js`

But it wasn't really working, got the same error as previously. So instead I simply put whole zui.js file into "plugins" folder in my solution and imported it from there in the same way (just changing the path). That got it working marvelously! I'm not really sure what's the difference here (as I don't consider myself a JS expert), but from my experience, JS code in Vue.js can be a little bit tricky sometimes, especially if you're trying to extend classes from an npm package.

Nonetheless, everything is working fine now. I'm working on importing .dxf from CAD software to a web viewer and with two.js I was able to develop a concept in just one day, so it's a really great piece of code.

**Comment by jonobr1** [comment]
Hmm, it should work the way you described. I'll have to check and make sure there isn't something else happening.

**Comment by jonobr1** [comment]
Thanks, this is currently broken on the stable build on npm. However, just updated and fixed on the current `dev` branch, so the next build will have this fixed. Thanks for reporting!

**Comment by devthrough** [comment]
Hi there, 

im running into the same issue. The code, see link below, works. 

https://codepen.io/michael-kamil-mcik/pen/wvqPPWE

If im trying to run the code with Angular (i have build your es6 and dev tag, i have also used the npm package to install the two.js) i'm running into the "ZUI is not a constructor error". I have tried the following ways to import two.js (ZUI):

**1.  Solution**

I'm importing ZUI like proposed `import ZUI from "@jonobr1/two.js/extras/js/zui`, but if im running `var zui = new ZUI(this.stage);` it's missing the two.js (Two) dependencies.

**2.  Solution**

If i'm importing ZUI like proposed `import ZUI from "@jonobr1/two.js/extras/jsm/zui` and  running `var zui = new ZUI(this.stage);` no dependency issues occur, but zooming does not work and `Two.shape.getBoundingClientRect();` is undefined. 


There is no `/build/extras` path, just `/extras`. The base two.js stuff works, like drawing rects etc.

Kind regards and many thanks in advance!

**Comment by jonobr1** [comment]
Sorry for the delay. I can confirm that your codepen is working. I'm not sure exactly the issue you're having with two.js in Angular, but I was able to recreate a ZUI example in codesandbox in Angular here: https://codesandbox.io/s/nostalgic-volhard-6zzfd?file=/src/app/app.component.ts

Hope this helps.
