### ISSUE TITLE
Scientific Notation for coordinate in polybézier not parsed correctly

### ISSUE THREAD

**Issue by gsarosi67** [jonobr1/two.js#476]
The polybezier in the attached SVG file was created using Inkscape and does not render in two.js.  It is because one of the coordinates in the curve command of the path is in scientific notation:

```svg
<path
            id="sga-upperdome"
            d="m -124.34692,-8.5080247 c 2.05982,-6.6660983 4.11965,-13.3322293 9.4153,-18.5340613 5.29566,-5.201831 13.82637,-8.938647 22.352194,-8.938579 8.525823,6.7e-5 17.045519,3.73682 22.33554,8.938637 5.290022,5.201818 7.349973,11.868008 9.409872,18.534028"
            style="display:inline;fill:none;stroke:#000000;stroke-width:0.705556;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
```
The file renders fine in chrome, just not with two.js interpret method.  The problem is in the path method of src/utils/interpret-svg.js line 509:
```javascript
 var items = command.slice(1).trim().split(/[\s,]+|(?=\s?[+-])/);
```
When splitting the command string, it is splitting on [+-] which means that value using Scientific Notation get split incorrectly:
```javascript
items
(25) ["2.05982", "-6.6660983", "4.11965", "-13.3322293", "9.4153", "-18.5340613", "5.29566", "-5.201831", "13.82637", "-8.938647", "22.352194", "-8.938579", "8.525823", "6.7e", "-5", "17.045519", "3.73682", "22.33554", "8.938637", "5.290022", "5.201818", "7.349973", "11.868008", "9.409872", "18.534028"]          
```
As you can see the 6.7e-5 is split into 6.7e and -5.

[dome.svg.txt](https://github.com/jonobr1/two.js/files/4949118/dome.svg.txt)

**Comment by jonobr1** [comment]
Thanks for posting. The latest dev branch has a patch for this: https://github.com/jonobr1/two.js/commit/11f38f5c9577eff83a7566d2695b2c549a93eb87

**Comment by davidwebca** [comment]
Is there a reason why the same parsing isn't applied to externally loaded SVGs through Two.load? I just found myself stumbling on this for a good hour and wondering why my paths were all messed up.

For anyone stumbling on this, loading the file yourself through xhr and passing its parsed dom node to Two.js works fine. Here's a working example with fetch: 

```js
let two = new Two({
    width: window.innerWidth,
    height: window.innerHeight,
    type: Two.Types['webgl'],
    autostart: true
});

fetch('file.svg').then(r => r.text()).then((text) => {
    let parser = new DOMParser();
    let doc = parser.parseFromString(svg, "image/svg+xml");
    two.interpret(doc.querySelector('svg'));
});
```

**Comment by jonobr1** [comment]
@davidwebca, I'm not sure I understand in the context of this question. Are you saying scientific notation not work when using `two.load`?

**Comment by davidwebca** [comment]
Yeah exactly. Sorry for the lack of details. I was reading two.js code to find out what was happening and I thought I had seen something that made two.load bypass the scientific notation parsing only when loaded through two.load... but now that I re-read the code, I'm not sure anymore. Again, I'll get back to you when this deadline is passed 💀  But I can confirm that loading my external svg file through two.load bypasses something and doesn't yield the same result as loading it externally myself and then passing it to interpret manually.

**Comment by jonobr1** [comment]
Thanks, please post a new thread once you have time!
