### ISSUE TITLE
ArcSegment disable outer/inner radius option

### ISSUE THREAD

**Issue by markiewiczjakub** [jonobr1/two.js#477]
Hi!

I was wondering if I can make an ArcSegment without outer/inner part. Giving function the same radius ain't doing the job, because when I scale it enough it can be seen that they are splitting and I can't allow that.
I was trying to remove one of ArcSegment parts directly in two.js file, but I couldn't manage to achieve desired effect.

Preview of splitting arcs:
![arc-split](https://user-images.githubusercontent.com/44529823/88286628-5694d300-ccf1-11ea-88f9-0f9f4b9a0496.png)
Radiuses value:
![radius](https://user-images.githubusercontent.com/44529823/88286632-572d6980-ccf1-11ea-9dc0-3cc999638e0a.png)

**Comment by jonobr1** [comment]
You can make a `Two.Circle` and then control its `beginning` or `ending` which are values from zero to one in order to achieve this. e.g:

```javascript
var circle = two.makeCircle(two.width / 2, two.height / 2, 50);
circle.beginning = 0.25;
circle.ending = 0.75;
// Should see a semi-circle a.k.a an arc.
```

**Comment by markiewiczjakub** [comment]
> You can make a `Two.Circle` and then control its `beginning` or `ending` which are values from zero to one in order to achieve this. e.g:
> 
> ```js
> var circle = two.makeCircle(two.width / 2, two.height / 2, 50);
> circle.beginning = 0.25;
> circle.ending = 0.75;
> // Should see a semi-circle a.k.a an arc with no inner or outer radius.
> ```

It won't work, because the maximum arc i can get is from 0 to 3/2π and I need way bigger range. I would rather edit ArcSegment function in two.js file to remove one of the part. Can you help me with that?

**Comment by markiewiczjakub** [comment]
I managed to do it by commenting whole "Outer Circle" section + "Final Point" in punctured if statement.

Thanks for help anyway.

**Comment by jonobr1** [comment]
Glad you were able to figure it out!
