### ISSUE TITLE
Custom uniforms to custom shader

### ISSUE THREAD

**Issue by kekkorider** [jonobr1/two.js#478]
I've added a custom fragment shader to the WebGL renderer following the instructions in https://github.com/jonobr1/two.js/issues/186#issuecomment-233435799, but now I need to pass it a couple of custom uniforms.

Any way to do that? 🤔

**Comment by kekkorider** [comment]
Ok, I've had to dig into WebGLFundamentals to learn how to do that, but it was really worth it! There are only two steps

```js
...
// Setup TwoJS
...

// 1. Get the custom uniform location
const gl = two.renderer.ctx
const program = gl.getParameter(gl.CURRENT_PROGRAM)

// `u_custom` is the uniform name you use in the shaders
const customUniformLocation = gl.getUniformLocation(program, 'u_custom')

// 2. Pass the uniform's value to the program on each `update` cycle
two.bind('update', frameCount => {
    const uniformValue = Math.sin(frameCount * 0.1) // Just an example
    gl.uniform1f(customUniformLocation, uniformValue)
})
```

Peace ✌️

**Comment by jonobr1** [comment]
Nice work! Interested to see whatever you make 👍
