### ISSUE TITLE
What is a right path.cap, path.join and path.miter defaults?

### ISSUE THREAD

**Issue by Filyus** [jonobr1/two.js#480]
In the code:
```js
/**
 * @name Two.Path#cap
 * @property {String}
 * @see {@link https://www.w3.org/TR/SVG11/painting.html#StrokeLinecapProperty}
 */
this.cap = 'butt';      // Default of Adobe Illustrator

/**
 * @name Two.Path#join
 * @property {String}
 * @see {@link https://www.w3.org/TR/SVG11/painting.html#StrokeLinejoinProperty}
 */
this.join = 'miter';    // Default of Adobe Illustrator

/**
 * @name Two.Path#miter
 * @property {String}
 * @see {@link https://www.w3.org/TR/SVG11/painting.html#StrokeMiterlimitProperty}
 */
this.miter = 4;         // Default of Adobe Illustrator
```
In the docs:

> **cap** path.cap
> A string representing the type of stroke cap to render. All applicable values can be found on the w3c spec.
> Defaults to "round".
> 
> **join** path.join
> A string representing the type of stroke join to render. All applicable values can be found on the w3c spec.
> Defaults to "round".
>
> miter path.miter
> A number representing the miter limit for the stroke. Defaults to 1.

**Comment by jonobr1** [comment]
The code is always right. I'm in the middle of updating the documentation, so I'll be sure to make sure that update makes it too. Thanks!

**Comment by Filyus** [comment]
Thanks!
