### ISSUE TITLE
A way to enable/disable render of groups?

### ISSUE THREAD

**Issue by korg** [jonobr1/two.js#482]
Im trying to find a way to switch between a couple of scenes depending on state.

Im was hoping to maintain two groups (one for each scene/view) and then disable one and enable the other but i cant see a way to do that in the source (#include <javascript_newbie.h> so i might have missed the blindingly obvious)

**Comment by jonobr1** [comment]
You mean something like `group.visible = false;`?

**Comment by korg** [comment]
haha. Yep. Exactly like that. I didnt think to search for that. (tried disable/hide/.. etc)

Although i note that .visible is only listed in the docs under text.visible. Should most of the elements listed under the details of Two.Text should be put in a 'common attributes' section? I see the github wiki has better docs. Ive been using https://two.js.org/#two-text

**Comment by jonobr1** [comment]
Yes it should! The wiki is the new docs I'm working on. As you can see it's not perfect, but it is more up-to-date than the two.js.org/ documentation. Hoping to have the wiki out soon! Though to be honest, I've been working on it for quite awhile... 😅
