### ISSUE TITLE
Problems with SVG interpretation

### ISSUE THREAD

**Issue by alessandroRoaro** [jonobr1/two.js#483]
Hi,

Thank you for creating this library! It works well and it's easy to use.

I'm having a problem with SVG interpretation, that often ends up with wrong results.
This is what I'm doing, after having loaded an external svg:
```

const two = new Two({width: 500, height: 500}).appendTo(document.getElementById("test"));
let div = document.createElement('div')
div.innerHTML = svg
let icon = two.interpret(s.getElementsByTagName('svg')[0])

two.add(icon)
two.update()
```

I'm loading icons from nounproject.com, and the issue presents itself quite often.
For example, this: 
![Screenshot from 2020-09-02 16-58-58](https://user-images.githubusercontent.com/3339135/92001076-88f90d80-ed3e-11ea-87f3-6430fc29ffc6.png)

Becomes this:
![Screenshot from 2020-09-02 16-59-13](https://user-images.githubusercontent.com/3339135/92001097-8f878500-ed3e-11ea-846a-f36d9e946082.png)

And this:
![Screenshot from 2020-09-02 17-02-26](https://user-images.githubusercontent.com/3339135/92001142-9a421a00-ed3e-11ea-842a-b0b558116666.png)

Becomes this:
![Screenshot from 2020-09-02 17-02-18](https://user-images.githubusercontent.com/3339135/92001154-9f9f6480-ed3e-11ea-88ae-4c6fe9d24719.png)

Refer to these links for the icons of the examples:
https://thenounproject.com/search/?q=what&i=1480784
https://thenounproject.com/search/?q=what&i=3455678

Thank you for your time

Alessandro

**Comment by jonobr1** [comment]
These issues are solved with the latest `dev` branch. Please use this version ([link](https://github.com/jonobr1/two.js/blob/dev/build/two.js)) in your project. Or if you're using NPM install via the git repository: 

```
npm install git+https://git@github.com/jonobr1/two.js.git
```

**Comment by alessandroRoaro** [comment]
Thank you for the quick reply. I had already tried the latest dev version,
but that doesn't seem to help unfortunately.

Could you kindly check?

**Comment by jonobr1** [comment]
Works fine for me:

<img width="1440" alt="Screen Shot 2020-09-03 at 11 26 40 AM" src="https://user-images.githubusercontent.com/220033/92135130-5e5b9300-edd8-11ea-9d78-e295a00d1219.png">

🤔 how are your svgs added to the DOM?

**Comment by alessandroRoaro** [comment]
I'm doing this:

```
api.getIconSvg({ iconUrl: this.iconURL }).then(res => {
	twoGroup.remove(oldIcon);
	
	// create new icon
	const s = document.createElement('div')
        s.innerHTML = svg
        const icon = two.interpret(s.getElementsByTagName('svg')[0])
        
        twoGroup.add(icon);
        two.update();
})
```

**Comment by jonobr1** [comment]
That seems like it should work. Any change you can put a version of this up online somewhere I can poke around?

**Comment by alessandroRoaro** [comment]
I eventually found out that the issue was in the getIconSvg call, which was doing some SVG "optimization" of its own. Sorry for not seeing that before, I took into my hands someone else's code and it took me a while to realize the issue

**Comment by jonobr1** [comment]
Glad to hear you were able to figure it out. Any chance you could share what your or the other person's code is so that if someone else runs into this problem they can find an answer?

**Comment by alessandroRoaro** [comment]
It's not really helpful I think, it was just some manipulation of the raw SVG that actually ended up messing it up. When I removed all of that and updated two.js to the latest dev version it all worked fine. Thank you for your help! Much appreciated
