### ISSUE TITLE
NPM zui is not a constructor

### ISSUE THREAD

**Issue by blu-towers** [jonobr1/two.js#484]
I am trying to use two via angular with:

import Two from "two.js";
import {ZUI} from "two.js/extras/zui.js";

before i used to import via the assets folder but want to update to use npm.

but i am now receiving this error when trying to use ZUI:

ERROR TypeError: two_js__WEBPACK_IMPORTED_MODULE_7__.default.ZUI is not a constructor

I have tried a few ways to import it but still getting this error, can you confirm the current package is working correctly.

**Comment by jonobr1** [comment]
I believe that's because it's `import ZUI from 'two.js/extras/zui.js';`, but if that doesn't work let me know and we can troubleshoot further.

**Comment by blu-towers** [comment]
No still same error, i am using angular 10.1 and latest version of two from npm install --save two.js

**Comment by jonobr1** [comment]
Try using the latest `dev` version with: `npm install git+https://github.com/jonobr1/two.js.git`. The stable npm version isn't defined with modules for extras yet.

**Comment by blu-towers** [comment]
Thanks that does seem to fix the ZUI issue but the .interpret used to work on this svg but now does not:

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="27.5" height="27.5" x="0px" y="0px" 
     viewBox="0 0 30 27.5" enable-background="new 0 0 30 27.5" xml:space="preserve">
<rect x="-13.8" y="-13.8" fill="#FFFFFF" stroke="#1D1D1B" stroke-miterlimit="10" width="27.5" height="27.5"/>
<circle fill="#FFFFFF" stroke="#1D1D1B" stroke-width="0.75" stroke-miterlimit="10" cx="5.6" cy="-5.7" r="3.9"/>
<circle fill="#FFFFFF" stroke="#1D1D1B" stroke-width="0.75" stroke-miterlimit="10" cx="-5.5" cy="5.6" r="3.9"/>
<circle fill="#FFFFFF" stroke="#1D1D1B" stroke-width="0.75" stroke-miterlimit="10" cx="-5.5" cy="-5.7" r="3.9"/>
<circle fill="#FFFFFF" stroke="#1D1D1B" stroke-width="0.75" stroke-miterlimit="10" cx="5.6" cy="5.6" r="3.9"/>
</svg>`

I have updated to the latest git version, this is the same for a few of my svg icons used to work with interpret before but now showing either too large or overlapping.

**Comment by adroitwhiz** [comment]
This is just a guess but try removing the `viewBox`?

**Comment by blu-towers** [comment]
That does create it at the right size but the circles then overlap each other when they never in the previous version.

**Comment by jonobr1** [comment]
Sorry about that. This has to do with a change in `Two.Utils.applySvgAttributes` which was updated for path interpretation but not Circles and Ellipses. This is now updated in the current `dev` branch. Given the number of changes and time that's passed, I'm thinking I'll update npm soon.

**Comment by blu-towers** [comment]
Hi,

That update seems to have fixed the circle and ellipse but i have one svg where ellipse is not as big as it should be, the circle and rect should be inside it:

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"  enable-background="new 0 0 48 36" xml:space="preserve">
                <path fill="#FFFFFF" stroke="#000000" stroke-width="0.7" d="M-33.4-33.4h66.7v17.6C29,9.3,9.3,29-15.7,33.4h-17.6V-33.4z"/>
                <ellipse transform="matrix(0.7071 -0.7071 0.7071 0.7071 0 0)" fill="none" stroke="#000000" stroke-width="0.4" cx="0" cy="0" rx="35.3" ry="17.6"/>
                <rect x="-25.1" y="23.5" transform="matrix(0.7071 -0.7071 0.7071 0.7071 -24.034 -9.8024)" fill="#1D1D1B" stroke="#000000" stroke-width="0.2" width="2.5" height="1.3"/>
                <circle id="svg_4" fill="#1D1D1B" stroke="#000000" stroke-width="0.2" cx="-18.9" cy="18.9" r="1.5"/>
                </svg>`

**Comment by jonobr1** [comment]
Thanks @blu-towers, I just updated the `dev` branch with improvements that should fix your issue.

**Comment by jonobr1** [comment]
If you have further errors, please start a new issue. Thanks for reporting! 👍
