### ISSUE TITLE
Problem with with <use /> 

### ISSUE THREAD

**Issue by TextTL** [jonobr1/two.js#485]
I used the latest codes to to test <use /> in an SVG, and I have this problem: 

two.min.js:4548 Uncaught TypeError: Cannot read property 'call' of undefined
    at X.use (two.min.js:4548)
    at X.g (two.min.js:4560)
    at ve.g (two.min.js:4560)
    at ve.svg (two.min.js:4517)
    at ve.interpret (two.min.js:7576)

What would be the cause? 
It seems like the localName is not defined after the cloneNode. 

Thanks,

**Comment by TextTL** [comment]
I think I found the issue. two.js  is not supporting <symbol/>.

**Comment by jonobr1** [comment]
Yeah, Two.js doesn't support `<use />` tags.

**Comment by iamtekeste** [comment]
@jonobr1 what other limitations does the SVG interpreter have?

**Comment by jonobr1** [comment]
+ `<defs />`
+ `<use />`
+ `<image />`

This could make it problematic to have clipped elements or masks that are defined in `<defs />` interpreted correctly into Two.js.

Hope this helps!
