### ISSUE TITLE
Is <text> supported? 

### ISSUE THREAD

**Issue by txtl** [jonobr1/two.js#488]
I have a simple SVG with a text element, but two.js couldn't load it. There was an error in the console: "Error: <g> attribute transform: Expected number, "matrix(NaN NaN NaN NaN …".". 

Two codes: 
```
        two.load('text.svg', function (svg) {
            svg.center(); // I center the object's shapes
            two.renderer.setSize(window.innerWidth, window.innerHeight);
            svg.translation.set(two.width / 2, two.height / 2); // move to the center of the canvas
            two.add(svg);
        });
```
the SVG:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400.00001" height="400">
   <g id="layer1">
      <text id="text3350" y="80.2851" x="22.981991"
         style="font-style:normal;font-weight:normal;font-size:82.61395264px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#ff0000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;"
         xml:space="preserve">Test Text
      </text>
   </g>
</svg>
```

**Comment by txtl** [comment]
I tried two.interpret. It seems to work even though there was an error on the console. that's odd.

**Comment by jonobr1** [comment]
This is because text isn't supported in `v0.7.0`. I just added it to the `dev` branch though. So if you use the latest builds there it should work.

**Comment by txtl** [comment]
I just tried the dev, and two.js now shows the text, font, color. The X, Y position is not respected somehow. 

Thank you very much!

**Comment by jonobr1** [comment]
The example you provided above works for me fine when I reproduce it locally. What do you mean the X / Y position is not respected?

**Comment by txtl** [comment]
Sorry, I was my mistake. I have "svg.center();" which makes text appears in the center always. 

Thank you very much for your help!

**Comment by txtl** [comment]
I tried another example, and it does not work as expected; the text positions rendered by the current dev branch are not correct; the correct example of text position is here:  https://jsfiddle.net/api/mdn/
```
  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
    <text x="20" y="35" style="font-style:italic;font-family:sans-serif;font-size:13px;fill:yellow">My</text>
    <text x="40" y="35" style="font-style:bold;font-family:sans-serif;font-size:30px;fill:green">cat</text>
    <text x="55" y="55" style="font-style:italic;font-family:sans-serif;font-size:13px;fill:yellow">is</text>
    <text x="65" y="55" style="font-style:italic;font-family:serif;font-size:40px;fill:red">Grumpy!</text>
</svg>
```

Thi

**Comment by jonobr1** [comment]
This was due to not taking into account a default `alignment` and `baseline` (which in Two.js are `center` and `middle` respectively. But, in SVGs are `left` and `baseline`). So, the latest `dev` branch has this patched in to work.

**Comment by txtl** [comment]
Great! I tried it out, and it worked as expected. 

Thank you very much!
