### ISSUE TITLE
Text className

### ISSUE THREAD

**Issue by blu-towers** [jonobr1/two.js#489]
When trying to add a class to Two.Text it doesn't seem to work, it works fine for Two.Group but not Two.Text, tried both ways below, test.className works fine for a Two.Group.

`var test = new Two.Text(
      'TEST',
      0,
      15,
      {className: 'TEST'}
    );
    test.className='TEST'`

**Comment by blu-towers** [comment]
It looks like it is added to the className but not the ._renderer.elem.className or classList, the Two.Text is inside a Two.Group if this helps. I have also done many two.Update() but the object does not have the class='TEST' rendered.

**Comment by jonobr1** [comment]
Thanks for posting! The fix for this is in the latest `dev` branch.

**Comment by blu-towers** [comment]
Thanks i also now don't seem to be able to set visible?, test.visible=true
