### ISSUE TITLE
Two.Group.visible should not trickle down to children

### ISSUE THREAD

**Issue by blu-towers** [jonobr1/two.js#490]
Creating new ticket as old is closed. The text.className now works but i now don't seem to be able to set visible?, test.visible=true

---

`Two.Group.visible` shouldn't be a pass-through getter/setter to apply visibility to its children, but rather a property on itself. To fix will require:
1. Remove `visible` from `Two.Group.Properties`
2. Write a plain getter/setter for `Two.Group.visible`
3. Amend all renderers to accommodate `Two.Group.visible`

**Comment by jonobr1** [comment]
I'm not sure I understand your question. Elements are visible by default and when I set a text's `visible` property it shows up (or doesn't) as intended. What exactly is happening when you set `test.visible = true`?

**Comment by blu-towers** [comment]
When you set text.visible = false, visibility="visible" is rendered on the Text object but on the console.log object visible=false

**Comment by blu-towers** [comment]
same issue i have before with the text.className ='test' would show in the console but not on the rendered object

**Comment by jonobr1** [comment]
Can you post an example code because I'm not getting that issue when I recreate a scene with a text object and set `visible` to `true` or `false`.

**Comment by blu-towers** [comment]
I figured the issue out, my Two.Text is inside a Two.Group i set visible=false on the Text and visible=true on the Group. In my code i set the visibility on the Group after the Text and this then sets the Text to visible.

I have reordered my code to solve this issue but not sure if setting the visibility on the Group should amend the Text.

**Comment by jonobr1** [comment]
Glad to hear. Fill, stroke, opacity, and visible are all properties on a Two.Group that trickle down to their children. But, it's a good point. Maybe visible shouldn't work like that.

**Comment by jonobr1** [comment]
This [commit](https://github.com/jonobr1/two.js/commits/dev) fixes those issues. Thanks for reporting!
