### ISSUE TITLE
makeArcSegment cool side effect

### ISSUE THREAD

**Issue by patgarcia** [jonobr1/two.js#492]
When the arc revolves around the circumference more than one time (end angle > 2π), it seems that some vertices get shot out, creating some cool side effects (image below).

For practical purposes, an arc should be less than 2π, so I don't see this as a bug, but I wrote this ticket to catalog the effect. 

[Here is a pen](https://codepen.io/commonzen/pen/MWjWWbO) to illustrate.

![Image of makeArcSegment cool side effect](https://github.com/patgarcia/my_images/blob/master/makeArcSegment.jpg?raw=true)

**Comment by jonobr1** [comment]
Wow, that is super cool!
