### ISSUE TITLE
Source code for examples?

### ISSUE THREAD

**Issue by PrestonII** [jonobr1/two.js#493]
First off, said it before but it's worth saying twice - I love this library 🥇 

Quick question though - is there source code available for any of the [examples](https://two.js.org/examples/) on the main page? I'd love to dig in and see how some of them work but I couldn't find anything anywhere - other than sneaking through the devTools obviously ;-)

**Comment by adroitwhiz** [comment]
Currently they're in the `gh-pages` branch: https://github.com/jonobr1/two.js/tree/gh-pages/examples

**Comment by jonobr1** [comment]
Glad you like it so much! All the examples live on the gh-branch under /examples in their own html folder. These were made before all the UMD madness

**Comment by PrestonII** [comment]
Thanks @adroitwhiz @jonobr1! 

Just checked it out and looked through those and that's exactly what I was looking for !
