### ISSUE TITLE
Creating object trails

### ISSUE THREAD

**Issue by NickXitco** [jonobr1/two.js#500]
Hi Jono!

I just started using two.js today and am loving it so far. I've been running into an issue however and wanted to see if you had any thoughts or could guide me.

```javascript
function loop(frameCount) {
    for (const boid of boids) {


        boid.setAcceleration(boids);
        boid.drawing.translation.set(boid.x, boid.y);
        boid.drawing.rotation = Math.atan2(boid.vy, boid.vx) + Math.PI / 2;


        // Update path by adding on another anchor and removing the first in the list
        const collection = boid.trailDrawing.vertices;
        collection.push(new Two.Anchor(boid.x, boid.y, boid.x, boid.y, boid.x, boid.y))
        collection.shift();


        boid.update();
    }
}
```

Here is my main draw loop.  It creates a boids animation that looks like this!
![1nr4ExB33N](https://user-images.githubusercontent.com/34454344/102435065-f9712500-3fe3-11eb-8ebd-18233775cd28.gif)

My question/issue is in regards to the Two.Path object. The ideal for my application would be a object trail, which I'm currently generating by creating a Two.Path for every flyer guy, then on every loop I'm adding a new point onto the path and taking off the first point on the path. This seems to be the most obvious way to do it without redrawing the whole path.

However, WebGL HATES this. I can't seem to find a way to do this that WebGL doesn't hate. In doing some research I came across this hackernews page (https://news.ycombinator.com/item?id=9897329) where you said:

> "This is because when a shape is first created the WebGL Renderer draws the shape as a texture in Canvas2d and then uploads that texture to GL. The operations "Vertices" and "Scale" force each shape to be redrawn so there are a lot of textures being uploaded and deleted every frame this scenario. If you keep things to translation / rotation you can make the WebGL renderer push wayyyy more shapes than the other 2 renderers.
> I'm currently developing a way to "cache" textures that don't change much so if you had a Two.Group that doesn't change much you can turn that into 1 texture. This will greatly increase performance as well. Thanks for checking it out!"

Is there a better way to do this with groups that I'm missing? I'm very new to two.js and eager to learn. Rendering this with canvas works fine, however it starts to chug at around 200 paths or so, and WebGL can seemingly handle up to tens of thousands of flyers no problem, but not more than 5 paths. Hopefully there's some middle ground?

Here's the full source if you're curious.

```javascript
let two = null;
let group = null;
const numBoids = 200;

let boids = [];
let cohesion = 0.005;
let avoidance = 0.05;
let alignment = 0.05;
let speed = 8;

let background = null;

function setup() {
    two = new Two({ fullscreen:true, autostart: true, type: Two.Types.canvas});
    two.appendTo(document.getElementById("main"));

    background = two.makeRectangle(0, 0, window.innerWidth * 2, window.innerHeight * 2);
    background.fill = "#fafaf7"

    resetBoids();
}

function resetBoids() {
    boids = [];

    for (let i = 0; i < numBoids; i++) {
        const b = new Boid(Math.random() * window.innerWidth, Math.random() * window.innerHeight);
        const p = b.getHeadPoints();
        b.drawing = two.makePath(p[0].x, p[0].y, p[1].x, p[1].y, p[2].x, p[2].y, p[3].x, p[3].y, false);
        b.drawing.fill = '#bbb';
        b.drawing.stroke = '#bbb';

        const trail = [];
        for (let i = 0; i < 10; i++) {
            trail.push(new Two.Anchor(0, 0, 0, 0, 0, 0));
        }

        b.trailDrawing = two.makePath(trail, false, true);
        b.trailDrawing.stroke = '#bbb';
        b.trailDrawing.noFill();

        boids.push(b);
    }
}

function loop(frameCount) {
    for (const boid of boids) {


        boid.setAcceleration(boids);
        boid.drawing.translation.set(boid.x, boid.y);
        boid.drawing.rotation = Math.atan2(boid.vy, boid.vx) + Math.PI / 2;


        // Update path by adding on another anchor and removing the first in the list
        const collection = boid.trailDrawing.vertices;
        collection.push(new Two.Anchor(boid.x, boid.y, boid.x, boid.y, boid.x, boid.y))
        collection.shift();


        boid.update();
    }
}

setup();
two.bind('update', loop)

class Boid {

    x;
    y;
    vx;
    vy;

    drawing;
    trail;
    trailDrawing;

    constructor(x, y) {
        this.x = x;
        this.y = y;
        this.vx = (Math.random() - 0.5) * 5;
        this.vy = (Math.random() - 0.5) * 5;
        this.trail = [];
    }

    update() {
        this.x += this.vx;
        this.y += this.vy;
        //this.updateTrail();
    }

    // updateTrail() {
    //     this.trail.push(new Two.Anchor(this.x, this.y, this.x, this.y, this.x, this.y));
    //     if (this.trail.length > 15) {
    //         this.trail.shift();
    //     }
    // }

    getHeadPoints() {
        const v = new Two.Vector(this.vx, this.vy);
        v.normalize();
        v.multiplySelf(10);
        const sharpness = 4;
        const p0 = new Two.Vector(sharpness, sharpness);
        const p1 = new Two.Vector(0, 0);
        const p2 = new Two.Vector(-sharpness, sharpness);
        const p3 = new Two.Vector(0, -10);

        return [p0, p1, p2, p3];
    }

    setAcceleration(boids) {
        let inRange = this.getInRange(boids);
        this.cohesion(inRange);
        this.avoidance(inRange);
        this.alignment(inRange);
        this.maxSpeed();
        this.walls();
    }

    walls() {
        const padding = 50;
        const c = 1;

        if (this.x < padding) {
            this.vx += c;
        }
        if (this.x > innerWidth - padding) {
            this.vx -= c;
        }
        if (this.y < padding) {
            this.vy += c;
        }
        if (this.y > innerHeight - padding) {
            this.vy -= c;
        }
    }

    maxSpeed() {
        const mag = Math.hypot(this.vx, this.vy);
        const vLimit = speed;
        if (mag > vLimit) {
            this.vx = (this.vx / mag) * vLimit;
            this.vy = (this.vy / mag) * vLimit;
        }
    }

    cohesion(boids) {
        const c = cohesion;
        if (boids.length === 0) return;
        let centerX = boids.reduce((acc, cur) => acc + cur.x, 0) / boids.length;
        let centerY = boids.reduce((acc, cur) => acc + cur.y, 0) / boids.length;
        this.vx += (centerX - this.x) * c;
        this.vy += (centerY - this.y) * c;
    }

    alignment(boids) {
        const c = alignment;
        if (boids.length === 0) return;
        let centerX = boids.reduce((acc, cur) => acc + cur.vx, 0) / boids.length;
        let centerY = boids.reduce((acc, cur) => acc + cur.vy, 0) / boids.length;
        this.vx += (centerX - this.vx) * c;
        this.vy += (centerY - this.vy) * c;
    }

    avoidance(boids) {
        const dist = 20;
        const c = avoidance;

        let centerX = 0;
        let centerY = 0;

        for (const boid of boids) {
            if (Boid.distance(this, boid) < dist) {
                centerX += this.x - boid.x;
                centerY += this.y - boid.y;
            }
        }

        this.vx += centerX * c;
        this.vy += centerY * c;
    }

    static distance(b1, b2) {
        return Math.hypot(b1.x - b2.x, b1.y - b2.y);
    }

    getInRange(boids) {
        //TODO edit to account for angle
        let inRange = [];
        for (const boid of boids) {
            if (boid !== this && Math.hypot(boid.x - this.x, boid.y - this.y) < 50) {
                inRange.push(boid);
            }
        }
        return inRange;
    }

}

```

**Comment by jonobr1** [comment]
Thanks for posting and glad you're digging Two.js! Unfortunately, the short answer to your question is: if you want to make tens of thousands of objects that each have changing vertices on the path, then Two.js will have trouble in every renderer type.

Part of this issue is the rendering itself, all the renderers have limits to how many draw calls are invoked. One Path is one draw call. You can get around some of this by consolidating multiple trails into one path via custom commands.

Part of this issue, though, is JavaScript invocations. You're running a lot of JS specific calculations on each frame, so finding ways to either reduce this or offload it to some other resource are ways you can work around these limitations.

---

In general, web developers use WebGL to offload these kinds of JavaScript calculations onto the GPU. Unfortunately, for the moving images you are trying to achieve, there isn't a whole lot in the Two.js library that will enable this at the scale you want. My recommendation would be to get the quality of the animation you want using Two.js and then once you've found a specific aesthetic you like to do a kind of port of those calculations into WebGL yourself.
