### ISSUE TITLE
Feature suggestion: Check if shape is at given screen location

### ISSUE THREAD

**Issue by juxtapus** [jonobr1/two.js#501]
The app that I am building makes significant use of mouse gestures, and it is generally easy to determine whether the user has clicked on a rectangular area. But, there are times when I would like to determine if the user has clicked on something of a more complex shape, such as a curved line. For example, I might want to give the user the ability to click and drag a curved line. But currently, I know of no way to determine whether the mouseEvent was actually on the line.

It would be great if there was a function in Two.JS where it could check for me if the shape/line intersects with a given XY coordinate.

**Comment by jonobr1** [comment]
If you're using the SVG Renderer, you can use the native functionality for hit testing as in this example: https://two.js.org/examples/svg-events.html

It works on arbitrary paths.

**Comment by jonobr1** [comment]
This is also a duplicate of this issue: https://github.com/jonobr1/two.js/issues/306
