### ISSUE TITLE
Drawing Thin Lines

### ISSUE THREAD

**Issue by hscndr** [jonobr1/two.js#513]
Hello, 
I am currently checking out possible 2D JS libraries for a project and must say, that to me, Two.js is by far the most comprehensible, nicest and cleanest library that I have come across.

Only, I am struggeling with drawing very thin lines. I am simply doing `makeLine` and get a pretty thick line as a result. Setting `linewidth=1` does not change anything, only making the black line grey, but the thickness stays. `linewidth=2` gives a line with the same thickness, but in black and as of `linewidth=3` the line gets thicker.
The result that I am aiming for is what the terrain looks like in the "Land on the moon" project.

Is there anything, I am missing ? 

Thanks for any suggestions !!!

**Comment by jonobr1** [comment]
Thanks for checking out Two.js! Depending on the renderer that you're using (SVG, Canvas 2D, or WebGL) the line drawing is slightly different. SVG and Canvas2D render it what is native to the browser's calls. WebGL uses Canvas 2D to draw the bitmap information and then load it into WebGL through textures.

Another thing worth considering to achieve the effect you're going for is the resolution of your screen and the density of pixels. If you have a DPI screen you'll be able to get lines that are thinner that 1px. Conversely if you have a low resolution screen this can make `linewidth=1` yield something more fuzzy. You can control this directly by upping the `ratio` property when instantiating Two.js like so:

```javascript
var two = new Two({
  fullscreen: true,
  autostart: true,
  ratio: 4 // If nothing is given, then the default is whatever matches your screens pixel density
}).appendTo(document.body);
```

Last thing.., in the Canvas 2D rendering environment you can turn antialiasing off. This will not make things blurring and give off the effect that when you diminish the size the color changes. You can set this by changing `smoothing: false` in the same JavaScript object I described above.

Hope this helps gives some context around line renders.

**Comment by hscndr** [comment]
Hello jonobr1,

thank you very much for the quick and thorough answer. Unfortunately, none of your suggestions helped to deal with the problem. I would have given up and booked it under "constraints of my setup", if I had not seen the desired result from other libraries I tested.

Thanks anyway for you help and time !

Greetings,
hscndr

**Comment by jonobr1** [comment]
Mind sharing what other libraries you tested and the results you got?

**Comment by hscndr** [comment]
Sure, no problem. Right now, I am still testing, which library works best for me.
As soon as I have results to share, I will happily come back...

**Comment by jonobr1** [comment]
Awesome, thanks. Could be helpful for others who stumble on this thread. Best of luck
