### ISSUE TITLE
If the points changes for rectangle how to redraw again ?

### ISSUE THREAD

**Issue by ayush11-11** [jonobr1/two.js#515]
I am giving dimension from the UI and applies two way data binding ,If values from UI changes the Rectangle must also change.How this is possible with two.js

**Comment by jonobr1** [comment]
You can change the rectangle's `width`, `height`, `position`, `scale`, and `rotation`. So whatever changes you apply will be automatically updated. 

You can also edit the rectangle's `vertices` property which is an array of points that make up the rectangle. However, if you change those it invalidates the `width` and `height` property, so you won't be able to use those afterwards. If you have a code example online, I'd be able to more accurately help you out.
