### ISSUE TITLE
issue in npm package of two.js

### ISSUE THREAD

**Issue by ayush11-11** [jonobr1/two.js#518]
two.makeArrow() is available in Two.js library but is not available in npm package of Two.js.

**Comment by jonobr1** [comment]
Which nom package are you using?

This one?

```
npm install two.js
```

**Comment by ayush11-11** [comment]
npm install twojs-ts    this one

**Comment by jonobr1** [comment]
That is not under my ownership, please use `npm install two.js`.

**Comment by ayush11-11** [comment]
import * as Two from 'two.js';

 const im=document.getElementById("im");
 
 var two= new Two({
    width: 300,
    height: 500,
    
  }).appendTo(im);

After npm install two.js
I did using above code I am getting issue that ,
"index.js:11 Uncaught TypeError: two_js__WEBPACK_IMPORTED_MODULE_1__ is not a constructor"

I am working on vanilla javascript with webpack .

**Comment by jonobr1** [comment]
You have to import Two.js like so:

`import Two from 'two.js';`
