### ISSUE TITLE
How to implement Pan ? Like with pan and zoom

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#519]
**Describe your question**
I am implementing pan and zoom feature in my drawing editor. I just found out how to implement zoom from one of the issues here. But struggling to implement "pan" feature

Would also love an example(fiddle) demonstrating it.

**Comment by jonobr1** [comment]
Thanks for your question. Here's an example with the pan feature implemented as well: https://codepen.io/jonobr1/pen/PobMKwb

**Comment by meetzaveri** [comment]
@jonobr1 Cool. But I noticed about Zui. It isn't in version `0.7.0-stable.1`. So in which version I can use Zui?

**Comment by meetzaveri** [comment]
And also what is Zui? I didn't find it in documentation

**Comment by jonobr1** [comment]
The version in npm is an ES6 module. So if you're using react or some other module system it should be fine. If you need to use a simple `<script />` with vanilla JavaScript then you'll have to use this new one I just checked into the repository.
