### ISSUE TITLE
How to use ZUI in ES6 environment?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#521]
I imported zui in my react codebase. I have imported it as

`import Zui from 'two.js/extras/zui'`

**Regarding that codepen** - https://codepen.io/jonobr1/pen/PobMKwb

How should I structure my code to use that similar functionalities with ZUI as a module rather than a cdn script?

I have added one line to my codebase  as

`let zui = new  Zui(two.scene, domElement)`

what should I do ahead to match use case of that codepen's example

**Comment by meetzaveri** [comment]
This is the file which I am utilizing - https://github.com/jonobr1/two.js/blob/dev/extras/jsm/zui.js

**Comment by jonobr1** [comment]
It works exactly the same. You just import it instead of adding a script tag.

**Comment by meetzaveri** [comment]
It is showing me error

![chrome-capture - 2021-03-22T150846 615](https://user-images.githubusercontent.com/21293048/111969676-81555680-8b20-11eb-8e93-6627a32b5ff7.jpg)


Here is my code

`      
      
        import Two from 'two.js'

        import Zui from 'two.js/extras/zui'

        const two = new Two({
            fullscreen: true,
            // width: "auto",
        }).appendTo(elem)
        two.update()

     
        addZUI()
        function addZUI() {
            // zuifn()
            let domElement = document.getElementById(two.scene.id)
            let zui = new Two.Zui(two.scene, domElement)

            let mouse = new Two.Vector()
            let touches = {}
            let distance = 0
            zui.addLimits(0.06, 8)

            domElement.addEventListener('mousedown', mousedown, false)
            domElement.addEventListener('mousewheel', mousewheel, false)
            domElement.addEventListener('wheel', mousewheel, false)

            domElement.addEventListener('touchstart', touchstart, false)
            domElement.addEventListener('touchmove', touchmove, false)
            domElement.addEventListener('touchend', touchend, false)
            domElement.addEventListener('touchcancel', touchend, false)

            function mousedown(e) {
                mouse.x = e.clientX
                mouse.y = e.clientY
                window.addEventListener('mousemove', mousemove, false)
                window.addEventListener('mouseup', mouseup, false)
            }

            function mousemove(e) {
                var dx = e.clientX - mouse.x
                var dy = e.clientY - mouse.y
                zui.translateSurface(dx, dy)
                mouse.set(e.clientX, e.clientY)
            }

            function mouseup(e) {
                window.removeEventListener('mousemove', mousemove, false)
                window.removeEventListener('mouseup', mouseup, false)
            }

            function mousewheel(e) {
                var dy = (e.wheelDeltaY || -e.deltaY) / 1000
                zui.zoomBy(dy, e.clientX, e.clientY)
            }

            function touchstart(e) {
                switch (e.touches.length) {
                    case 2:
                        pinchstart(e)
                        break
                    case 1:
                        panstart(e)
                        break
                }
            }

            function touchmove(e) {
                switch (e.touches.length) {
                    case 2:
                        pinchmove(e)
                        break
                    case 1:
                        panmove(e)
                        break
                }
            }

            function touchend(e) {
                touches = {}
                var touch = e.touches[0]
                if (touch) {
                    // Pass through for panning after pinching
                    mouse.x = touch.clientX
                    mouse.y = touch.clientY
                }
            }

            function panstart(e) {
                var touch = e.touches[0]
                mouse.x = touch.clientX
                mouse.y = touch.clientY
            }

            function panmove(e) {
                var touch = e.touches[0]
                var dx = touch.clientX - mouse.x
                var dy = touch.clientY - mouse.y
                zui.translateSurface(dx, dy)
                mouse.set(touch.clientX, touch.clientY)
            }

            function pinchstart(e) {
                for (var i = 0; i < e.touches.length; i++) {
                    var touch = e.touches[i]
                    touches[touch.identifier] = touch
                }
                var a = touches[0]
                var b = touches[1]
                var dx = b.clientX - a.clientX
                var dy = b.clientY - a.clientY
                distance = Math.sqrt(dx * dx + dy * dy)
                mouse.x = dx / 2 + a.clientX
                mouse.y = dy / 2 + a.clientY
            }

            function pinchmove(e) {
                for (var i = 0; i < e.touches.length; i++) {
                    var touch = e.touches[i]
                    touches[touch.identifier] = touch
                }
                var a = touches[0]
                var b = touches[1]
                var dx = b.clientX - a.clientX
                var dy = b.clientY - a.clientY
                var d = Math.sqrt(dx * dx + dy * dy)
                var delta = d - distance
                zui.zoomBy(delta / 250, mouse.x, mouse.y)
                distance = d
            }
        }`

**Comment by jonobr1** [comment]
Try changing `Two.ZUI` to just  `ZUI`. Since your using imports, the object is declared in your import script within the scope of the module and not attached to Two.js's globally accessible namespace.

Hopefully that should be the only change from the example. 🤞

**Comment by meetzaveri** [comment]
@jonobr1  Did accordingly as what you said. Error did dissapeared, but I cannot pan or zoom

**Comment by jonobr1** [comment]
My hunch is that the `domElement` you set should be the renderer's dom element, not the stage. You can access this through `two.renderer.domElement`.

**Comment by meetzaveri** [comment]
That solves my main issue. Thanks for your quick responses.

**Comment by jonobr1** [comment]
Glad to hear. Happy coding!

**Comment by meetzaveri** [comment]
@jonobr1 Also can you include documentation about ZUI in current two.js website? I wanted to take a look at that API and its docs but couldn't find any reference in current two.js website

**Comment by jonobr1** [comment]
Yes, I'll add it to this: https://github.com/jonobr1/two.js/issues/295

**Comment by meetzaveri** [comment]
@jonobr1 What does `zui.translateSurface(dx, dy)` do ?
