### ISSUE TITLE
[Bug] extras/js global reference to Two fails eslint

### ISSUE THREAD

**Issue by jonobr1** [jonobr1/two.js#523]
**Describe the bug**
The linter throws errors on extras/js files because they reference the global object `Two`. This happens even though `.eslintrc` has `Two` declared as a global writable object.

**To Reproduce**
1. Run `npm run lint`.

**Expected behavior**
No errors.

**Screenshots**
<img width="682" alt="Screen Shot 2021-03-21 at 6 24 14 PM" src="https://user-images.githubusercontent.com/220033/111922864-c4f18700-8a72-11eb-98b6-5e385a325c50.png">

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [ ] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)
- [x] One of Two.js's Utility Script

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jonobr1** [comment]
Got any ideas @adroitwhiz on how to alleviate these errors _and_ keep a global reference to Two?

**Comment by adroitwhiz** [comment]
Sorry I didn't see this earlier! ESLint lets you [specify globals](https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals).

**Comment by adroitwhiz** [comment]
Looks like the current `.eslintrc.json` only specifies `Two` as a global in tests:
```
		{
			"files": ["tests/**"],
			"globals": {
				"QUnit": "writable",
				"resemble": "writable",
				"Two": "writable",
				"_": "writable"
			},
			"rules": {
				"no-redeclare": "off"
			}
		}
```

**Comment by jonobr1** [comment]
Oh got it! Easy fix. Thanks!
