### ISSUE TITLE
[Question] "Property '_renderer' does not exist" on add event listener to svg

### ISSUE THREAD

**Issue by satanya-zero** [jonobr1/two.js#524]
**Describe your question**

When I try to add a listener to a rectangle just like what https://two.js.org/examples/svg-events.html did,
the IDE returns a error that `Property '_renderer' does not exist on type 'Rectangle'` (I am using Typescript & React.js)

**Your code (either pasted here, or a link to a hosted example)**
``` typescript
const two = new Two({
     fullscreen: true
 }).appendTo(document.body)

const rect = two.makeRectangle(70, 0, 100, 100);
rect.fill = 'rgba(0, 200, 255, 0.75)';
rect._renderer.elem.addEventListener('click', () => {
     console.log("clicked")
});
```
**Screenshots**
![screenshot](https://user-images.githubusercontent.com/16162768/112447494-57a06780-8d8c-11eb-8bbc-98e8c523a8d6.png)

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

---

If applicable:

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser edge(chromium core)
 - Version 19042

**Additional context**

**Comment by satanya-zero** [comment]
it works with `// @ts-ignore`
seems to be that the @types/two.js is outdated

**Comment by jonobr1** [comment]
I just pushed Typescript declaration types to Two.js yesterday. So, I'll have to publish a new version on npm. But, I think this will error regardless because the documentation (which is what the types are generated from) describes `_renderer` as a private property and as such may throw an error.

**Comment by satanya-zero** [comment]
So, are there other ways to handle click event when using Typescript?

**Comment by jonobr1** [comment]
Short answer not with Two.js. I need to figure out what to do here and I think what I'll do is add a `getRenderer()` method so you can access it.

But, you can still add click events to `two.renderer.domElement`. You'll have to iterate through all the shapes and do a kind of hit test logic. This logic is also something I want to add to Two.

**Comment by satanya-zero** [comment]
Thanks for your answer! it help me a lot!

**Comment by jonobr1** [comment]
Glad it's helpful. You can now access the renderer through `path.renderer`. The Typescript types in the repo and the documentation in the /wiki folder reflect this. I'll update the npm package so that this is more convenient for people.

**Comment by satanya-zero** [comment]
In the latest version, I tried to use ` rect.renderer.elem.addEventListener()` but found that `elem` is undefined.

**Comment by xabr0** [comment]
> But, you can still add click events to `two.renderer.domElement`. You'll have to iterate through all the shapes and do a kind of hit test logic. This logic is also something I want to add to Two.

Hi Jono, any update on the hit test logic with webgl and canvas renderers?

**Comment by jonobr1** [comment]
See this issue @xabr0: https://github.com/jonobr1/two.js/issues/724

**Comment by jonobr1** [comment]
@xabr0, yes that is being tracked here: https://github.com/jonobr1/two.js/issues/306
