### ISSUE TITLE
[Bug] Some methods seem to be missing from the v0.7.3 npm package

### ISSUE THREAD

**Issue by satanya-zero** [jonobr1/two.js#526]
**Describe the bug**
After upgrading to the v0.7.3, I found that the `two.js` was conflicted with the `@types/two.js`, and then I uninstalled the `@types/two.js` and used the 
```typescript
import Two from 'two'
```
, but `two.makeXXX()` or `two.appendTo()` method cannot be found in the `two.module.d.ts`, so these methods can't be used.

**Comment by jonobr1** [comment]
Ah shoot, sounds like the automated Typescript generator doesn't work too well. I'll have to continue to work on this. Thanks for reporting!

**Comment by jonobr1** [comment]
Unfortunately, in order to use [this script](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) it will take significant changes to the codebase. I think it would be better to generate the declaration file ourselves when the script generates the wiki documentation. This too, unfortunately, will take some time to get setup.

**Comment by jonobr1** [comment]
Because of the semantics around how Two.js was originally wrote and how to get types declared properly, this issue relates to [this issue](https://github.com/jonobr1/two.js/issues/509) in that there are number of stylistic changes the codebase could take in order to elegantly solve this issue.

**Comment by jonobr1** [comment]
I found a better library to convert JSDocs documentation into Typescript types. There are likely _a few_ rough edges still, but give the latest version a try: https://www.npmjs.com/package/two.js which is `v0.7.4`.

**Comment by stefnotch** [comment]
I tried installing the latest version but it seems like the types are missing from the npm package?
![image](https://user-images.githubusercontent.com/10220080/115158155-29f9c600-a08d-11eb-9f33-c9a29b58a583.png)

**Comment by jonobr1** [comment]
Sorry for the delay and thanks for sharing this @stefnotch. I'll update the NPM package today with the appropriate updates I just pushed to `dev`.

**Comment by jonobr1** [comment]
@stefnotch, types are now present in the NPM build. If you see issues with the types (which I'm sure there are, because i'm not a Typescript user!) please file a new issue. Thanks!
