### ISSUE TITLE
How to use Two.Command.arc command for path?

### ISSUE THREAD

**Issue by ivanbacher** [jonobr1/two.js#532]
I am trying to replicate this path string:

```
M source.x source.y A dr dr 1 0 1 target.x target.y
```

using the following approach: 

```javascript
...
let points = [
    new Two.Anchor(source.x, source.y, 1, 2, 3, 4, Two.Commands.move),
    new Two.Anchor(target.x, target.y, 5, 6, 7, 8, Two.Commands.arc)
];

points.forEach(p => p.relative = false);

let line = new Two.Path(points);
line.automatic = false;

...
```

This is the result I am getting atm:

```
M 7.018459 -0.297655 A undefined undefined undefined undefined undefined 12.056918 17.555244 
```

So the values for `source.x`, `source.y`, `target.x`, and `target.y` are in the correct "position". However the other values are all undefined. Not quite sure why.

Any Ideas?

**Comment by jonobr1** [comment]
Ah yes, sorry for this issue. When using the arc command, each renderer looks at different properties on a `Two.Anchor`. They are as follows (I believe):

```javascript
var anchor = new Two.Anchor();
anchor.command = Two.Commands.arc;
anchor.rx = 25;               // X Radius in pixels
anchor.ry = 25;               // Y Radius in pixels
anchor.xAxisRotation = 0;     // X Axis Rotation in Radians
anchor.largeArcFlag = 0;      // Radians
anchor.sweepFlag = 0;         // Radians
```

I really need to update the documentation to reflect this. Thanks for bringing it to my attention!

More information on arcs here to reference x axis rotation, large arc flag, and sweep flags: https://www.w3.org/TR/SVG11/paths.html#PathDataEllipticalArcCommands

**Comment by ivanbacher** [comment]
Awesome, thanks.
