### ISSUE TITLE
Local to World Coordinates [Question]

### ISSUE THREAD

**Issue by ivanbacher** [jonobr1/two.js#534]
Apologies if I might have missed this in the documentation. Does two.js have a function to translate world coordinates to local coordinates and the other way round?

E.g.

```javascript
let group = two.makeGroup();
group.translation.set(100, 100);

let circle = two.makeCircle(5,5,5);
group.add(circle);
```

Local `x` and `y` of circle are: `5,5`. World would be `105, 105`;

**Comment by jonobr1** [comment]
There is a function to get the world / local position of the object

```javascript
var rect = circle.getBoundingClientRect();
var x = rect.left + rect.width / 2; // 105
var y = rect.top + rect.height / 2; // 105

rect = circle.getBoundingClientRect(true); // Get local calculation
var x = rect.left + rect.width / 2; // 5
var y = rect.top + rect.height / 2; // 5
```

If there are other use cases though, happy to convert this into a feature request and track. Hope this helps!

**Comment by ivanbacher** [comment]
Awesome! Thanks.

I guess `getBoundingClientRect()` could also return the x and y position of the shape. This would save the user having to calculate it? However, it's simple enough, so not sure how helpful adding that in would actually be.

**Comment by ivanbacher** [comment]
Yeah makes total sense. I also move the origin of the scene to the center of the canvas, similar to the way three.js does it. 

I think the way you showed in the code snippet above is the most flexible.

**Comment by jonobr1** [comment]
Smart!
