### ISSUE TITLE
[Question] is Two made for recognising free-hand paths, too ?

### ISSUE THREAD

**Issue by gg4u** [jonobr1/two.js#535]
I did not know about Two, and looked at the example:
`https://two.js.org/examples/dynamic-vertices.html`

I'd like to know if the library can ease out the process to extract SVG figures from freehand, and if so, possibly introduce to high-level concepts for explaining how it could be done.

As an example, I'd like to draw a "square" and a "line" on top of that, and would like to approximate the freehand pictures as Square and Line (Svg elements) and finally test if the there is an intersection between the two elements.

From what I see in the console, two elements are drawn as `<path>` already, so I thought that being already drawing SVG elements might already something in between of the process to "regularise" the shape (e.g. by extracting coordinates ?) but most of all test if they are overlapping.

Thank you.

<img width="1440" alt="Screen Shot 2021-05-22 at 11 48 34 AM" src="https://user-images.githubusercontent.com/284214/119222305-eebb3e80-baf3-11eb-811b-9d0f22b79d3e.png">

**Comment by jonobr1** [comment]
Thanks for the question. Two.js doesn't currently have the packaged ability to recognize higher order primitive shapes from a list of points or arbitrary paths.

That being said, combining this example to have that detection for certain shapes is certainly possible. I'm in the middle of finishing some freelance work, but will look into putting together an example of how to do at least one of the primitives to give a sense of how it could work. Best of luck with your project.
