### ISSUE TITLE
Inner and outer radius wrong when cloning arc[Bug]

### ISSUE THREAD

**Issue by ivanbacher** [jonobr1/two.js#536]
When cloning an arc shape, inner and outer radius are incorrect. The cloned arc's inner radius is 0 and it's outer radius is the inner radius of the original arc. Please see image

![Screenshot 2021-05-25 at 12 22 39](https://user-images.githubusercontent.com/5493114/119482248-efeaa680-bd53-11eb-890d-86a1a5345f52.png)

Runnable code: https://observablehq.com/@ivanbacher/two-js-arc-clone-bug

**Comment by jonobr1** [comment]
Thanks! Yes, that is incorrect and I pushed a fix on the latest dev branch here: https://github.com/jonobr1/two.js/commit/a32c165469e0d91aa13d803cc7d6c7e9a6c9a942
