### ISSUE TITLE
Nodejs: memory leak while drawing image and returning it in response

### ISSUE THREAD

**Issue by anka-tomasiak** [jonobr1/two.js#538]
I don't know if this behavior is intentional, but I have question about drawing image in node.js.

I have some code which is generating image in loop (for example from the biggest square to the smallest, skipped some logic to show it more clear)

```javascript
function drawSquare(context, colors, threads, colorCount) {
    var x = 400;
    var y = 200;
    var width = 400;
    var height = width;

    for(var i = 1; i <= 400; i++){
        var square = two.makeRectangle(x, y, width, height);
        square.fill = colors[colorRow][colorColumn];
        square.noStroke();
        width--;
        height--;
    }
}
```

and the rest of my code which is creating an image (also simplified)

```javascript
function draw(shape, threads, colors) {
    var canvas = createCanvas(800, 400);
    Two.Utils.shim(canvas, Image);
    var two = new Two({
        width: 800,
        height: 400,
        domElement: canvas
    });

    var colorChangesArray = somefunction();
    var colorCount = colors.length;

     drawSquare(two, colorChangesArray, threads, colorCount);

    two.update();
    return canvas;
}
```
and response

```javascript
exports.get_image = async function (request, response) {
    var used = process.memoryUsage().heapUsed / 1024 / 1024;
    console.log(`controller start: The script uses approximately ${used} MB`);

   drawing.draw(request.params.shape, request.params.threads, request.body).createPNGStream().pipe(response);     
}
```

Everything worked fine (locally) until deployed on heroku - there I have limited resources so I've got error:

**FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory**

So after debugging it localy I've noticed that used memory increases significantly with each request:

![196160157_978455999360022_6399343626252546384_n](https://user-images.githubusercontent.com/4233851/120901807-34701f00-c63d-11eb-89a8-d3dffd160021.png)

Checking it with chrome://inspect shows, that there are some problems with two library:

![196586144_195628458988436_246024224777761196_n](https://user-images.githubusercontent.com/4233851/120901854-84e77c80-c63d-11eb-94d5-8785b4c5b3ef.png)

**My question: So it seems that all created shapes are stored in memory - forever (or until server restart)? It this some bug or  correct behavior?**

My solutions is added  `Two.Instances = []; ` after `two.update();` in draw function.

**Environment (please select one):**
- Node.js

**Comment by jonobr1** [comment]
Thanks for the question @anka-tomasiak. Yes, when objects are created and added to an instance of `Two`, which is the case if you use the `Two.makeRectangle` method, then the objects persist for the duration of the server's life. By rearranging your code a bit, you _should_ be able to manage this a bit easier. The pseudocode is:

```javascript

// Create an instance / canvas of two when the session starts
var canvas = createCanvas(800, 400);
Two.Utils.shim(canvas, Image);

var two = new Two({
  width: 800,
  height: 400,
  domElement: canvas
});

exports.get_image = async function (request, response) {

  // Draw your rectangles
  var rect = two.makeRectangle(two.width / 2, two.height / 2, 50, 50);
  // Render them with Two.js
  two.update();
  // Remove any Two.js objects, but no need to delete the core
  // instance / canvas of `two`.
  two.remove(rect);

  // Create png stream and export out image

};
```

Hope this helps!

**Comment by anka-tomasiak** [comment]
@jonobr1  thanks for quick response! I'm drawing my images in some specific way - because I need to draw my shapes line by line (this is some crochets shawls and similar projects simulation and each 1px line shows 1 thread, threads are in different colors)
There is an example image:
![image](https://user-images.githubusercontent.com/4233851/120935212-f688fe80-c701-11eb-8666-73eedeb20ae2.png)

So I need for example 400 rectangles or 400 lines or 400 circles and so on. 
I cannot use update every each `two.makeRectangle` because this significantly affects the waiting time for a response: from **195 ms** with one `two.update()` after drawing all required shapes to **11.47 s** with `two.update()` after each rectagle.
So I think that maybe I should add all created rectangles to array and later call `two.remove()`  on this array after single `two.update()`

**Comment by jonobr1** [comment]
Thanks for sharing @anka-tomasiak, looks very cool! In this scenario you can use `overdraw` mode. In this mode you can have one rectangle draw multiple times like so:

```javascript
// Create an instance / canvas of two when the session starts
var canvas = createCanvas(800, 400);
Two.Utils.shim(canvas, Image);

var two = new Two({
  width: 800,
  height: 400,
  overdraw: true,
  domElement: canvas
});

var rect = two.makeRectangle(two.width / 2, two.height / 2, 50, 50);

exports.get_image = async function (request, response) {

  var renderer = two.renderer;
  var ctx = renderer.ctx;

  // Clear the canvas of bitmap content
  // from potentially an earlier request
  ctx.clearRect(0, 0, renderer.width, renderer.height);

  for (var i = 0; i < 100; i++) {
    // Style your rectangle
    rect.scale = 2 * (i + 1) / 100;
    rect.stroke = 'black';
    rect.noFill();
    rect.opacity = Math.random();
    // Render the rectangle to the canvas
    two.update();
  }

  // Create png stream and export out image

};
```

This will **drastically** reduce the memory footprint.

**Comment by anka-tomasiak** [comment]
Thank you! I'm going to mix all these solutions to get the best performance and memory usage. Your library is great. At the beginning I was using just canvas (client side) but I had a lot of problems with that one. Now (after moved drawing code to server) despite this one problem that I can easily deal with, it works very well. Thank you for your time and work. 😄

**Comment by jonobr1** [comment]
Glad to hear! Happy coding
