### ISSUE TITLE
[Question] How to set svg element properties like text-anchor?

### ISSUE THREAD

**Issue by misterlocations** [jonobr1/two.js#539]
Hi there. Thanks for the work on the library! I'm using it to make a 2D game.

Question - If there's a DOM element property that's not represented in the codebase, such as the "text-anchor" property on <text>, what's the way of going about changing that within the Javascript?

Would I have to somehow set an Id and retrieve the <text> node manually? Is there a better way to do it? Or is there a way to adjust text-anchor within the Two.Text code that I haven't found?

Thanks.

**Comment by jonobr1** [comment]
Very cool! Thanks for asking @misterlocations. You can do the following if you're using the latest version on npm or the dev branch directly from the repo:

```javascript
var text = new Two.Text('hello world', two.width / 2, two.height / 2);
two.add(text);
two.update(); // This happens automatically if you have `autostart: true` when you instantiate Two.js
// Once the object has been added to an instance
// and it has rendered at least once, then the corresponding SVG element
// will be generated and can be accessed here:
var svg = text.renderer.elem;
```

**Comment by misterlocations** [comment]
@jonobr1 This worked perfectly! I forgot about the direct element access, even though I had set up event listeners at one point. 

Thanks much!

**Comment by jonobr1** [comment]
Glad to hear that helps! Please share what you're working on when you feel ready :) Would love to check it out.
