### ISSUE TITLE
[Question] How to get relative coordinates in zoomed plane?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#540]
**Describe your question**
I want to pan(drag) my element in zoomed space where the actual cursor/pointer is

**Problem**
It works fine when zoom is 0. I can drag element where the mouse pointer is. But I am facing issues for dragging when zoom is less than 0. vice versa for greather than 0. The element is not in sync with mouse pointer

**Screenshots**
You would get correct explanation of what I am facing via this small 13 second video. 

Here's the link - https://www.loom.com/share/12b9bd256b3845fcb024baba4ff2be56

---

**Comment by meetzaveri** [comment]
For pan & zoom, I am using code reference from - https://github.com/jonobr1/two.js/issues/519

**Comment by jonobr1** [comment]
Not being able to see any code makes it pretty hard to understand why the video is responding in the way that it is. But, off the top of my head and based on your other question [here](https://github.com/jonobr1/two.js/issues/521#issuecomment-855451440), once you use ZUI you shouldn't use `translation` or `position`, but instead use `zui.translateSurface` to add translation / panning movement to the matrix.

**Comment by meetzaveri** [comment]
Oh. Can you provide a codepen example of "element being dragged(can be panned) in zoomed space" ?

**Comment by meetzaveri** [comment]
@jonobr1 Also here is my seperate code for dragging. This is seperate one from zoom util function


```js
 	function handleDrag(twoJSInstance, group) {
		let domElement = group._renderer.elem
		let zui = new ZUI(group, domElement)
		let mouse = new Two.Vector(group.translation.x, group.translation.y)
		twoJSInstance.update()
		domElement.addEventListener('mousedown', mousedown, false)

		function mousedown(e) {
			mouse.x = e.clientX
			mouse.y = e.clientY
			window.addEventListener('mousemove', mousemove, false)
			window.addEventListener('mouseup', mouseup, false)
		}

		function mousemove(e) {
			let dx = e.clientX - mouse.x
			let dy = e.clientY - mouse.y

			zui.translateSurface(dx, dy)
			mouse.set(e.clientX, e.clientY)
			group.translation.set(e.clientX, e.clientY)

			twoJSInstance.update()
		}

		function mouseup(e) {
			window.removeEventListener('mousemove', mousemove, false)
			window.removeEventListener('mouseup', mouseup, false)
			twoJSInstance.update()
		}

		// function mousewheel(e) {
		//     let dy = (e.wheelDeltaY || -e.deltaY) / 1000
		//     zui.zoomBy(dy, e.clientX, e.clientY)
		//     two.update()
		// }

		return {
			mousemove: mousemove,
			mouseup: mouseup,
		}
	}

```

**Comment by jonobr1** [comment]
Updated the same codepen to reflect how you would translate one object: https://codepen.io/jonobr1/full/PobMKwb
