### ISSUE TITLE
[Enhancement] Add return type for vector functions

### ISSUE THREAD

**Issue by supjs** [jonobr1/two.js#542]
**Is your feature request related to a problem? Please describe.**
I am using PhpStorm and the automatically generated typings for the vector all use return type `void`.

Examples:
```ts
clone(): void;
add(v: Two.Vector): void;
sub(v: Two.Vector): void;
```

**Describe the solution you'd like**
Add a return type to the documentation so that it returns `Two.Vector` instead.

See functions like `makeRectangle`:
```ts
/**
 * @name Two#makeRectangle
 * @function
 * @param {Number} x
 * @param {Number} y
 * @param {Number} width
 * @param {Number} height
 * @returns {Two.Rectangle}
 * @description Creates a Two.js rectangle and adds it to the scene.
 */
```

**Comment by jonobr1** [comment]
Thanks for posting this and sorry for the delayed response. I'll track this on the `es6` features branch here: https://github.com/jonobr1/two.js/tree/es6

**Comment by jonobr1** [comment]
I haven't tested this, but it looks like phpStorm can infer types from imported packages. Two.js's latest version has these included.
