### ISSUE TITLE
I want to save the 2-D image in Database and then send it to pdf .How can I retrieve that svg?

### ISSUE THREAD

**Issue by ayush11-11** [jonobr1/two.js#543]
**Describe your question**
In my  use case I need to save 2-D image in Database and then attach it into the pdf
**Your code (either pasted here, or a link to a hosted example)**
<svg version="1.1" width="360" height="960" style="overflow: hidden;"><defs></defs>

<g id="two-0" transform="matrix(1 0 0 1 0 0)" opacity="1"><path transform="matrix(1 0 0 1 180 478.75)" d="M -89.5335 -238.125 L 89.5335 -238.125 L 89.5335 238.125 L -89.5335 238.125 Z " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-1"></path><path transform="matrix(1 0 0 1 0 0)" d="M 80 240 L 80 720 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-2"></path><path transform="matrix(1 0 0 1 0 0)" d="M 80 240 L 80 720 L 77.878679 717.878679 M 80 720 L 82.12132 717.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-3"></path><path transform="matrix(1 0 0 1 0 0)" d="M 80 720 L 80 240 L 82.12132 242.12132 M 80 240 L 77.878679 242.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-4"></path><path transform="matrix(1 0 0 1 0 0)" d="M 90 730 L 270 730 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-5"></path><path transform="matrix(1 0 0 1 0 0)" d="M 90 730 L 270 730 L 267.878679 732.12132 M 270 730 L 267.878679 727.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-6"></path><path transform="matrix(1 0 0 1 0 0)" d="M 270 730 L 90 730 L 92.12132 727.878679 M 90 730 L 92.12132 732.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-7"></path><path transform="matrix(1 0 0 1 179.805694 395)" d="M -24.8812 -25 L 24.8812 -25 L 24.8812 25 L -24.8812 25 Z " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-8"></path><path transform="matrix(1 0 0 1 179.805694 395)" d="M -20.8812 -21 L 20.8812 -21 L 20.8812 21 L -20.8812 21 Z " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-9"></path><path transform="matrix(1 0 0 1 0 0)" d="M 158.9245 374 L 154.9245 370 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-10"></path><path transform="matrix(1 0 0 1 0 0)" d="M 158.9245 416 L 154.9245 420 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-11"></path><path transform="matrix(1 0 0 1 0 0)" d="M 200.6869 374 L 204.6869 370 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-12"></path><path transform="matrix(1 0 0 1 0 0)" d="M 196.6869 416 L 204.6869 420 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-13"></path><path transform="matrix(1 0 0 1 0 0)" d="M 154.9245 180 L 154.9245 365 " fill="#fff" stroke="#000" stroke-width="0.5" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-14"></path><path transform="matrix(1 0 0 1 0 0)" d="M 204.6869 180 L 204.6869 365 " fill="#fff" stroke="#000" stroke-width="0.5" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-15"></path><path transform="matrix(1 0 0 1 0 0)" d="M 209.6869 370 L 330 370 " fill="#fff" stroke="#000" stroke-width="0.5" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-16"></path><path transform="matrix(1 0 0 1 0 0)" d="M 209.6869 420 L 330 420 " fill="#fff" stroke="#000" stroke-width="0.5" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-17"></path><text transform="matrix(1 0 0 1 180 750)" font-family="sans-serif" font-size="13" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-18">36.1719</text><text transform="matrix(1 0 0 1 180 780)" font-family="sans-serif" font-size="13" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-19">Door Width ( NOMINAL )</text><text transform="matrix(1 0 0 1 60 480)" font-family="sans-serif" font-size="13" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-20">96</text><text transform="matrix(-0.000001 -1 1 -0.000001 30 480)" font-family="sans-serif" font-size="13" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-21">Door Height ( NOMINAL )</text><path transform="matrix(1 0 0 1 0 0)" d="M 90 230 L 154.9245 230 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-22"></path><path transform="matrix(1 0 0 1 0 0)" d="M 90 230 L 154.9245 230 L 152.803179 232.12132 M 154.9245 230 L 152.803179 227.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-23"></path><path transform="matrix(1 0 0 1 0 0)" d="M 154.9245 230 L 90 230 L 92.12132 227.878679 M 90 230 L 92.12132 232.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-24"></path><text transform="matrix(1 0 0 1 122.462249 210)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-25">13.0469</text><text transform="matrix(1 0 0 1 122.462249 180)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-26">H3</text><path transform="matrix(1 0 0 1 0 0)" d="M 154.9245 230 L 204.6869 230 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-27"></path><path transform="matrix(1 0 0 1 0 0)" d="M 154.9245 230 L 204.6869 230 L 202.565579 232.12132 M 204.6869 230 L 202.565579 227.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-28"></path><path transform="matrix(1 0 0 1 0 0)" d="M 204.6869 230 L 154.9245 230 L 157.04582 227.878679 M 154.9245 230 L 157.04582 232.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-29"></path><text transform="matrix(1 0 0 1 179.805694 210)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-30">10</text><text transform="matrix(1 0 0 1 179.805694 180)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-31">H2</text><path transform="matrix(1 0 0 1 0 0)" d="M 204.6869 230 L 270 230 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-32"></path><path transform="matrix(1 0 0 1 0 0)" d="M 204.6869 230 L 270 230 L 267.878679 232.12132 M 270 230 L 267.878679 227.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-33"></path><path transform="matrix(1 0 0 1 0 0)" d="M 270 230 L 204.6869 230 L 206.80822 227.878679 M 204.6869 230 L 206.80822 232.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-34"></path><text transform="matrix(1 0 0 1 237.343444 210)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-35">13.125</text><text transform="matrix(1 0 0 1 237.343444 180)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-36">H1</text><path transform="matrix(1 0 0 1 0 0)" d="M 280 240 L 280 370 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-37"></path><path transform="matrix(1 0 0 1 0 0)" d="M 280 240 L 280 370 L 277.878679 367.878679 M 280 370 L 282.12132 367.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-38"></path><path transform="matrix(1 0 0 1 0 0)" d="M 280 370 L 280 240 L 282.12132 242.12132 M 280 240 L 277.878679 242.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-39"></path><text transform="matrix(1 0 0 1 300 305)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-40">26</text><text transform="matrix(0 1 -1 0 330 305)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-41">V1</text><path transform="matrix(1 0 0 1 0 0)" d="M 280 370 L 280 420 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-42"></path><path transform="matrix(1 0 0 1 0 0)" d="M 280 370 L 280 420 L 277.878679 417.878679 M 280 420 L 282.12132 417.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-43"></path><path transform="matrix(1 0 0 1 0 0)" d="M 280 420 L 280 370 L 282.12132 372.12132 M 280 370 L 277.878679 372.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-44"></path><text transform="matrix(1 0 0 1 300 395)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-45">10</text><text transform="matrix(0 1 -1 0 330 395)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-46">V2</text><path transform="matrix(1 0 0 1 0 0)" d="M 280 420 L 280 720 " fill="#fff" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" id="two-47"></path><path transform="matrix(1 0 0 1 0 0)" d="M 280 420 L 280 720 L 277.878679 717.878679 M 280 720 L 282.12132 717.878679 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-48"></path><path transform="matrix(1 0 0 1 0 0)" d="M 280 720 L 280 420 L 282.12132 422.12132 M 280 420 L 277.878679 422.12132 " fill="transparent" stroke="#000" stroke-width="1" stroke-opacity="1" fill-opacity="1" visibility="visible" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="4" id="two-49"></path><text transform="matrix(1 0 0 1 300 570)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="500" text-decoration="none" fill="#cc0000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-50">60</text><text transform="matrix(0 1 -1 0 330 570)" font-family="sans-serif" font-size="11" line-height="17" text-anchor="middle" dominant-baseline="middle" alignment-baseline="middle" font-style="normal" font-weight="bolder" text-decoration="none" fill="#000" stroke="transparent" stroke-width="1" opacity="1" class="" visibility="visible" id="two-51">V3</text></g></svg>
**Screenshots**
![image](https://user-images.githubusercontent.com/43935806/122753450-ea7b7000-d2af-11eb-9820-5f4dbce34021.png)

****In the above code I just wanted the image started from the <g> tag.
could you please help me how to do that or Two.js have anything to do that?****

**Comment by jonobr1** [comment]
If you use the Canvas Renderer you can save out an image in JavaScript like so:

```javascript
var two = new Two({
  type: Two.Types.canvas
});
// Draw something to the canvas
var imageData = two.renderer.domElement.toDataURL();
// imageData is a string which represents a PNG you can post to your server
```

**Comment by joex92** [comment]
> If you use the Canvas Renderer you can save out an image in JavaScript like so:
> 
> ```js
> var two = new Two({
>   type: Two.Types.canvas
> });
> // Draw something to the canvas
> var imageData = two.renderer.domElement.toDataURL();
> // imageData is a string which represents a PNG you can post to your server
> ```

but is there a way to, for example, convert a SVG render to canvas just to download it as an image? 
or how do I create another Two canvas from a Two SVG (like duplicating it to canvas type)? so that way I may be able to get the image out of it...

**Comment by jonobr1** [comment]
There are lots of ways to create a bitmap image from an SVG file. In theory you should be able to simply add your objects to the new instance:

```javascript
var twoSvg = new Two();
// Add your objects
var group = two.makeGroup();
// then on save
var twoCanvas = new Two({ type: Two.Types.canvas });
twoCanvas.add(group);
var imageData = twoCanvas.renderer.domElement.toDataURL();
```

You could also `interpret` the SVG directly in a new instance like so:

```javascript
var two = new Two({ type: Two.Types.canvas });
two.interpret(document.body.querySelector('svg'));
var imageData = two.renderer.domElement.toDataURL();
```

Probably some other ways I'm not even thinking of as well using `<img />`.

**Comment by joex92** [comment]
> There are lots of ways to create a bitmap image from an SVG file. In theory you should be able to simply add your objects to the new instance:
> 
> ```js
> var twoSvg = new Two();
> // Add your objects
> var group = two.makeGroup();
> // then on save
> var twoCanvas = new Two({ type: Two.Types.canvas });
> twoCanvas.add(group);
> twoCanvas.update();
> var imageData = twoCanvas.renderer.domElement.toDataURL();
> ```
> 
> You could also `interpret` the SVG directly in a new instance like so:
> 
> ```js
> var two = new Two({ type: Two.Types.canvas });
> two.interpret(twoSvg.renderer.domElement);
> two.update();
> var imageData = two.renderer.domElement.toDataURL();
> ```
> 
> Probably some other ways I'm not even thinking of as well using `<img />`.

oh, that second option is better for me... 
but wouldn't the 2 `Two` instances shown on the page?
I would be using the 2nd one just for getting a "snapshot" of the SVG instance...
also, when doing this: 
```js
two.interpret(twoSvg.renderer.domElement);
two.update();
```
wouldn't the second instance would be loaded using more web resources?

**Comment by jonobr1** [comment]
It only shows up on the page if you add it to the page 😏 through `two.appendTo();` or directly adding the element `two.renderer.domElement` to your document. Otherwise it'll just sit in JS memory.

It certainly will take resources depending on the size of your scene. So be careful about the references you keep to the variables and garbage collection (if this happens more than once on a user's session).

**Comment by joex92** [comment]
> It only shows up on the page if you add it to the page 😏 through `two.appendTo();` or directly adding the element `two.renderer.domElement` to your document. Otherwise it'll just sit in JS memory.
> 
> It certainly will take resources depending on the size of your scene. So be careful about the references you keep to the variables and garbage collection (if this happens more than once on a user's session).

oh ok... noted... so, taking the previous example, would using 'clear()' method on the "snapshot" instance free some js memory after downloading the image?

**Comment by jonobr1** [comment]
You'd want to remove everything like so:

```javascript
group.remove(); // remove itself from scene
two.release(group); // remove all event listeners
```

**Comment by joex92** [comment]
> You'd want to remove everything like so:
> 
> ```js
> group.remove(); // remove itself from scene
> two.release(group); // remove all event listeners
> ```

would `two.release()` remove everything? even elements that are not in groups?

**Comment by jonobr1** [comment]
No, `two.release` goes through all objects passed as arguments and removes event listeners. Though it would be easy (albeit perhaps dangerous) to make it go through everything and remove all listeners.

**Comment by meetzaveri** [comment]
@jonobr1 `two.release` is not available in version of `v0.7.1`. Can I know in which version it is available?

**Comment by jonobr1** [comment]
Before `two.release` existed there was `Two.release`. you should be able to use that in 0.7.1

**Comment by jonobr1** [comment]
Closing question due to inactivity.
