### ISSUE TITLE
Path and Curve don't have a fill and only a stroke?

### ISSUE THREAD

**Issue by strich** [jonobr1/two.js#549]
It seems Paths and Curves are made up only of stroke components? The documentation is unclear and trying to create one that has a fill color and a stroke outline color fails.
I initially spent some time trying to change the color of a path assuming the fill property was the correct one given that that is how the other shapes work.

**Comment by jonobr1** [comment]
Hmm, do you have an example that you can share the elaborate on this issue better? Curves are paths with a boolean set to auto calculate the bezier handles for you. Stroke and fill should work and look something like this:
```javascript
path.stroke = 'red'; // Any CSS string value like a hex or rgb / rgba works
path.fill = 'blue';  // Again any CSS string value works here
path.curved = true; // This makes it a curve instead of straight lines
```

**Comment by strich** [comment]
Code:
```
    var path = two.current.makePath(200, 200, 250, 280, true);
    path.fill = 'blue';
    path.stroke = 'red';
    path.cap = 'round';
    path.linewidth = 30;
    path.curve = true;
```
![image](https://user-images.githubusercontent.com/987896/128495390-8a1ef01d-1db3-4553-b8ed-96e3b3cb9028.png)

If I comment out the stroke color it will go black. The fill color seems to be never used.

**Comment by jonobr1** [comment]
That's because your path only has 2 points. You need to have at least 3 points to fill the hull of a path.

**Comment by strich** [comment]
Added another point:
![image](https://user-images.githubusercontent.com/987896/128514317-acd613e8-641c-462a-ae60-16416ffedf23.png)

**Comment by strich** [comment]
Hang on. Ah. I see. A Path is NOT what I thought it was. Or rather, the way it works is not as I thought. My goal here has been to draw a line, which in Two.js is a Curve it seems.

None the less: It does not appear that a Curve can contain a filled color as you seem to draw it exclusively with a stroke?

**Comment by strich** [comment]
Here is an example of what I was trying to accomplish:
![image](https://user-images.githubusercontent.com/987896/128521947-d31c8d3f-f9eb-4679-8677-e46566443d71.png)

`var path = two.current.makeCurve(200, 200, 250, 280, 250, 350, true);
    path.stroke = 'red';
    path.cap = 'round';
    path.linewidth = 30;
    path.curve = true;
    path.noFill();
    var path2 = two.current.makeCurve(200, 200, 250, 280, 250, 350, true);
    path2.stroke = 'blue';
    path2.cap = 'round';
    path2.linewidth = 20;
    path2.curve = true;
    path2.noFill();`

**Comment by jonobr1** [comment]
Looks cool! Also, `path.curve` isn't a property. `makeCurve` and `makePath` create the same `Two.Path` object with one difference the `path.curved` with a "**d**" at the end is set to `true` for the curve. Nice work!

**Comment by strich** [comment]
Weird I wonder why it didn't create any error calling `curve`. Anyway thanks - If you do have any time I could imagine this issue could result in some additional documentation on the website. However I think I'll close this one for now.

**Comment by jonobr1** [comment]
Noted, thanks!
