### ISSUE TITLE
two.js line 8657 items[i].bind is not a function

### ISSUE THREAD

**Issue by danchallis** [jonobr1/two.js#557]
Full error (same in Firefox and Chrome both current versions) also occurs in the current two.min.js version...

two.js:8657 Uncaught TypeError: items[i].bind is not a function
    at Two.Path.BindVertices (two.js:8657)
    at Two.Path.set [as vertices] (two.js:8875)
    at new Two.Path (two.js:8582)
    at Two.root.Two.makeCurve (two.js:2813)
    at Element.<anonymous> ((index):408)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at Object.success ((index):107)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)

My calling code...

				// b1 is an HTML Collection no direct .forEach method 
																
				var b1 = $(this).find('drawing').find('bezier').find('approximation').find('line');
								
				var args = new Array();
									
				Array.from(b1).forEach(element => 
					{
					console.log(element);
					var pt = $(element).attr("pt1").split(',');
					var anchor = new Two.Anchor(pt[0] / sf, pt[1] / sf);
					args.push(anchor);
					});
				
				args.push(true);
				
                                var curveSegment = two.makeCurve(args);

                                curveSegment.id = $(this).attr("id");
		                curveSegment.linewidth = 10;
                                curveSegment.scale = 1;
                                curveSegment.stroke = 'blue';
                                curveSegment.opacity = 0.75;

                                two.update();

**Comment by danchallis** [comment]
Found my error, it's adding that last true to args, if you call it as 

two.makeCurve(args, true); 

it's fine - so this is just an FYI.

**Comment by jonobr1** [comment]
Glad you were able to solve your issue. Just curious, how many `Two.Anchor`s ended up being added to the array you passed to `two.makeCurve`?

In general, you shouldn't _have_ to pass `true` as the final parameter, so this could be an error on the Two.js side.

**Comment by danchallis** [comment]
Jono,

Wow - that was quick - thanks for the super support - I really appreciate
the library.  As for the Anchor count, it's not many - this is the original
XML I'm reading...

<approximation>
<line width="0.9cm" pt1="4029,4892" pt2="3996,4924"/>
<line width="0.9cm" pt1="3996,4924" pt2="3960,4952"/>
<line width="0.9cm" pt1="3960,4952" pt2="3922,4978"/>
<line width="0.9cm" pt1="3922,4978" pt2="3881,5001"/>
<line width="0.9cm" pt1="3881,5001" pt2="3838,5019"/>
<line width="0.9cm" pt1="3838,5019" pt2="3793,5033"/>
<line width="0.9cm" pt1="3793,5033" pt2="3746,5041"/>
<line width="0.9cm" pt1="3746,5041" pt2="3696,5045"/>
</approximation>

So just eight Anchor points (nine if you count the very last pt2 which is
the end point).  Hope this helps.

Regards, Dan
