### ISSUE TITLE
two.load() creates multiple groups

### ISSUE THREAD

**Issue by Ra1nko** [jonobr1/two.js#558]
Hello there!

Found out that two.load() creates separate group for each element in one image and adds them to scene.

Sandbox with example: https://codesandbox.io/s/staging-wood-3kg6g?file=/src/App.js

I expect that exactly one object will be added when i use two.load

Image for reference:
![image](https://user-images.githubusercontent.com/25159887/133474321-8cfb5df8-147b-42dc-a016-d465d3414856.png)

**Environment (please select one):**
- [?] Code executes in browser (e.g: using script tag to load library)
- [✔️ ] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [?] Running headless (usually Node.js)

 - OS: Mac
 - Browser: Chrome
 - Version: 93.0.4577.63

two.js version: 0.7.8

**Comment by jonobr1** [comment]
Thanks again for posting this issue. The latest dev branch has this resolved ([see this commit](https://github.com/jonobr1/two.js/commit/1d44e6300a0b717f62a87946f55a8ad7493839cf)). In the case of your example, the icon imports at a more consistent scale to the SVG written.
