### ISSUE TITLE
two.js projects - Analog clock

### ISSUE THREAD

**Issue by putilatex** [jonobr1/two.js#559]
where is the code for the clock ? the download button just leads to an error !
disappointing to say the least :-(

**Comment by jonobr1** [comment]
You'll have to ask @mnmly. That's his project 😺

**Comment by mnmly** [comment]
Oi, Hi @putilatex. I wrote the screensaver when swift was first introduced and wanted to learn how to write an App in the language. And I'm not sure if I have the codebase somewhere, but will try to find it and ping here if I can!

**Comment by putilatex** [comment]
Great ! 
I would like to use the clock and convert it to a 24 hour clock which will be the basis of an astronomical clock like the one 
in the Markt Platz in Prague, it's called the Orloj.

I also made a live Orrery in two.js and put it on codepen.io     https://codepen.io/seanbalfour/pen/qBjEaYz
it's not one of those silly ones that just rotate and do nothing else, this one displays the current heliocentric positions of the planets
in our solar system.
live version here: https://skynetweather.com/html/weather34/index.php
just click on the orrery link to see the current positions
Positions generated using python-ephem and the two.js running inside a php module
I really like two.js very clean and sharp graphics much better than canvas.js ! :-)

**Comment by jonobr1** [comment]
FYI: I added a watch face sample to the Two.js examples: https://two.js.org/examples/#watch-face

Maybe it's useful for your needs.

**Comment by jonobr1** [comment]
Glad you're able to get the clock working. I'm not sure what your second statement is about though? What's the issue with `Two.ArcSegment`?
