### ISSUE TITLE
Clipping masks

### ISSUE THREAD

**Issue by araid** [jonobr1/two.js#56]
I just got started with this library and found that it doesn't allow clipping masks, a very handy feature in vector graphics. 

I basically wanted to ask if there's any workaround for that, and suggest it as a future enhancement.

Thanks for the good work!

**Comment by nlucis** [comment]
Just an FYI: The current version of this is doing the opposite of a clipping mask at the moment.

**Comment by jonobr1** [comment]
@nlucis, You mean that you'd expect it to work like this:

```javascript
var two = new Two({
  autostart: true,
  width: 200,
  height: 200
}).appendTo(document.body);

var rect = two.makeRectangle(100, 100, 100, 100);
var circle = two.makeCircle(100, 100, 40);
rect.linewidth = 10;
rect.fill = 'orange';
circle.noStroke().fill = 'blue';

// Inverse relationship
circle.mask = scene;

two.bind('update', function(frameCount) {
  circle.translation.x = 50 * Math.sin(frameCount / 60) + 100;
});
```

???

As demonstrated in [this example](https://codepen.io/jonobr1/pen/abyRyoY), the current version seems to work like how this thread describes.
