### ISSUE TITLE
*API expired when trying to donate 

### ISSUE THREAD

**Issue by mientje** [jonobr1/two.js#560]
**API expired when trying to donate*

I tried to give you 25 dollars today but I have not succeed. I see this EM:

**It says expired API provided
  px_CX ******** 5eM 

I work with ubuntu 2020 in firefox but it doesn't work in google chrome either. If it's my card, sorry about the bother, but I've donated in US dollars before and never had any problem. 
**
I'm enjoying two.js very much.

**Comment by jonobr1** [comment]
That's really sweet. Thank you for trying! Stripe changed their API so this is broken... Putting it on the list to fix!

**Comment by jonobr1** [comment]
Not using Stripe anymore and using Github's own sponsors ability. Thanks again for reporting! You can find that information here: https://github.com/sponsors/jonobr1
