### ISSUE TITLE
Support for holes in polygons

### ISSUE THREAD

**Issue by ghost** [jonobr1/two.js#57]
I am starting to learn two.js but have not yet figured out how to create holes in polygons, is this supported? 

It would be great to see a feature similar to the SVG path 'fill-rule' property exposed in two.js: http://www.w3.org/TR/SVG/images/painting/fillrule-nonzero.svg.

**Comment by chrisboustead** [comment]
I know this is very old, but I came across same problem and realized the answer/fiddle is deprecated.  Instead of a Polygon, the method to do this is now creating two (or more) closed sets of anchors in a Path.

http://jsfiddle.net/vtbqsmd1/1/

**Comment by jonobr1** [comment]
Thanks for updating with a working fiddle!

**Comment by chrisboustead** [comment]
Not to open this back up, but as I chased down the code to create a circle in reverse, realized it would be fantastic (and not too involved for some shaped) if an additional flag could be provided to the API for built in shapes to reverse the path direction.  Circle as a simple example, a boolean which would control whether theta is positive or negative could be added here:

https://github.com/jonobr1/two.js/blob/16b1c06e044dc35e7b3e1a9355c13a116885b233/src/shapes/circle.js#L53

So one could do:
```
const outerCircle = new Two.Circle(50, 50, 50);
const hole = new Two.Circle(50, 50, 20, true);
const donut = two.makePath([...outerCircle.vertices, ...hole.vertices], true, true, true);
```
Just a thought, not too familiar with this project or it's guidelines but happy to submit a PR if you'd like.

**Comment by jonobr1** [comment]
I think that's a great idea. Yeah, start a PR and we can add it. I think we could add a `isCounterClockwise` boolean to the primitives.
