### ISSUE TITLE
[Question] Importing SVGs with data attributes 

### ISSUE THREAD

**Issue by elShiaLabeouf** [jonobr1/two.js#575]
Hi, Jono! 

I'm trying to import an SVG with elements that have classes and data attributes, then slightly change it via two.js and export it. The problem is that after the import, the classes and data attributes are gone, i.e.:
```
<g id="Layer_1" transform="matrix(0.657999 0 0 0.657999 680.2677 365.992767)" opacity="1" clip-path="url(#two-14)" data-id="46c816bb-cfbe-4344-be53-3f60533a4e0d" class="md-desk"><path ....
```
but after appending it to the scene, the class and data-id are missing:
```
var office = document.querySelector('div#office svg');
office = two.interpret(office, false);
two.renderer.setSize(office.getBoundingClientRect().width, office.getBoundingClientRect().height);
office.visible = true;
two.scene.add(office);
```
```
<g id="Layer_1" transform="matrix(0.657999 0 0 0.657999 680.2677 365.992767)" opacity="1" clip-path="url(#two-15)"><path ....
```
I guess I've misunderstood the conception of working with two.js. Can you please hint me if it's possible to keep the attributes?

The working code is here https://jsfiddle.net/felixfearest/6cyoxtes

**Comment by jonobr1** [comment]
Thanks for posting your question. The `interpret` method goes through a given SVG element and recreates Two.js specific objects that represent your image. In the SVG Renderer, this duplicates your SVG and replaces `id`s to ensure there are only 1 kind of element on the page.

It _should_ inherit the `class` property from your reference SVG elements, however it won't include every property (for instance `data-id`). Hope this clears up some high level concepts.

**Comment by elShiaLabeouf** [comment]
Hi again @jonobr1 !

Could you please have a look at [my pull request](https://github.com/jonobr1/two.js/pull/578)? I think adding the support of data attributes is a good feature overall. Plus, the [SVG standard](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*) implies the support of data attributes. 

Shall we also start doing this? :)

It works, please see the screenshot below: 
![screenshot](https://user-images.githubusercontent.com/20026712/146474957-e5b6a2a0-136f-49bf-995c-5437797c9fd9.png)

**Comment by jonobr1** [comment]
Awesome work. Just merged!

**Comment by elShiaLabeouf** [comment]
Uber-awesome!! Thank you for the library and for a chance to contribute!
