### ISSUE TITLE
Drawing Partial Ellipses

### ISSUE THREAD

**Issue by dickinson0718** [jonobr1/two.js#585]
I would like to be able to draw more than half of an ellipse that begins and ends  on the same *side* of an ellipse. Something like these: 

https://codepen.io/dickinson0718/pen/YzrryOX

<img width="282" alt="partial circles" src="https://user-images.githubusercontent.com/9343855/147107130-d805f097-b9b9-4360-93f9-81f628418559.png">

Notice how the circle arcs begin and end on the same side of the horizontal - i.e. both end and start points have the same y coordinate.

I have been experimenting with the beginning/ending parameters and the Ellipse like this

https://codepen.io/dickinson0718/pen/abLyPeJ

<img width="1050" alt="partial ellipse" src="https://user-images.githubusercontent.com/9343855/147107499-61afeb9a-1d66-4080-907e-745f214ad147.png">

Which is close, but I would like the "1" of the ending to be in a different spot like this:

<img width="1286" alt="Screen Shot 2021-12-22 at 9 27 19 AM" src="https://user-images.githubusercontent.com/9343855/147108152-31782af0-efd3-4ac1-a2ce-d7fc245ddbd6.png">

Parameters like this

```javascript
path.beginning = 0.4
path.ending = 1.1
```
would seem to indicate the behavior I would like (for closed curves only), but it appears that the ending parameter is cut off at 1.

Is this possible with the current version of the code? If so, I would love to know how. In the meantime, I have been thinking about how this functionality might be included.

Parameters bigger that one and even negative would be nice (for *closed* paths only, of course!).  You could obtain full functionality if you restricted `-1<=  beginning < ending <= 2` and  `ending - beginning <=1` this would allow the user to draw any part of an ellipse or closed curve going ending beyond one or starting before zero.  

In my *very minimal* dive into the code this seems to be controlled by this code starting at line 1303 of `path.js` 

```javascript
  _update: function() {

    if (this._flagVertices) {

      if (this._automatic) {
        this.plot();
      }

      if (this._flagLength) {
        this._updateLength(undefined, true);
      }

      var l = this._collection.length;
      var closed = this._closed;

      var beginning = Math.min(this._beginning, this._ending);
      var ending = Math.max(this._beginning, this._ending);

      var bid = getIdByLength(this, beginning * this._length);
      var eid = getIdByLength(this, ending * this._length);

      var low = ceil(bid);
      var high = floor(eid);
```

this, in turn calls 

```javascript
/**
 * @private
 * @param {Two.Path} path - The path to analyze against.
 * @param {Number} target - The target length at which to find an anchor.
 * @returns {Number}
 * @description Return the id of an anchor based on a target length.
 */
function getIdByLength(path, target) {

  var total = path._length;

  if (target <= 0) {
    return 0;
  } else if (target >= total) {
    return path._lengths.length - 1;
  }

  for (var i = 0, sum = 0; i < path._lengths.length; i++) {

    if (sum + path._lengths[i] >= target) {
      target -= sum;
      return Math.max(i - 1, 0) + target / path._lengths[i];
    }

    sum += path._lengths[i];

  }

  return - 1;

}
```

It seems that perhaps, if the curve was closed , part of this could become something like

```javascript
var startSearch = 0
var endSearch= path._lengths.length
var startSum = 0

if (!path._closed){
  if (target <= 0) {
    return 0;
  } else if (target >= total) {
    return path._lengths.length - 1;
  }
} else {
  if (target <= -total) {
    return 0;
  } else if (target >=2* total) {
    return path._lengths.length - 1;
  }
  startSearch =-path._lengths.length
  endSearch = 2* path._lengths.length
  startSum = -path._lengths.length
}

 var m = path._lengths.length 
// for the modulus operator ( ( i % m  ) + m ) % m 
// See the note in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder
// https://en.wikipedia.org/wiki/Modular_arithmetic 

  for (var i = startSearch, sum = startSum; i < endSearch; i++) {

    if (sum + path._lengths[ ( ( i % m  ) + m ) % m ] >= target) {
      target -= sum;
      return Math.max( ( ( ( i % m  ) + m ) % m) - 1, startSearch ) + target / path._lengths[  ( ( i % m  ) + m ) % m ];
    }

    sum += path._lengths[ ( ( i % m  ) + m ) % m ];

  }

  return - 1;

}
```

I'm sure that the above is not 100% correct. Further, I don't know what implications allowing negative parameters or those bigger than one would have on the rest of the code.  Nor do I understand exactly how the 'low' and 'high' in `path.js` work or how the. expanded parameters would affect them.

Something like this would really help me improve the efficiency of the spherical drawing program that I'm working on: https://easelgeo.app/

---
 - OS: iOA
 - Browser Chrome
 - Version 96.0.4664.110 (Official Build) (x86_64)

**Comment by jonobr1** [comment]
Thanks for the detailed question. There are a couple "out of the box" solutions Two.js offers for rendering this:

1. When changing `beginning` and `ending` also change `circle.rotation` to offset the way that you want. ([example](https://codepen.io/jonobr1/pen/RwLLobM)): your mouse's y position affects the stroke.
3. Use a mask. ([example](https://codepen.io/jonobr1/pen/Yzrrpwa)): your mouse's y position affects the stroke.

As an aside, making the first example made me realize there are other irregularities happening:

<img width="192" alt="Screen Shot 2021-12-22 at 10 29 34 AM" src="https://user-images.githubusercontent.com/220033/147138805-db24b4af-0006-4712-a349-e9b7552fc818.png">
( ⬆️ this should be zero'd out with nothing visible, but actually displays a small bubble-like stroke)

**Comment by dickinson0718** [comment]
Thanks for your work around! I think that I can make the rotation by Pi/2 work to draw what I need. I think that masking would lead me to really complicate my program.  Neither work around will be helpful drawing the part of the ellipse (x/2)^2+ (y/10)^2=1 under the line y=-4x+11 (See https://www.desmos.com/calculator/siqxjp08ka ). Perhaps you can put this on your to do list -  and maybe for closed curves like Ellipses and Circle the angle from the center could be the parameter as in the TikZ command ```\tikz \draw (0,0)
arc [start angle=0, end angle=315,
x radius=1.75cm, y radius=1cm];```

**Comment by jonobr1** [comment]
I think combining some of this functionality into a proposed `Two.Arc` would be productive. See: https://github.com/jonobr1/two.js/issues/585
