### ISSUE TITLE
Two.js not loading local otf/ttf fonts?

### ISSUE THREAD

**Issue by sgates** [jonobr1/two.js#586]
I have some otf and ttf fonts in my react/electron app. Before switching to two.js, I was rendering everything directly on a canvas with the regular js 2d graphics context. I was able to use custom fonts defined as @font-face's in the CSS. Fonts installed on my system are working fine with two.js, but custom families just don't work, they revert to the default as if not found. Is this unsupported by two.js or could I be doing something wrong?

**Your code (either pasted here, or a link to a hosted example)**
**app.css**
```css
    @font-face {
        font-family: led-light;
        src: url("fonts/LEDLIGHT.otf");
    }
```

**app.js**
```javascript
    import "./App.css"
    // ...
    two.makeText('myText', 500, 100, {
      fill: ctx.currentTheme.textColor,
      size: "128",
      family: "led-light"
    })
```

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [X] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

---

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Browser: (electron/chromium)
 - Version: 14.0.0

**Comment by jonobr1** [comment]
Thanks for your question. 🤔 

If you've had success with just `<canvas />` commands and custom fonts then Two.js _should_ behave the same. I'll need a little bit more information to help diagnose what the issue is:

1. What renderer are you using? E.g: `var two = new Two({ type: Two.Types.canvas });`? If you didn't set any then it would be SVG.
2. Are there network errors in the console for loading the font file?
3. Are you setting `swap` on the `@font-face` declaration?

**Comment by sgates** [comment]
Thanks for the quick reply!

> What renderer are you using? E.g: var two = new Two({ type: Two.Types.canvas });? If you didn't set any then it would be SVG.
I’m using opengl
> Are there network errors in the console for loading the font file?
No - and if I add a sanity check declaration such as:

@font-face {
font-family: fart;
src: url("fonts/fart.otf");
}
It barfs as I would expect: Uncaught Error: Cannot find module './fonts/fart.otf'
> Are you setting swap on the @font-face declaration?
I am not. I tried setting 

font-display: block;
and
font-display: swap;

just now to see if there was a difference - no change. 

If this is a real head scratcher, I can try to re-create a failing example - if this is unexpected behavior then it could very well be it just my code messing something up.

Thanks again, I’m really loving this lib so far!

—Steffen

**Comment by jonobr1** [comment]
If you're loading WebGL then I believe you'll need to add this check to ensure the fonts are loaded in JavaScript:

```javascript
document.fonts.load('bold 20px led-light, Arial, sans-serif').then(function() {
  var text = two.makeText('hello world', 500, 100, {
      fill: ctx.currentTheme.textColor,
      size: "128",
      family: "led-light"
    });
});
```

**Comment by sgates** [comment]
OMG that did the trick. Thanks for much for this! I’ll report back if I have any more issues, but this worked like a treat. Happy new year!

—Steffen

**Comment by jonobr1** [comment]
Glad to hear!
