### ISSUE TITLE
[Bug] Vector#rotate logic incorrect

### ISSUE THREAD

**Issue by fivegreenapples** [jonobr1/two.js#588]
I think I've found a bug in `Vector#rotate`.

Current code is:

```
rotate: function(Number) {
  var cos = Math.cos(Number);
  var sin = Math.sin(Number);
  this.x = this.x * cos - this.y * sin;
  this.y = this.x * sin + this.y * cos;  // error on this line
  return this;
}
```

The issue is that the new `y` value is calculated based on the _new_ `x` not the old `x`. This error was introduced in [`b297935ba2557bce7a1f8ccbf60e8bda57b04fbb`](https://github.com/jonobr1/two.js/commit/b297935ba2557bce7a1f8ccbf60e8bda57b04fbb)

**Comment by jonobr1** [comment]
Indeed it is. Thank you!

**Comment by jonobr1** [comment]
Fixed in latest `dev` branch: https://github.com/jonobr1/two.js/commit/6eac5462221d91fe10bd0ee8faf784ec34f99589

Hoping this next version is published in the next couple of weeks. Just about finished with a big ES6 port of the entire library.

**Comment by fivegreenapples** [comment]
Glad to be of help.
And, sorry - I should have mentioned this in the initial report, but the bug affects the `BoundProto` version of rotate as well. I've submitted a PR for this https://github.com/jonobr1/two.js/pull/589
