### ISSUE TITLE
How to Shade a Non-Convex Closed Shape Bounded by Parts of Ellipses and Circles?

### ISSUE THREAD

**Issue by dickinson0718** [jonobr1/two.js#591]
Thank you for writing and maintaining the `Two.js` package. I have enjoyed using this package and the SVG rendering is exactly what I need!

I would like to easily shade a closed region that is bounded by ellipse and circle segments (each formed using the `beginning` and `ending` features) like this crescent shaped one:

<img width="343" alt="Screen Shot 2022-01-03 at 6 09 41 PM" src="https://user-images.githubusercontent.com/9343855/147990094-ce72714f-f57d-4533-a0b5-93a17f7d8d84.png">

https://codepen.io/dickinson0718/pen/abLyPeJ

My application involves displaying the projection of circles on spheres (in 3 dimensional x,y,z space) onto the x-y plane and typically there are many circles at different angles and location that need to be projected. The above example only shows one fairly typical one and how it is computed. Each circle in 3D projects to an ellipse in the plane and parts of the ellipse need to be rendered differently depending on if they come from parts of the 3D circle that are above or below the plane z=0.

Is there something like a [compound path made of ellipse/circle/straight segments](https://tex.stackexchange.com/questions/225638/filling-a-non-convex-path-in-tikz) that will do this without creating a `Two.js path` object?

_Partial/possible solution(?)_: I know that `Two.Path` objects can be non-convex so I could convert each of the above ellipse/circle segments to single continuous closed `Path` object and then fill it.  However, I saw no easy way of doing this even using the `getPointAt` percent of path feature. For example, in 

https://codepen.io/dickinson0718/pen/GRMdmzm

where the ellipse segment is green. I attempted to use the `getPointAt` percent of path feature on the ellipse. Ideally I would like to sample over the interval of the `beginning` to `ending`

```(java script)
path.beginning = 0.2807779902644728  
path.ending = 0.7192220097355273
```
but this produces points on the *unrotated* ellipse -- see the 60 circles centered on the vectors returned by the `getPointAt` command. 

To fix this, I can't rotate the entire layer because there will be many projected circles, each at their own angles. I guess I could apply a rotation matrix to each vector, but this would duplicate (some) of the computations that `Two.js` has already done and therefore wouldn't be very efficient (which is important with *lots* of circles being projected). I was hoping there would be an easy way to simply *copy* the locations of vectors/anchors in each of the segments from a fixed `beginning` (like 0.280) to a fixed `ending` (like 0.719) to create a `Two.Path` object.

Is there a simple way to copy the locations of the vectors/anchors making up a rotated partial ellipse/circle? If so, then my question is solved. 

While I was doing this, I noticed something else that I didn't understand and didn't expect. In the example above, `getPointAt` didn't seem to produce the vectors at the correct spots on the unrotated ellipse. For example, the point `path.getPointAt(0,vec);` should be the right-most point on the unrotated ellipse but when I plotted it (the blue point in the screenshot below) it seemed to be a bit above and left of the right-most extreme of the ellipse.  Further, it would seem to me that, on a closed curve like this ellipse, that `path.getPointAt(0,vec);` (in blue below) and `path.getPointAt(1,vec);` (in red below) should be the same point, but they are not. 

<img width="331" alt="Screen Shot 2022-01-03 at 6 22 56 PM" src="https://user-images.githubusercontent.com/9343855/147990899-aa9ef495-86a5-40ac-89cf-4f4f9772cab7.png">

I thought this might have to do with the fact that I used the `path.closed = false` option, but even setting this to true doesn't change this behavior.  Perhaps this is an undesired interaction between the use of `getPointAt`, `beginning`, `ending` and a closed curve?

Thank your for your time and any ideas that you might have to help me. I really appreciate it!

**Comment by jonobr1** [comment]
Sorry for the delay @dickinson0718, I was busying publishing the `v0.8.0` latest version of Two.js and haven't had time to address all the good questions here. I'll try to answer each question as a separate response in this thread:

**Comment by jonobr1** [comment]
**1. Is there Compound Path Operations in Two.js?**
Not at the moment. I would like to add Boolean Operations at some point to the library as a WASM module to not impede draw calls because there is a lot of mathematical computations that run to do them.

That being said, you _should_ be able to make compound paths by simply concatenating the `vertices` array of a `Two.Path`. E.g:

```javascript

var circle = new Two.Circle(...);
var ellipse = new Two.Ellipse(...);

var path = new Two.Path(circle.vertices.concat(ellipse.vertices));
// This disables auto calculating bezier handles
// and commands for each anchor. It's important
// to check this as `false`.
path.automatic = false;

two.add(path);

```

In the example above you're creating a singular path out of the vertices of two other shapes. But, and this gets into the next question, all shapes have their own matrix where position data is held. So, all vertices are drawn from a `0, 0` local center. Adding a circle and ellipse together will look like this: https://codepen.io/jonobr1/pen/XWeymVq?editors=0010

<img width="283" alt="Screen Shot 2022-01-11 at 4 27 58 PM" src="https://user-images.githubusercontent.com/220033/149042420-f0f7c018-5ede-4fed-8e5b-633006702d3d.png">

⚠️ __Closed shapes are handled in the renderer and don't append reduplicated anchors in a vertices list. So, the shapes here are missing a quarter of their arc.__

**Comment by jonobr1** [comment]
**2. Matrices Don't Apply To Vertices**
Vertex positions are calculated in a space _local_ to the object they are referenced by. In the primitive cases of Two.js (e.g `Two.Circle`) these go from `- radius` to `+radius` in the x and y space. This is why you get the discrepancy between the circles and the line. Currently you'll need to apply the world or local matrix of the object to the vertices that you extract. You can do that like so:

```javascript
var localMatrix = path.matrix;
var worldMatrix = Two.Utils.getComputedMatrix(path);
var point = path.getPointAt(0.33);
var matrix = worldMatrix; // local matrix works for just the position, rotation, and scale of that object
point = matrix.multiply(point.x, point.y, 1);
```

**Comment by jonobr1** [comment]
**3. Beginning, Ending, and Get Point At Discrepancies**
There is additional logic on every primitive to make the `beginning` and `ending` properties working correctly even though there are only the required number of vertices available to draw. Take `Two.Rectangle` for instance. It doesn't make sense for a rectangle to have 5 vertices, there are only 4 distinct points to any rectangle. But, to draw from the `t=0` to the `t=1` you're going _back_ to the first vertex at the end; effectively filtering through 5 vertices. In 0.7.x this was addressed to `beginning` and `ending` based on whether `path.closed = true` or not. But, this hasn't been added to `getPointAt`. To your point, I think it should be added to Two.js for the sake of consistency.

**Comment by jonobr1** [comment]
This PR adds an easy way to get the calculated `path.worldMatrix`: https://github.com/jonobr1/two.js/pull/594

**Comment by jonobr1** [comment]
Last thing I'll add to this is that you can access the vertices that actually get passed to the renderer for drawing. The property `path.renderer.vertices` is the clipped set of vertices after `beginning` and `ending` have been applied. E.g:

```javascript
path.vertices.length; // 10
path.beginning = 0.5;
... // After the renderer is updated
path.renderer.vertices.length; // 5
```

**Comment by dickinson0718** [comment]
I was able to use Two.js to successfully implement my partial ellipses using your suggestion of `renderer.vertices` and carefully picking `beginning` and `ending` values after rotating the ellipse Pi/2.  You did a great job of interpolating between the vertices to get the `beginning` and `ending` values right. Thank you so much for your help!

**Comment by jonobr1** [comment]
Glad to hear!
