### ISSUE TITLE
Shape's add method throws an error when I use vite

### ISSUE THREAD

**Issue by Linkontoask** [jonobr1/two.js#597]
```javascript
const stage = new Two.Group()
stage.add(new Two.Rectangle(0, 0, 50, 50))
```

I found that this error occurs in the last two versions, but the prompts are different

- 0.7.13
Uncaught (in promise) TypeError: 'get' on proxy: property '_events' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '#<Object>')

- 0.8.0
Uncaught (in promise) TypeError: Cannot read from private field

**Comment by jonobr1** [comment]
Any chance you can explain a bit more the circumstances of your issue. I just ran `vite` vanilla and `vanilla-ts` with the below code and don't get those errors.

```javascript
import Two from 'two.js';

const two = new Two({
  fullscreen: true,
  autostart: true
}).appendTo(document.body);

const rectangle = new Two.Rectangle(0, 0, 50, 50);
const group = new Two.Group(rectangle);

two.add(group);

two.scene.position.set(two.width / 2, two.height / 2);

```

**Comment by Linkontoask** [comment]
I wrote a minimal reproduction code based on vite and vue-ts

```typescript
import Two from 'two.js'

export class Stage {
  root: Two.Group

  constructor() {
    this.root = new Two.Group()
  }

  add() {
    this.root.add(new Two.Rectangle(0, 0, 50, 50))
  }
}

const stage = new Stage()
stage.add() // Uncaught (in promise) TypeError: Cannot read from private field
```

**Comment by jonobr1** [comment]
In the latest npm version `0.8.1` I removed ES6 specific private invocations. Let me know if that alleviates the problem for you.

🤞 🤞 🤞

**Comment by Linkontoask** [comment]
thx
