### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by alfredo-valero** [jonobr1/two.js#598]
In the new version 0.8.0 when trying to import the class to component (angular 13) the error appears  "index.d.ts is not a module". Version 0.7.13 works fine

**Comment by jonobr1** [comment]
Thanks for posting. I just published a new version `0.8.1` to npm. Let me know if that resolves the problem.

**Comment by jonobr1** [comment]
Glad to hear and thanks for the hot fix and confirmation!

**Comment by alfredo-valero** [comment]
Thank you @jonobr1, congratulations for the fantastic work you do
