### ISSUE TITLE
[Bug] Typescript typing is incorrectly defined

### ISSUE THREAD

**Issue by drbolsen** [jonobr1/two.js#599]
**Describe the bug**
After playing a little bit with the library it seems that Typescript typing is incorrectly defined.  This causes that Typescript throws a compilation error.  It is possible to wrap instance with any to avoid the compilation error but it defeats the whole purpose of using Typescript.

**To Reproduce**
Just grabbed one of the available examples [Dynamic Vertices](https://codepen.io/jonobr1/pen/gOxQRXd)

```
function createGrid(s) {

...skipped...

  let A = two.makeLine(two.width / 2, 0, two.width / 2, two.height);
  let B = two.makeLine(0, two.height / 2, two.width, two.height / 2);
  A.stroke = B.stroke = '#6dcff6';

...skipped...

}
```

The **_`stroke`_** property is not available on either A or B. This is due to that in **_types.d.ts_** the inheritance from Path class, where **_`stroke`_** is defined, is missed.

````
    export class Line  ->> missed extends Path <<-  {
        constructor(x1: any, y1: any, x2: any, y2: any);
        automatic: boolean;
    }
````

Judging by a brief look it seems like it is not an isolated case, the  inheritance information is missed across multiple declarations.

**Expected behavior**
All declared types should properly reflect all inherited properties

**Environment (please select one):**
- [x ] Packaged software (ES6 imports, vue.js, typescript)

**Desktop (please complete the following information):**
 - OS: [e.g. OSX]
 - Browser [chrome]
 - Version [latest]

**Comment by jonobr1** [comment]
Thanks for sharing this. It's a shame either A) I'm not setting up the `tsconfig.json` correctly or B) the TypeScript types declarations don't infer extending modules. I'll noodle with this and see if I can figure something out.

Obviously I can manually add it, but I'm hoping to have an automated solution and I had been under the impression that if I the codebase was in ES6 that TypeScript would be able to generate type declarations from the source files. More soon!

**Comment by jonobr1** [comment]
Looks like there is a conflict between for TypeScript between the jsdocs and the code...

**Comment by jonobr1** [comment]
Can you try this `types.d.ts` https://github.com/jonobr1/two.js/blob/issue-599/types.d.ts and let me know if that fixes the problem?

**Comment by drbolsen** [comment]
> Thanks for sharing this. It's a shame either A) I'm not setting up the `tsconfig.json` correctly or B) the TypeScript types declarations don't infer extending modules. I'll noodle with this and see if I can figure something out.
> 
> Obviously I can manually add it, but I'm hoping to have an automated solution and I had been under the impression that if I the codebase was in ES6 that TypeScript would be able to generate type declarations from the source files. More soon!

Not a worry mate,  all good. JS -> TS journey is never straightforward, unfortunately tools can't infer all details, so sometimes a manual processing is an unavoidable evil.  Thanks for addressing this issue, much appreciated.

**Comment by drbolsen** [comment]
> Can you try this `types.d.ts` https://github.com/jonobr1/two.js/blob/issue-599/types.d.ts and let me know if that fixes the problem for you?

I had a look this morning, it seems that changes go to the right direction. Just wander whether factory functions, e.g. makeLine, returning *_typeof Class_* instead of the instance of the class  is intentional or just another artefact from the conversion process?

Changing from *_typeof Class_* to *_Class_* in dts makes the example I've used for testing compiling and working without a glitch in my Typescript environment.

**Comment by jonobr1** [comment]
Yeah, that sounds like it's an issue with compilation.

I've also noticed numerous other issues. At this stage, I think it may make sense to just write the `types.d.ts` manually because Two.js does so many things specific to _JavaScript_ which TypeScript doesn't infer.

**Comment by jonobr1** [comment]
If you try out the latest dev branch this particular issue should be resolved. I imagine there will be many other TypeScript types related issues, but hopefully the majority of use cases (e.g: simply instantiation of classes and properties from the library) will be much more usable.
