### ISSUE TITLE
[Bug] Import ZUI

### ISSUE THREAD

**Issue by rugarve** [jonobr1/two.js#601]
Great work, Two.js is cool!

In the version 0.8.1 when trying to import ZUI (angular 13) show this error:

Error: export 'default' (imported as 'ZUI') was not found in 'two.js/extras/jsm/zui.js' (possible exports: ZUI)

I tryaing import with: import ZUI from "two.js/extras/jsm/zui.js"

Thanks

**Comment by jonobr1** [comment]
Glad you're enjoying it! You have to import ZUI like this:

```javascript
import { ZUI } from "two.js/extras/jsm/zui.js";
```

Does that work for you?

**Comment by sxsnwangrenfei** [comment]
Me too.
`"TypeError: two_js__WEBPACK_IMPORTED_MODULE_2__.default.ZUI is not a constructor"`

**Comment by rugarve** [comment]
Thanks, 
I import as you says and i can use ZUI.

**Comment by rugarve** [comment]
In Two.js documentation, in example "Basic Angular template" (https://codesandbox.io/s/nostalgic-volhard-6zzfd?file=/src/app/app.component.ts) the import of ZUI is:
import ZUI from "two.js/extras/jsm/zui.js"; 
and the correct form is: 
import { ZUI } from "two.js/extras/jsm/zui.js"; 
as you told me.

Thanks @jonobr1

**Comment by jonobr1** [comment]
Ah, thanks. Previous version of Two.js imported that way. I just updated to the latest.
