### ISSUE TITLE
How can I scale an svg in one direction

### ISSUE THREAD

**Issue by marcuskielly** [jonobr1/two.js#606]
I'm trying to scale an element along it's `y` axis - but struggling to see how to achieve this. 
My code base is broken into several files, but I'll try and convey what i've got here: 

```js
const body = two.scene.getById('body');

const update = ({ value }) => {
  body.matrix.manual = true;
  body.matrix.scale(1, value);
}

const endTween = new T.Tween({ value: 1 })
    .to({ value: 0.5 }, 1000)
    .onUpdate(update);

const startTween = new T.Tween({ value: 0.5 })
    .to({ value: 1 }, 1000)
    .onUpdate(update);
    .onComplete(() => endTween.start());

two.play();
```
In this example, even though the value I'm getting is correct, the element scales vertically to 0, and then doesn't return to it's original size. Can you give me some guidance on this?

**Comment by jonobr1** [comment]
Also, if you're using @tweenjs/tween.js be careful of passing the object to multiple tweens at the same time.

The starting value is set when you make the new tween, not when you start it.

**Comment by jonobr1** [comment]
One potential reason: the `getBoundingClientRect` command applies the scale you just applied. So you need to calculate the rect before you set the scale. Try modifying the vertices like in #471 before you set the scale:

```javascript
var rect = path.getBoundingClientRect();
var offset = new Two.Vector();
offset.x = rect.width * 0.5;
offset.y = rect.height * 0.5;
for (var i = 0; i < path.vertices.length; i++) {
  path.vertices[i].add(offset);
}
path.scale = new Two.Vector(1, 2);
```

**Comment by marcuskielly** [comment]
Hmm - sorry but that hasn't worked - see here: https://jsfiddle.net/sunwukung/jst2049g/

The error I'm getting is this: 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at e.Anchor.add (two.min.js:84:329)
    at (index):53:5
    at Collection.forEach (<anonymous>)
    at (index):50:20
```

**Comment by jonobr1** [comment]
You're using a really old version of Two.js. You're importing `v0.6.0` and the latest is `v0.8.3`. If you're using `Two.Rectangle`s there is a special property, `rectangle.origin` that you can use to handle offsets like this: https://codepen.io/jonobr1/pen/XWzeMYa

**Comment by marcuskielly** [comment]
Hi again - I think I need to be really specific about my use case: 

1. I'm loading some svg assets from files
2. I want to scale them by different amounts along their x/y axis
3. I want to be able to change the origin point this transformation occurs around.

**Comment by jonobr1** [comment]
K, I think making a new issue with some kind of example would be most helpful. I think we've exhausted this thread.
