### ISSUE TITLE
[Question] How to make shapes selector on drag ?

### ISSUE THREAD

**Issue by meetzaveri** [jonobr1/two.js#612]
I have already a working code for dragging shapes in zoomed or non-zoomed plane. Problem is when I tried to implement group selector (which increases its width and height on drag as it selects shape in that area) which increases area upon dragging, in zoomed plane its not working as expected.

I have also attached that video recording. First the scale is default `1`. When zoomed out, you can see the selector's position was not accurate

https://user-images.githubusercontent.com/21293048/155694905-f4b7a40f-b1d8-4071-ad8b-79772d50504c.mov

Thank you for your work.

**Comment by jonobr1** [comment]
Yes, this can be tricky. You need to "project" the user input (x, y position) to the world space that the object exists in. Here's an example showing that: https://codepen.io/jonobr1/pen/BamqKvd?editors=0020
