### ISSUE TITLE
Is there a way to access `Two.group.renderer.elem`?

### ISSUE THREAD

**Issue by hughplay** [jonobr1/two.js#616]
**Describe your question**

I try to access `Two.Group.renderer.elem` as Olivier described in  https://github.com/jonobr1/two.js/issues/209. However, it failed. Accessing elem through the returned `Proxy` object seems not feasible. I wonder if there is another way to do this?

**Your code (either pasted here, or a link to a hosted example)**

Olivier's [code](https://jsfiddle.net/hro2mgku/6/) (need to replace two.js in resource to make it work ) works in jsfiddle but failed under my environment.

My testing code:

```
this.ball = this.two.interpret(svg);
this.ball.center();
console.log(this.ball.renderer)
console.log(this.ball.renderer.elem)
```

**Screenshots**

What I see in my console:

![image](https://user-images.githubusercontent.com/30553791/157041919-87439e3f-47d5-422b-b23e-3d62e939c5c5.png)

You can see that `this.ball.renderer` contains `elem`, but directly accessing it will get `undefined`.

I know it must be something related to [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) but have no idea how to resolve this problem.

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

---

If applicable:

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome Version 98.0.4758.109 (Official Build) (x86_64)

**Additional context**

I use Vue 3 and import two.js like:

```
import Two from "two.js";
```

**Comment by hughplay** [comment]
Ok, I got it. After manually `update`, it works! Thanks! : )

**Comment by jonobr1** [comment]
Glad to hear. Happy coding!
