### ISSUE TITLE
Unable to remove an object

### ISSUE THREAD

**Issue by hughplay** [jonobr1/two.js#617]
**Describe your question**

Recently, I am implementing a line plot function for a tacticboard: https://github.com/tacticalboard/tacticalboard/issues/2.
I have already implemented this function and it is natural to also implement an "eraser" function to remove selected lines. It is weird that `obj.remove()` does not work. 

**Your code (either pasted here, or a link to a hosted example)**

The removing code is here:
```javascript
var line = this.lines[elem.id];

console.log("line:", line);
console.log("children before remove", this.two.scene.children);
// try to remove
var res = this.two.remove(line)
console.log("return from remove", res)
console.log("childrena after remove", this.two.scene.children);
console.log("ids", this.two.scene.children.ids)
// line.visible = false;
```

**Screenshots**

The output in the console:

![image](https://user-images.githubusercontent.com/30553791/157395558-1897dcf6-a965-40ab-8bdf-0d7a2c3555bd.png)

You can see that after `remove`, the size of children keeps the same. (But `line.visible = false` could work).

I read the [code of `remove`](https://github.com/jonobr1/two.js/blob/cbc2a255ebef8b6bc11d5e6320080f25079c3a7e/src/group.js#L537) and found it depends on `two.scene.children.ids`. However, in my case, the value of `two.scene.children.ids` is empty (see the screenshot).

Any ideas on how this happened and how to resolve this problem?

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

---

**Additional context**

The "line" is added by `this.two.makeArrow`.
I init the two object with:

```
this.two = new Two({
  type: Two.Types.svg,
  fitted: true,
  autostart: true,
}).appendTo(document.getElementById("panel"));
```

The version of used two.js: 0.8.3.

**Comment by jonobr1** [comment]
Hmm, this could be a bug, but I need to learn more about your code before I can say for sure. Anyway you can make a stripped down version to show as an example on something like CodePen or jsfiddle?

Also, does this remove the line?

```javascript
var line = this.lines[0];
line.remove();
```

That should remove itself from its parent.

**Comment by hughplay** [comment]
> Also, does this remove the line?
> 
> ```js
> var line = this.lines[0];
> line.remove();
> ```
> 
> That should remove itself from its parent.

No, I even tried to directly remove the `line` from `this.two.scene.children` and it doesn't work.

> Hmm, this could be a bug, but I need to learn more about your code before I can say for sure. Anyway you can make a stripped down version to show as an example on something like CodePen or jsfiddle?
> 

I will try this later, thx.
