### ISSUE TITLE
I can select a line or segment in two.js [Question]

### ISSUE THREAD

**Issue by rugarve** [jonobr1/two.js#618]
Hello,

I am working on making a geometric route editor.
I draw points that I can later select using 'distanceToSquared'.
I also draw lines and I need to select them. How can I select lines? is it better to use path or two.line to select lines?

Thanks in advance,
Greetings

**Comment by jonobr1** [comment]
A `Two.Line` extends a `Two.Path` so either will work fine. If you're using the SVG renderer you can use browser event handlers to capture a click like so:

```javascript
var line = new Two.Line(x1, y1, x2, y2);
two.add(line);
two.update(); // Updating Two.js will generate the SVG Element
line.renderer.elem.addEventListener('click', click, false);

function click(e) {
  var target = e.target;
  var line = two.scene.getById(target.id);
  console.log('Clicked', target.id);
}
```

**Comment by rugarve** [comment]
I needed this development to calculate the distance between the cursor and the segments.

segments.vertices.forEach( item => {
      startNode = [];
      endNode = [];
      startNode.push(item.vertices[0].x , item.vertices[0].y);
      endNode.push(item.vertices[1].x, item.vertices[1].y);
      px = endNode[0] - startNode[0];
      py = endNode[1] - startNode[1];
      temp = (px*px)+(py*py);
      u = ((mouse.x-startNode[0]) * px + (mouse.y-startNode[1]) * py) / temp;
      if (u > 0 && u < 1) {
        x = startNode[0] + u * px;
        y = startNode[1] + u * py;
        dx = x - mouse.x;
        dy = y - mouse.y;
        d = Math.sqrt(dx*dx + dy*dy);
        if (d <= this.mouse['radiusSquared']) {
          return d;
       }
     }
});

Thanks for the reply. 
Greetings

**Comment by jonobr1** [comment]
Thanks for sharing. Glad you got it working
