### ISSUE TITLE
[Bug] Missing some constructors in types.d.ts

### ISSUE THREAD

**Issue by queuedq** [jonobr1/two.js#620]
**Describe the bug**
Some classes like `Rectangle` or `Circle` don't have a constructor declared in `types.d.ts`. Since they inherit from `Path`, the constructors for them default to the `Path`'s constructor. However, their constructors are different from the `Path`'s constructor.

**To Reproduce**
```js
import Two from 'two.js';

const rect = new Two.Rectangle(0, 0, 100, 100);
// Error: Argument of type 'number' is not assignable to parameter of type 'Anchor[]'.
```

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

I'm using Parcel with TypeScript.

tsconfig:
```json
{
  "target": "es6",
  "module": "es2020",
  "compilerOptions": {
    "jsx": "react",
    "lib": ["dom", "es6"],
    "plugins": [{ "name": "typescript-plugin-css-modules" }]
  }
}
```

**Comment by jonobr1** [comment]
Thanks for posting @queuedq. Mind giving the latest `dev` branch a try and see if that fixes the issue?

You can do that like so:

```bash
npm install --save https://github.com/jonobr1/two.js
```

If it's good on your end then I can publish a new version to NPM

**Comment by queuedq** [comment]
Thank you for the quick response!

After installation, I imported two.js like this:

```js
import Two from '@jonobr1/two.js';
```

But it emits the following error message.

```
File '.../node_modules/@jonobr1/two.js/types.d.ts' is not a module.
```

**Comment by queuedq** [comment]
> `File '(...)/node_modules/@jonobr1/two.js/types.d.ts' is not a module.`

Nvm, it works when I set `compilerOptions.moduleResolution` to `node` in tsconfig. I think the error occurred due to the name mismatch and it should work without problems after publishing.

**Comment by jonobr1** [comment]
Ah, right because everything is expecting `@jonobr1/two.js` not `two.js`. I'll push the release now.

**Comment by jonobr1** [comment]
Okay that's up: https://www.npmjs.com/package/two.js

Thanks again for you posting.

**Comment by queuedq** [comment]
It works fine now, thank you!

**Comment by jonobr1** [comment]
Glad to hear! Thanks again for reporting
