### ISSUE TITLE
[Bug] Missing property types in types.d.ts

### ISSUE THREAD

**Issue by queuedq** [jonobr1/two.js#621]
**Describe the bug**

`Two.Group` has properties `stroke`, `fill`, `visible`, etc., but it is not declared in `types.d.ts`. Instead, it has `_stroke`, `_fill`, `_visible`, etc., which I guess should not be exposed. I didn't check other classes, so I don't know whether any other classes also have similar problems. (Related: #620)

**To Reproduce**
```ts
import { Group } from "two.js/src/group";
const group = new Group();
group.visible; // Property 'visible' does not exist on type 'Group'. Did you mean '_visible'?
```

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

I'm using Parcel with TypeScript.

tsconfig:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2020",
    "jsx": "react",
    "lib": ["dom", "es6"],
    "plugins": [{ "name": "typescript-plugin-css-modules" }]
  }
}
```

**Comment by queuedq** [comment]
Also, there is a problem where `Two.Group.clone()` returns `Shape` instead of `Group`.

**Comment by queuedq** [comment]
Also, there is a problem that `Two.Group.clone()` returns `Shape` instead of `Group`.

**Comment by jonobr1** [comment]
Thanks for sharing. Those changes are published on npm for `0.8.5`.

**Comment by cyndra0** [comment]
I found that the problem is not fully solved, could you reopen this issue? For example,  public properties of `Two.Text` is still missing in the latest dts file: https://github.com/jonobr1/two.js/blob/dev/types.d.ts#L2970 .

**Comment by jonobr1** [comment]
Okay, this is updated. You'll need to use the `dev` branch for a few more days until I have the time to go through and package up a new version to NPM.

Thanks again for posting!

**Comment by danieldavies99** [comment]
I think there still might be some missing properties:

Group.remove(element) and Group.RemoveChildren() both appear to be missing

![image](https://user-images.githubusercontent.com/62446934/216391198-b9838ad8-9f4d-43f7-9e8b-81635bcdd391.png)

**Comment by jonobr1** [comment]
There are certainly missing properties, please let me know which ones! I'll address these ones today

**Comment by jonobr1** [comment]
This commit should fix those issues: https://github.com/jonobr1/two.js/commit/f622bd2e5d1bea9c5ccdd3d815291075e0a9a945
