### ISSUE TITLE
[Bug] makeCurve doesn't work in typescript

### ISSUE THREAD

**Issue by itayYaakov** [jonobr1/two.js#624]
Hi,
a simple call like:
two.makeCurve([v1, v2], true);

don't work in typescript environment since function signature is: makeCurve(points)

```
TS2345: Argument of type 'boolean' is not assignable to parameter of type 'number'.
    65 |             const v1 = makePoint(mouse.x, mouse.y);
    66 |             const v2 = makePoint(x, y);
  > 67 |             line = twoRef.current.makeCurve([v1, v2], true);
       |                                                       ^^^^
    68 |             line.noFill().stroke = "#333";
    69 |             line.linewidth = 10;
    70 |             line.vertices.forEach((v) => {
```

and ts doesn't allow an extra parameter.
Maybe is it possible to introduce an optional curve_flag (in current or a new function)

Thanks!

**Comment by jonobr1** [comment]
[This commit fixes that issue](https://github.com/jonobr1/two.js/commit/1007fceda3380c4240ddae07fa96612f3ddd36ff), but to clarify for you the optional flag isn't to determine if it's curved or not. It's to describe the object is open or not.

The equivalent to this without the arguments would look like this:

```javascript
line = twoRef.current.makeCurve([v1, v2], true);
// Is equivalent to:
line = twoRef.current.makeCurve([v1, v2]);
line.closed = false;
```
