### ISSUE TITLE
[Bug] Typescript complains about incompatibility when typechecking `Two.Element`

### ISSUE THREAD

**Issue by cyndra0** [jonobr1/two.js#628]
**Describe the bug**
By definition,  any kind of objects are extended from `Two.Element`, so it should be ok to give a `Text` to where asking for an `Element`. But this call fails in v0.8.6:
``` ts
const two = new Two()
two.add(new Two.Text()) // Error: Argument of type 'Text' is not assignable to parameter of type 'Element'
```

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

**Additional context**
 When I peek the type definition I found that  `Element` refers to the Element in `lib.dom.d.ts` instead of `Two.Element`. It turns out to be a name collision between two.js and dom.
https://github.com/jonobr1/two.js/blob/7db7ba6be546f305cd63431941266c7b8a2e42c0/types.d.ts#L4103

**Comment by jonobr1** [comment]
Thanks for PRing the solution!

**Comment by endquote** [comment]
I ran into this conflict and was waiting for this change to land before updating my two.js version. In `0.8.8` I think I'm seeing the same or a similar issue.

Here's I'm adding a `Rectangle` to a `Group`, the error seems to make it seem like a DOM element is expected.

![Screen Shot 2022-05-31 at 6 57 26 PM](https://user-images.githubusercontent.com/330010/171312727-b7fe3a2e-46a4-42af-b6c1-c75dc9b95869.png)

**Comment by jonobr1** [comment]
Ah thanks, good eyes @endquote. This commit should fix that: https://github.com/jonobr1/two.js/commit/ccb29aa9a9b2dd798b1fd537ef89b496be522f6a

I'll do a soft update on npm to 0.8.9: https://www.npmjs.com/package/two.js/v/0.8.9

**Comment by endquote** [comment]
Yes, looks good now! 🎉
