### ISSUE TITLE
[Bug] WebGL text positioning is affected by the length of the text

### ISSUE THREAD

**Issue by student020341** [jonobr1/two.js#633]
**Describe the bug**
When left aligned, webgl text seems to offset to the right slightly the longer the text is.

**To Reproduce**
Here is a minimal code snippet to demonstrate the issue. I deployed this to [surge](https://abundant-society.surge.sh/) in case looking at it will help anyone. The code makes a rectangle and some text next to it. The text increases with each line which also seems to increase the gap.

```javascript
import Two from "two.js";

const two = new Two({
  fullscreen: true,
  type: Two.Types.webgl
}).appendTo(document.getElementById("app"));

for (let i = 0;i < 50;i++) {
  two.makeRectangle(100, 50 + i*10, 10, 10);
  two.makeText("A".repeat(1 + i), 120, 50 + i*10, {alignment: "left"});
}

two.update();
```

**Expected behavior**
Left aligned text would be anchored to the left of the text element.

**Screenshots**
See surge url for the live issue (will tear down when resolved)

**Environment (please select one):**
- [x ] Code executes in browser (e.g: using script tag to load library)
- [ ] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [Chrome]
 - Version [Version 101.0.4951.54 (Official Build) (64-bit)]

**Additional context**
The offset seems consistent and I might be able to work around this in the short term. Note in the code sample there is no scaling or groups, just alignment.

Not sure if this detail will be useful, but offsetting seems to be based on font family and size. I'm using 16px monospace in my project and multiplying the length of the text by 1.1 for an offset makes it appear aligned.

**Comment by jonobr1** [comment]
In WebGL it's unfortunately not an exact science to get the width of text (which determines how it's drawn in WebGL). Through the `Text.Ratio` property, you can finesse this. The default is `0.6`, but if you increase or decrease this value you should be able to find a ratio that works and doesn't create this offset.
