### ISSUE TITLE
What is the origin of coordinates?

### ISSUE THREAD

**Issue by rugarve** [jonobr1/two.js#635]
I am reviewing the transformation matrix of my scene. I see that the matrix is the identity matrix, so I imagine that the origin of coordinates is the lower left corner, is it so? or is it the upper left corner as would be the case of offsetX and offsetY of the event.

I need to change the origin of coordinates of the transformation matrix of two.js and of offsetX and offsetY of the events and that the new (0, 0) is the lower left corner.

Thanks

**Comment by rugarve** [comment]
This was the first thing I thought and provided... but it doesn't work. The reason is that even if you enter x and y corrected as you indicate me in some zui method, for example zoomby or translateSurface when you make your internal changes in the transformation matrix it resets the matrix and puts back the origin of coordinates in the upper left corner.

It's becoming a puzzle this, a challenge... How can I solve this?

I have also tried setting the matrix to manual = true. But I lose the functionality of zui and several other things.... I have problems to modify the transformation matrix at will.... Even making a custom traslateSurface I can't apply it to the scene.

How to modify the matrix and apply the changes through custom methods?

Thanks in advance

**Comment by jonobr1** [comment]
Right, what you can do is nest the groups and how ZUI is applied. This is just a snippet, but should give you an idea how to both take ZUI into account and offset the world by the offset:

```javascript

var two = new Two({ fullscreen: true }).appendTo(body);
var stage = new Two.Group();
two.add(stage);

var zui = new ZUI(stage);
two.scene.position.y = two.height; // Create your offset so the origin is the bottom left corner

window.addEventListener('pointermove', function(e) {

  var px = e.clientX;
  var py = e.clientY;

  var x = px - two.scene.position.x;
  var y = py - two.scene.position.y;

  // Apply ZUI calculations with x, y

}, false);

```

**Comment by jonobr1** [comment]
Glad it worked
