### ISSUE TITLE
Duplicate Element ID

### ISSUE THREAD

**Issue by dulimarta** [jonobr1/two.js#639]
**TwoJS Scene and Groups share the same ID**

I noticed that TwoJS scene (which is a `Group`) and the first user-created group share the same ID: `two-0`. Here is the sample code I used:

```ts
import Two from "two.js"; // Version 0.8.9
import { Group } from "two.js/src/group";
import { Circle } from "two.js/src/shapes/circle";

const two = new Two({
  width: 512,
  height: 512,
  autostart: true,
});

two.scene.matrix.manual = true;
two.scene.matrix.translate(256, 256);
two.appendTo(document.body);
let layers: Group[] = [];

for (let k = 0; k < 3; k++) {
  const g = new Group();
  g.addTo(two.scene);
  layers.push(g);
}
const c1 = new Circle(0, 0, 128);
c1.stroke = "red";
c1.linewidth = 3.0;
c1.addTo(layers[0]);
```

**Screenshots**

The following is the screenshot from FireFox inspector panel:

![Screenshot 2022-06-02 160744](https://user-images.githubusercontent.com/3125417/171729172-3a66a0db-9ed6-4500-a2d1-8fdf8c84c4f7.png)

I'm not submitting this issue as a bug report, but it may potentially becomes a bug in the future.

**Comment by jonobr1** [comment]
Thanks for reporting. That looks like a bug. Which version of Two.js is this?

**Comment by jonobr1** [comment]
Oh, if you're going to import the individual modules _instead_ of the project as a whole then you need to get the Two module as well. Change your import statement to this:

```javascript
import Two from 'two.js/src/two';
```

Or don't import group and circle and access them off of the `Two` object like so:

```javascript
import Two from "two.js"; // Version 0.8.9

const two = new Two({
  width: 512,
  height: 512,
  autostart: true,
});

two.scene.matrix.manual = true;
two.scene.matrix.translate(256, 256);
two.appendTo(document.body);
let layers: Two.Group[] = [];

for (let k = 0; k < 3; k++) {
  const g = new Group();
  g.addTo(two.scene);
  layers.push(g);
}
const c1 = new Two.Circle(0, 0, 128);
c1.stroke = "red";
c1.linewidth = 3.0;
c1.addTo(layers[0]);
```

**Comment by dulimarta** [comment]
Thank you for your prompt response. My project is in TypeScript and using `Two.Group` as a type like in the second line below


```ts
import Two from "two.js/src/two";

let layers: Two.Group[] = []; // Compiles with error
const g = new Two.Group(); // Compiles OK  
```

produces the following compiler error 

```sh
Namespace '"two.js/src/two"' has no exported member 'Group'. ts(2694)
```

**Comment by jonobr1** [comment]
I'm not well versed in Typescrip, but I think you need to do this:

```javascript
import Two from 'two.js';

const layer = new Two.Group();
const layers: typeof Two.Group[] = [layer];
```
