### ISSUE TITLE
[Bug] Type Error when using vector from two.module.js

### ISSUE THREAD

**Issue by eulertour** [jonobr1/two.js#654]
**Describe the bug**
Using `Two.Vector` after importing two.module.js results in a type error, despite working properly in the browser.

**To Reproduce**
```
import Two from '../src/lib/two.module.js

new Two.Vector();
```

**Expected behavior**
No type error when using the Vector class.

**Screenshots**
![Screen Shot 2022-08-14 at 3 04 02 AM](https://user-images.githubusercontent.com/43117506/184526326-4b46343b-86e6-475f-a3bb-b0f63297d711.png)

**Environment (please select one):**
- [] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 56e1e7d5609b81df78a4e00ad7e74c987684e14d

**Comment by eulertour** [comment]
FWIW, I managed to get around the error by building the `Two` and `Vector` modules manually and importing them separately:
```js
  // utils/build.js

  esbuild.buildSync({
    entryPoints: [
      path.resolve(__dirname, '../src/two.js'),
      path.resolve(__dirname, '../src/vector.js'),
    ],
    // outfile: paths.esm,
    outdir: path.resolve(__dirname, '../build/modules'),
    bundle: true,
    target: 'es6',
    format: 'esm'
  })
```
However, the code is then duplicated between the `two.js` module (which is enormous) and the `vector.js` module. Is this unavoidable without tree shaking?

**Comment by jonobr1** [comment]
The Two object isn't just a namespace but a class that depends on a lot of things (including Vector). So, it's not possible to tree shake. But, if you know what renderer you're using you can use that directly and it will benefit from trees shaking. Your code unfortunately needs to change a bit to conform to how the renderers work. Let me know if you'd like to see an example of this.

**Comment by eulertour** [comment]
Seeing an example would be a big help 👍

**Comment by jonobr1** [comment]
Here's a simple example: https://codepen.io/jonobr1/pen/xxWQbJj

I'm using remote imports, but you should be able to use NPM or clone the repository and then directly access the source files for your project. Then, each module will only import what's needed and when you finally build (in what looks like `esbuild` for your project) the overall size of Two.js will be drastically reduced.
