### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by car1ot** [jonobr1/two.js#656]
**Describe your question**

Hello. How can I make camera following object?

**Your code (either pasted here, or a link to a hosted example)**

```
const circle = two.makeCircle(x, y, radius);
// Circle added to TWO.JS scene 
tick((dt) => circle.position.x += 10 / dt) 
// Circle is moving right
// ... I need camera to follow this circle!
// So this circle always should be at the screen center, and only objects around are moving when circle moves
```

**Comment by jonobr1** [comment]
Something like this? https://codepen.io/jonobr1/pen/wvmYXXr

**Comment by car1ot** [comment]
> Something like this? https://codepen.io/jonobr1/pen/wvmYXXr

Yes, exactly! Thank you.

**Comment by car1ot** [comment]
The issue was resolved. Example how to make following camera effect: https://codepen.io/jonobr1/pen/wvmYXXr
