### ISSUE TITLE
[How to use arrays or objects to draw curves?]

### ISSUE THREAD

**Issue by landy101** [jonobr1/two.js#662]
**No tutorials using arrays or objects**

**					var ddd = [400, 600, 120, 50, 140, 150, 160, 50, 180, 150, 190, 100, true]
					this.electronArray.push(
						this._two.makeCurve(ddd)
					)**

**Comment by landy101** [comment]
Ask the mouse to draw the Versailles line example

**Comment by jonobr1** [comment]
This would be a way to to accept an array of points by [x, y, x, y ...] configuration: 

```javascript
const path = two.makeCurve.apply(two, ddd);
```
