### ISSUE TITLE
Why is the drawing overwritten?

### ISSUE THREAD

**Issue by landy101** [jonobr1/two.js#663]
**I want to develop programs similar to CAD. The graphics are always covered. How can I solve this problem? thank you**

**this.electronArray.push(
					    this._two.makeRectangle(X, Y, 300, 100)
					)	**

**Do you have any examples similar to CAD?**
![Dingtalk_20220825105402](https://user-images.githubusercontent.com/54479305/186564202-b98f9b3d-bdd8-4a8e-a60d-970acb3444f4.jpg)

**Comment by jonobr1** [comment]
```javascript
const rect = two.makeRectangle(x, y, 300, 100);
rect.noFill();
// or
rect.fill = 'transparent';
```

The default is that they are filled white. You can remove the fill with the above code.
