### ISSUE TITLE
[Question] Resizing image loaded into sprite

### ISSUE THREAD

**Issue by Lucasvo1** [jonobr1/two.js#666]
How can I resize an image loaded into a sprite? Now I use the following:

`var sprite = two.makeSprite('./cala-text.jpg', two.width/2, two.height/2);
`
The actual dimensions of the picture are 15000x150000. When I resize them on the server before it works. Is it possible to do it client-side?

**Comment by jonobr1** [comment]
Sorry for the delay, I'm on vacation right now. Short answer is yes, I'll put together an example to show how this works.

**Comment by jonobr1** [comment]
Here's the simplest way to scale images that are loaded in as `Two.Sprite`s: https://codepen.io/jonobr1/pen/ZEowwQR
