### ISSUE TITLE
[Question] Is it possible to use some Video formats as Texture of a Shape?

### ISSUE THREAD

**Issue by joex92** [jonobr1/two.js#667]
**Describe your question**
just as you create a texture from an image to `.fill` a shape, as well use a video file (like mp4, flv, mov, etc) to `.fill` a shape, so the shape show the video displayed.

**Your code (either pasted here, or a link to a hosted example)**
[this is an example on Three.js](https://threejs.org/examples/?q=video#webgl_materials_video) 
instead of being a 3D mesh, this time it would be a 2D shape:
```js
tex = new Two.Texture('path/to/video.mp4');
rec = two.makeRectangle(0,0,128,72);
rec.fill = tex;
```

**Environment (please select one):**
- [X] Code executes in browser (e.g: using script tag to load library)
- [X] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [X] Running headless (usually Node.js)

**Comment by jonobr1** [comment]
Yep, you cannot use it as a path. But, you can directly add a `<video />` element to the texture to get it to work. Here's an example: https://codepen.io/jonobr1/pen/PoazvEv
