### ISSUE TITLE
[Question] Is it possible to cite your package used in an academic project?

### ISSUE THREAD

**Issue by moomoofarm1** [jonobr1/two.js#675]
Hi there,

I am currently working on a visualisation work for an academic project.
The problem is I have not found the citation info on your website.

Could you pls kindly share related information to me?

Thanks in advance and have a nice day.

**Comment by jonobr1** [comment]
Not sure what information you need from me, but here's MIT's guide for citing Open Source code: https://libguides.mit.edu/c.php?g=551454&p=3900280
