### ISSUE TITLE
[Bug] Command Docs broken

### ISSUE THREAD

**Issue by mechanoid** [jonobr1/two.js#676]
The reference for Anchor.Commands is not available

**To Reproduce**
1. Go to 'https://two.js.org/docs/anchor/'
2. Click on 'Two.Commands' link
3. No page with commands visible

**Expected behavior**
Expect to find Command Docs

**Comment by jonobr1** [comment]
Thanks for posting. This PR fixes that issue: https://github.com/jonobr1/two.js/pull/678 and I have just updated the website build to reflect it as well.

**Comment by mechanoid** [comment]
Thx for fixing it 👌
