### ISSUE TITLE
[Bug] Two.Measure is referenced in Two.Text Docs but seems to be removed

### ISSUE THREAD

**Issue by mechanoid** [jonobr1/two.js#679]
Two.Measure is referenced here -> https://two.js.org/docs/text/#measure but seems to be removed in the code and I cannot find it elsewhere

**Comment by jonobr1** [comment]
Ah yes, this is a new addition to `v0.8.11` which is the current development branch. I recently updated the docs for a few different issues and the latest code is now the documentation. Sorry about that. It does not exist in prior versions.

However, I will be updating npm in the coming days with this new version. So, if you update then you'll be able to find it in the `Two.Text` module.

In the meantime, here is the code for `Two.Text.Mesaure` https://github.com/jonobr1/two.js/blob/dev/src/text.js#L328 for reference.
