### ISSUE TITLE
[Enhancement] Code completion hint for `Two.Renderer.setSize()` method

### ISSUE THREAD

**Issue by cdaein** [jonobr1/two.js#683]
It's not really a bug, but I am not getting code completion (VSCode IntelliSense) when using `Two.Renderer.setSize()` method in TypeScript.

Renderer gets completion hint:
<img width="508" alt="Screenshot 2023-01-06 at 2 44 40 PM" src="https://user-images.githubusercontent.com/3522003/211088356-33585ce1-9ff5-49b5-8198-92ee3ac5da6b.png">

setSize doesn't:
<img width="466" alt="Screenshot 2023-01-06 at 2 44 52 PM" src="https://user-images.githubusercontent.com/3522003/211088404-f5452b84-359d-4220-94b4-78321cd7ee48.png">

and after writing the method, no documentation appears:
<img width="390" alt="Screenshot 2023-01-06 at 2 45 05 PM" src="https://user-images.githubusercontent.com/3522003/211088431-552e6d1e-9d81-43e9-aa1d-7bc7bd6605c4.png">

**Comment by jonobr1** [comment]
Hmm, those completion hints are incorrect. Renderers don't have `settings` or `SketchSettings`. I'll take a look into this and it should be easy to add the completion hints for methods and properties to the renderers.

**Comment by cdaein** [comment]
thanks for the reply. those `settings` and `SketchSetting` are the what I defined, so no issues with them. 🙂

**Comment by jonobr1** [comment]
This patch should fix your issue: https://github.com/jonobr1/two.js/pull/684
