### ISSUE TITLE
[Question] Why Two.makeRoundedRectangle returns Two.Rectangle

### ISSUE THREAD

**Issue by zhangzheheng12345** [jonobr1/two.js#686]
Just want to ask why `Two.makeRoundedRectangle` returns `Two.Rectangle` but not `Two.RoundedRectangle`?
And how to create a rounded rectangle whose radius can be changed?

**Comment by jonobr1** [comment]
Looks like only the documentation is incorrect. The code does return a `Two.RoundedRectangle`. You can modify the `radius` property like in this [Codepen](https://codepen.io/jonobr1/pen/oNMGdJR?editors=0010) to change the radius.

**Comment by jonobr1** [comment]
This commit fixes the documentation. It will take a few days for the docs on the website to reflect these changes. Thanks for posting!

**Comment by zhangzheheng12345** [comment]
Yeah in the codepen it works well, but in my project, it seems just not work. Neither I can pass the build process (tsup, while generating .d.ts file) or make the code editor with no error marks.
My Two.js version is v0.8.10. And if I find a place to upload images, I'll put up my screen shots.

**Comment by zhangzheheng12345** [comment]
Photos here:

![](https://s1.ax1x.com/2023/01/18/pS3Kt7F.jpg)

![](https://s1.ax1x.com/2023/01/18/pS3Kt7F.jpg)

**Comment by jonobr1** [comment]
Thanks for sharing. The types for TypeScript are generated from the documentation, so the types are incorrect throwing errors in your project. If you want to remedy the issue immediately, use the github version of the repository instead of npm. You can use it like so:

```bash
npm install --save https://github.com/jonobr1/two.js
```

**Comment by zhangzheheng12345** [comment]
OK I got it. Thank you for solving my problem.
I'll use github version first and really hope this can be solved soon in the next npm version.
Issue closed.

**Comment by jonobr1** [comment]
Yes, this will be fixed in the next NPM version. Thanks again for posting!
