### ISSUE TITLE
Two.Utils.read.path throws an error

### ISSUE THREAD

**Issue by AbdallahZ7** [jonobr1/two.js#698]
**Describe the bug**
I'm trying to create a twojs path from an svg path string

**To Reproduce**
var d = 'M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z';
var heart = Two.Utils.read.path(d);
two.add(heart);

trying the above code throws this error

caught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.applySvgAttributes (

**Expected behavior**
twojs path created from an svg path

**Screenshots**
<img width="357" alt="image" src="https://user-images.githubusercontent.com/15262636/232651134-2d489d57-cf3a-43b6-948b-593359b8961d.png">

**Environment (please select one):**
- [ x] Code executes in browser (e.g: using script tag to load library)
- [ ] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

**Comment by jonobr1** [comment]
Thanks for reporting. This PR fixes that issue: https://github.com/jonobr1/two.js/pull/699

**Comment by jonobr1** [comment]
A new package isn't up, but you can npm install the git repo directly
