### ISSUE TITLE
[Bug] WebGL Renderer Blurry

### ISSUE THREAD

**Issue by benz2012** [jonobr1/two.js#703]
**Describe the bug**
Using the WebGL renderer in my conditions produces far blurrier output shapes than with the Canvas renderer or SVG renderer. I wouldn't be surprised if Retina magic (or lack thereof) is at play here.

**To Reproduce**
1. Head to any of the "[Drawing Your First Shapes](https://two.js.org/#drawing-your-first-shapes)" examples
2. Add `type: Two.Types.webgl` to the params object
3. Observe the shapes (especially their strokes)

**Expected behavior**
The WebGL renderer should produce the same or near the same image sharpness as the other two renderers.

**Desktop:**
 - Device: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
 - OS: MacOS 12.6.5
 - Browser: Google Chrome 112.0.5615.137

**Screenshots**
<img width="1435" alt="all3" src="https://user-images.githubusercontent.com/4582095/235276653-ae587378-320e-497a-9abc-26947884d46c.png">

**Comment by benz2012** [comment]
To make it even easier, simply navigate to the [Rendering Types](https://codepen.io/jonobr1/pen/NWvJZPp example codepen) to see the differences as well

**Comment by jonobr1** [comment]
Thanks for posting. Yes, this has to do with retina displays. The way the WebGL Renderer works is that textures are created of each individual path. These textures are uploaded to WebGL and then rendered on quads. The WebGL canvas takes into account the DPI, but the canvas that generates each texture isn't. I'll have to address this, though I'm not sure what performance hit this will create yet.

**Comment by jonobr1** [comment]
It could also have to do with how the textures are filtered: https://github.com/jonobr1/two.js/blob/dev/src/renderers/webgl.js#L1418-L1420

**Comment by benz2012** [comment]
@jonobr1 I played around with the filters and using nearest with MAG eliminates the blurriness. Changing MIN didn't seem to have any effect.

However, once the blurriness was gone, it became apparent that the root cause was still present -- so I think your first hunch might be correct. Pixelation was present.

<img width="999" alt="rendering types with  mag nearest" src="https://user-images.githubusercontent.com/4582095/235558571-03363d27-66e2-4e28-b7b9-8759294a8f8f.png">

**Comment by jonobr1** [comment]
This will be published on NPM by the end of the week. Thanks for reporting!
