### ISSUE TITLE
Text `BoundingClientRect` in nested groups

### ISSUE THREAD

**Issue by dan-fritchman** [jonobr1/two.js#705]
Fiddle: 
https://jsfiddle.net/danfritchman/q9sdxzr8/1/

```js
var two = new Two({
  fullscreen: true,
  autostart: true
}).appendTo(document.body);

const g = new Two.Group();
g.position = new Two.Vector(100,100);
const g2 = new Two.Group();
g2.position = new Two.Vector(100,100);
const text = new Two.Text("???");
text.position = new Two.Vector(100, 100);

// Add those into nested groups. `two(g(g2(text)))``
two.add(g);
g.add(g2);
g2.add(text);

// Uncomment *either* of these, and the rect will show up around `text`
/* g.getBoundingClientRect(false); */
/* g2.getBoundingClientRect(false); */

// Now get the text element's bounding box 
const bbox = text.getBoundingClientRect(false);

// And draw it
const rect = new Two.Rectangle(
  (bbox.left + bbox.right)/2,
  (bbox.top + bbox.bottom)/2,
  bbox.width,
  bbox.height,
)
rect.stroke = "red";
rect.fill = "none";
two.add(rect);
```

Produces this: 

<img width="498" alt="image" src="https://github.com/jonobr1/two.js/assets/20178855/8dd80276-c27f-4b10-b89b-ccfdce49002a">

Uncomment the calls to `getBoundingClientRect` on *either* group `g` or `g2` and `rect` shows up around the boundary of `text`.  
Is that the expected behavior?

**Comment by jonobr1** [comment]
Sorry for the delay. This is not ideal behavior, but it is currently accepted. To elaborate:

When you instantiate Two.js with `autostart: true`, what happens is that an animation loop (an interval function gets set to call multiple times a second) is initiated. This loop starts on the frame _after_ all the code written subsequent to the initialize and in the same scope.

So, in this case the update to render hasn't fired when you call `getBoundingClientRect` and certain transform values haven't been set yet. You can get around this by ensuring the application is "up-to-date" when you call certain functions:

```javascript
// ...
g2.add(text);

two.update(); // This forces an update to be called and rendered

const bbox = text.getBoundingClientRect(false);
// ...
```

**Comment by dan-fritchman** [comment]
Works here, thanks!
