### ISSUE TITLE
compile error typescript[Bug]

### ISSUE THREAD

**Issue by detrothe** [jonobr1/two.js#708]
I get a compiler error with current version 0.8.11 of two.js with typescript compiler tsc Version 5.2.2 . The error only happens with the typescript compiler tsc, which is used by vite to build the distribution version. The debug version with esbuild, which has its own typescript compiler?, works fine. The Problem existes on local machines (windows and Linux) and when deploying on Netlify.

> tsc && vite build
line 2851: error TS2304: Cannot find name 'Anchor'
left: Anchor;
line 2857: error TS2304: Cannot find name 'Anchor'
right: Anchor;
Found 2 errors in the same file, ...

I had no problems in version 0.8.10

Hope it helps.

**Comment by jonobr1** [comment]
Thanks, this PR should resolve this issue: https://github.com/jonobr1/two.js/pull/709

**Comment by detrothe** [comment]
Hi,

Thank you, now it works.

Am 03.10.23 um 20:56 schrieb Jono:
