### ISSUE TITLE
Two.Path.curved flag does not set bezier handles for start and end Anchors on non-closed paths

### ISSUE THREAD

**Issue by chrisdelbuck** [jonobr1/two.js#71]
When creating a non closed Polygon, using the curved flag.  The first and last Anchors passed in do not have Right and Left bezier handles set, each should have one or the either respectively.

**Comment by jonobr1** [comment]
Finally revisiting this, I've thought about this and tested more. I think the most sense makes to bundle this type of functionality with the `smooth` functionality of this [issue](https://github.com/jonobr1/two.js/issues/467). When this is implemented you could go in and __add__ the endpoints' bezier handles manually. This gives developers the most control.

This [commit](2c2eddb0b6a8335eec40937fcd11efa12530d609) is the latest exploration and there are just too many edge cases where the curvature is incorrect.

When the `smooth` method is implemented you could do something like this:
```javascript
var path = new Two.Path(points);
path.automatic = false;
path.smooth();
path.vertices[path.vertices.length - 1].controls.left.x = 50;
```

This allows you to manually change things, but also gives you the option of auto-calculating the curve (_but not overwriting your own logic afterwards_).
