### ISSUE TITLE
Text Baseline in SVG Backend

### ISSUE THREAD

**Issue by dan-fritchman** [jonobr1/two.js#716]
https://codepen.io/jonobr1/pen/MWvVBdx

```js
import Two from 'https://cdn.skypack.dev/two.js@latest';

const two = new Two({
  type: Two.Types.webgl,
  fullscreen: true,
  autostart: true
}).appendTo(document.body);

// Create one text of each `baseline` value
const t1 = two.makeText("TOP", two.width / 2, two.height / 2, {size:100});
t1.baseline="top";
const t2 = two.makeText("MID", two.width / 2, two.height / 2,{size:100});
t2.baseline="middle";
const t3 = two.makeText("BOT", two.width / 2, two.height / 2,{size:100});
t3.baseline="bottom";
```

That code snippet, with the WebGL backend, looks like so: 

<img width="371" alt="image" src="https://github.com/jonobr1/two.js/assets/20178855/8f1cf7bb-9d29-4f90-9556-aeec4998c55a">

Change it to `canvas`, and it looks like so: 

<img width="406" alt="image" src="https://github.com/jonobr1/two.js/assets/20178855/b60dccb1-178e-4774-ab08-fd5a21d3d54e">

Which are not, like, identical, but for purposes of this, close enough.  
But change to `Two.Types.svg`, and it looks like so: 

<img width="378" alt="image" src="https://github.com/jonobr1/two.js/assets/20178855/b19fc9e4-ecfd-4388-9335-9eaafee9dc48">

Is that the expected behavior?  
I.e. does the `baseline` attribute not work with the SVG back-end?

**Comment by dan-fritchman** [comment]
Thanks for jumping on this.
And agree that looks right. Particularly Mozilla’s featured example. 

And I think I understand enough to get you an effective PR here. If you’ve got advice, preferences, or things to know, appreciate sharing.

**Comment by jonobr1** [comment]
Oop, thanks for this but I beat you to it 😅

**Comment by jonobr1** [comment]
This will be published on npm in the next week or so. I have a couple of other PRs that need tending to.

**Comment by dan-fritchman** [comment]
Awesome thanks!
