### ISSUE TITLE
[Bug] Image texture does not display under svg renderer

### ISSUE THREAD

**Issue by Okay6** [jonobr1/two.js#726]
**Describe the bug**
-  As title describe, image texture does not display under svg renderer.

**To Reproduce**
-  Here is sample code on codepen. [[Example of Using a Sprite](https://codepen.io/jonobr1/pen/rNdZNwM)]

**Screenshots**
- Under canvas renderer and webgl render, it works well.
![image](https://github.com/jonobr1/two.js/assets/61047127/811f7ab8-3691-4984-bb91-e8d6e70964b1)
- Under svg renderer, texture doesn't display.
![image](https://github.com/jonobr1/two.js/assets/61047127/7da94da4-22be-49db-bd18-c5918dda8264)

**Additional context**
- two.js version is v0.8.13.

**My solution**
- Use developer tool in chrome , i found a issue:
![image](https://github.com/jonobr1/two.js/assets/61047127/9604d119-c890-4ee0-b52b-06a55e8027e1)
- The location of  source code  caused it is [svg.js#line 1073](https://github.com/jonobr1/two.js/blob/2e7dfea3f91908db01b51d1bf71489421ef161f9/src/renderers/svg.js#L1073)
 Here should keep same width and height in [pattern]  and  [image].
- Add ``` styles.width  = changed.width
             styles.height = changed.height```  after  [svg.js#line 1073](https://github.com/jonobr1/two.js/blob/2e7dfea3f91908db01b51d1bf71489421ef161f9/src/renderers/svg.js#L1073) look like this:
   ```
   ....
    if (this._scale instanceof Vector) {
            changed.width *= this._scale.x;
            changed.height *= this._scale.y;
          } else {
            changed.width *= this._scale;
            changed.height *= this._scale;
          }
         // added to keep same width and height between pattern and image
          styles.width = changed.width
          styles.height  = changed.height
  ....
  ```
- I tested modified code in my local environment, it works well
    ```
    import Two from "../two.js/src/two";
    
    const two = new Two({
      type: Two.Types.svg,
      fullscreen: true,
      autostart: true
    }).appendTo(document.body);
    
    const rectangle = new Two.Rectangle(two.width / 2, two.height / 2, 200, 200);
    rectangle.fill = new Two.Texture('/texture.jpg', onLoad);
    rectangle.noStroke()
    rectangle.position.x = 200
    two.add(rectangle);
    
    function onLoad() {
      const image = rectangle.fill.image;  
      const desiredWidth = rectangle.width;
      const desiredHeight = rectangle.height;
      const sx = desiredWidth / image.width;
      const sy = desiredHeight / image.height;
      rectangle.fill.scale = new Two.Vector(sx, sy);
    }
    ``` 
   ![image](https://github.com/jonobr1/two.js/assets/61047127/fe69dee7-e2b7-4715-88fd-2fdc08b0def1)

**Comment by jonobr1** [comment]
Ah, Thank you! I will patch this.

**Comment by jonobr1** [comment]
Okay, Two.js version 0.8.14 addresses this issue. Thank you again!

**Comment by Okay6** [comment]
> Okay, Two.js version 0.8.14 addresses this issue. Thank you again!

Cool!
