### ISSUE TITLE
[Question] Additional 1px on rectangle dimensions?

### ISSUE THREAD

**Issue by JohnPaulHarold** [jonobr1/two.js#731]
**Describe your question**

When I create a rect with specific dimensions, I'm finding that when calling `getBoundingClientRect()` there is an additional `1px` added. Is this expected behaviour, and if so, why does it happen? 

If this feels like a bug, I can update the ticket, or raise a new one.

**Your code (either pasted here, or a link to a hosted example)**

https://codepen.io/johnpaulharold/pen/Rwzwrmw

**Environment (please select one):**
- [x] Code executes in browser (e.g: using script tag to load library)
- [x] Packaged software (e.g: ES6 imports, react, angular, vue.js)
- [ ] Running headless (usually Node.js)

---

If applicable:

**Desktop (please complete the following information):**
 - OS: OSX (I can test others if needs be)
 - Browser: Chrome/Safari
 - Version: latest stable on both

**Comment by jonobr1** [comment]
Yes, due to browser inconsistency `noStroke` is actually the same as `stroke = 'transparent'`. As a result, the stroke _technically_ exists, but is not visible to the end user. This can be remedied by `path.linewidth = 0`

But, to your point we can add `path.linewidth = 0` to the `noStroke` method to increase coverage.

**Comment by JohnPaulHarold** [comment]
Thanks. I thought I'd tried that, but I realised I might have been using `lineWidth`. 

Do you want me to raise a request ticket asking for `linewidth = 0` to be added to the `noStroke()` function?

**Comment by jonobr1** [comment]
No need, fixed it here: https://github.com/jonobr1/two.js/pull/732

**Comment by JohnPaulHarold** [comment]
Thanks! This question is answered for me.
