### ISSUE TITLE
[Question] How to completely destroy instances of TwoJS ？

### ISSUE THREAD

**Issue by duping123456** [jonobr1/two.js#734]
I have a Vue project that references this JS. In one of the pages, four graphics drawn by TwoJS were rendered. When I re rendered the page, the four TwoJs were not destroyed and were regenerated. This caused the memory to constantly increase every time I switched data and re rendered the component, until the webpage crashed

**Comment by jonobr1** [comment]
Ah yes, on unmount you'll want to do this:

```javascript
const index = Two.Instances.indexOf(two);
const parent = two.renderer.domElement.parentElement;
if (index >= 0) Two.Instances.splice(index, 1);
if (parent) parent.removeChild(two.renderer.domElement);
two.release(two.scene);
```
