### ISSUE TITLE
[Bug] Check the typescript in your code

### ISSUE THREAD

**Issue by Domipoke** [jonobr1/two.js#739]
(I place a space between @ and the next word because github tag me an user)
In the file two.js/src/anchor.js the typescript is
`/**
 * @ class
 * @ name Two.Anchor
 * @ param {Number} [x=0] - The x position of the root anchor point.
 * @ param {Number} [y=0] - The y position of the root anchor point.
 * @ param {Number} [lx=0] - The x position of the left handle point.
 * @ param {Number} [ly=0] - The y position of the left handle point.
 * @ param {Number} [rx=0] - The x position of the right handle point.
 * @ param {Number} [ry=0] - The y position of the right handle point.
 * @ param {String} [command=Two.Commands.move] - The command to describe how to render. Applicable commands are {@ link Two.Commands}
 * @ extends Two.Vector
 * @ description An object that holds 3 {@ link Two.Vector}s, the anchor point and its corresponding handles: `left` and `right`. In order to properly describe the bezier curve about the point there is also a command property to describe what type of drawing should occur when Two.js renders the anchors.
 */`

but you have no use of the variable lx and ly because you replace them with ax and ay in

`constructor(x = 0, y = 0, ax = 0, ay = 0, bx = 0, by = 0, command = Commands.move)`

Am I wrong something?

**Comment by jonobr1** [comment]
Yes, sorry that's a discrepancy between jsdocs and TypeScript types. The project is written in JavaScript, so whatever is written in jsdocs actually has no actual implications on the code. So, `lx` is `ax`, `ly` is `ay`, etc..

I should change this in the documentation. That's super confusing.

**Comment by jonobr1** [comment]
Fixed here: https://github.com/jonobr1/two.js/commit/0b01e96655ee31d3cce2c8bd5602552d90b197b3
