### ISSUE TITLE
[Bug] Race condition at startup when setMatrix is called

### ISSUE THREAD

**Issue by aamcrae** [jonobr1/two.js#749]
**Describe the bug**

I believe I have found a race condition that causes a startup crash thus:

Uncaught ReferenceError: Cannot access 'Path' before initialization
at Module.Path (￼matrix.js:607:1)
at ../../../node_modules/two.js/src/shapes/arc-segment.js (￼arc-segment.js:20:1)
at webpack_require (￼bootstrap:22:1)
at fn (￼hot module replacement:61:1)
at ../../../node_modules/two.js/src/group.js (￼events.js:189:1)
at webpack_require (￼bootstrap:22:1)
at fn (￼hot module replacement:61:1)
at ../../../node_modules/two.js/src/renderers/canvas.js (￼registry.js:57:1)
at webpack_require (￼bootstrap:22:1)
at fn (￼hot module replacement:61:1)

It may have something to do with Webpack, and the order that modules are imported and intialised.

In src/matrix.js there is a call setMatrix(Matrix).
In src/utils/math.js, there is:

let Matrix;
...
  setMatrix(matrix) {
...
}

So if there is any getComputedMatrix() calls made before setMatrix is called, the 'Matrix' value in utils/math.js will be unset, and will cause the issue (I presume).
Since Path is referenced, I am assuming the error is being caught because Matrix is not set (since Path inherits Shape, and Shape initialises some Matrix properties using new().

I am not sure of the best way to fix this. As an experiment, I removed the 'Matrix' variable from utils/Math.js and used this in
matrix.js:

export let Matrix = Matrix;

The client seems to run fine after this change.

However I am no JS expert and it is not clear to me whether this has fixed the issue or just moved things around.

**To Reproduce**
Hmm this is hard, since it seems to be dependent on Webpack.
I have a large amount of code that gets bundled together, including two.js

**Expected behavior**
The client not to crash with an Uncaught ReferenceError.

**Screenshots**

**Environment (please select one):**
- [ ] Code executes in browser (e.g: using script tag to load library)
- [X] Packaged software (e.g: ES6 imports, react, angular, vue.js) - using Webpack to create bundle.
- [ ] Running headless (usually Node.js)

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 24.10
 - Browser Chrome
 - Version 131.0.6778.204 (Official Build) (64-bit)

**Additional context**

**Comment by aamcrae** [comment]
Upon further investigation, it's likely this is caused by a circular dependency outside of two.js.
So closing this, and apologies for the noise.

**Comment by jonobr1** [comment]
No worries. Glad you figured it out
