### ISSUE TITLE
Is it possible to export an SVG generated in two.js?

### ISSUE THREAD

**Issue by thisissami** [jonobr1/two.js#80]
Hi,

I am curious - is it possible to export an SVG that we create with two.js? I am working on an app that deals heavily with both SVG & Raster images. The current library we are using supports both, but is quite lacking (functionally) on the SVG side. I really like how Two.js functions, but would need to be able to export creations from here into the other library (which can read XML string, JSON, or load an actual SVG file) before I can use Two.js. 

There isn't anything about this in the documentation, but I figured that if the library can import SVGs, there's a good chance that it can export them too. 

Best, and thanks either way,
Sami

**Comment by nanmenxue** [comment]
i hava the same question.i want to export a svg made by two.js

**Comment by nanmenxue** [comment]
i want to know how to export svg by code rather than by hand

**Comment by jonobr1** [comment]
No problem. Export to where? A database the user's desktop?

**Comment by nanmenxue** [comment]
thank you very much for your reply,i am a Chinese.you are the first foreign person i talk with.
i think if it can export a txt or a svg on desktop by code when i press a button will be better.
and i want to know that,if i can control the polygon in svg which just used c sign.
my english is not good .thank you for your reading

**Comment by jonobr1** [comment]
No worries! your English is far better than my Chinese. So, the tricky thing about this is that `svg`s are like `html`. The text describes everything. So if you wanted to save an scene in Two to a databse then you could just extract the text like so:

````javascript
var container = document.createElement('div');
var two = new Two().appendTo(container);
// ... Draw some stuff
two.update();
var svgString = container.innerHTML;
````

If you want to use it as `image-data` then you can use the prefix before dumping in the content like this jsfiddle example: http://jsfiddle.net/jonobr1/jpvgmj2g/

Hope this helps!

**Comment by nanmenxue** [comment]
thank you so much.i want to follow your facebook if it wont bother you .my facebook is 458873729@qq.com~~

**Comment by ddfreyne** [comment]
Worth noting: the exported SVG, when using `innerHTML`, lacks `xmlns="http://www.w3.org/2000/svg"`. Without it, Chrome will show

> This XML file does not appear to have any style information associated with it. The document tree is shown below.

Adding the `xmlns`, e.g.

```xml
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="800" height="800" …
```

… makes Chrome render the SVG rather than showing its XML source.

**Comment by MichaelKatiba** [comment]
Is there a way to add `xmlns` into svg using two.js without having to paste it every time after exporting?

**Comment by jonobr1** [comment]
You could add it in via a simple string replace like so:

```javascript
var str = container.innerHTML.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
```

**Comment by MichaelKatiba** [comment]
Thanks again, that worked :)
