### ISSUE TITLE
Add background image to polygons

### ISSUE THREAD

**Issue by RoxasShadow** [jonobr1/two.js#9]
Should be nice allowing to set a background image to polygons instead a simple color filling.

**Comment by vibertthio** [comment]
@feenr I wonder what's the detail of your solution ?
Can you please share it. I really appreciate it!
Did you use the original Two.js API only, or have you implemented some custom function into the Two.js ?

**Comment by jonobr1** [comment]
@vibertthio here's an early example of using images in the latest `dev` branch of Two.js: https://jsfiddle.net/jonobr1/Lbu6795r/ works with SVG, Canvas, and WebGL 👍

**Comment by vibertthio** [comment]
@jonobr1  Doooooooope!

**Comment by jonobr1** [comment]
Nearing completion of tests for imagery in Two.js. Closing out now that the API is squared away and will be shipping with the next release `v0.7.0`.
